### ISSUE TITLE
feat: <ion-select> should have the same base functionality as <select> in regards to keyboard events

### ISSUE THREAD

**Issue by Tankatronic** [ionic-team/ionic-framework#13362]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[X ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X ] feature request

**Current behavior:**
With the standard `<select>` HTML element, if the element has keyboard focus a user can either use the arrow keys to change between options or type the value that they desire, and if that value is present it will be selected. `<ion-select>` does not have this functionality.

**Expected behavior:**
`<ion-select>` should respond to keyboard events the same way `<select>` does

**Steps to reproduce:**
Sample app:
http://plnkr.co/edit/yPC6r8IsYw9lhkXLReBY?p=preview

1. Give keyboard focus to the `<select>` element (easiest way is to click on it and select a value).
2. Use the up and down arrow keys to change values
3. Type "myvalue" and see that it is now in the selected value
4. Give keyboard focus to the `<ion-select>` element.
5. Use the up and down arrow keys and observe how the the screen scrolls instead of changing values
6. Type "myvalue" and see that `<ion-select>` is indeed inferior to `<select>` and does not update the value

**Other information:**
According to the [ionic docs](https://ionicframework.com/docs/api/components/select/Select/), the `<ion-select>` element is supposed to "[make] it easier for users to sort through and select the preferred option or options". For a mobile device, yes I can agree. However, on desktop using the keyboard to find your value is the most efficient way to use a drop down list and the lack of that functionality is contradictory to the documentation.

**Comment by tcigrand** [comment]
Is there a design for what it should look like when a specific option has focus? Would need designs for ActionSheets, Alerts and Popovers.

**Comment by aleksander351** [comment]
Makes it pretty much unusable, if the basic functionality is so different. Name it to something else at least.

**Comment by colabottles** [comment]
> Is there a design for what it should look like when a specific option has focus? Would need designs for ActionSheets, Alerts and Popovers.

Some mobile users may use a virtual keyboard to assist them with navigating an app or page. iOS users may use Voice Control as well (not sure if Android has a similar function to Voice Control).

When an item in a `<select>` receives focus, the item can be chosen by either two methods when traversing with the up/down arrows to the preferred menu item:

1. The `Space` key to trigger the select menu to show all options
2. The `Enter` or `Space` keys will choose the preferred option and that item receives focus.

Focus indication should also be apparent and have sufficient contrast for low-vision and users that use the keyboard or a virtual keyboard/voice command on mobile. Whether that is a focus ring, a background color change or text change to bold, for example. Focus ring is the desirable option with anything else being a bonus.

I would recommend these article for more on selects that are accessible:

https://adamsilver.io/blog/building-an-accessible-autocomplete-control/
https://cantina.co/consistently-inconsistent-the-pitfalls-of-abandoning-external-consistency/
https://adrianroselli.com/2021/03/under-engineered-select-menus.html
https://www.24a11y.com/2019/select-your-poison/

**Comment by shessafridi** [comment]
Selection on `ion-select` works with the `Space` key but `Enter` doesn't work

**Comment by thetaPC** [comment]
Thank you for submitting the issue!

We have made improvements to the keyboard interactions to `ion-select`, aligning them with recognized [web standards for accessibility](https://www.w3.org/). These changes are available started in [Ionic v7.5.0](https://github.com/ionic-team/ionic-framework/releases/tag/v7.5.0).

While IonSelect allows users to choose from a list of options much like the native select, it is not designed to have the same functionality. The main reason for this is IonSelect presents a dialog with different control options: buttons, radios, and checkboxes.
  
Rather than forcing the native `<select>` interaction on a different user interface, we think it would be best to align with the WCAG interaction recommendations for these components. For example, an IonSelect can present checkboxes in an alert dialog, and users can use the "Space" key to toggle between checked and unchecked states. The native `<select>` lets users choose an option using the "Enter" key. However, adding this behavior would make the checkbox behavior not align with the WCAG recommendations.
    
As part of this, we also updated the `aria-haspopup` attribute on IonSelect to `'dialog'` to more accurately describe the type of popup users can expect.

For more information on the updated keyboard interaction, we encourage everyone to refer to our [docs page](https://ionicframework.com/docs/api/select#keyboard-interactions). It provides comprehensive details on how to use the keyboard functionality, allowing you to take full advantage of the enhanced accessibility features we've implemented.

**Comment by shessafridi** [comment]
I am not a fan of this decision. Most users use the `Enter` key for dropdowns and the majority of them don't even know about selecting with `Space`, We should focus on solving real problems more than aligning to some spec, The `interface="popover"` should replicate the native browser select functionality as much as possible.

Other libraries like MUI and Radix UI also support selecting with the `Enter` key.

**Comment by liamdebeasi** [comment]
While the popover in Ionic does look like a dropdown menu in this case, it is actually a dialog which is why there is a behavior difference.

Dropdown menus typically use the [listbox](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role) role while dialogs use the [dialog](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role) or [alertdialog](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alertdialog_role) role. The functional requirements between the listbox and dialog/alertdialog are very different, and what screen readers announce are also very different.

While I understand that it is disappointing that `ion-select` is not usable as a listbox, the reality is `ion-select` was never designed to be a dropdown menu. Our previous ARIA `role` and documentation were not clear on that which contributed to some of the confusion here. The team has opted to prioritize consistency with assistive technologies such as screen readers to make Ionic more accessible.
