### ISSUE TITLE
[ionic 4] i18n support

### ISSUE THREAD

**Issue by vvdwivedi** [ionic-team/ionic-framework#15153]
# Ionic angular and i18n support

Angular 6 has this build in i18n support that requires to build different builds for different languages. How is this going to work with ionic 4 app? Is there a way to provide dynamic language switching?

**Comment by smartifier-salomaa** [comment]
I have been using http://www.ngx-translate.com (or https://github.com/ngx-translate/core) in my Ionic 4 app and that supports dynamic language switching. You can have one build with multiple language files.

**Comment by vvdwivedi** [comment]
ngx-translate is there, but I was looking for built in support for translation. I am also using ngx-translate for now.

**Comment by Nigdor** [comment]
I'm in the same situation.
Did you find an answer ?
@vvdwivedi

**Comment by abhijitdhobale** [comment]
In Ionic is i18n works similar to angular (e.g. i18n-title, i18n-placeholder etc.) with locale file   messages.<language>.xlf?

**Comment by yosigolan** [comment]
This was also an issue on ionic 3: https://github.com/ionic-team/ionic/issues/8542
it will be great if this time it will get an answer in version 4.

**Comment by Chris1234567899** [comment]
Any news on this?

I tried using ngx-translate meanwhile but I had trouble setting it up. The way it functioned in ionic 3 does not seem to work in ionic 4 anymore. Did someone get it to run already?
Kind of important.

**Comment by vvdwivedi** [comment]
@Chris1234567899 You can setup ngx-translate just by following the guide on their site. I am using it the same way without any issue. Not sure if ionic is planning to do something about this, but ngx-translate works just fine.

**Comment by smartifier-salomaa** [comment]
I'm using it without any issues. What kind of problems are you having?

I have in app.module.ts
```
import { TranslateLoader, TranslateModule, TranslateService } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';

export function createTranslateLoader(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/i18n/', '/translations.json');
}
```

and then in each page you want to use it

YOUR_PAGE.module.ts
`import { TranslateModule } from '@ngx-translate/core';`

and

```
imports: [
 CommonModule,
 FormsModule,
 IonicModule,
 TranslateModule.forChild(),
 RouterModule.forChild(routes)
],
```
YOUR_PAGE.page.ts
Use it as any other plugin.

**Comment by Chris1234567899** [comment]
@vvdwivedi 
Thanks, I got it now. No idea what the issue was, after restarting several times ionic serve, it worked.

**Comment by tonyawad88** [comment]
@vvdwivedi Thank you this helped !

**Comment by yosigolan** [comment]
Hey.
@paulstelzer why did you closed the issue? does ionic 4 has support for angular i18 framework?

**Comment by paulstelzer** [comment]
Thought it's clear by using ngx-translate. Do you want it at feature? okay, I label it so

**Comment by venkatesh4446** [comment]
> # Ionic angular and i18n support
> Angular 6 has this build in i18n support that requires to build different builds for different languages. How is this going to work with ionic 4 app? Is there a way to provide dynamic language switching?

what are steps to follow the translate in ionic4

**Comment by pjc2007** [comment]
The big difference with `ngx-translate` vs the built in Angular is that `ngx-translate` allows **all languages to exist in the one single build**, and, if required, you **can swap languages at runtime**.

Having all languages in the one build is essential in my case, and `ngx-translate` does EXACTLY this, and **does it well**. I have been using ngx-translate since the beginning (was originally ng2-translate). To me (and just my opinion), the ngx-translate a a far superior solution to the Angular built in way.

While upgrading to **Ionic 4**, I did have an issue with it working (could not find pipe in the first Page I proted), but the comment by @smartifier-salomaa helped me out here (so thanks for that!).

**Comment by yosigolan** [comment]
You are right that when using angular built in translation a different build is required for every language but this is not a disadvantage since you can hold all the builds together as one package. The reason it works this way is to gain the maximum performance possible. This way the html holds the final text it self and it is not required to read it from the model before rendering.

**Comment by jvoigt** [comment]
We would also love this feature, as we are using the builtin i18n in all our other none-ionic/pure-angular projects. 
On the other hands there is going to be an huge change in the angular i18n-process with the new "ivy"-renderer. So maybe we should not expect anything before its release.

**Comment by Unkn0wn0x** [comment]
You can use / adapt the Ionic 3 i18n Documentation for Ionic 4 too:
- https://ionicframework.com/docs/v3/developer-resources/ng2-translate/

**Comment by telmaco** [comment]
I would love to see the angular built in i18n support working on ionic! Please!

**Comment by jimbarrett33** [comment]
The purpose of this issue is to request that Angular's native implementation of i18n be supported by the Ionic framework itself. While pointing people to ngx-translate may seem helpful, as long as the team knows this is a viable workaround this issue will never get the attention that it needs. More importantly, ngx-translate will probably die at some point. It started out as a stop-gap to fill in for features that the Angular team did not deem to be a priority. Ionic not supporting Angular's i18n at all just seems like a gap that needs to be addressed sooner rather than later. Either you support a framework or you don't.
