### ISSUE TITLE
Prepending slides to ion-slides

### ISSUE THREAD

**Issue by georgechr** [ionic-team/ionic-framework#16504]
# Bug Report

```
insert the output from ionic info here
```

**Describe the Bug**
Current behavior: When prepending slides it pops to the newly added slides

**Steps to Reproduce**
Create a slider and fill it with ngFor and a dynamic list of slides. Try adding a slide or more before the current slide. The slide now pops to the first slide
```
slides = newSlides.concat(slides);
```

**Expected Behavior**
When prepending slides it should stay on the current slide

**Comment by bryce13950** [comment]
Can you attach the entire component file for where you are experiencing this issue?

**Comment by RHinderiks** [comment]
@bryce13950 It's been quite a while and this issue still persists, any news ?

**Comment by liamdebeasi** [comment]
Thanks for the issue. @georgechr is this still an issue with the latest version of Ionic?

**Comment by kalu06** [comment]
@liamdebeasi that issue persists with Ionic5 as well (see this [stackblitz](https://stackblitz.com/edit/ionic-v5-angular-prepend-slides-issue?embed=1&file=src/app/home/home.page.html)). Should I track that issue in an Ionic5 thread?

**Comment by liamdebeasi** [comment]
You can keep it here, and I will take a look.

**Comment by kalu06** [comment]
Any progress on your side?

**Comment by kalu06** [comment]
Have you guys made any progress on this? Thanks.

**Comment by liamdebeasi** [comment]
Thanks for the issue! With the release of Ionic 6, we made the decision to deprecate `ion-slides` in favor of using Swiper.js directly.

Moving forward, `ion-slides` will only receive critical security fixes, and the component will be removed in Ionic 7. As a result, I am going to close this issue.

We have prepared migration guides for each of the 3 JavaScript frameworks we support, so developers can get started migrating right away.

[Migration for Angular](https://ionicframework.com/docs/angular/slides)
[Migration for React](https://ionicframework.com/docs/react/slides)
[Migration for Vue](https://ionicframework.com/docs/vue/slides)

We believe this change will lead to a healthier Ionic ecosystem as it frees up resources for the Ionic team to dedicate to other areas of this project while still giving developers options for carousels in their apps. Since `ion-slides` currently uses Swiper under the hood, the behavior of your carousels should remain the same even after you migrate.

For more information on the reasoning for and benefits of this change, please see the [ion-slides documentation](https://ionicframework.com/docs/api/slides#migration).

Thank you!
