### ISSUE TITLE
Select popover is not getting closed when user navigates back

### ISSUE THREAD

**Issue by neerajrd25** [ionic-team/ionic-framework#16946]
I am currently using Ionic 4 RC.

https://beta.ionicframework.com/docs/api/select
# Bug Report
Whenever a select popover is opened and when user clicks browser back button, the page is changed but the popover remains floating. 

**Expected behavior:**
All the popover should get closed if it is not assocated with the current state where it was opened.

**Steps to reproduce:**
1. Open a Select popover.
2. click browser back button
O/p : Popover remains floating
**Related Code **
```
  <ion-item>
                                            <ion-label color="primary" position='floating'>Country</ion-label>
                                            <ion-select formControlName="country" interface="popover">
                                                <ion-select-option *ngFor="let country of countriesArray" [value]="country">{{country}}</ion-select-option>
                                            </ion-select>
                                        </ion-item>
```

**Other information:**
I have tiried to close it via cpaturing the select control using @ViewChild , but the select docs doesn't have any close method. I think close() should also be provided w.r.t closing of popovers
![imageedit_3_6837966490](https://user-images.githubusercontent.com/13258711/50629959-bb98a480-0f64-11e9-9ccc-1e90387001d1.png)
![imageedit_1_3408587884](https://user-images.githubusercontent.com/13258711/50629960-bc313b00-0f64-11e9-965b-2072a8ce4e17.png)

**Comment by joelmeaders** [comment]
Anyone find a workaround for this yet?

**Comment by AkshayKanchan** [comment]
Hi Any updates on this issue? I am facing same problem, unable to close modal or alert when navigating back from browser. Is there any official way to handle this issue?

**Comment by Jannnnnn** [comment]
Today I also came across the issue

```
   Ionic CLI                     : 5.4.13 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.803.21
   @angular-devkit/schematics    : 8.3.21
   @angular/cli                  : 8.3.21
   @ionic/angular-toolkit        : 2.1.1
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. The problem here is we do not have much control over the back button when running an app in the browser. In Capacitor/Cordova, we have access to a `backbutton` event which is emitted when the hardware back button is pressed on an Android device. In those cases, we can dismiss the popover whenever that event is emitted.

When running in the browser, this is not possible as there is no `backbutton` event. Getting this behavior to work would require us to integrate overlay components, such as `ion-alert` and `ion-popover`, with your framework's router. We do not feel that it would be correct to take a temporary component such as `ion-modal` and link it with the global state of the router. This could lead to many inconsistencies. For example, if a user lands on the url `/app/show-signup-modal` which presents a sign up modal, what should be shown underneath the modal? Additionally, what should happen when the user decides to cancel out the modal? The modal is very much dependent on the context in which it was presented, and the same goes for the popover in the example provided in this thread. This is something we lose by integrating these kinds of components with the router.

----

As an alternative, one thing you could do is manually dismiss the popover in an `ionViewWillLeave` lifecycle hook. This would ensure that the popover is dismissed whenever you navigate away from the page that presented it. For more information on lifecycle hooks please see https://ionicframework.com/docs/angular/lifecycle.

----

We have also released hardware back button docs: https://ionicframework.com/docs/developing/hardware-back-button that may contain information useful for your application. I am going to close this issue as we do not currently have plans to integrate our overlay components with the router. For full back button support, we recommend using Capacitor. Thank you!
