### ISSUE TITLE
[Ionic 4] autoclose option with ion-select alert interface 

### ISSUE THREAD

**Issue by marlonpatrick** [ionic-team/ionic-framework#17270]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
I would like to request an option to use an ion-select with alert interface, where, when choosing the desired option the alert was closed immediately without needing to click the "OK" button.

**Describe Preferred Solution**
One way I imagine this to be implemented is by creating a property, something like:

`<ion-select interface="alert" autoclose="true">`

That way, the "OK" button would not be rendered, and with this, clicking on the option the alert would already be closed automatically.

**Describe Alternatives**
An alternative approach would be to make an IonSelect.close method available and call it manually:

`<ion-select #myIonSelect>
    <ion-select-option (click)="myIonSelect.close()">Option 1</>
</>`

**Additional Context**
Well, the whole point for me is that the other interfaces (popover, action-sheet) do not align well with the UX needs of my project.
The alert interface has a header, an explicit close button. The only thing missing for my needs is to close automatically when selecting an option.

**Comment by salime45** [comment]
i have the same issue, any solution?

**Comment by ShahramCodeDeveloper** [comment]
this is my problem, how fix?

**Comment by lcsnwmn** [comment]
+1 to this enhancement request.

**Comment by codewise-nicolas** [comment]
+1 to this enhancement request.

**Comment by Toub** [comment]
The current behavior is not acceptable, and make the component not usable on my app.

Is there a workaround?

**Comment by liamdebeasi** [comment]
Hi everyone,

Thanks for the feedback and apologies for the delay. I discussed this with the team, and this is not a pattern we are looking to encourage with `ion-alert`.

Our concern here is this pattern does not match what native iOS and Android applications do. When presented with an alert, there is typically an explicit confirmation button that users need to press in order to confirm their selection in the alert. We think removing this confirmation will lead to a confusing user experience. Additionally, implementing this functionality would lead to inconsistencies within `ion-alert` particularly when users can select multiple values within the alert.

We strongly recommend using either `ion-action-sheet` or `ion-popover` with `ion-select` instead as the autoclose functionality is better suited for those user interfaces: https://ionicframework.com/docs/api/select

For developers who are unable to use `ion-action-sheet` or `ion-popover`, we recommend creating a [custom dialog with `ion-modal`](https://ionicframework.com/docs/api/modal#custom-dialogs) instead.

I am going to close this. Thank you!
