### ISSUE TITLE
bug: remove global hidden attribute styles

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-framework#17583]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
We have the following CSS in the global [`core` stylesheet](https://github.com/ionic-team/ionic/blob/master/core/src/css/core.scss#L90-L93):

```css
[hidden] { 
  display: none !important;
}
```

This causes conflicts with the native `hidden` attribute, see the MDN docs here:  https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden

<img width="695" alt="screen shot 2019-02-22 at 3 13 36 pm" src="https://user-images.githubusercontent.com/6577830/53268570-7830fb80-36b4-11e9-8d54-0f5ca17a83e9.png">

**Expected behavior:**
This style should not be there or it should not use `!important`. It may be seen as a breaking change to remove it but I'd argue it is a fix to a problem because it interferes with the native functionality of the attribute. Up for discussion.

**Steps to reproduce:**
1. Open this Codepen: https://codepen.io/brandyscarney/pen/XOLLLj
    - Verify the div is not displaying even though it has display block (adding `!important` does not override either)
1. Open this Codepen: https://codepen.io/brandyscarney/pen/YBooma
    - See that the div is displaying properly when Ionic is not included

**Other information:**
I stumbled on this while reviewing the following PR:  https://github.com/ionic-team/ionic/pull/17359

**Comment by ElNinjaGaiden** [comment]
I would say, more than only remove the `important!` config, this has to be removed at all, or treated in a different way.

On my code I do have an `IonButton` (@ionic/react) where I'm binding the hidden button property to a value on handled by the state of my main/parent component (the component that holds the IonButton) and even after my flag on the state is set to `false` and I get this code rendered:

<img width="457" alt="Screen Shot 2019-06-09 at 3 52 12 PM" src="https://user-images.githubusercontent.com/3424036/59164779-e74d2700-8ace-11e9-8a83-50d86f34ba37.png">

Even having the value of the property set to `false`, the button is inheriting the whole set of styles.

This, or, at least for that specific use case, the render logic should remove the `hidden` attribute at all instead of keep sending it as `hidden="false"` because the CSS is not using the attribute value in consideration due [this](https://github.com/ionic-team/ionic/blob/master/core/src/css/core.scss#L90)

**Comment by brandyscarney** [comment]
@ElNinjaGaiden Yes, I think that it should be removed entirely since it interferes with the functionality of the native attribute. My only concern is that it may be a breaking change to some apps if we remove this, so I would need to do some more thorough testing on it.

**Comment by liamdebeasi** [comment]
This was fixed in https://github.com/ionic-team/ionic-framework/pull/25829. Please note that since this is a breaking change, the fix will be available in Ionic 7, the next major release.
