### ISSUE TITLE
[Ionic 4] Angular Ionic router `animated: false` does not work on initial load

### ISSUE THREAD

**Issue by rossholdway** [ionic-team/ionic-framework#17714]
# Bug Report

**Ionic version:**

[x] **4.1.0**

**Current behavior:**
On initial load of an Angular Ionic app, the initial view containing a link that defines an `{animated: false}` option will still animiate on first click / tap.

**Expected behavior:**
I expect there to be no animation.

**Steps to reproduce:**
Create a link to another page with `animated: false` on the page that your app loads after booting. The link will still animiate to the next page on the first click / tap.
Clone the repo to see an example - [https://github.com/rossholdway/ionic-v4-nav-bug](https://github.com/rossholdway/ionic-v4-nav-bug)

**Related code:**
`this.navCtrl.navigateForward('/tabs/tab1/page1', {animated: false});`

**Comment by sean-perkins** [comment]
Hello, I realize this issue is a little old, but I wanted to thank you for reporting it all the way back in 2019!

I have confirmed this issue has since been resolved and works as expected in v6 (the page will not animate with the provided code snippet and reproduction app, upgraded to latest dependencies).
