### ISSUE TITLE
Being able to prevent ion-toggle from toggling

### ISSUE THREAD

**Issue by sneko** [ionic-team/ionic-framework#17748]
Hi,

I know there is the "disabled" property to completely prevent any click on the ion-toggle element but in some cases I would like to let the user clicks on the toggle, then it does an async process, and switch only if the process has succeeded.

For example, the user wants to turn ON an option that requires additional information (little form through a modal), if the user leaves the process, I would like to let the toggle on OFF (without seeing a quick transition OFF/ON/OFF).

I tried to catch the `click` event to stopPropagation... but it doesn't work, the toggle continues to move.

Maybe the easiest solution would be to make us able to trigger stopPropagation from the $event passed inside `ionChange`.

What do you think :) ?

Thanks,

**Comment by comfortme** [comment]
I think it's nice to have but seeing that transition also reminds the user consequences of his action.

**Comment by rathodkaran07** [comment]
@brandyscarney , any update on this?

**Comment by alemit** [comment]
You can read here https://medium.com/@aleksandarmitrev/ionic-toggle-asynchronous-change-challenge-7e7cbdd50cb7 how I worked around this thing

**Comment by alex-steinberg** [comment]
I did a similar workaround: https://github.com/alex-steinberg/ion-toggle-workaround-ionic5

**Comment by khaledosman** [comment]
had the same usecase, listening to click event instead of ionChange and using
```
e.stopImmediatePropagation();
e.stopPropagation();
e.preventDefault();
```
did the trick

**Comment by khaledosman** [comment]
I ended up reverting back to `ionChange` but overwrite the value in the event handler like this
```
e.target.checked = this.isToggleChecked
```

**Comment by amandaesmith3** [comment]
Hi everyone, thanks for the request. While the modal example is a valid use case, preventing the toggle from switching at all (without disabling it) creates confusion in UX. After internal discussion, we do not feel this feature would be a good fit for Ionic.

A more typical flow for native applications is:
1. Allow the toggle to switch on when the user taps it.
2. Run the async process (show the modal etc).
3. If the user cancels or the async process otherwise fails, manually switch the toggle back off.

This helps the user understand the connection between their actions and the toggle's state.

Here is an example from the Mint app: https://user-images.githubusercontent.com/90629384/142031270-ad66b956-092e-4d2c-a328-a7274f45f0a2.MP4

And here is a very simple demo repo with example code: https://github.com/amandaesmith3/toggle-demo The relevant code is in `src/app/home`.

For async processes that run in the background (i.e. without a visible modal), the MD spec suggests using a progress bar for delayed toggles (https://material.io/components/switches#behavior, under "Display processing status"). This could be accomplished with an `ion-progress-bar` component with type `indeterminate` (https://ionicframework.com/docs/api/progress-bar). Note that the toggle should still be allowed to switch; it can be manually switched back, perhaps with an error message, if the process fails.

I'm closing this issue out. See earlier posts for alternative workarounds, but we will not be implementing this feature directly. Thanks for using Ionic!
