### ISSUE TITLE
ionic vue virtual scroll

### ISSUE THREAD

**Issue by randytarampi** [ionic-team/ionic-framework#17887]
# Feature Request

It's not so much a feature request as just a question. I can see that it's supported in [`@ionic/react`](https://github.com/ionic-team/ionic/blob/master/react/src/components/index.ts#L106) and it seems like it just hasn't been gotten to on the Vue side.

Context here is that I'm trying to sell some folks at work on using Ionic+Vue at the moment, but it seems like loading large lists of images is the last stumbling block for our technical demonstrator.

Thanks for reading!

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
An `ion-virtual-scroll` Vue component, per the above.

**Describe Preferred Solution**
_It magically appears in `@ionic/vue@0.0.3`_

**Describe Alternatives**
I could roll my own solution but if it's as simple as what I think the [React port is doing](https://github.com/ionic-team/ionic/commit/696f62cfabcaa09a3f6cb9480b7c8b18ab1d39fd) and just passing things along, I figured that I'd ask.

**Related Code**
N/A

**Additional Context**
No related code, but the good folks behind `@modus/ionic-vue` in ModusCreateOrg/ionic-vue#85, pointed me in this direction.

**Comment by Livijn** [comment]
@randytarampi Did you make any progress on this?

**Comment by liamdebeasi** [comment]
Hey everyone,

Our current plan is to recommend solutions built and maintained by the Vue community. We are evaluating [vue-virutal-scroller](https://github.com/Akryum/vue-virtual-scroller) and [vue-virtual-scroll-list](https://github.com/tangbc/vue-virtual-scroll-list/issues/253) as potential solutions, but neither have shipped support for Vue 3 yet.

I am going to keep this issue open for now, but will close it out when clearer guidance has been put out on our docs. Thanks!

**Comment by HakobiDev** [comment]
It seems it doesn't supported yet by both alternatives, any plans to use this built in ionic virtual scroll for vue3? @liamdebeasi

**Comment by liamdebeasi** [comment]
We do not have plans to use our own custom virtual scroll solution for Ionic Vue. I need to do more research into https://github.com/tangbc/vue-virtual-scroll-list to see what parts of Vue 3 it does not support yet.

**Comment by TomDeSmet** [comment]
This one is working: https://www.npmjs.com/package/vue3-virtual-scroller

**Comment by florian72810** [comment]
[vue-virtual-scroller](https://github.com/Akryum/vue-virtual-scroller) has now support for Vue3 ([478](https://github.com/Akryum/vue-virtual-scroller/issues/478))

[Docs for Vue3 here](https://github.com/Akryum/vue-virtual-scroller/blob/next/packages/vue-virtual-scroller/README.md)

**Comment by liamdebeasi** [comment]
Hi everyone,

We are working on documentation to show how to get your Ionic Vue app setup with packages such as `vue-virtual-scroller`: https://github.com/ionic-team/ionic-docs/pull/1943

One thing to note is that certain components (like `ion-refresher` and the collapsible large title) are not currently compatible with virtual scrolling solutions due to their reliance on scrolling on `ion-content`. I created https://github.com/ionic-team/ionic-framework/issues/23437 which will track progress on improving compatibility with these components.

We are wrapping up the new docs now, so I plan on closing this issue out once those docs ship. Thanks!

**Comment by liamdebeasi** [comment]
Hi everyone,

We added a Virtual Scroll guide to the Framework v6 docs on how to get setup with a virtual scrolling solution in Ionic Vue: https://beta.ionicframework.com/docs/vue/virtual-scroll

While these are the v6 docs, you should be able to get setup with virtual scrolling in your v5 application (We are shipping the docs for v6 since `ion-virtual-scroll` will be deprecated then).

I am going to close this issue out since virtual scrolling in Ionic Vue has been documented. Thanks!
