### ISSUE TITLE
ion-icons not being aligned correctly in label and button

### ISSUE THREAD

**Issue by mpanneck** [ionic-team/ionic-framework#18033]
# Bug Report

**Ionic version:**

[x] **4.2.0**

**Current behavior:**

When using ion-icon inside a button or label, text and icon are not aligned correctly.

**Expected behavior:**

Icon and text should be aligned.

**Steps to reproduce:**

**Related code:**

```
<ion-header>
  <ion-toolbar>
    <ion-title>Anmeldung</ion-title>
  </ion-toolbar>
</ion-header>
<ion-content>
  <ion-item>
    <ion-label position="floating"><ion-icon name="person"></ion-icon> Benutzername</ion-label>
    <ion-input></ion-input>
  </ion-item>
  <ion-item>
    <ion-label position="floating"><ion-icon name="lock"></ion-icon> Passwort</ion-label>
    <ion-input></ion-input>
  </ion-item>
  <ion-item>
    <ion-label position="floating"><ion-icon name="globe"></ion-icon> Server</ion-label>
    <ion-input></ion-input>
  </ion-item>
  <ion-button expand="block" class="ion-margin-top">
    <ion-icon slot="start" name="star"></ion-icon> Anmelden
  </ion-button>
</ion-content>
```
results in
![ionic-bug](https://user-images.githubusercontent.com/37032012/56136696-97048d80-5f93-11e9-8e8b-7692e4e28123.JPG)

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\mpanneck\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.19
   @capacitor/core           : 1.0.0-beta.19

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! Would you say this is the same as https://github.com/ionic-team/ionic/issues/16422?

Thanks!

**Comment by mpanneck** [comment]
It looks similar but has a little difference:
In my example I've included the icons inside the labels. This is necessary because I want to use floating labels. So the icons should float as well.

Besides in #16422 no buttons are mentioned.

**Comment by brandyscarney** [comment]
Thanks for the issue! Here's a workaround for this: https://codepen.io/brandyscarney/pen/WWXrLg?editors=1100

**Comment by CitizenBeta** [comment]
@brandyscarney should we be doing that globally or will that create issues? Not recommended?

**Comment by troygilbert** [comment]
I'm encountering this as well, and it's not related to ion-label, it occurs with an ion-item and any textual content (I want the ion-icon to flow as part of the text). The fix above kinda fixes it, but the padding-bottom has to be adjusted based on the text size or icon. Feels wrong!

**Comment by brandyscarney** [comment]
Hello! We have revisited this issue with the latest version of Ionic Framework (v7) and have found the following:

The **button alignment** has been resolved since this issue was created. Below is a comparison between the button from the image in this issue and a button using the latest version of Ionic Framework: 

![button-comparison](https://github.com/ionic-team/ionic-framework/assets/6577830/73c401ad-bc06-4f1d-bb96-cc68377eb491)

---

The **label alignment** is a bit trickier. Due to the fact that `ion-label` is used in many components & different scenarios, we cannot add the CSS I originally included as a workaround. For example, adding `display: flex` to `ion-label` causes the following markup in an `ion-label` to render horizontally:

| `display: block` | `display: flex` |
| ---| ---|
| ![display block](https://github.com/ionic-team/ionic-framework/assets/6577830/4e9488c5-7440-4b4c-93f0-d03ebfd4ac24) | ![display flex](https://github.com/ionic-team/ionic-framework/assets/6577830/385c1b07-f21e-4fcd-8fe9-c076c7e767a6) |

The above could be solved by applying `flex-direction: column`, but that would result in breaking the markup in this issue:

| `flex-direction: row` (initial value) | `flex-direction: column` |
| ---| ---| 
| ![flex direction initial](https://github.com/ionic-team/ionic-framework/assets/6577830/0a949051-ddc4-49a6-8469-5291360a8581) | ![flex direction column](https://github.com/ionic-team/ionic-framework/assets/6577830/1709d9c5-57bf-433f-9d38-d1cc4fda5f2f) |

In addition, adding an icon inside of a floating label does not align with the Material Design Guidelines. In both [Material Design 2](https://m2.material.io/components/text-fields#interactive-demo) (released in 2018) and [Material Design 3](https://m3.material.io/components/text-fields/specs) (released in 2021) the leading icon does not float with the text. 

| Material Design 2 | Material Design 3 |
| ---| ---|
| ![Material Design 2](https://github.com/ionic-team/ionic-framework/assets/6577830/bb2dbf45-fdf5-4419-9d43-206a6e3349c2) | ![Material Design 3](https://github.com/ionic-team/ionic-framework/assets/6577830/1135ec87-10f7-4d6c-828a-404d90c4981c) |

---

As a result of the above, we have decided not to change the styling on the `ion-label` element as adding the required styling to solve this issue would break other use cases. Any custom styles should be added by the app developer. To achieve the UI requested in the original issue, a [label slot](https://ionicframework.com/docs/api/input#label-slot-experimental) can be used with the modern syntax (note that `v7.1.0` or later is required for this to work):

```html
<ion-item>
  <ion-input label-placement="floating">
    <div slot="label" style="display: flex; align-items: center;">
      <ion-icon name="person" style="margin-right: 6px;"></ion-icon>
      Benutzername
    </div>
  </ion-input>
</ion-item>
<ion-item>
  <ion-input label-placement="floating">
    <div slot="label" style="display: flex; align-items: center;">
      <ion-icon name="lock-closed" style="margin-right: 6px;"></ion-icon>
      Passwort
    </div>
  </ion-input>
</ion-item>
<ion-item>
  <ion-input label-placement="floating">
    <div slot="label" style="display: flex; align-items: center;">
      <ion-icon name="globe" style="margin-right: 6px;"></ion-icon>
      Server
    </div>
  </ion-input>
</ion-item>
``` 

<img width="386" alt="items with inputs" src="https://github.com/ionic-team/ionic-framework/assets/6577830/4ac98f29-6aaf-4fe3-ad07-240b55be355a">

---

However, if you intend to match Material Design Guidelines, which we recommend, we are working on adding [start and end slots to input](https://github.com/ionic-team/ionic-framework/pull/28397) to support [icons in an input](https://github.com/ionic-team/ionic-framework/issues/26297). 

If anyone is running into other alignment issues please create a new issue, thank you!
