### ISSUE TITLE
feat: disable content scrolling on ion-item-sliding slide event

### ISSUE THREAD

**Issue by Spinnenzunge** [ionic-team/ionic-framework#18219]
# Feature Request
Disable content scrolling if ion-item-sliding slide-event is in motion.

**Ionic version:**

[x] **4.3.1**

**Describe the Feature Request**
Disable the content scrolling while sliding an ion-item-sliding, so it feels more natural. iOS Mail app can not scroll vertically while sliding.

**Describe Preferred Solution**
Scrolling is not possible while sliding. e.g. iOS Mail.

**Additional Context**

![scrollmove](https://user-images.githubusercontent.com/11189008/57371459-0e909b80-7193-11e9-8d38-59b881385e94.gif)

**Comment by topalavlad** [comment]
Would it be OK if I gave this feature implementation a try?

As a quick prototype, in `item-sliding.tsx` I added a custom class containing `--overflow: hidden;` to `this.el.closest('ion-content')` from `onStart()` and removed it `onEnd()`.

Is this a bad approach since it modifies properties on a parent element or is it OK? Would an event-based approach be better?

**Comment by topalavlad** [comment]
Gave it a try. Tried to see if consuming the event is an option but it is not since the event is wrapped in `GestureDetail`

**Comment by roopeshreddy** [comment]
Is there any update on this? We're on v4.9.0 and issue still exists!

**Comment by tomfebry** [comment]
v4.9.1 still nothing

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved in Ionic Framework v5.6.14.
