### ISSUE TITLE
bug: Vue routing in tabs mode cause re-render

### ISSUE THREAD

**Issue by xar** [ionic-team/ionic-framework#18292]
# Bug Report

**Ionic version:**
[x] **4.4**

**Current behavior:**
Simple tabs structure in vue project with ionic vue router. When I switch tab previous component is removed from DOM and after that It needs to be fully re-rendered when I go back to that tab. It's reproducible also on ionic-vue-conference app. But working correctly on ionic-conference-app.

**Expected behavior:**
Component doesn't get removed but will be hidden.

**Steps to reproduce:**
![Ionic conference app bug](https://d2ddoduugvun08.cloudfront.net/items/0c232s2k111Z0i2T0G2g/Screen%20Recording%202019-05-16%20at%2011.43%20pm.gif?X-CloudApp-Visitor-Id=1293225&v=794002c1)

**Related code:**
```
<ion-tabs>
    <ion-tab tab="dashboard">
        <!--                <DashboardIndex />-->
        <ion-vue-router name="dashboard" />
    </ion-tab>
    <ion-tab tab="benefits" :routes="['page2']">
        <ion-vue-router name="page2" />
    </ion-tab>
    <ion-tab tab="results" :routes="['page3']">
        <ion-vue-router name="page3" />
    </ion-tab>
    <ion-tab tab="profile" :routes="['page4']">
        <ion-vue-router name="page4" />
    </ion-tab>
    <template slot="bottom">
        <ion-tab-bar :key="1">
            <ion-tab-button v-for="tab in tabs" :key="tab.routeName" :tab="tab.routeName">
                <ion-label>{{ tab.title }}</ion-label>
                <ion-icon name="home"></ion-icon>
            </ion-tab-button>
        </ion-tab-bar>
    </template>
</ion-tabs>
```

**Comment by michaeltintiuc** [comment]
@xar what's the behaviour if the contents of the tabs are not `ion-vue-router` elements but a Vue component or simple HTML instead?

**Comment by michaeltintiuc** [comment]
@xar if you look closely, the contents of the router are now an empty comment, this is due to the fact that the router renders an empty node as it did not match the route you're currently on, this is ultimately an issue with the Vue router, you can save it's state though by doing this:
1. Using `router-view` instead of `ion-vue-router`
2. Wrapping the above in `keep-alive`

The reason for switching to `router-view` is due to a hard requirement of the `transition` element being the parent of `keep-alive` as per [the docs](https://vuejs.org/v2/api/#keep-alive). Unfortunately this is what is powering ionic transitions in Vue.

**Comment by xar** [comment]
@michaeltintiuc aa, you are correct. I understand now. In the end I have used router-view and probably will end making some ionic like transitions other way

**Comment by michaeltintiuc** [comment]
I'll be working towards enabling `keep-alive` support for `ionic-vue-router` it is a nice feature to have

**Comment by Livijn** [comment]
There are tons of other bugs in the *ionic-conference-app* example. The `ion-tabs` is unusable at the moment. Looking forward seeing some updates! 🍺

**Comment by michaeltintiuc** [comment]
I totally forgot to mention the PR here, it's been open for quite a few days now ;)
https://github.com/ionic-team/ionic/pull/18561
