### ISSUE TITLE
feat: ion-datetime: add required property

### ISSUE THREAD

**Issue by tomavanc** [ionic-team/ionic-framework#18581]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Add a `required` property to `ion-datetime` to use and validate in a **form**.

**Related Code from `ion-input`**

```javascript
/**
 * If `true`, the user must fill in a value before submitting a form.
 */
@Prop() required = false;
```

**Comment by liamdebeasi** [comment]
Thanks for the report. There has not been much support for this from the community since the issue was opened. Due to this, the team does not have plans to implement this in the immediate future. I am going to close this for now. However, we may re-consider this feature in the future if community support grows.
