### ISSUE TITLE
bug: Ion-slides starts at index 0 then swaps to initialSlide slide

### ISSUE THREAD

**Issue by oneserve** [ionic-team/ionic-framework#19082]
# Bug Report

**Ionic version:**
[x] **4.7.1**

**Current behavior:**
Ion-slides starts at index 0 then swaps to initialSlide slide

**Expected behavior:**
Ion-slides starts initialSlide index

**Steps to reproduce:**

As can be seen on example app, the slide with 0 index (red background) flashes for number milliseconds, before it is set to index set in options property (yellow background)

**Related code:**

Editor
https://stackblitz.com/edit/ionic-v4-angular-tabs-xhahxe

Sample App
https://ionic-v4-angular-tabs-xhahxe.stackblitz.io

**Comment by yunho2141** [comment]
please fix this issue...

**Comment by ops5** [comment]
Why do you want to start from 3 and not from 0?

**Comment by oneserve** [comment]
Does it matter ? This is part of settings so it should work. My case is that each slide represents a day and "today" slide can be at any index.

**Comment by ops5** [comment]
You can reorder your 'dynamicSlides' array in your component according to the current day and solve the problem temporarily.

**Comment by liamdebeasi** [comment]
Thanks for the issue!

Starting with Ionic 5.7.0, we deprecated `ion-slides` in favor of having developers install Swiper.js directly in their projects. This gives developers access to new features, an improved developer experience, and bug fixes that they did not have access to when using `ion-slides`.

Since `ion-slides` uses Swiper.js under the hood, this migration should allow the functionality of your slides to remain exactly the same.

As a result of this deprecation, we have suspended any new development on `ion-slides` with the exception of critical fixes, such as resolving security issues.

I am going to close this issue out, but we strongly encourage you to try out the latest version of Swiper.js in your project. We have found that upgrading to the latest version of Swiper.js resolved a large number of common problems that Ionic developers were running into.

Please see https://ionicframework.com/docs/api/slides for more information on this change as well as a step by step migration guide for your apps. Developers will have approximately 1 year to migrate, starting from the initial deprecation in September 2021.

I understand this may not be the immediate resolution you were hoping for, but we think this change will significantly improve the developer experience in the long run by placing control of slides back in the hands of the developers.
