### ISSUE TITLE
bug: Ionic 4.7 web components styles bug

### ISSUE THREAD

**Issue by GuilhermeBCC** [ionic-team/ionic-framework#19121]
# Bug Report

**Ionic version:**

[x] **4.7**

**Current behavior:**
Parent component styles are not incorporated into web components correctly.
![image](https://user-images.githubusercontent.com/28517010/63209137-85eb9a80-c0b3-11e9-8a06-f2b83dd4645b.png)
Here only 3 styles have been added.
**Expected behavior:**
Web components should incorporate all styles of parent components.
The problem for me: Not incorporating the AppComponent style BREAK all my web components.

**Steps to reproduce:**
See:
https://stackblitz.com/edit/ionic-v4-angular-tabs-mrvktt

**Comment by liamdebeasi** [comment]
Thanks for the issue. What is the issue you are running into? I'm not sure I quite understand your screenshot.

**Comment by GuilhermeBCC** [comment]
The capture shows that only 3 styles were incorporated into the Web Component my-card.

I know and you may be wondering what ionic has to do with it.. 

Sorry, but i don't know why this is happening when installing ionic version 4.7. I did a lot of testing to find out what was causing it.

See this is how it is in version 4.6.

![image](https://user-images.githubusercontent.com/28517010/63315137-74d3a100-c2e0-11e9-965e-3374def1bde5.png)

All styles are incorporated into my web component.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This issue was resolved during Ionic v5, but the issue was never closed out. Updating to the latest version of Ionic v5 causes this issue to no longer reproduce, so I am going to close this thread out. The main issue here appeared to be related to multiple versions of Ionic and Stencil being installed, but updating both packages to the latest version fixes the issue on my end.

If you encounter any additional problems, please open a new issue and include a code reproduction. Thank you!
