### ISSUE TITLE
ion-slides scrollbar="top|bottom"

### ISSUE THREAD

**Issue by mewild** [ionic-team/ionic-framework#19139]
**Ionic version:**
4.7.1

**I'm submitting a ...** 
[ ] bug report
[ x] feature request

**Current behavior:**
Ion-slides allow the ability to add a scroll bar to the bottom of slides.

**Expected behavior:**
The ability to specify where the scrollbar is placed

**Steps to reproduce:**
```
<ion-slides scrollbar="true>
    <ion-slide>CONTENT</ion-slide>
</ion-slides>

```

**Potential solution**
The underlying library Swiper has a HTML element that is placed at the end of the block. Moving this to the front may result in the scrollbar being at the top?

```
<div class="swiper-container">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
        <!-- Slides -->
        <div class="swiper-slide">Slide 1</div>
        <div class="swiper-slide">Slide 2</div>
        <div class="swiper-slide">Slide 3</div>
        ...
    </div>
    <!-- If we need pagination -->
    <div class="swiper-pagination"></div>

    <!-- If we need navigation buttons -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>

    <!-- If we need scrollbar -->
    <div class="swiper-scrollbar"></div>
</div>
```

**Comment by liamdebeasi** [comment]
Thanks for the issue!

Starting with Ionic 5.7.0, we deprecated `ion-slides` in favor of having developers install Swiper.js directly in their projects. This gives developers access to new features, an improved developer experience, and bug fixes that they did not have access to when using `ion-slides`.

Since `ion-slides` uses Swiper.js under the hood, this migration should allow the functionality of your slides to remain exactly the same.

As a result of this deprecation, we have suspended any new development on `ion-slides` with the exception of critical fixes, such as resolving security issues.

I am going to close this issue out, but we strongly encourage you to try out the latest version of Swiper.js in your project. We have found that upgrading to the latest version of Swiper.js resolved a large number of common problems that Ionic developers were running into.

Please see https://ionicframework.com/docs/api/slides for more information on this change as well as a step by step migration guide for your apps. Developers will have approximately 1 year to migrate, starting from the initial deprecation in September 2021.

I understand this may not be the immediate resolution you were hoping for, but we think this change will significantly improve the developer experience in the long run by placing control of slides back in the hands of the developers.
