### ISSUE TITLE
bug: setting a slide active does not work if it is already visible

### ISSUE THREAD

**Issue by petergrau** [ionic-team/ionic-framework#19156]
# Bug Report

**Ionic version:**
[x] **4.8**

**Current behavior:**
Topic: `ion-slides`
If you display multiple `ion-slide` at the same time using the setting `slidesPerView: 3,` the method 

```
slideTo(index: number, speed?: number | undefined, runCallbacks?: boolean | undefined) => Promise<void>
```

does not activate / execute the `slideTo`

**Expected behavior:**
Expectation would be that even if the slide is visible the slider would mark the desired slide as `active`

**Steps to reproduce:** 
In the code example press the button `make pic three active`
With the setting
```
public slideOptsThumb = {
    slidesPerView: 3,
  };

```
it will NOT mark the third slide as active.

With the setting

```
public slideOptsThumb = {
    slidesPerView: 1,
  };
```
it will correctly mark the third slide as active.

**Related code:**

https://stackblitz.com/edit/ionic4-slider

**Other information:**

**Ionic info:**
Here is my local ionic info - version might be a bit different than on stackblitz but same error.

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/.nvm/versions/node/v8.11.4/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.7
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.7
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 29 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 6.1.3
   NodeJS     : v8.11.4 
   npm        : 5.6.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61

```

**Comment by liamdebeasi** [comment]
Thanks for the issue!

Starting with Ionic 5.7.0, we deprecated `ion-slides` in favor of having developers install Swiper.js directly in their projects. This gives developers access to new features, an improved developer experience, and bug fixes that they did not have access to when using `ion-slides`.

Since `ion-slides` uses Swiper.js under the hood, this migration should allow the functionality of your slides to remain exactly the same.

As a result of this deprecation, we have suspended any new development on `ion-slides` with the exception of critical fixes, such as resolving security issues.

I am going to close this issue out, but we strongly encourage you to try out the latest version of Swiper.js in your project. We have found that upgrading to the latest version of Swiper.js resolved a large number of common problems that Ionic developers were running into.

Please see https://ionicframework.com/docs/api/slides for more information on this change as well as a step by step migration guide for your apps. Developers will have approximately 1 year to migrate, starting from the initial deprecation in September 2021.

I understand this may not be the immediate resolution you were hoping for, but we think this change will significantly improve the developer experience in the long run by placing control of slides back in the hands of the developers.
