### ISSUE TITLE
ion-tab-button as a directive

### ISSUE THREAD

**Issue by LeandroDoldan** [ionic-team/ionic-framework#19226]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
There are a lot of issues open in the forums and in StackOverflow regarding tabs navigation. styling. A lot of developers -me included- would benefit for adding that behavior to any button.

Just to give an example, creating a [material like navigation](https://www.google.com/search?q=material+fab+navigation&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj9xJn0iajkAhV3IrkGHVzhDGQQ_AUIESgB&biw=1707&bih=803&dpr=1.13) is very difficult.

**Describe Preferred Solution**
An `ion-tab-button` directive that can be added to any HTML element -or at least to any button- that aggregates the `tab` attribute. When the element is clicked, the normal tab behavior is triggered.

**Describe Alternatives**
The current alternative is to use the `ion-tab-button` component and modify its look-and-feel.

Thank you!

**Comment by liamdebeasi** [comment]
Thanks for the issue, and apologies for the delay. We do not have plans to implement this feature at the moment. In the time since this feature request was created, we have added the `native` CSS Shadow Part to `ion-tab-button` which should allow for additional customization: https://ionicframework.com/docs/api/tab-button#css-shadow-parts

If there are other styling-related issues with `ion-tab-button`, please open a new issue and we will happy to address them.
