### ISSUE TITLE
feat: DateTime field should allow placeholder as well as starting date

### ISSUE THREAD

**Issue by REPTILEHAUS** [ionic-team/ionic-framework#19310]
I need a placeholder which says "select date of birth (optional)" and I also need that when the user interacts with the field the default date is set to the year 1960, but this is not a min/max the user should be freely able to select a year anytime in the past or future, if they have not selected anything then the field displays the placeholder.

```Ionic:

   Ionic CLI                     : 5.2.1
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.801.0
   @angular-devkit/schematics    : 8.1.0
   @angular/cli                  : 8.1.0
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.0.0, ios 5.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 29 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed```

**Comment by REPTILEHAUS** [comment]
I would like to reference this Stackoverflow post https://stackoverflow.com/questions/55242266/ionic-3-ion-datetime-possible-to-show-both-preassigned-value-and-placeholder

**Comment by liamdebeasi** [comment]
Thanks for the issue. With the release of Ionic v6 we are releasing a brand new `ion-datetime` component that displays a calendar picker instead of a wheel. As a result, a placeholder is no longer used.

I am going to close this issue since it no longer applies to the new `ion-datetime` component. We will have a full migration guide for `ion-datetime` that will show you how to apply this customization to your app as we get closer to launch. Thank you!

For more information on Ionic v6, please see: https://ionicframework.com/blog/announcing-the-ionic-framework-v6-beta/.
