### ISSUE TITLE
feat: NavController.pop() go back multiple pages.

### ISSUE THREAD

**Issue by tienphan1096** [ionic-team/ionic-framework#19314]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
Allow navController.pop() to to go back multiple pages.

**Describe Preferred Solution**
navController.pop() will accept a 'deep' variable as the number of pages to go back. If 'deep' is not specified, default to going back one level.

**Describe Alternatives**
N/A

**Related Code**
To be submitted in PR.

**Additional Context**
I'm working on an app where going back 2 pages is crucial to user experience, but there isn't an easy way to do that right now in Ionic, apart from using navigateBack(). However, navigateBack() is not very ideal since the URL has to be the exact same, which means route params also have to be the same, i.e /home;foo=bar.

I already have this implemented locally. I've tested it going back to earlier pages in the navigation stack. Can I submit a PR for this?

**Comment by tienphan1096** [comment]
Here's the PR https://github.com/ionic-team/ionic/pull/19328

**Comment by Franco-Alejandro** [comment]
Why wasn't this merged already?

**Comment by amandaesmith3** [comment]
Thanks for the issue and PR! We appreciate your work, and I wanted to circle back to this.

In the time that's passed, we've moved away from our own `navController` in favor of integrating with the official Angular Router (https://ionicframework.com/docs/reference/migration#navigation). Because of this, I'm going to close this out. If this is still something you're facing in the latest version of Ionic, feel free to open a separate issue. Thank you!
