### ISSUE TITLE
ionic 4 angular 8 ionic lab windows platform bug

### ISSUE THREAD

**Issue by FernandoFranzini** [ionic-team/ionic-framework#19394]
HI
I am trying to run a simple ionic blank --type=angular project in ionic lab on localhost:8200. The ios and android platfoms are working well but the windows platform doesn't work, it shows black screen in the virtual emulator. I checked in the google browser inspect element and ther is the issue: Error: Cannot find module './undefined.entry.js' at .*.entry.js$ include: .entry.js$ exclude: .system.entry.js$ namespace object:394 at ZoneDelegate.invoke (zone-evergreen.js:365) at Zone.run (zone-evergreen.js:124) at zone-evergreen.js:851 at ZoneDelegate.invokeTask (zone-evergreen.js:400) at Zone.runTask (zone-evergreen.js:168) at drainMicroTaskQueue (zone-evergreen.js:570)

zone-evergreen.js:659 Unhandled Promise rejection: Cannot read property 'isProxied' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'isProxied' of undefined at initializeComponent (chunk-84f6bf13.js:1684) TypeError: Cannot read property 'isProxied' of undefined at initializeComponent (http://localhost:8100/vendor.js:104980:24)

**Comment by meanstack-perficient** [comment]
receiving same
this one is terrible... no leads as to where to track it down

**Comment by meanstack-perficient** [comment]
This error is a manifestation of a variety of things
an object is expected somewhere and is not modeled properly
in iOS and Android, if your plugins are not configured properly, you will get a blank screen because something was expected that was not configured properly within the package.json, plugins config as it pans into the platforms

for me though I am doing simple ngrx on ionic and this was due to a malformed ngrx state configuration whereby the configuration of the ngrx model was expecting something that wa not rigged/configured properly

its a shame these kinds of errors are not more descriptive as they land fairly deep and will take days to figure them out

I am still modeling my way out of this and if this does persist to be an actual bug I will remit

but for now its leaning towards malformed configuration landing deep

**Comment by meanstack-perficient** [comment]
if your using sidenav menu
for ionic
make sure you remove "mode='push'" from your html menu element 
otherwise ionic will fall thru the floor and you will have no app

the bug
`<ion-menu type="overlay" #sidenav mode='push'>`
the solution
`<ion-menu type="overlay" #sidenav>`

i remain unimpressed with the stack trace 
deceiving misleading 
spent days tearing down my module architecture in every direction to try and shake this out
because it eluded to a module and entry... (lazy loaded module? or other router module?)
luckily some issue on internet mentioned mode=" "

ngrx is solid

and runs beautiful... never an issue

**Comment by meanstack-perficient** [comment]
so im unsure... what to call this, bug?

**Comment by FernandoFranzini** [comment]
I'm not using <ion-menu....
here is my simple page:

`<ion-header>
  <ion-toolbar>
    <ion-title>
      Transferência Bancária
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content fullscreen>
    <ion-list lines="full" class="ion-no-margin ion-no-padding">
      <ion-item>
        <ion-label position="stacked">Conta Débito:</ion-label>
        <ion-input type="text" placeholder="Digite conta débito"(focusout)="getConta1()" [(ngModel)]="dados.conta1"></ion-input>
        <ion-input type="text" [(ngModel)]="dados.desc1"></ion-input>
      </ion-item>
      <ion-item>
        <ion-label position="stacked">Conta Crédito:</ion-label>
        <ion-input type="text" placeholder="Digite conta crédito" (focusout)="getConta2()" [(ngModel)]="dados.conta2"></ion-input>
        <ion-input type="text" [(ngModel)]="dados.desc2"></ion-input>
      </ion-item>
      <ion-item>
        <ion-label position="stacked">Valor R$</ion-label>
        <ion-input type="text" placeholder="Digite o valor" [(ngModel)]="dados.valor"></ion-input>
      </ion-item>
      </ion-list>
      <div class="ion-padding">
        <ion-button expand="block" type="submit" class="ion-no-margin" (click)="transferir()">Transferir</ion-button>
      </div>
</ion-content>`

**Comment by meanstack-perficient** [comment]
my research points to mode="whatever"

when removed the error is gone

im movin on

**Comment by FernandoFranzini** [comment]
mode="whatever"?
Where a set this?

**Comment by lincolnthree** [comment]
The issue here is not that you need to *add* the mode flag, it's that you probably have the mode flag defined with an invalid value.

Mode can either be 'md', 'ios', or not set at all.

If it is set to anything else, this error occurs. I have reported this issue to the Ionic team here:
https://github.com/ionic-team/ionic/issues/20055

**Comment by Neseek77** [comment]
I have just created a blank app using "ionic start myApp blank".
While "ionic serve --lab" throws this error.

![Screen Shot 2020-01-08 at 12 12 42 PM](https://user-images.githubusercontent.com/13345837/71956248-a78b2100-3210-11ea-8178-f9c97cb1eec9.png)

**Comment by bleuscyther** [comment]
if the value of mode is wrong like **ioss**, it will generate that error thx @meanstack-perficient . 😭 one hour lost on this

**Comment by PatrykJankowski** [comment]
I have found a similar bug. To reproduce:
- create new project by using `ionic start testAaa list --capacitor`
- `ionic serve`
- open app in chrome and set offline mode in developer tools
- click on one of the items from the list on scrren

However, if you first open an item, go back to the main screen and then turn on offline mode and click the item again everything is ok.

So, the bug occurs only if you click on an item (open new a window) in offline mode before you do it online.

![obraz](https://user-images.githubusercontent.com/16896903/77457525-1e41be80-6dfd-11ea-8d35-3192b0b80ff1.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
