### ISSUE TITLE
bug: ion-slides don't scroll vertically properly when inside a modal

### ISSUE THREAD

**Issue by rhoffmancastlight** [ionic-team/ionic-framework#19431]
#Bug Report

**Ionic version:**
4.9.1

**Current behavior:**
When using ion-slides within a modal (created with ModalController), there is an issue with vertical scrolling. If user scrolls and then pauses for a moment, when trying to resume scrolling the screen freezes for several moments and does not allow scrolling. This is happening on iOS, not on browser.

**Expected behavior:**
User should be able to scroll vertically without getting stuck.

**Steps to reproduce:**
Run ionic serve, and click on "Present Modal" button on landing page

**Related code:**
https://gitlab.castlighthealth.com/rhoffman/test-modal

**Other information:**
Created a new topic in the Ionic forum with this issue: https://forum.ionicframework.com/t/issue-with-scrolling-ion-slides-in-modal/173807 

**Ionic info:**
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 4 other plugins)

System:

   Android SDK Tools : 26.0.2 (/Users/rhoffman/Library/Android/sdk)
   NodeJS            : v12.10.0 (/Users/rhoffman/.nvm/versions/node/v12.10.0/bin/node)
   npm               : 6.11.3
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8

**Comment by liamdebeasi** [comment]
Thanks for the issue!

Starting with Ionic 5.7.0, we deprecated `ion-slides` in favor of having developers install Swiper.js directly in their projects. This gives developers access to new features, an improved developer experience, and bug fixes that they did not have access to when using `ion-slides`.

Since `ion-slides` uses Swiper.js under the hood, this migration should allow the functionality of your slides to remain exactly the same.

As a result of this deprecation, we have suspended any new development on `ion-slides` with the exception of critical fixes, such as resolving security issues.

I am going to close this issue out, but we strongly encourage you to try out the latest version of Swiper.js in your project. We have found that upgrading to the latest version of Swiper.js resolved a large number of common problems that Ionic developers were running into.

Please see https://ionicframework.com/docs/api/slides for more information on this change as well as a step by step migration guide for your apps. Developers will have approximately 1 year to migrate, starting from the initial deprecation in September 2021.

I understand this may not be the immediate resolution you were hoping for, but we think this change will significantly improve the developer experience in the long run by placing control of slides back in the hands of the developers.
