### ISSUE TITLE
feat: Ionic v4 : Disable closing animation on ion-menu backdrop

### ISSUE THREAD

**Issue by raghav-kanwal** [ionic-team/ionic-framework#19687]
# Feature Request

**Ionic version:**

[x] **4.10.2

**Describe the Feature Request**

I wish to disable animations when opening and closing ion-menu.

When menu-type is overlay, opening the ion-menu reveals an ion-backdrop element. Clicking outside the menu on ion-backdrop triggers the close() method, which always triggers with an animation. Having some control to disable the animation, similar to what we have in close() in ion-menu would be nice.

**Describe Alternatives**

- Disable ion-backdrop click event for ion-menu and have a custom close method with a boolean for animation, similar to ion-menu's close() method.

**Related Code**

Reference : https://stackblitz.com/edit/ionic4-angular6-sidemenu-starter.
Need to be able to close the menu on Clicking of backdrop, without any closing animation. 

**Additional Context**

**Comment by liamdebeasi** [comment]
Hey there,

I spoke with the team, and we have decided to close this issue. There hasn't been much community support for this since the request was opened. If you are still interested in this feature, please open a new request and include your use case. We need to better understand the need for this feature before we can add it. Thank you!
