### ISSUE TITLE
bug: Text of the button is not visible when it's inside of ion-slide

### ISSUE THREAD

**Issue by daviddgl** [ionic-team/ionic-framework#19896]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
The text of the button doesn't appear until I click it when it's inside in an `ion-slide`. This happens only in iOS, iPhone or emulator.

**Expected behavior:**
The text of the button should be always visible.

**Steps to reproduce:**
You need to add an `ion-slide`, fill one slide from content and add a button at the bottom, so you'll need to scroll to the bottom of the slide to see the button.

You have to add the following style in the slide style scss:
```
ion-slides,
ion-slide {
  overflow-y: scroll;
  border-radius: 10px;
  height: 100% !important;
}
```

**Related code:**
Here you have a test project to reproduce this issue:
https://github.com/daviddgl/ionic_test_button

**Other information:**
Only reproducible with iOS, real iPhone and emulator. It works in Chrome and Android.

Here you can see a video reproducing the issue:
https://vimeo.com/372614579

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.2.7 (/Users/yc00082/.nvm/versions/node/v10.16.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.3
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 (update available: 0.2.9)

System:

   Android SDK Tools : 26.1.1 (/Users/yc00082/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/Users/yc00082/.nvm/versions/node/v10.16.3/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 11.2 Build version 11B52
```

**Comment by liamdebeasi** [comment]
Thanks for the issue!

Starting with Ionic 5.7.0, we deprecated `ion-slides` in favor of having developers install Swiper.js directly in their projects. This gives developers access to new features, an improved developer experience, and bug fixes that they did not have access to when using `ion-slides`.

Since `ion-slides` uses Swiper.js under the hood, this migration should allow the functionality of your slides to remain exactly the same.

As a result of this deprecation, we have suspended any new development on `ion-slides` with the exception of critical fixes, such as resolving security issues.

I am going to close this issue out, but we strongly encourage you to try out the latest version of Swiper.js in your project. We have found that upgrading to the latest version of Swiper.js resolved a large number of common problems that Ionic developers were running into.

Please see https://ionicframework.com/docs/api/slides for more information on this change as well as a step by step migration guide for your apps. Developers will have approximately 1 year to migrate, starting from the initial deprecation in September 2021.

I understand this may not be the immediate resolution you were hoping for, but we think this change will significantly improve the developer experience in the long run by placing control of slides back in the hands of the developers.
