### ISSUE TITLE
bug: address bar appears when navigating in pwas on ios

### ISSUE THREAD

**Issue by huang145632** [ionic-team/ionic-framework#19890]
# Bug Report

**Ionic version:** 4.11.0

**Current behavior:**

Open in the homescreen , enter other pages, an unexpected address bar appears

**Expected behavior:**

No address bar

**Steps to reproduce:**

**Related code:**

```
ionic start myApp tabs --type=react
cd myApp
ionic serve
```

**Other information:**

**Ionic info:**

![1.jpg](https://i.loli.net/2019/11/11/qbBPizxD9aHmTQc.jpg)
![2.jpg](https://i.loli.net/2019/11/11/7DpVjXMud4GSNiL.jpg)
![3.jpg](https://i.loli.net/2019/11/11/F6uoxsSEQwq1VGt.jpg)
![4.jpg](https://i.loli.net/2019/11/11/mRSxOA8tdBFXquc.jpg)
Unexpected address bar

**Comment by jeanp117** [comment]
You have to use HTTPS and a valid SSL certificate

**Comment by liamdebeasi** [comment]
Hi everyone,

This appears to be a behavior with how iOS handles navigating inside of a PWA. We are looking into what the root cause may be.

**Comment by liamdebeasi** [comment]
I checked with the team, and the problem is that your application likely does not have a `manifest.json` file. This is required for PWAs to function properly on iOS.

Here are steps you can take to get a simple `manifest.json` file added:

1. Create a `manifest.json` file in the public directory of your app (where `index.html` is served from).
2. Add the following to the `head` of your `index.html`:

```html
<link rel="manifest" href="manifest.json" />
```

3. In the `manifest.json` file you can add something like this:

```json
{
  "name": "TestApp",
  "short_name": "TestApp",
  "display": "standalone",
  "description": "An Ionic starter app"
}
```

From there you will need to re-add the app to the home screen.

**Comment by liamdebeasi** [comment]
We also have dedicated PWA guides for each framework integration.

Angular: https://ionicframework.com/docs/angular/pwa
React: https://ionicframework.com/docs/react/pwa
Vue: https://ionicframework.com/docs/vue/pwa
