### ISSUE TITLE
bug: Fixed ion-label width variable

### ISSUE THREAD

**Issue by mebibou** [ionic-team/ionic-framework#19970]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
This was already an issue I raised in version 3, but still present in version 4: #11666.
When using `<ion-label position="fixed">`, the width of the label is arbitrarily set to `100px`

**Expected behavior:**
We should be able to customize the width of the ion-label when using `fixed` positioning:
```
ion-select {
  --width: 50px;
}
```

**Related code:**

```html
<ion-item>
  <ion-label position="fixed">Label that will be ellipsized</ion-label>
  <ion-input type="text"></ion-input>
</ion-item>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.5 (/.nvm/versions/node/v12.5.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.3
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.6.0 (update available: 0.8.1)
   native-run  : 0.2.5 (update available: 0.2.9)

System:

   Android SDK Tools : 26.1.1 (/usr/local/Cellar/android-sdk/24.4.1_1)
   ios-deploy        : 1.9.2
   ios-sim           : 8.0.2
   NodeJS            : v12.5.0 (/.nvm/versions/node/v12.5.0/bin/node)
   npm               : 6.13.1
   OS                : macOS Catalina
   Xcode             : Xcode 11.2.1 Build version 11B500

```

**Comment by brandyscarney** [comment]
Thanks for the issue! The `ion-label` is a scoped component so the CSS can be changed directly without CSS variables:

```css
ion-label {
  flex: 0 0 100% !important;
}
```

Due to it being scoped it does need a higher specificity selector or the use of `!important`. We've written some on this here: https://ionicframework.com/docs/reference/glossary#scoped. You can tell if a component is scoped by the badge in the top right of its component documentation: https://ionicframework.com/docs/api/label

Example Codepen: https://codepen.io/brandyscarney/pen/dyMWgVm
