### ISSUE TITLE
bug: virtual-scroll updates list although already destroyed

### ISSUE THREAD

**Issue by jase88** [ionic-team/ionic-framework#20040]
# Bug Report

**Ionic version:**
[x] **4.11.5** ionic-angular

**Current behavior:**
if using a virtual scroll list in a short living component (e.g. modal) a Angular error occurs sometimes, because the component tries to update itself, although already destroyed:
```
Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
    at viewDestroyedError (core.js:19641)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:30040)
    at checkAndUpdateView (core.js:29439)
    at callWithDebugContext (core.js:30309)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (core.js:30011)
    at ViewRef_.push.../../node_modules/@angular/core/fesm5/core.js.ViewRef_.detectChanges (core.js:20686)
    at fesm5.js:4899
    at ZoneDelegate.invoke (zone.js:396)
    at Object.onInvoke (core.js:26256)
    at ZoneDelegate.invoke (zone.js:395)
```

If looking at the stack trace it occurs after a timeout on that component which calls ```updateVirtualScroll()``` after the view got destroyed (modal closed in my case). See related code

**Expected behavior:**
- component does abort updating if view is already destroyed
- no Angular error occurs

**Steps to reproduce:**

- Create a modal component with virtual-scroll on button click
- interact with list and close modal immediately

(sorry not able to provide a repo or StackBlitz)

**Related code:**

Corresponding code: 
https://github.com/ionic-team/ionic/blob/48a27636c76c1a05dc6d878be26cbe028552cbf7/core/src/components/virtual-scroll/virtual-scroll.tsx#L348

and

https://github.com/ionic-team/ionic/blob/48a27636c76c1a05dc6d878be26cbe028552cbf7/core/src/components/virtual-scroll/virtual-scroll.tsx#L246-L259

**Other information:**

**Ionic info:**

```
Ionic:
   Ionic CLI                     : 5.4.9 (C:\Users\kerosin\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.5 (c:\src\my-project\node_modules\@ionic\angular)
   @angular-devkit/build-angular : 0.803.20 (c:\src\my-project\node_modules\@angular-devkit\build-angular)
   @angular-devkit/schematics    : 8.3.20 (c:\src\my-project\node_modules\@angular-devkit\schematics)
   @angular/cli                  : 8.3.20 (c:\src\my-project\node_modules\@angular\cli)
   @ionic/angular-toolkit        : 2.1.1 (c:\src\my-project\node_modules\@ionic\angular-toolkit)

Utility:
   cordova-res : not installed
   native-run  : not installed

System:
   NodeJS : v12.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! With the release of Ionic 6 we will be deprecating `ion-virtual-scroll` in favor of JavaScript Framework solutions. As a result, we have a freeze on new development with the exception of critical bugs, such as security issues.

Using these new virtual scrolling solutions should provide a better developer experience, more performant app, and fewer bugs! We have created migration guides for the main 3 JavaScript Frameworks Ionic supports to make this migration easy for developers.

Migration for Angular users: https://ionicframework.com/docs/angular/virtual-scroll
Migration for React users: https://ionicframework.com/docs/react/virtual-scroll
Migration for Vue users: https://ionicframework.com/docs/vue/virtual-scroll  

The documentation for `ion-virtual-scroll` still exists at https://ionicframework.com/docs/api/virtual-scroll.

`ion-virtual-scroll` will be removed in Ionic 7. Developers do **not** need to migrate off `ion-virtual-scroll` in order to upgrade to Ionic 6 or to continue using it in Ionic 4/5.

I am going to close this issue. Thank you!
