### ISSUE TITLE
bug: Progress bar doesn't use theme colors

### ISSUE THREAD

**Issue by schontz** [ionic-team/ionic-framework#20098]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Using an `ion-progress-bar` with a dark theme results in a white progress bar.

**Expected behavior:**

Progress bar would pick up the theme colors.

**Steps to reproduce:**

1. Create an app with a progress bar
2. Use the dark theme
3. Progress bar is a white strip

**Related code:**
I had to do the following to fix it:
```css
ion-progress-bar {
  --buffer-background: var(--ion-background-color);
  --background: var(--ion-background-color);
  --progress-background: var(--ion-color-step-400);
}
```

It seems like that should be the default.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.12 
   Ionic Framework : @ionic/react 4.11.6

Capacitor:

   Capacitor CLI   : 1.2.1
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.11.0 
   npm    : 6.13.4
   OS     : macOS Mojave
```

**Comment by brandyscarney** [comment]
Thanks for the issue! The progress bar background is actually using `--buffer-background: rgba( 56,128,255 ,0.2);` which is appearing as white, but it is a shade of the primary color.

Per the [Material Design spec for dark theme](https://material.io/design/color/dark-theme.html#), it does need to be a darker shade of the primary color:

<img width="515" alt="Screen Shot 2019-12-18 at 4 16 32 PM" src="https://user-images.githubusercontent.com/6577830/71124575-1dbcda80-21b3-11ea-873f-916ea682b7ff.png">

I am adding all of this because this is a bug but when this issue is fixed it won't be using the colors you are setting it to. 🙂

**Comment by schontz** [comment]
Thanks for the update. I don't expect it to be the colors I picked, per se, but I assume it would pick up the appropriate theme colors.

**Comment by infacto** [comment]
Here's a demo on [Stackblitz](https://stackblitz.com/edit/ionic-5-progress-bar-dark-mode-issue?embed=1&file=src/app/tab1/tab1.page.html)

![image](https://user-images.githubusercontent.com/60390085/99792742-d445df80-2b27-11eb-80c4-a23a28004b5c.png)

![image](https://user-images.githubusercontent.com/60390085/99792749-d6a83980-2b27-11eb-8435-b671016cd1bb.png)

![image](https://user-images.githubusercontent.com/60390085/99792762-d90a9380-2b27-11eb-87dc-05f171a68cb1.png)
(Toggle the `background` in Browser DevTools)

Why is the background set to `255, 255, 255` (white)? It's not a variable. No half opacity. It's just fixed white.

**Comment by domske** [comment]
https://github.com/ionic-team/ionic-framework/blob/0a765c7172d49211e94ca5f37ca6059a33844b40/core/src/components/progress-bar/progress-bar.scss#L74-L77

Any demo / screenshots about this bug of "seen through"? But anyway. There should be no fixed color values. Any suggestions?

**Comment by domske** [comment]
https://github.com/ionic-team/ionic-framework/blob/0a765c7172d49211e94ca5f37ca6059a33844b40/core/src/components/progress-bar/progress-bar.scss#L74-L77

I'm not sure if this is the correct code line. Because changing it has no effect. 🤔 I tested it in the Ionic sources `test/basic` with the dark theme. And checked the dev tools. There is still:

```css
.progress-buffer-bar {
    background: #fff;
    z-index: 1;
}
```

**Comment by domske** [comment]
Here is the reason for the solid color.

https://github.com/ionic-team/ionic-framework/blob/0a765c7172d49211e94ca5f37ca6059a33844b40/core/src/components/progress-bar/progress-bar.scss#L74-L77

![demo](https://user-images.githubusercontent.com/28209992/99861787-b7e18b80-2b97-11eb-8997-98c195aaefbe.gif)

But, this should not be the solution. Never use fixed colors. Use theme variables or fixed colors with semi transparent color which does not interfere the theme. 

We need a dark mode for the test bench during development and in the docs.
But back to this issue: Any suggestions?

**Comment by infacto** [comment]
Could we assign `--buffer-background` with default `#fff` to keep the current behavior. But with the option that the user can change the it? It's better than a fixed solid color. I think the buffer feature is more rarely used than the default appearance. So with the accessibility to the buffer background variable I can control that color. This is the way how all other Ionic components work.

**Comment by domske** [comment]
I have a new idea and will make a pull request. I just use the solid theme color and overlay / blend it with pseudo element. I tested it with dark and light theme. Commit soon. 

Btw. testing with Stencil in Ionic Core is hell. Because the live relaod does not work when chaning styles in scss. It refreshes, but without the changes. Argh... I have to stop the server and build again. So it takes longer.
@brandyscarney Do you have the same problems with Stencil?

**Comment by domske** [comment]
Ok, I found a solution and will create a pull-request soon.
![fixed](https://user-images.githubusercontent.com/28209992/100153281-32662000-2ea4-11eb-9377-8ddb8f48da9f.gif)

**Comment by domske** [comment]
Just for info: I see that the [Angular Material](https://material.angular.io/components/progress-bar/) UI framework also have this issue. I guess for that same reason. 😃 (You can switch the theme light / dark in the toolbar above.)
![demo](https://user-images.githubusercontent.com/28209992/101090912-aba5f700-35b7-11eb-97f8-29c00f3fdb9e.gif)
To be honest, I have to say that I don't like the Angular Material Framework. Because it is too limited. A good material design framework is [Vuetify](https://vuetifyjs.com/en/components/progress-linear/). Which have a great progress-bar with the same behavior as the Ionic progress bar with my changes. See:
![demo-vue](https://user-images.githubusercontent.com/28209992/101091591-a5fce100-35b8-11eb-89e3-c73dd04effc1.gif)
I have not checked the source code yet. ...
