### ISSUE TITLE
bug: CSS Variables does not seem to get applied when placed within Shadow Dom of Lit Element component

### ISSUE THREAD

**Issue by tvvignesh** [ionic-team/ionic-framework#20294]
Hi. I am using IONIC within Lit-Elements. So, all my IONIC components are scoped to the shadow dom of the Lit Components. 

While IONIC provides css for supporting dark mode, the variables are anyways not propagated to the shadow dom due to isolation. How do we achieve dark mode for all the components in this case without having to go to each and every component and modify its css?

**PS:** While I have raised this issue for dark mode, the same issue occurs for all the cases. For eg. If I try to color the ionic button by giving the scheme as light or primary, it does not work since it is not able to get the css variable from within the shadow dom. I have to manually style it inside. Wondering if styles for such properties can be scoped within the component itself rather than having them as global styles.

**Comment by brandyscarney** [comment]
Thanks for the issue! Are you talking about styling the components using `color` or are you using the global theme variables here to theme an entire app: https://ionicframework.com/docs/theming/themes

It would be helpful to provide some code examples. Thank you!

**Comment by tvvignesh** [comment]
@brandyscarney Sorry for the confusion. It looks like I was doing it wrong. The dark mode is working. I had to set it properly. I did follow your guide to do the same.

But, the other issue regarding the css variables not being propagated still applies.

For eg: if I do `<ion-button color="light">Light</ion-button>`

While the element gets the relevant class for light color button like so when inspected:
`<ion-button color="light" class="ion-color ion-color-light md button button-solid ion-activatable ion-focusable hydrated">Light</ion-button>`

I still get the css for primary button like this where both the button as well as text is white:

```
:host(.button-solid) {
    --background-activated: #3880ff;
    --box-shadow: 0 3px 1px -2px rgba(0,0,0,0.2),0 2px 2px 0 rgba(0,0,0,0.14),0 1px 5px 0 rgba(0,0,0,0.12);
}
:host(.button-solid) {
    --background: #3880ff;
    --background-focused: #3171e0;
    --background-hover: #4c8dff;
    --color: #fff;
    --color-activated: #fff;
    --color-focused: #fff;
}
:host {
    margin-left: unset;
    margin-right: unset;
    margin-inline-start: 2px;
    margin-inline-end: 2px;
}
```

But, this works as expected when I use it outside the LitElement component (outside shadow dom)

**PS:** Since I don't have the dark mode issue anymore, renaming the title of this issue for the second part of the problem.

**Comment by brandyscarney** [comment]
@tvvignesh Thanks for the response! So this is an issue with Ionic components being placed inside of shadow DOM, you can see Manu's response on this here: https://github.com/ionic-team/ionic/issues/14840#issuecomment-439365125

I've brought this up to the Stencil team, but as of right now you would need to implement a workaround like the following:

```
:root {
  --ion-color-primary: #3880ff;
}

ion-button {
  --background: var(--ion-color-primary);
}
```

And repeat this for all of the variables / components you would want to change.

The conference app has some usage examples of this:

- variables file - https://github.com/ionic-team/ionic-conference-app/blob/master/src/theme/variables.scss
- using a variable - https://github.com/ionic-team/ionic-conference-app/blob/f67bfc73154457e9726ef6fae371b16c5217c238/src/app/pages/about/about.scss#L14

**Comment by tvvignesh** [comment]
@brandyscarney Thanks. Hmm.. I was wondering if I was doing something wrong. Got it. So, its basically declaring the styles again internally. While I can do this, my only concern is that, if the IONIC team changes CSS vars from one version to another, I have to upgrade each and every component's CSS to accomodate that in this case as opposed to 1 CSS file being changed.

I understand that the shadow dom does not let the styles to be applied, but isn't it possible for IONIC to bring the css of the component locally to the component level rather than a global CSS file? Just wondering.

Will go with this now then. Should I close this issue?

**Comment by brandyscarney** [comment]
@tvvignesh You shouldn't have to set all of the styles on the component again internally. This is only an issue with `color` because the way the color gets set is like the following:

```
<ion-button color="primary">
```

becomes

```
<ion-button class="ion-color ion-color-primary">
```

And the class for adding that color is defined globally like the following:

```
.ion-color-primary {
  --ion-color-base: var(--ion-color-primary, #3880ff) !important;
  --ion-color-base-rgb: var(--ion-color-primary-rgb, 56, 128, 255) !important;
  --ion-color-contrast: var(--ion-color-primary-contrast, #fff) !important;
  --ion-color-contrast-rgb: var(--ion-color-primary-contrast-rgb, 255, 255, 255) !important;
  --ion-color-shade: var(--ion-color-primary-shade, #3171e0) !important;
  --ion-color-tint: var(--ion-color-primary-tint, #4c8dff) !important;
}
```

Then inside of button (a solid one) it looks for this basically:

```
ion-button {
  background: var(--ion-color-base);
  color: var(--ion-color-contrast);
}
```

So the reason is that when you place the `ion-button` inside of a shadow element, it's not able to get the CSS variables it needs from the global class. 

The reason for this is to avoid adding all of the CSS for all of the colors inside of each component which would bloat the CSS files significantly, and this is how users are able to add new colors since that is defined by the user globally as well, see: https://github.com/ionic-team/ionic-conference-app/blob/master/src/theme/variables.scss#L165-L226

These variables are defined by default in the Ionic starters, so ideally you'd only need to update that when they change, which you can always look at the starters to see what the latest is, or the documentation here: https://ionicframework.com/docs/theming/colors. They were created as defaults but you can always update them for whatever theme your app needs, and if you were to update them they wouldn't need to be changed because they'd always override the defaults. 

This should be solvable using constructable stylesheets, but it's something that needs to happen in Stencil. I'm waiting on a response on where we are with that. If you'd like to keep the issue open I can use it to remind me to get an answer. 🙂
