### ISSUE TITLE
bug/feat: inconsistent ion-item click behavior for ion-select and ion-input

### ISSUE THREAD

**Issue by cmaas** [ionic-team/ionic-framework#20362]
# Feature Request

**Ionic version:**
[x] **4.x**
[x] **5.x**

**Describe the Feature Request**
The follow setup shows a ripple effect and triggers `ion-select` when clicking on `ion-label`:
```
<ion-item>
  <ion-label>A</ion-label>
  <ion-select>...</ion-select>
</ion-item>
```
But if you use a label in combination with `ion-input` or `ion-toggle`, clicking the label doesn't do anything:
```
<ion-item>
  <ion-label>A</ion-label>
  <ion-input />
</ion-item>
```

**Describe Preferred Solution**
I think from a HTML spec perspective, a *label* should actually focus the element which is labelled by the label.
I'd expect that clicking the label focuses the ion-input next to it.

Even the docs say so, in a way:

> Label is a wrapper element that can be used in combination with ion-item, ion-input, ion-toggle, and more.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This issue was resolved during Ionic v5, but the issue was never closed out. Updating to the latest version of Ionic v5 causes this issue to no longer reproduce, so I am going to close this thread out.

If you encounter any additional problems, please open a new issue and include a code reproduction. Thank you!
