### ISSUE TITLE
bug: checkbox and radio in item not toggable with element slotted left

### ISSUE THREAD

**Issue by Spinnenzunge** [ionic-team/ionic-framework#21513]
# Bug Report
Items with an ion-checkbox or ion-radio element and an element slotted (e.g. ion-icon) do not toggle the checkbox / radiobutton if the click event happens on the ion-icon element.

Maybe could be solved with feature request https://github.com/ionic-team/ionic/issues/17694

**Ionic version:**

[ ] **4.x**
[x] **5.2.1**

**Current behavior:**
Only the label and checkbox element toggle the checkbox, not the whole item

**Expected behavior:**
The whole item should toggle the checkbox / radiobutton

**Steps to reproduce:**

Create an item with checkbox slot end and icon slot start

**Related code:**

https://github.com/Spinnenzunge/action-sheet-button-bug

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.0 (/Users/pascalgraf/.nvm/versions/node/v12.11.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.1
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res (update available: 0.14.0) : 0.9.0
   native-run (update available: 1.0.0)   : 0.2.9

System:

   NodeJS : v12.11.1 (/Users/pascalgraf/.nvm/versions/node/v12.11.1/bin/node)
   npm    : 6.13.7
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the report. In Ionic 7 we are introducing a new syntax for working with form components. This issue is fixed when using that new syntax. We will have an Ionic 7 beta in the future where developers can test and provide feedback. There will also be a migration guide to show how to update to the new form component syntax.

The work required to resolve this has been completed, so I am going to close this thread. Let me know if there are any questions.
