### ISSUE TITLE
bug: IonReactRouter re-renders each page multiple times when changing routes

### ISSUE THREAD

**Issue by lindadick** [ionic-team/ionic-framework#21635]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When navigating between routes, the old route and the new route get re-rendered multiple times. This is a major performance issue with large pages that contain many components.

**Expected behavior:**

The page being replaced should not re-render, and the new page should only render once.

**Steps to reproduce:**

1. Create a new app using the ionic starter:
`ionic start myApp2 tabs --type react`
2. Add a console.log statement to each tab
3. Open the inspector and click between the tabs. Observe that each tab gets re-rendered multiple times.

**Related code:**

Sample application on Github: https://github.com/lindadick/ionic-routing-issue-example

**Other information:**

Here is a screenshot of what appears in the log after loading the app and clicking on Tab 2 once:
![image](https://user-images.githubusercontent.com/33604777/85929849-a06ad480-b87d-11ea-97ca-2d22f0c0da5b.png)

I confirmed that this same issue occurs if you navigate using IonRouterLink instead of tabs. The tabs were included in the example to make it easier to illustrate the problem. 

**Ionic info:**

```
➜  myApp git:(master) ✗ ionic info

Ionic:

   Ionic CLI       : 6.10.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.2.2

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.1 (/usr/bin/node)
   npm    : 6.14.5
   OS     : Linux 5.3
```

**Comment by elylucas** [comment]
Hi Linda,

We have a dev build that slightly reduces the number of renders the parent component's due to IonPages, you can try it out by installing it here, and let us know how it goes:

`npm i @ionic/react@5.3.0-dev.202006291715.9e74f80 @ionic/react-router@5.3.0-dev.202006291715.9e74f80`

This should be included in the next release of Ionic.

Besides that, there are a few other things you can do to cut down on the render.

If you don't care about route changes in your page, you can change the route so it doesn't get passed the router props like so:

`<Route path="/tab1" render={() => <Tab1 />} exact={true} />`

Next, you can memoize your component (its like making a functional component a pure component) by simply wrapping your component in the React.memo function like so when you export Tab1:

`export default React.memo(Tab1);`

These two steps will both cut down on the number of rerenders in your pages. Let me know if that helps.

Thanks

**Comment by lindadick** [comment]
Hi Ely,

Thanks for your reply! I haven't had a chance to try out your suggestions in my "real" app yet, but I tested with the example repo and found the following:

1. Updating to the `5.3.0-dev.202006291715.9e74f8` had no effect on the render count.
2. Changing the routes marginally cut down the number of renders (when loading the page and then clicking on Tab 2) - from 10 to 9.
3. Memoizing the tab components had a *huge* impact, making each tab only render once.

I still don't understand why the application would need to render each tab multiple times before settling on the newly selected tab - it feels like a bug to me. But thanks for the memoize tip, which should help for now!

Thanks,
Linda

**Comment by puku0x** [comment]
I'm facing the similar problem on a sample which has list and detail page that the previous page is rendered after the page transition.
https://codesandbox.io/s/ionic-react-router-v530-render-should-not-be-called-twice-4hlu2?file=/src/pages/UserListPage.tsx

This is the biggest problem when implementing searching in the list page because it calls render function in the detail page and occurs unnecessary communication.

**Comment by puku0x** [comment]
@elylucas 
Oh no, this issue should keep being opened because the new IonReactRouter has the same bug.

**Comment by elylucas** [comment]
@puku0x,

I closed it because its not a bug. Your components are going to get rendered if they receive new props or if their parent component renders, and you can cut down on those renders using the techniques I discussed above. In your code sandbox, I got your UserListPage down to a single render by not passing the router props to them by using the render prop instead of the component prop like so:

`<Route exact path="/users" render={() => <UserListPage />} />`

**Comment by elylucas** [comment]
For those that still come along to this issue, I wrote up an article on how to reduce the renders in your Ionic React apps: https://dev.to/ionic/how-to-reduce-the-number-of-renders-in-an-ionic-react-app-26mm
