### ISSUE TITLE
bug: ion-split-pane hides ion-menu-toggle inside menu

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#21701]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

`ion-split-pane` hides `ion-menu-toggle` inside a menu

**Expected behavior:**

`ion-menu-toggle` should be visible

**Steps to reproduce:**

Create `ion-list-pane` with `ion-menu-toggle` inside a menu.

**Related code:**

See code here: [https://pastebin.berkearas.de/?f9746b06b56d2189#3TGLJqJ45FuTJ6sHvy56EBTHAWASSF9F9SGwJPeSDF5w](https://pastebin.berkearas.de/?f9746b06b56d2189#3TGLJqJ45FuTJ6sHvy56EBTHAWASSF9F9SGwJPeSDF5w)

**Ionic info:**

Cannot run `ionic info` because using via CDN. Ionic version: ``5.2.3``

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am unable to reproduce the issue using the code provided. Can you please provide a full repo?

**Comment by BerkeAras** [comment]
@liamdebeasi Of course! [https://github.com/BerkeAras/ionic-split-pane-problem](https://github.com/BerkeAras/ionic-split-pane-problem)

**Comment by liamdebeasi** [comment]
Can you clarify the issue you are seeing? I am not seeing anything wrong with the repo provided.

**Comment by BerkeAras** [comment]
Shouldn't the ion-menu-toggle be visible?

**Comment by liamdebeasi** [comment]
The menu toggle should not be visible when the split pane is expanded. For example, on a desktop device you should be able to see the sidebar and the main content. In that case, the menu toggle should be hidden since there is no need to hide the menu.

On a mobile device, the menu toggle should be visible since the screen is not large enough to show both the sidemenu and the main content.

What is the issue you are running into?

**Comment by BerkeAras** [comment]
@liamdebeasi Oh, im soo sorry. I thought, that ion menu toggle is there to close the menu if a item gets clicked. Im so sorry!
Closing issue!
