### ISSUE TITLE
bug: leaving page is not transitioning out when using split pane on ios

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#21731]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Split-Pane removes ion-header animation on opening new page for iOS (Slide navigation to left on page opening)

**Expected behavior:**
Transition should work like wothout Split-Pane

**Steps to reproduce:**
Just use Split Pane (on homepage, not on others)

**Related code:**
[https://pastebin.berkearas.de/?f9746b06b56d2189#3TGLJqJ45FuTJ6sHvy56EBTHAWASSF9F9SGwJPeSDF5w](https://pastebin.berkearas.de/?f9746b06b56d2189#3TGLJqJ45FuTJ6sHvy56EBTHAWASSF9F9SGwJPeSDF5w)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please reproduce this in an Ionic starter application, and post a link to the repo?

**Comment by BerkeAras** [comment]
@liamdebeasi Of course, here you are!
[https://codepen.io/BerkeAras/pen/WNrKgQb?editors=1010](https://codepen.io/BerkeAras/pen/WNrKgQb?editors=1010)

**Comment by liamdebeasi** [comment]
Thanks! Can you please clarify the issue you are seeing? Everything appears to be functioning properly.

**Comment by BerkeAras** [comment]
@liamdebeasi The issue is not a really problem, its a small fix. If I remove ion-split-pane 'ion-title' animates by sliding to left (on iOS Page transition). If I use ion-split-pane it is not sliding to left as excepted.

**Comment by liamdebeasi** [comment]
Thanks for the report. I took a closer look at this, and this does not appear to be a bug in Ionic. The problem here is the sample application has the menu and the main content as a single view. When going from `page-home` to `page-about` both the menu and main content transition away. The more common pattern is to have the menu at the root of the application and have `ion-nav` only render your main content. That should cause the titles to transition as expected.
