### ISSUE TITLE
feat(generic | placeholder): provide --placeholder-font-size

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#21900]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**
We have everything related to placholder except font-size 

--placeholder-color | Color of the input placeholder text
--placeholder-font-style | Font style of the input placeholder text
--placeholder-font-weight | Font weight of the input placeholder text
--placeholder-opacity | Opacity of the input placeholder text

**Describe Preferred Solution**

Just like other css custom properties expose --placeholder-font-size

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I am going to close this as it is already possible to target the placeholder of `ion-input`, `ion-searchbar`, and `ion-textarea`, so adding additional CSS variables are not necessary.

As I explained in https://github.com/ionic-team/ionic-framework/issues/21898#issuecomment-671359294, you may need to place the styles in a global stylesheet in order for it to work due to Angular's component encapsulation.
