### ISSUE TITLE
bug: ios 14, card style modal and swipe to go back not working properly

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#21978]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Swipable Modals are stuttering when swiping down, but not closing. (SEE VIDEO)

**Expected behavior:**
Modal should swipe up **animated**.

**Steps to reproduce:**
Simply create ion-modal and test on iOS Device (Does not work on Browser)

**Related code:**
Git-Repo: [https://github.com/EatsApp/ionic-5-modal-issue](https://github.com/EatsApp/ionic-5-modal-issue)

**Other information:**
Video: [https://youtu.be/SrwCbv-2L6A](https://youtu.be/SrwCbv-2L6A)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This appears to be a WebKit bug, and I am only able to reproduce this on iOS 14/Safari Tech Preview. I will look into reporting this to the WebKit team.

**Comment by BerkeAras** [comment]
@liamdebeasi Thanks for reporting to WebKit :D

There are soo many WebKit Bugs in iOS 14 Beta :(

**Comment by liamdebeasi** [comment]
Hey there,

I wanted to follow up on this issue and provide some info for anyone else who may run into this. Please see below:

**What happened?**

There was a regression in an iOS 14 beta that caused the card-style modal and swipe to go back gesture to behave erratically. The underlying issue was that the animation engine in WebKit was not taking into account direction when updating easing curves.

The issue was resolved and code to fix the issue was merged last week; however, the issue was fixed too late in the iOS 14 release cycle to be considered at a time when only high-impact bug fixes could have made it into the next release. As a result, **this issue will still appear when iOS 14.0 is released later today**.

**When will the fix be released?**

This fix should be available in the first iOS 14 update (I.e. iOS 14.0.1, 14.1 or whatever the actual version ends up being). The Ionic Framework team will test any betas beforehand to verify that a fix is in place. We will follow up on this thread when the fix has been released.

**Is there a workaround?**

Currently, there is no workaround. If this issue is something that would impact your applications, we recommend not updating to iOS 14 until the fix is released.

I am going to re-open this issue for now, and will close it once the fix has been released in an iOS 14 update. Please do not create new issues asking for status updates or reporting the same issue again as they will be closed. We are waiting on Apple to release this fix, so we will provide more information as we have it. Thank you!

**Comment by liamdebeasi** [comment]
Hi everyone,

I have verified that this fix is in iOS 14.2 Beta 3. I will post here when this fix has shipped.

Thanks!

**Comment by liamdebeasi** [comment]
Hi everyone,

This fix has been released with iOS 14.2. Everyone looking to receive this fix should update their devices to that version.

Thanks!
