### ISSUE TITLE
bug: Navigating from one page to another using a nested route results in an error

### ISSUE THREAD

**Issue by ashleydavis** [ionic-team/ionic-framework#22007]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**

Navigating from one page to another using a nested route results in the error `TypeError: Cannot read property 'removeChild' of null`.

**Expected behavior:**

The error should not happen.

**Steps to reproduce:**

Minimal example application here: https://github.com/ashleydavis/ionic-remove-child-issue

Clone or download that repo. Run npm install and then ionic serve. You can trigger the error by clicking Click me to trigger the problem.

**Related code:**

Minimal example application:

https://github.com/ashleydavis/ionic-remove-child-issue

**Other information:**

![error](https://user-images.githubusercontent.com/625126/91651611-2b608900-ead2-11ea-946d-a81b1b0460fa.png)

**Ionic info:**

```
> ionic info

Ionic:

   Ionic CLI       : 6.11.7 (C:\Users\ash\AppData\Roaming\nvm\v12.18.1\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.3.2

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   NodeJS : v12.18.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.5
   OS     : Windows 10
```

**Comment by elylucas** [comment]
Hi @ashleydavis,

I've been looking into this one for awhile, and it looks like it will be quite a bit of work for a conventional use case.  The issue lies in that the route has a strong tie to the <IonPage> it renders, and when you use a key on the component the route renders, the <IonPage> gets destroyed and recreated each time, and the router looses its reference to the IonPage. 

One thought I had was (if you absolutely needed to use keys), was to move the key lower down, and have it be a child of the <IonPage>. I put together a sample on how to do this based on your repo and made a PR to your repo here: 
https://github.com/ashleydavis/ionic-remove-child-issue/pull/1

I was also wondering if you could use Props to accomplish the same deal. From the majority of apps I've seen, a change in props is used by the page to load new data, so if thats what you are looking to do you might check that out.

Thanks for the issue. I'm going to close it for now, but if you have more questions please feel free to ask.

**Comment by ashleydavis** [comment]
So the solution to the bug in Ionic is that I have to fudge my own code?

This issue shouldn't be closed while there is still a bug in Ionic.
