### ISSUE TITLE
bug: merging custom slides options does not work with nested objects such as pagination

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [ionic-team/ionic-framework#22044]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
Options passed via "options" property are not merged with the default options object, they are assigned instead.

**Expected behavior:**
Object.assign is not merge. They should be merged, as in: properties not specified in new object should not override old ones.

**Steps to reproduce:**
Try to pass options related to pagination in ion-slides, i.e.:
`<ion-slides pager="true" [options]="{ pagination: { clickable: true} }">`
This will override whole pagination object beneath and break pagination altogether.

**Related code:**
```
var options = { pagination: {a: true, b: false, c: 1, d: '2'}}; 
var customOptions = { pagination: {a: false}}; 
var result = Object.assign(options, customOptions);
```
result is equal to customOptions, but should be `{ pagination: {a: false, b: false, c: 1, d: '2'}};`

**Other information:**
None

**Ionic info:**
```

Ionic:

   Ionic CLI                     : 6.11.6 (/opt/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.1001.0
   @angular-devkit/schematics    : 10.0.6
   @angular/cli                  : 10.1.0
   @ionic/angular-toolkit        : 2.3.1

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res (update available: 0.15.1) : 0.14.0
   native-run (update available: 1.0.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/rattkin/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.18.3 (/opt/local/bin/node)
   npm               : 6.14.8
   OS                : macOS Catalina
   Xcode             : Xcode 11.7 Build version 11E801a
```

**Comment by indraraj26** [comment]
It is not related to ionic framework
Explanation: https://stackoverflow.com/a/34986585/10842900
Solution would be
```
var options = { pagination: {a: true, b: false, c: 1, d: '2'}}; 
var customOptions = { pagination: {a: false}}; 
var result = {}
result.pagination = Object.assign(options.pagination, customOptions.pagination);
console.log(result)
```

**Comment by sebastian-zarzycki-es** [comment]
It *is* related to Ionic framework because it uses Object.assign on whole options object (in fact, three times, merging with couple of other objects), rendering `options` property almost unusable.

**Comment by liamdebeasi** [comment]
Thanks for the issue, could you provide a code reproduction via a GitHub repo?

**Comment by sebastian-zarzycki-es** [comment]
Not really. But simple `<ion-slides pager="true" [options]="{ pagination: { clickable: true }}">` should demonstate the problem well. Attempting to override just one property results in overriding whole pagination object, rendering slides paginator broken.

**Comment by liamdebeasi** [comment]
Object.assign does not merge nested objects, so we likely need to do some additional work to handle nested param objects such as `pagination`.

As a workaround, you can do the following:

```typescript
import { ViewChild } from '@angular/core`;
import { IonSlides } from '@ionic/angular';

...

@VIewChild('slides', { static: true }) slides: IonSlides;

...

async ngOnInit() {
  const swiper = await this.slides.getSwiper();
    
  swiper.params.pagination.clickable = true;
  swiper.pagination.init();
}
```

```html
<ion-slides #slides [pager]="true">
  <ion-slide>Slide 1</ion-slide>
  <ion-slide>Slide 2</ion-slide>
  <ion-slide>Slide 3</ion-slide>
</ion-slides>
```

**Comment by sebastian-zarzycki-es** [comment]
Yep, thanks. I've figured that one, too. Still, the property field should be handled properly (or removed and users should be redirected to the way of doing this above).

**Comment by liamdebeasi** [comment]
Thanks for the issue! With the release of Ionic 6, we made the decision to deprecate `ion-slides` in favor of using Swiper.js directly.

Moving forward, `ion-slides` will only receive critical security fixes, and the component will be removed in Ionic 7. As a result, I am going to close this issue.

We have prepared migration guides for each of the 3 JavaScript frameworks we support, so developers can get started migrating right away.

[Migration for Angular](https://ionicframework.com/docs/angular/slides)
[Migration for React](https://ionicframework.com/docs/react/slides)
[Migration for Vue](https://ionicframework.com/docs/vue/slides)

We believe this change will lead to a healthier Ionic ecosystem as it frees up resources for the Ionic team to dedicate to other areas of this project while still giving developers options for carousels in their apps. Since `ion-slides` currently uses Swiper under the hood, the behavior of your carousels should remain the same even after you migrate.

For more information on the reasoning for and benefits of this change, please see the [ion-slides documentation](https://ionicframework.com/docs/api/slides#migration).

Thank you!

**Comment by sebastian-zarzycki** [comment]
That makes sense, thanks.
