### ISSUE TITLE
bug: IonTabButton with Root URL

### ISSUE THREAD

**Issue by tmccurbin** [ionic-team/ionic-framework#22077]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When "/" is given as the href prop for an IonTabButton two things break.

1. The aforementioned IonTabButton remains highlighted regardless of which tab is selected.
2. Switching to the aforementioned IonTabButton from another tab produces an unexpected page transition animation.

**Steps to reproduce:**

Install a basic Ionic React tabs application
`ionic start photo-gallery tabs --type=react --capacitor`
Substitute the `<App/>` component with the code provided

**Related code:**

```
const App: React.FC = () => (
  <IonApp>
    <IonReactRouter>
      <IonTabs>
        <IonRouterOutlet>
          <Route path="/" component={Tab1} exact={true} />
          <Route path="/tab2" component={Tab2} exact={true} />
          <Route path="/tab3" component={Tab3} exact={true} />
        </IonRouterOutlet>
        <IonTabBar slot="bottom">
          <IonTabButton tab="tab1" href="/">
            <IonIcon icon={triangle} />
            <IonLabel>Tab 1</IonLabel>
          </IonTabButton>
          <IonTabButton tab="tab2" href="/tab2">
            <IonIcon icon={images} />
            <IonLabel>Tab 2</IonLabel>
          </IonTabButton>
          <IonTabButton tab="tab3" href="/tab3" rel="help">
            <IonIcon icon={square} />
            <IonLabel>Tab 3</IonLabel>
          </IonTabButton>
        </IonTabBar>
      </IonTabs>
    </IonReactRouter>
  </IonApp>
);
```

**Ionic info:**

```
Ionic:

   Ionic CLI : 6.11.7

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.1.0) : 1.0.0

System:

   NodeJS : v10.19.0
   npm    : 6.14.4
   OS     : Linux 5.4
```

**Comment by BerkeAras** [comment]
@tmccurbin Please edit the Issue Title to get more answers

**Comment by elylucas** [comment]
Hi @tmccurbin,

Thanks for the issue.

In order for a tab to work properly, it needs to know what the base url is for that particular tab. When you set Tab1's href to `/`, the tabs components thinks anything that starts with `/` belongs to that tab, so when you go to `/tab2` or `/tab3`, it still thinks you are on tab1 because both those routes start with `/`.

This is why going to the other tabs the component still thinks you are on tab1 and probably why theres an transition issue as well.

I would suggest having a root redirect take you to '/tab1', and setting tab1's href to '/tab1' so that tab has its own, unique prefix that won't collide with the other tabs.

Going to close this issue for now as the usage isn't really a supported method, but if you have more questions please reach out.

Thanks
