### ISSUE TITLE
bug: Selectors within shadow dom for ion-menu and similar components

### ISSUE THREAD

**Issue by tvvignesh** [ionic-team/ionic-framework#22122]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
If you use `ion-menu` the content-id selector cannot be within the shadow dom, If it is within, ion-menu won't be able to find it even if `ion-menu` is placed within same the shadow dom since it looks at the global document object.

**Expected behavior:**
If there was ability to either specify some selector or some way to refer to the content within the shadow dom, it would be great. Currently `content-id` parameter refers to the global scope.

**PS:** I use IONIC along with Lit Element.

**Comment by tvvignesh** [comment]
I did a bit of digging and noticed in the IONIC source code that elements are referred to with `document` which won't work within shadowRoot. The best option I feel is that you must allow the user to pass in the DOM node itself and not just the ID. 

So, instead of getting the ID and then doing document.getElementById, I can get the element from the shadowRoot and send it to IONIC or the other way is that IONIC should check the current shadowRoot instead of going to the global document scope.

Currently, quite a few cases are causing trouble cause of this.

<img width="478" alt="Capture" src="https://user-images.githubusercontent.com/1165845/93732900-18346b00-fbf1-11ea-81c8-94b2bf10fc54.PNG">

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide your use case for using shadow component inside of Ionic's own components? We strongly advise against this as there is usually not a big benefit to doing this. Additionally, you will likely run into issues with piercing your component's shadow DOM to apply the global Ionic styles.

**Comment by tvvignesh** [comment]
> Thanks for the issue. Can you provide your use case for using shadow component inside of Ionic's own components? We strongly advise against this as there is usually not a big benefit to doing this. Additionally, you will likely run into issues with piercing your component's shadow DOM to apply the global Ionic styles.

@liamdebeasi I don't use shadow dom within IONIC but the other way round, IONIC within shadow dom. All my components are isolated based on lit element and I use IONIC components within the shadowRoot.

I am trying to stick as much as possible to web component standards where piercing the shadow dom, leaking styles or accessing global DOM is not recommended but rather with each component having its own scripts, styles and so on isolated from each other and to be honest, I thought that IONIC supports pure shadow dom since there have been a lot of blogs from IONIC about it: https://ionicframework.com/blog/tag/web-components/

One sample use case:
Say my `index.html` has this:
```html
<app-root></app-root>
```
and that's it. everything else is within the sub-components.

app-root might load any of this based on routing (I use vaadin router):
```html
<app-login></app-login>
<app-signup></app-signup>
<app-home></app-home>
```

And say that I have a app-menu within app-home component which has this where the menu and its content is relevant only to app-home:
```html
<ion-menu content-id="mycontent">
...
</ion-menu>

<ion-content id="mycontent"></ion-content>
```

I can't do this today since `mycontent` will refer to the global dom which does not have any element with id `mycontent`

I am facing the same problem with many components. Hope this makes sense.

**Comment by liamdebeasi** [comment]
Yeah, that's what I was referring to previously. We do not recommend using Ionic Framework within the Shadow DOM of your Lit Components. While having Shadow DOM encapsulation is useful for individual components, using multiple nested levels of Shadow DOM will not bring any notable performance improvements and can actually make it harder to work with the Shadow DOM (as you have experienced).

This isn't really an Ionic Framework limitation so much as it is how the Shadow DOM was designed. As Brandy noted in https://github.com/ionic-team/ionic-framework/issues/20294#issuecomment-578537616 another issue you may see is Ionic's global styles not always being applied due to your app's nested Shadow DOM structure. This is something that Constructable Stylesheets could potentially solve, but it has not shipped in most browsers yet.

It sounds like you are mostly interested in style encapsulation. So in terms of a workaround, I would recommend looking into scoping your styles to avoid them leaking out of your components. This could be as simple as doing:

```css
app-login ion-button {
  --background: green;
}
```

In this case, you can use CSS specificity to your advantage to scope your styles.
