### ISSUE TITLE
bug: @ionic/react ion-slides breaks when navigating using IonReactRouter

### ISSUE THREAD

**Issue by brycelund** [ionic-team/ionic-framework#22147]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**
@ionic/react @5.0.7

**Current behavior:**

IonSlides component displays properly, page is navigated away from using Ion Router, navigating back to that page then results in the layout of the ion slides breaking. Photos below show ion slides functioning as expected, then the layout immediately after returning to the page.

![Screen Shot 2020-09-22 at 9 57 42 PM](https://user-images.githubusercontent.com/18741882/93965830-54b2b480-fd20-11ea-8e6d-0e20eab95340.png)

![Screen Shot 2020-09-22 at 9 58 16 PM](https://user-images.githubusercontent.com/18741882/93965846-5da38600-fd20-11ea-9abd-55b278a34615.png)

**Expected behavior:**

It is expected that ion-slides would function the same both before and after navigation.

**Steps to reproduce:**

1. Create a new ionic app.
1. Setup an ion-slides component in one page
1. Use IonReactRouter to push to a new page
1. go back
1. ion-slides is broken

**Related code:**

A sample application via GitHub
https://github.com/brycelund/ios-slides-bug

The master branch shows the bug.

*It is interesting to note that after removing the IonRouterOutlet, the ion-slides function normally.*

The working branch shows it working after removing IonRouterOutlet

**Comment by liamdebeasi** [comment]
Thanks for the issue!

Starting with Ionic 5.7.0, we deprecated `ion-slides` in favor of having developers install Swiper.js directly in their projects. This gives developers access to new features, an improved developer experience, and bug fixes that they did not have access to when using `ion-slides`.

Since `ion-slides` uses Swiper.js under the hood, this migration should allow the functionality of your slides to remain exactly the same.

As a result of this deprecation, we have suspended any new development on `ion-slides` with the exception of critical fixes, such as resolving security issues.

I am going to close this issue out, but we strongly encourage you to try out the latest version of Swiper.js in your project. We have found that upgrading to the latest version of Swiper.js resolved a large number of common problems that Ionic developers were running into.

Please see https://ionicframework.com/docs/api/slides for more information on this change as well as a step by step migration guide for your apps. Developers will have approximately 1 year to migrate, starting from the initial deprecation in September 2021.

I understand this may not be the immediate resolution you were hoping for, but we think this change will significantly improve the developer experience in the long run by placing control of slides back in the hands of the developers.
