### ISSUE TITLE
feat: Disable AutoHide for menu components

### ISSUE THREAD

**Issue by Lindsor** [ionic-team/ionic-framework#22156]
# Feature Request

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**
There should be a property in the ion-menu component which allows the menu to remain open while interacting with the main page. This would remove the backdrop from the page and allow the menu to persist. This is useful for projects using Ionic in a fully response web app + native app.
On desktop you would be able to keep the menu open permanently (or allow the user to close manually) and on mobile the menu would close automatically.

**Describe Preferred Solution**
`<ion-menu [autoClose]="false"></ion-menu>`
NOTE: This is the angular implementation but the idea is the same for all frameworks.
Default to `true` to maintain backwards compatibility.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please describe the problem you are running into? I'm not quite sure what you are trying to achieve. You can change the breakpoints at which the menu hides/shows if that is what you are trying to do.

**Comment by Lindsor** [comment]
Sure Liam.

So essentially i want the menu to be "stuck" in open state. Never close, unless i specifically tell it to.

So in desktop i would essentially never tell it to close, it would be permanently open on the left side of the browser. User would be able to interact with the right side of the page with no issues while the menu remains open.
```
_________________________
|   |                   |
|   |                   |
|   |   MAIN CONTENT    |
|   |                   |
|   |                   |
|___|___________________|
```

VERY crude idea haha ^
But that left side would remain permanently closed unless i decided to add an explicit
`this.menuController.close('side-nav')`

**Comment by liamdebeasi** [comment]
Thanks for the clarification - that makes sense. In that case, you can do this by adjusting the `when` property on `ion-split-pane`. This property allows you to change when the menu is shown: https://ionicframework.com/docs/api/split-pane#setting-breakpoints.

You can set the value to any valid media query, or the pre-defined breakpoints we have in Ionic Framework. For your use case, you would want to do `when="(min-width: 0px)"`. This will cause the menu to be shown when the minimum screen width is 0px (I.e. always).

CodePen Example: https://codepen.io/liamdebeasi/pen/oNxmgLE

I am going to close this as this behavior is already possible in Ionic Framework. Thanks!

**Comment by Lindsor** [comment]
@liamdebeasi this doesn't fully solve the problem please don't close tickets prematurely. It always makes it seem like you guys don't care and just have your "quotas" for the day.

Split pane is too dumb in terms of control. Its literally (if this size show otherwise hide) thats not what i need.
I need one that i can control WHEN and IF i want.
I don't need this menu on all pages and adding `ngIf` listening to router events just seems sloppy and lazy.

Also the split pane makes it so all my menu code has to be in the `app.component.html` file which is just generally bad practice while using menu directly i can have it in a sub component.

**Comment by liamdebeasi** [comment]
Thanks for clarifying. Using the `when` and `disabled` properties on `ion-split-pane` gives you full control of when and if the menu should be shown. The [ion-split-pane Documentation](https://ionicframework.com/docs/api/split-pane) explains both.

I updated the CodePen to demonstrate this usage: https://codepen.io/liamdebeasi/pen/oNxmgLE

Using `when="(min-width: 0px)"` allows you to effectively disable the auto hide functionality for the menu. Using the `disabled` property allows you to determine if the menu should be shown or not. 

Additionally, I understand you would like to use your menu in a subcomponent. In this case, you can use the `disabled` property on your `ion-menu` component to show/hide the menu without having to touch `ion-split-pane`. I am assuming you are using Ionic Angular, but you can also use the `MenuController` dependency injection to programatically show/hide your `ion-menu` without needing to directly access the component yourself.

If I understand your use case correctly, using the `when` property should satisfy your "When" need, and the `disabled` property should satisfy your "If" need.

I did not close this issue because I do not care or need to fill a "quota" for the day, I closed this issue because the feature you are requesting is already possible within Ionic Framework.

**Comment by Lindsor** [comment]
Yeah i tried all of that. Using menuController.close doesn't work on a menu in split-pane
Split pane `disabled=true|false` removes all animation from the "closing" and "opening"

So there is still no native way of handling this.
In the modal Stencil code in `@ionic/core` you can see that the backdrop is always listening for off-component clicks and closing it. There should be a simple `[backdropDismiss]=false` like there are for modals

And sorry for being crass i didnt mean you dont care just that it makes it appear when these are closed instantly. I've been working with ionic for a while and have had/seen many of these closed to no ones satisfaction.

**Comment by liamdebeasi** [comment]
Can you put together an example that shows what you are trying to do and highlights the issues you are running into?

**Comment by Lindsor** [comment]
If you can add normal animation to your example i would be able to work with it.

https://codepen.io/lindsor-the-lessful/pen/dyMaYEV
Very dumbed down version but this is what i want. You click anywhere on the page and the side nav doesn't close.
Only if you click the button.

https://codepen.io/lindsor-the-lessful/pen/xxVMZKq
Now if you look at this one, you see we get the nice ionic animations but once the menu is open you can click anywhere on the right side and the menu will close.

If you look at yours (https://codepen.io/liamdebeasi/pen/oNxmgLE)
You notice that is 99% of what i want but its missing the nice ionic animations.

So what i want is essentially yours with animations
