### ISSUE TITLE
feat: allow to access glob matches of route redirects

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic-framework#22150]
# Feature Request

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**

I want to be able to do

```html
<ion-route-redirect from="/foo/*" to="/bar/$1" />
```

so that if i go to `/foo/bar` it redirects to `/bar/bar`.

**Additional Context**

I need this to allow a certain route before a route guard, i. e.

```tsx
{!loggedIn && [
  <ion-route-redirect from="/reset-password/*" to= "/reset-password/$1">,
  <ion-route-redirect from="*" to= "/">,
]}
```

**Describe Alternatives**

I've worked around this by manually matching the location's path and only rendering the route guard conditionally.

```tsx
{!loggedIn && !window.location.pathname.startsWith('/reset-password/') && (
  <ion-route-redirect from="*" to= "/">
)}
```

However this only works if the pathname matches on page load, not when later routing to that route client-side.

**Comment by liamdebeasi** [comment]
Thanks for the report. There has not been much support for this from the community since the issue was opened. Due to this, the team does not have plans to implement this in the immediate future. I am going to close this for now. However, we may re-consider this feature in the future if community support grows.
