### ISSUE TITLE
feat: Currency Input Field

### ISSUE THREAD

**Issue by ElDiabolus** [ionic-team/ionic-framework#22334]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
It's currently not possible to create a input field which accepts a currency input or converting an integer input in a currency input.

**Describe Preferred Solution**
There should be a input element which provides a input format like $ 23,54 / 23,54 € like in iOS/android vanilla apps. You should be able to change the currency and set the decimal places.

**Related Code**
Like this https://www.youtube.com/watch?v=YBBNPH6JYxY

**Comment by liamdebeasi** [comment]
Thanks for the feature request. Most frameworks (Angular, React, etc) already have solutions for these so I recommend investigating those first. Which framework are you interested in using? I can point you to some resources with how to use these in Ionic.

**Comment by ElDiabolus** [comment]
Thanks for your fast answer. I am using angular and searched for a solution but I couldn't find a working solution which is compatible to ionic. Can you provide some?

**Comment by liamdebeasi** [comment]
I made a quick example to show you how it can be done. Can you give it a try and let me know if it works for your use case?

StackBlitz: https://stackblitz.com/edit/ionic-v4-angular-tabs-jvxkez

There are a few things going on here:

1. We set the `ngModel` on the `ion-input` to be our formatted string that is returned from the currency pipe in Angular.
2. We have the pipe run again when `ionBlur` is fired.
3. in `tab1.page.ts`, since the pipe returns a formatted string but expects a number as input, we need to get rid of the `$` and `,` characters before updating the value.

I tried getting it to run whenever `ionInput` is fired (I.e. whenever someone inputs a new character), but the user experience was not great as I found myself fighting with the pipe to get it to format the string correctly. I tried this with a regular `input` and got the same result, so it seems that the Angular currency pipe is better fired on input `blur`.

**Comment by ElDiabolus** [comment]
Thanks a lot for this quick answer. I am gonna test it as soon I have time. Is there also a way to set the user keyboard to just select numbers and a comma or something like that?

**Comment by liamdebeasi** [comment]
You can try setting the `type` to `"number"`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number
