### ISSUE TITLE
bug: Scrollbar in IonSlide disappears upon navigating from page

### ISSUE THREAD

**Issue by asharonbaltazar** [ionic-team/ionic-framework#22406]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
`IonSlide` scrollbar likes to disappear when the page is navigated away and back. Instead, the scrollbar grey container is visible without a scrollbar. 

**Expected behavior:**
The scrollbar should never disappear. 

**Steps to reproduce:**
[Link to CodeSandbox](https://codesandbox.io/s/musing-sinoussi-tnfnw?file=/src/slices/app.ts) Search a city and select it. Wait for the weather to load. Scroll the carousel to confirm the presence of a scrollbar. Press Search or Settings and navigate back. Scroll the carousel to find the scrollbar missing.

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce this. It looks like on page transition, the `options` are somehow being updated which results in Swiper being updated. Swiper then sets transform values on the scrollbar, but the scrollbars values are invalid. I need to look into this some more, but so far I can only reproduce this in a React environment.

**Comment by liamdebeasi** [comment]
Thanks for the issue! With the release of Ionic 6, we made the decision to deprecate `ion-slides` in favor of using Swiper.js directly.

Moving forward, `ion-slides` will only receive critical security fixes, and the component will be removed in Ionic 7. As a result, I am going to close this issue.

We have prepared migration guides for each of the 3 JavaScript frameworks we support, so developers can get started migrating right away.

[Migration for Angular](https://ionicframework.com/docs/angular/slides)
[Migration for React](https://ionicframework.com/docs/react/slides)
[Migration for Vue](https://ionicframework.com/docs/vue/slides)

We believe this change will lead to a healthier Ionic ecosystem as it frees up resources for the Ionic team to dedicate to other areas of this project while still giving developers options for carousels in their apps. Since `ion-slides` currently uses Swiper under the hood, the behavior of your carousels should remain the same even after you migrate.

For more information on the reasoning for and benefits of this change, please see the [ion-slides documentation](https://ionicframework.com/docs/api/slides#migration).

Thank you!
