### ISSUE TITLE
bug: md mode is applied on iPad (via Safari)

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#22419]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I just mentioned, that when i run my App via `ionic serve` and setup safari as an iPad, the app uses **md** style.
I don't have an iPad so i don't know/ i don't hope this happens on real device too.

**Expected behavior:**

I expect to use **ios** mode on iPad.

**Steps to reproduce:**

Happens to me in a blank new starter Project

**Related stuff:**

I found this Issue: #19050 - maybe the logic behind that changed?

![Bildschirmfoto 2020-11-02 um 19 50 29](https://user-images.githubusercontent.com/20899975/97906904-b9602680-1d44-11eb-90ea-dbc82c4746e9.png)

![Bildschirmfoto 2020-11-02 um 19 50 39](https://user-images.githubusercontent.com/20899975/97906908-ba915380-1d44-11eb-8a2f-cb567f45a570.png)

**Other information:**

I use Safari Technology Preview: Release 115 (Safari 14.1, WebKit 15611.1.3.5)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.4.1
   @angular-devkit/build-angular : 0.1002.0
   @angular-devkit/schematics    : 10.1.7
   @angular/cli                  : 10.2.0
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 27 other plugins)

Utility:

   cordova-res                          : 0.15.1
   native-run (update available: 1.2.2) : 1.0.0

System:

   Android SDK Tools : 25.2.3 (/Users/hanskrywalsky/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.18.3 (/usr/local/bin/node)
   npm               : 6.14.8
   OS                : macOS Catalina
   Xcode             : Xcode 12.1 Build version 12A7403
```

**Comment by liamdebeasi** [comment]
This is a tricky one, and I'm not sure there is a whole lot we can do. We detect an iPad (and therefore iOS mode) with the following logic:

1. If the `/iPad/i` regex matches on the user agent, return `true`.
2. If the `/Macintosh/i` regex matches on the user agent and the `(any-pointer: coarse)` media query matches, return true.
3. Otherwise, return `false`.

With the introduction of iPadOS, iPad devices stopped reporting "iPad" in the user agent string and now reports "Macintosh" instead.

To get around this, we check if `(any-pointer: coarse)` matches, which will match when running the app on a device with a touch screen. When spoofing the user agent in Safari, `(any-pointer: coarse)` still does not match since there is no touch screen on your Mac. As of now, Safari cannot simulate touch events when in Responsive Design Mode. We can't remove this check as it would cause the `ipad` platform check to incorrectly return `true` when running in desktop mode on Safari.

How big of an issue is this for your development? This should not affect physical iPad devices.

**Comment by EinfachHans** [comment]
Ok i understand. Because i don't have an iPad, but need to develop for it as well, i want to check in Safari how the App will look like. I can select "iOS ... - iPhone" instead of the auto selected "iPad" in Safari, but this will add the class "plt-iphone" to `<html>`-Tag. If this doesn't break anything and looks like it would later on a real device i think this workaround is okay for me 🤔

**Comment by liamdebeasi** [comment]
If you add `?ionic:mode=ios` to the end of your URL, does that work?

**Comment by EinfachHans** [comment]
Yeah that start the App in the `ios` mode directly - that's okay for testing! Thank you 😊
