### ISSUE TITLE
bug: ionic vue needs to mock overlay components for unit testing

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#22633]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When attempting to test unit test code such as the following by referencing the button and triggering a click on it, the test throws an exception ("TypeError: Cannot read property 'present' of undefined") since the modal is not created properly.

Code (in Home.vue)

```TypeScript
    async openModal() {
      const modal = await modalController.create({
        component: Modal,
        cssClass: 'my-custom-class',
        componentProps: {
          data: {
            content: 'New Content'
         },
          propsData: {
            title: 'New title'
          }
        }
      });
      return modal.present();
    }
```

Sample test stub:

```TypeScript
  it('displays the modal', async () => {
    const button = wrapper.findComponent('ion-button');
    await button.trigger('click');
  });
```

**Expected behavior:**

The `modalController.create()` would resolve and a modal would be created in the DOM that could be queried by the rest of the tests.

`@ionic/react` accomplishes this by mocking the modal controller: https://github.com/ionic-team/ionic-react-test-utils/blob/master/src/mocks/mockController.tsx

**Related code:**

Repro repo: https://github.com/kensodemann/test-modal-vue

**Comment by liamdebeasi** [comment]
Discussed with Ken offline, and it appears this issue is resolved. The sample repo provided no longer exists, but Ken was able to provide an alternative repo. In that repo I was able to verify that the modal is correctly constructed (including the shadow root) and added to the DOM without errors.

I am going to close this. If anyone else is running into similar errors please open a new issue. Thanks!
