### ISSUE TITLE
bug: bug: Navigation stops working for nested main ion-router-outlet with z-index

### ISSUE THREAD

**Issue by nhhockeyplayer** [ionic-team/ionic-framework#22720]
bug: bug: Navigation stops working for nested main ion-router-outlet with z-index implementation using sidemenu and std ionic tabs implementation

angular <router-outlet> is doing its thing beautifully middle tier to back end with feature sub modules but ionic front end isn't holding water results continue to be intermittent and unresponsive depending on legs of code introduced like single sign on etc... original initialize route dispatch etc or the default router config as modeled 

 have consulted docs, multiple issues remain open and locked where no one is allowed to talk about these

https://github.com/ionic-team/ionic-framework/issues/18197
https://github.com/ionic-team/ionic-framework/issues/20643
https://github.com/ionic-team/ionic-framework/issues/18197

I have seen commercial apps limp along released to public with this in the release

Can someone give a status? This is not a major bug its a show stopper for the commercial field committed to this framework.

Thanks for your hard work and care

a repo with workaround would be highly appropriate

Ionic:
   Ionic CLI : 6.12.2
System:
   NodeJS : v14.15.1
   npm    : 6.14.8
   OS     : macOS Catalina

**Comment by nhhockeyplayer** [comment]
well I seemed to have worked around this by remodeling my router config
avoiding anything ionic like reroute strategy
setting up a few async blocks with delay to prevent route dispatch collisions contending
and back filling my route config

router configurations should be alot clean then they have to be to work around his

best

**Comment by liamdebeasi** [comment]
Thanks for the issue. Ionic Angular does not fully support nested router outlets with relative/auxiliary routes at the moment. Properly supporting this will require a significant refactor of our current router setup. If we do this refactor, we would like to do it during a major version change. 

I recommend following https://github.com/ionic-team/ionic-framework/issues/18197 and https://github.com/ionic-team/ionic-framework/issues/18845 which is where we will post any updates regarding the status of this issue.

As for a workaround, I recommend re-evaluating whether or not you actually need a nested outlet. At least in the context of mobile apps, nested outlets are not that common and using them when they should not be used tends to lead to a confusing user experience.

An example of a good nested outlet usage is with tabs as the tab bar is rendered in outlet A and the actual tab content is rendered in outlet B. In other words, a good application of nested outlets is when you need to show secondary content (such as a toolbar) and main content that are not necessarily rendered from the same component/same route. Using nested outlets because you have shared URLs such as `/page` and `/page/child` does not necessarily require a nested outlet. (Not sure how you are using nested outlets in your application, but I figured I would mention this example since it is a common pitfall I have seen).

Hope this helps! For any follow up questions regarding implementation in your application, I recommend opening a thread on our forums: http://forum.ionicframework.com/

**Comment by nhhockeyplayer** [comment]
Thanks for update
I have outlets landing and improvising
