### ISSUE TITLE
bug: ion-label inside ion-item aligns wrongly or disappers if custom Angular component is used in this ion-item when stacked or floating position is set

### ISSUE THREAD

**Issue by MaximS** [ionic-team/ionic-framework#22736]
# `ion-label` inside `ion-item` aligns wrongly or disappers if custom **Angular** component is used in this `ion-item` when stacked or floating label position is set - because `item-label-stacked` class is not set on `ion-item`

**Ionic version:**

[x] **5.x** (Angular project)

**Current behavior:**
When custom **Angular** component is used inside `ion-item` a class `item-label-stacked` is not set on `ion-item` if there is a label with `position="stacked"` inside that `ion-item`. (When built-in Ionic components like `ion-input` are used the `ion-item` gets this class automatically)

**Expected behavior:**
`item-label-stacked` class should be set on `ion-item` regardless of component used after the label

**Steps to reproduce:**
See Related code

**Related code:**
See [stackblitz link](https://stackblitz.com/edit/ionic-5-angular-10-start-template-uqfjnh?file=src%2Fapp%2Ftab1%2Ftab1.page.html) 
In a demo `item-label-stacked` is **explicitly** added to an `ion-item`. If it's removed than the label aligns itself to the left like position="fixed" or disappers completely if all the chips are deleted (using red crosses). See comments in tabs/tab1.page.html

**Comment by liamdebeasi** [comment]
Hi there,

We are proposing some changes to form components that seek to resolve this issue. We would love your feedback on these proposed changes! You can read more about the changes and leave comments here: https://github.com/ionic-team/ionic-framework/discussions/25661

**Comment by liamdebeasi** [comment]
Thanks for the report. In Ionic 7 we will be introducing a new syntax for using form components such as `ion-input`. You can find a summary of the changes here: https://github.com/ionic-team/ionic-framework/discussions/25661

The reported issue is fixed with this new syntax. Work to update `ion-input` to use this new syntax has been completed, so I am going mark this issue as resolved. We plan to have a public beta period for Ionic 7 in the future. You can visit the [Ionic Blog](https://blog.ionicframework.com/), [Ionic Twitter](https://twitter.com/ionicframework), or our [GitHub Releases Page](https://github.com/ionic-team/ionic-framework/releases) to be notified when the Ionic 7 beta is released. Let me know if you have any questions. Thanks!
