### ISSUE TITLE
bug: Item line covers the icon when using ion-select.

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#22758]
# Bug Report

ionic/core (md)
[ion-select](https://ionicframework.com/docs/api/select)
[ion-item](https://ionicframework.com/docs/api/item)

**Ionic version:**
**5.x**

**Current behavior:**

Then an item has a select element, the item line has a full width. Even with an icon. 
![actual](https://user-images.githubusercontent.com/60390085/104417617-fd0db280-5575-11eb-99d0-5aeee3ce45f8.png)

**Expected behavior:**
By default, the line stops on the icon. The item with select should respect this style.
![expected](https://user-images.githubusercontent.com/60390085/104418490-43afdc80-5577-11eb-8412-69c73bcdd72d.png)
<sub>Image manipulated to show the expected behavior.</sub>

**Steps to reproduce:**

1. Create a ion-list with ion-items. Very simple with ion-label and ion-icon on slot start.
2. Add ion-select to an item and see that the item line has the full width.

**Related code:**

```html
<ion-item>
  <ion-icon slot="start" name="bug"></ion-icon>
  <ion-label>Select</ion-label>
  <ion-select>
    <ion-select-option value="1">One</ion-select-option>
    <ion-select-option value="2">Two</ion-select-option>
    <ion-select-option value="3">Three</ion-select-option>
  </ion-select>
</ion-item>
```

[StackBlitz Demo](https://stackblitz.com/edit/ionic-5-progress-bar-dark-mode-issue-workaround-rjxxux?embed=1&file=src/app/tab1/tab1.page.html)

**Ionic info:**

```
Ionic:
   Ionic CLI : 6.12.2  

System:
   NodeJS : v14.15.1
   npm    : 6.14.8
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the report. In Ionic 7 we are introducing a new syntax for working with ion-select. This issue is fixed when using that new syntax. Ionic 7 is currently in beta, and developers can find a migration guide on our documentation website: https://ionicframework.com/docs/v7/updating/7-0


The work required to resolve this has been completed, so I am going to close this thread. Let me know if there are any questions.
