### ISSUE TITLE
needs-reply: Just want to know how to imply micro apps in Ionic!

### ISSUE THREAD

**Issue by Ragul184** [ionic-team/ionic-framework#22811]
Yeah, Thanks for the reply @liamdebeasi . I just want to use Angular as my front end library. But what my doubt is can we actually divide entire application into several micro apps ( micro front ends ) and deploy it independently and integrate all the micro apps into single ionic mobile application? This is my doubt @liamdebeasi... If we can do, give me some idea about how to do it... I have been researching it for a while.

_Originally posted by @Ragul184 in https://github.com/ionic-team/ionic-framework/issues/22810#issuecomment-765451449_

**Comment by mhartington** [comment]
@Ragul184 Please keep comments to the same issue instead of opening new ones.


This is beyond the scope of Ionic, since Ionic is only the UI layer, not the application layer.
Using Ionic's UI components would not stop you from doing this. You need to investigate how to implement micro-frontend apps with the frameworks of choice.
