### ISSUE TITLE
bug: ion-slides swipe problem in modal when clicked on backdrop.

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#22833]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
When you click on the modal backdrop (`backdropDismiss: false`), the slider jumps to the last slide. 
In this moment you cannot slide back anymore. With every click on background you cannot reach the n+1 slide.

**Expected behavior:**
Don't jump to the last slide or fix the back slide issue.
Or we need an option to disable the backdrop interactions (of if this is the problem, the cancel role. Maybe the slider reacts on it.)

**Steps to reproduce:**

Just create the project setup as described below and open the slider modal.
Then click on the backdrop and see that the slider jumps to the last slide. 
Then try to swipe back to the first slide. You'll see a weird behavior.

Note: You have to view the Ionic app on a big (normal) screen to see the modal with the backdrop behind. Otherwise the modal is displayed like a fullscreen page on smaller screens.

**Related code:**

**[Stackblitz Demo](https://stackblitz.com/edit/ionic-5-issue-ion-slide-backdrop?embed=1&file=src/app/modals/slides.services.ts)**

```html
<ion-content fullscreen class="ion-padding" scroll-y="false">
  <ion-slides>
    <ion-slide>
      <img src="..." />
      <h2>Welcome</h2>
      <p>
        The <b>ionic conference app</b> is a practical preview of the ionic framework in action, and a demonstration of
        proper code use.
      </p>
    </ion-slide>

    <!-- ... Repeat 2 more times. -->

    <ion-slide>
      <img src="..." />
      <h2>Ready to Play?</h2>
      <ion-button fill="clear">Continue <ion-icon slot="end" name="arrow-forward"></ion-icon> </ion-button>
    </ion-slide>
  </ion-slides>
</ion-content>
```

```ts
this.modalElement = await this.modalController.create({
  component: SlidesComponent,
  backdropDismiss: false,
  mode: 'ios',
});
```
**Other information:**

![issue-demo](https://user-images.githubusercontent.com/60390085/106152128-5fbd9b80-617d-11eb-87af-473cf1845a1e.gif)

> Why does the slides jump to end on backdrop click? We should disable this behavior. 

**Ionic info:**

```
Ionic:

   Ionic CLI : 6.12.2  
   Ionic Angular: 5.5.2

System:

   NodeJS : v14.15.1
   npm    : 6.14.8
   OS     : Windows 10
```

**Comment by infacto** [comment]
I'm getting gray hair because of this issue. ^^ Any ideas for temporary workarounds?

**Comment by infacto** [comment]
I'm getting gray hair because of this issue. ^^ Any ideas for temporary workarounds?
Maybe hijack the `ion-backdrop` element? It will help if I get some infos from the Ionic team. 🙂 

The current backdrop element look like:
```html
<ion-backdrop class="sc-ion-modal-ios ios backdrop-no-tappable hydrated" tabindex="-1" aria-hidden="true" style=""></ion-backdrop>
```

I guess the option `backdropDismiss` just stops from closing, but does not stop the cancel role event. But idk. Need help. 🙏

**Comment by infacto** [comment]
Ok, my current workaround is: 

**global styles**
```scss
ion-backdrop.backdrop-no-tappable {
  pointer-events: none;
}
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! With the release of Ionic 6, we made the decision to deprecate `ion-slides` in favor of using Swiper.js directly.

Moving forward, `ion-slides` will only receive critical security fixes, and the component will be removed in Ionic 7. As a result, I am going to close this issue.

We have prepared migration guides for each of the 3 JavaScript frameworks we support, so developers can get started migrating right away.

[Migration for Angular](https://ionicframework.com/docs/angular/slides)
[Migration for React](https://ionicframework.com/docs/react/slides)
[Migration for Vue](https://ionicframework.com/docs/vue/slides)

We believe this change will lead to a healthier Ionic ecosystem as it frees up resources for the Ionic team to dedicate to other areas of this project while still giving developers options for carousels in their apps. Since `ion-slides` currently uses Swiper under the hood, the behavior of your carousels should remain the same even after you migrate.

For more information on the reasoning for and benefits of this change, please see the [ion-slides documentation](https://ionicframework.com/docs/api/slides#migration).

Thank you!
