### ISSUE TITLE
bug: ionSlideDidChange not fired but slide display changed with right swipe gesture with talkback on

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#22859]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Let me know if you would like to see the screen captures and I can share them with you via Slack.

Case 1: normal-slide-without-talkback.mp4 - Here, the Current slide index value gets updated while we slide to the next slide ( normal slide action)

Case 2: talkback-swipe-right-gesture-on-slide.mp4 - Here talkback Swipe Right gesture is used - This shows the next slide. How ever, the index value doesn't get updated. This is because, in the component .ts file, the index is updated in the "handleSlideChanges" method, which is triggred on "ionSlideDidChange".

The issue here is the slide changes, but the "ionSlideDidChange" is not triggred. So the application methods which depends on the "ionSlideDidChange" doesn't get executed.

Please refer to the updated code below to reproduce the above cases: 
https://github.com/ionic-afl/ionic-v5-observations.git; branch: set-one

Swipe right mentioned in below link is single finger swipe right.

https://support.google.com/accessibility/android/answer/6151827?hl=en

**Expected behavior:**
I am not entirely sure here.

Android talkback docs say of a single finger swipe right: Move to next item on screen

<img width="386" alt="Screen Shot 2021-02-03 at 6 38 06 AM" src="https://user-images.githubusercontent.com/1526846/106748157-6e2b0d80-65ea-11eb-90fe-aaabfb504dfc.png">

A swipe right with talkback on and the "Ion Slides Component" label currently selected does this:

1. moves to "Current Slide Index..." element
2. moves to "PREV" button
3. moves to "Slide 1" title
4. moves to "Slide 1 contents..."
5. moves to "Slide 2" title

At step 5, the slider displays Slide 2 though "ionSlideDidChange" is not fired.

Personally, I would have expected the selected item to transition to the "NEXT" button since that is the next item on the screen, whereas Slide 2 was not on the screen yet. I would have expected scroll actions, and only scroll actions to work on the slides.

FWIW, swiping left is worse. It will highlight hidden content and read it rather than displaying Slide 1.

Again, though, it seems to me that swipe left or right should just transition between elements that are currently visible on the page, not scroll the slider.

If it should scroll the slider, then it should do so in a consistent manner, and should fire the event.

**Steps to reproduce:**

For the main issue:

1. have talkback on
2. select but do not press the "PREV" button (in talkback terms, touch it once, not a double touch)
3. single finger swipe right (this can be tricky depending on device, my device is inconsistent as to when this actually does anything)
4. "Step 1" should be highlighted
5. Swipe right again
6. "Step 1 contents..." should be highlighted
7. Swipe right again
8. "Step 2" is highlighted and you can see from the "Current Slide Index" that the event was not triggered

My belief is that "NEXT" should be highlighted.
The developer that I am working with believes that "Slide 2" is appropriate and the event should fire.
If we can find some similar thing to test against, we probably should.

For the "Left" issue

1. double tap the "NEXT" button so we are on slide 2 properly (with "Current Slide Index" showing "1"
2. left swipe until "Slide 2" title is highlighted (should be twice).
3. left swipe again
4. Slide will not change, highlight goes to hidden element, "Slide 1 contents..." is announced
5. left swipe again
6. Slide will not change, highlight goes to another hidden element, "Slide 1" is announced
7. left swipe again
8. We are finally on "PREV" button

I believe we should have skipped the hidden "slide 1" elements entirely and gone to "PREV" button.

**Related code:**

https://github.com/ionic-afl/ionic-v5-observations.git; branch: set-one

**Comment by liamdebeasi** [comment]
Thanks for the issue! With the release of Ionic 6, we made the decision to deprecate `ion-slides` in favor of using Swiper.js directly.

Moving forward, `ion-slides` will only receive critical security fixes, and the component will be removed in Ionic 7. As a result, I am going to close this issue.

We have prepared migration guides for each of the 3 JavaScript frameworks we support, so developers can get started migrating right away.

[Migration for Angular](https://ionicframework.com/docs/angular/slides)
[Migration for React](https://ionicframework.com/docs/react/slides)
[Migration for Vue](https://ionicframework.com/docs/vue/slides)

We believe this change will lead to a healthier Ionic ecosystem as it frees up resources for the Ionic team to dedicate to other areas of this project while still giving developers options for carousels in their apps. Since `ion-slides` currently uses Swiper under the hood, the behavior of your carousels should remain the same even after you migrate.

For more information on the reasoning for and benefits of this change, please see the [ion-slides documentation](https://ionicframework.com/docs/api/slides#migration).

Thank you!
