### ISSUE TITLE
bug: vue, react, ion-slide crashes when tried to render dynamically

### ISSUE THREAD

**Issue by JosePerez27** [ionic-team/ionic-framework#22867]
# Bug Report

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[x] **6.x**

**Current behavior:**
I tried to render a dynamic sliders with a reactive data, in this case I'm simulating a HTTP request with settimeout, when i tried to fill the reactive variable, it turns in this error and the App crashes:

![image](https://user-images.githubusercontent.com/47994734/106836029-6315c300-6666-11eb-968c-455079e1dfbd.png)
![image](https://user-images.githubusercontent.com/47994734/106836068-745ecf80-6666-11eb-8bd2-551a294773c3.png)

```
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```

**Expected behavior:**
Render correctly the sliders with the dynamic data that i fill with the HTTP Request.
![image](https://user-images.githubusercontent.com/47994734/106835984-48dbe500-6666-11eb-8505-5d9710c7a4cc.png)

**Steps to reproduce:**
Step 1: Create an Ion Page.
Step 2: Call the IonSlides, IonSlide components from @Ionic/vue.
Step 3: Create an empty reactive variable to fill in the future (HTTP Request)
Step 4: Try to render dynamically the sliders with the directive v-for.

**Related code:**

https://github.com/JosePerez27/slidebug.git , Branch master, src/views/Home.vue

```
<template>
    <ion-page>
        <ion-content>
            <!-- Content -->
            <div class="content">
                <ion-label>Content</ion-label>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi labore quis, illo, possimus dolorem et doloremque nostrum quae repellat minus tempora ea dolores? Eveniet nostrum provident, numquam quia molestiae sequi.</p>
            </div>

            <!-- Services slider cards -->
            <div class="services">
                <ion-label>Services</ion-label>
                <ion-slides pager="true" :options="slideOpts">
                    <!-- Here the app crahses -->
                    <ion-slide v-for="(service, index) in services" :key="index">
                        <ion-card>
                           {{ service.name }}
                        </ion-card>
                    </ion-slide>
                    <!-- Here the app crahses -->
                </ion-slides>
            </div>
        </ion-content>
    </ion-page>
</template>
```

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.4 (C:\Users\josea\AppData\Roaming\npm\node_modules\@ionic\cli)      
   Ionic Framework : @ionic/vue 5.5.3

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res : not installed
   native-run  : 0.2.8

System:

   NodeJS : v14.15.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.7
   OS     : Windows 10
```

**Comment by JosePerez27** [comment]
Hi! There was any solution for this? I really need this functionality, Thanks!

**Comment by Suxsem** [comment]
I can confirm the same issue. Any workaround waiting for the proper fix?

**Comment by whitersun** [comment]
Hello there. Do you mean browser works fine, but after platform to devices, it doesn't work or the slider fired right?

**Comment by ivoevolution** [comment]
v-for not working on <ion-slide> element and crashes. I got the issue.

**Comment by Yonier** [comment]
i'm getting the same issue with v-for on ion-slide

**Comment by KuschL** [comment]
The same error also appears if content is dynamically added to `<IonCol>` in react.

So far I jut did not render the specific element when data is changing. But the issue with `<IonCol>` did work in Ionic v5.

**Comment by liamdebeasi** [comment]
Thanks for the issue! With the release of Ionic 6, we made the decision to deprecate `ion-slides` in favor of using Swiper.js directly.

Moving forward, `ion-slides` will only receive critical security fixes, and the component will be removed in Ionic 7. As a result, I am going to close this issue.

We have prepared migration guides for each of the 3 JavaScript frameworks we support, so developers can get started migrating right away.

[Migration for Angular](https://ionicframework.com/docs/angular/slides)
[Migration for React](https://ionicframework.com/docs/react/slides)
[Migration for Vue](https://ionicframework.com/docs/vue/slides)

We believe this change will lead to a healthier Ionic ecosystem as it frees up resources for the Ionic team to dedicate to other areas of this project while still giving developers options for carousels in their apps. Since `ion-slides` currently uses Swiper under the hood, the behavior of your carousels should remain the same even after you migrate.

For more information on the reasoning for and benefits of this change, please see the [ion-slides documentation](https://ionicframework.com/docs/api/slides#migration).

Thank you!
