### ISSUE TITLE
feat: add keyboard-push animation 

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#23006]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**
Native apps have an animation if the keyboard is presenting. (Content slides up)

**Describe Preferred Solution**
N/A

**Describe Alternatives**
N/A

**Related Code**
N/A

**Additional Context**
See YouTube-Video of the current animation: https://youtu.be/zQezwEPhpPg

**Comment by liamdebeasi** [comment]
Thanks for the issue. I think this is something better implemented on a per-app basis given that some developers may prefer to animate another element instead of the content. I go over some strategies for this in this blog: https://ionicframework.com/blog/keyboard-improvements-for-ionic-apps/ (see "Ionic Keyboard Events")


Also, Capacitor already will resize the webview/`ion-app` when the keyboard is opened. See https://capacitorjs.com/docs/apis/keyboard#keyboard-configuration-ios-only for more information.
