### ISSUE TITLE
feat: minlength/maxlength attributes for inputs with type number

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#23014]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**
minlength/maxlength-attributes should be usable for inputs with type number too. The documentation (https://ionicframework.com/docs/api/input#properties) says, that these attributes are only usable for following types: `text, email, search, password, tel, or url`.

**Describe Preferred Solution**
Allowing the usage of minlength/maxlength-attributes for input-types `text, email, search, password, tel, url` *and* `number`.

**Describe Alternatives**
Currently the users can create a custom EventListener to check the given length and can prevent the typing (maxlength; if length == maxlength) or can return an error (minlength; if length < minlength).

**Related Code**
N/A

**Additional Context**
N/A

**Comment by liamdebeasi** [comment]
Thanks for the issue. This is by design. We use a native input under the hood with `ion-input` and browsers do not allow `type="number"` to be used with `maxlength` and `minlength`. See https://stackoverflow.com/questions/18510845/maxlength-ignored-for-input-type-number-in-chrome and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-maxlength.

We are not likely to implement this as it goes against the web spec for `input` and could lead to a confusing user experience.
