### ISSUE TITLE
bug: vuejs > 3.0.5 with ionic/vue > 5.5.4 does not work

### ISSUE THREAD

**Issue by dcyou** [ionic-team/ionic-framework#23062]
Hi all I could write a long explanation but this so simple to just read that line:
https://github.com/ionic-team/ionic-framework/blob/master/packages/vue/src/ionic-vue.ts#L5

So using vuejs > 3.0.5 with a ionic/vue > 5.5.4 break some events

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Comment by liamdebeasi** [comment]
Thanks for the issue. The problem here is that Vue fixed a bug involving events in custom elements which resulted in this fix being needed. (see: https://github.com/vuejs/vue-next/issues/2841) If you are on Vue 3.0.6+ you should update to the latest version of Ionic Framework (v5.6.0 or newer). If you are on Vue <= 3.0.5 you should still update to the latest version of Ionic Framework, but we always recommend using the latest stable version of Vue.

**Comment by dcyou** [comment]
I were on vue v3.0.7 and Ionic Framework v5.6.0 but anyway I downgrade ionic to v5.5.4

![image](https://user-images.githubusercontent.com/6975084/111591339-98661280-87c7-11eb-8a6a-1fce1ae883d1.png)
![image](https://user-images.githubusercontent.com/6975084/111591365-a1ef7a80-87c7-11eb-9778-a10dfc9c0d1d.png)

**Comment by liamdebeasi** [comment]
Can you provide a code reproduction of the issue in Vue 3.0.7?
