### ISSUE TITLE
Ionic 5 + Angular, Maintain form data when revisiting page instead of clearing previously entered data

### ISSUE THREAD

**Issue by Madhukumar1226** [ionic-team/ionic-framework#23091]
**Ionic version:**

[x] **5.x**

**Current behavior:**

I have created an IONIC 5 application with tab menu with 3 tabs named  **tab1** ,**tab2** and **tab3**. For routing between tabs i'm using **ionic lazy load**. 
Inside Tab 3 page i have one more **floating menu option** with 5 different pages. example page1 ,page 2,page 3,page 4 and page 5. To provide routing between these pages i'm using **routerLink**.

 **ISSUE**
When i'm trying to visit the pages from floating menu that page state only remains constant and all other pages refreshing data when i trying to revisit that page from floating menu.
**Example :** 

- From Tab 3  screen floating menu i'm selecting page 2 option and landing into that screen and entered some data. 

- Now from page 2 floating menu i'm selecting page 3 option and landing into that screen and entered some data.

- So now from page 3 floating menu, selecting page 2 option and revisiting that page data entered before leaving the page is still visible. 

- But now when i visited back to page 3 in that page what i have entered data was cleared and  looks like new page.
- If i selected page 1 option for first from tab 3 screen then page 1 data will exists and remaining pages data cleared when revisited those other pages 

**Expected behavior:**

Floating menu screens remains constant how many times when i switch between the pages using floating menu. 

**Other information:**

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.1
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.5
   @angular/cli                  : 9.1.5
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.4.2
```

**Comment by Madhukumar1226** [comment]
https://github.com/Madhukumar1226/ionic-tabs-demo.git

@liamdebeasi Please find the code repo for reproducing issue

**Comment by liamdebeasi** [comment]
Did you push the code needed to reproduce this issue? All I see is a blank tabs starter application.

**Comment by Madhukumar1226** [comment]
@liamdebeasi  Please help on this bug , 
provided source code repo and actual issue is (based of  repo code) in tab 3 page i have floating menu , from that i'm selecting any one of the screen. let's us take example facebook enter any data and from that page navigate google page and entered some data and from google page navigating another page then again came back to google page that data it's cleared

**Comment by liamdebeasi** [comment]
Can you please double check the repo you provided? There is no floating menu in Tab 3 as the app you pushed to GitHub is the blank tabs starter application.

**Comment by Madhukumar1226** [comment]
@liamdebeasi  Sorry few of the files missed in last commit, can you please check now once

Repo : https://github.com/Madhukumar1226/ionic-tabs-demo.git

**Comment by Madhukumar1226** [comment]
@liamdebeasi CAN YOU PLEASE HELP ON THIS

**Comment by Madhukumar1226** [comment]
GUYS ,CAN ANYONE PLEASE HELP ON THIS ISSUE

**Comment by liamdebeasi** [comment]
Hi there,

You do not need to tag me/reply in all caps. I am subscribed to this issue, so I already get an email notification when you reply.

I started looking at your issue last week, but was out of office for part of the week so I did not get a chance to finish my investigation. I am continuing to look into your issue today and will post a reply when I have more to share.

**Comment by liamdebeasi** [comment]
Hi there,

I took a closer look at this issue and it looks like things are working as intended. Going from `/page2` to `/page3` and back to `/page2` will cause Ionic Angular to reuse the first instance of `/page2`. In other words, we consider navigating to `/page2 --> /page3 --> /page2` the same as doing `/page2 --> /page3 --> go back`. 

When Ionic Angular sees a user navigating to `/page2` again it pops `/page3` off the stack and destroys the component instance since it is no longer needed. This results in the behavior you are describing where the form data is "lost".

There are 2 reasons why we do this:

1. If we created a new instance of the page every time someone navigated to it, users could potentially navigate infinitely between `/page2` and `/page3`. Not only is this a confusing UX pattern, it also would lead to performance issues as you could have hundreds of pages in the DOM.
2. Ionic Angular has no idea what is being rendered on each page, so even if this was a functionality we wanted to implement, there is no way we could safely do this without potentially opening users up to memory leaks.

When going from `/page3` back to `/page2` you could use `routerDirection="back"` to give the visual indication that you are popping off the stack.
