### ISSUE TITLE
Slides component breaks on iOS physical devices when there's a large number of slides

### ISSUE THREAD

**Issue by gongiskhan** [ionic-team/ionic-framework#23126]
**Ionic version:**
[x] **4.x**
[x] **5.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**

When increasing the number of slides from 20 to 150 we see that swiping or clicking buttons that call slideNext() stops working (does not move to another slide).

This happens only on iOS (works on desktop) and only physical devices (we tested on iPhone XS Max - iOS 14.4.2, but we have reports of the issue for the iPhone 12).

**Expected behavior:**
The slides should move when swiping or calling slideNext()

**Steps to reproduce:**
We are providing a minimum reproducible example. 
For observing the issue simply run the app on iOS (capacitor) and try to swipe or clicking the right arrow.
For observing that it works with less slides, remove all but 20 slides form the file `src/app/home/theQuestions.ts`

**Related code:**

https://github.com/gongiskhan/Slides_Issue_Example

**Other information:**
There are no errors on the console.

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/Users/ggomes/.nvm/versions/node/v10.24.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.6.3
   @angular-devkit/build-angular : 0.1102.6
   @angular-devkit/schematics    : 11.2.6
   @angular/cli                  : 11.2.6
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   capacitor (Capacitor CLI) : 2.4.7
   @capacitor/core           : 2.4.7

System:

   NodeJS : v10.24.0 (/Users/ggomes/.nvm/versions/node/v10.24.0/bin/node)
   npm    : 6.14.11
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I can reproduce the behavior you are reporting, but I do not think that this is a bug in Ionic Framework. I looked at a performance timeline on iOS and noticed that is was spending a lot of time recalculating the styles. `ion-slides` uses Swiper.js under the hood, and they manage the slide transitions by setting `transform` directly on the wrapper element. In other words, for each frame rendered in the transition, the browser needs to recalculate the styles. Given that you have 150 slides in here, trying to recalculate the styles on a container with 150 slides is likely to lead to performance issues.

A few ideas:

1. You could use the Swiper library directly as it gives you access to a "Virtual Slides" module: https://swiperjs.com/swiper-api#virtual-slides. The Virtual Slides module allows Swiper to keep the minimum number of slides in the DOM at once, which should help performance issues here. There are Angular-specific instructions here: https://swiperjs.com/angular#virtual-slides

2. Instead of using `ion-slides` or Swiper.js directly, you might want to try CSS Scroll Snapping which allows you to create a carousel-like effect using just CSS. This might be a bit more work to wire up, but I think it would be the best in terms of performance. Here are some guides on how to get started with CSS Scroll Snap:

https://css-tricks.com/practical-css-scroll-snapping/
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/Basic_concepts

**Comment by gongiskhan** [comment]
Hey Liam,

Just wanted to say thank you for looking into it and your suggestions. I’m not used to posting issues (in 13 years this probably my first! :)) and thought github would warn about a reply...

Will leave the final solution here when have it. Just for the unlikely event someone else hits something similar...
