### ISSUE TITLE
bug: ion-slides lazy loading does not work

### ISSUE THREAD

**Issue by HyperLife1119** [ionic-team/ionic-framework#23142]
# Bug Report

**Ionic version:**

 **5.x**

**Current behavior:**

ion-slides lazy loading does not work

**Expected behavior:**

ion-slides lazy loading should work fine

**Steps to reproduce:**

**Related code:**

```html
  <ion-slides [options]="slideOpts">
    <ion-slide *ngFor="let item of data; trackBy: trackByFn">
      <img class="swiper-lazy" [attr.data-src]="item.data['url']">
    </ion-slide>
  </ion-slides>
```

```ts
  slideOpts = {
    initialSlide: 1,
    // Disable preloading of all images
    preloadImages: false,
    // Enable lazy loading
    lazy: true,
    zoom: {
      maxRatio: 3,
      minRatio: 0.75,
      toggle: true
    }
  };
```

**Other information:**

https://swiperjs.com/swiper-api#lazy-loading

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. The Lazy Loading feature is a separate module in Swiper that Ionic Framework's `ion-slides` does not ship with which is why this feature does not work. We have some big quality of life improvements with using Swiper in Ionic Framework coming in the next major release of the Framework, so for now we recommend using the Swiper Angular library directly if you want to access lazy loading: https://swiperjs.com/angular
