### ISSUE TITLE
bug: ion-back-button doesn't trigger any events

### ISSUE THREAD

**Issue by czzplnm** [ionic-team/ionic-framework#23196]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
Our user navigates between pages and upon entering a view with tabs & children it seems the ion-back-button will not fire any events.

**Expected behavior:**
A view event would be triggered.

**Steps to reproduce:**
Route to a component that has tabs/children, click <ion-back-button>, no events get triggered

**Related code:**

These are the events I am listening to: 
```

    ionViewWillLeave() {
      this.clearSystemHomeInterval();
    },

    ionViewDidLeave() {
      this.clearSystemHomeInterval();
    },

    ionNavDidChange() {
      this.clearSystemHomeInterval();
    },

    ionViewWillUnload() {
      this.clearSystemHomeInterval();
    },

    ionViewDidEnter() {
      this.reloadDataIntervalId = setInterval(() => {
        this.loadSystemHome();
        this.triggerChart();
      }, Config.interval.systemHomeReloadData);
    },
```

Only the ionViewDidEnter works

As a work around I added a custom @click handler to <ion-back-button>
`<ion-back-button default-href="/installations" @click="goBack"></ion-back-button>`

**Other information:**
https://github.com/czzplnm/ion-back-button-no-events

**Ionic info:**

Ionic:

   Ionic CLI       : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.6.4

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.19.0 (/usr/bin/node)
   npm    : 6.14.4
   OS     : Linux 5.8

  ─────────────────────────────────────────────────

     Ionic CLI update available: 6.12.3 → 6.13.1
          Run npm i -g @ionic/cli to update

  ─────────────────────────────────────────────────

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce this in an Ionic starter app and provide a link to the repo? Also `ionViewWillUnload` and `ionNavDidChange` are not valid Ionic page lifecycle events, so I would not expect those to fire.

**Comment by czzplnm** [comment]
Here is the reproduction:

https://github.com/czzplnm/ion-back-button-no-events

From the Home page, click 'Go to tabs' then from the tabs page, click the back button in the top left. No events are triggered.


![image](https://user-images.githubusercontent.com/5511418/114918716-41f6ee80-9ddc-11eb-84e0-85ca0df143a7.png)

![image](https://user-images.githubusercontent.com/5511418/114918737-491dfc80-9ddc-11eb-946a-fa28b54d20c6.png)

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce the behavior you are describing. The problem here is that when you click the back button you are navigating the `Tabs` component away, not just `Tab1`. You should have these lifecycle events on your `Tabs` component if you want to know when the entire tabs context shifts away.

Another way to look at it is when you go from `Tab1` to `Tab2`, the events fire as expected since the `Tab1` page itself is navigating away. When you navigate  back to the `Home` page, the `Tabs` component navigates away. However, within the `Tabs` component, `Tab1` remains active.

Ionic Lifecycle hooks are working as intended, though I can understand why this behavior may be confusing. We might be able to get the lifecycle hooks firing on the inner tab pages, though the downside is that we would need to unmount the `Tab1` page as your `Tabs` page begins to transition away. The work to do this is part of https://github.com/ionic-team/ionic-framework/issues/23058, so I am going to track progress there.

**Comment by czzplnm** [comment]
In the example I provided the Tab1 componenet has a setInterval running that we need to cancel when navigating away. There has to be a way to know when you are leaving Tab1.

**Comment by liamdebeasi** [comment]
You could listen for route changes within the Tab1 component rather than do a `setInterval`:

```js
import { watch } from 'vue';
import { useRoute } from 'vue-router';

...

const route = useRoute();

watch(route, () => {
  // do something in here
});
```

As per my previous comment we can look into adding support for this, but all progress will be tracked in https://github.com/ionic-team/ionic-framework/issues/23058.
