### ISSUE TITLE
bug: <ion-toast> is not a known element (angular)

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic-framework#23244]
Same as https://github.com/ionic-team/ionic-framework/issues/23068 but with the repo : https://github.com/Yohandah/ionic-bug-toast

**Ionic version:**

[x] 5.x

**Current behavior:**
I need to load IonToast js at startup in case I lose network to let the user know. So I did as Liam recommends here #17450 (comment) by just adding a `<ion-toast></ion-toast>` at the root of `<ion-app>`.

While this solution works for the loading at startup, my IDE (WebStorm) throw a warning :

![image](https://user-images.githubusercontent.com/15921402/116242248-065a0e00-a766-11eb-8278-9fb3d3c626d8.png)

And my Angular project compilation works in dev, but not in prod, it throws the following error and therefore I cannot compile :

`error NG8001: 'ion-toast' is not a known element`

I do import IonicModule.forRoot() in my app.module.ts.

I can make my app compile in prod by adding `schemas: [CUSTOM_ELEMENTS_SCHEMA]` in my app.module.ts, but since we can use `<ion-toast>` in a template, it would make sense if Ionic was exposing `<ion-toast>` tag to Angular ?

**Expected behavior:**

An Angular project using the tag `<ion-toast>` should compile in production configuration

**Steps to reproduce:**

* clone https://github.com/Yohandah/ionic-bug-toast.git
* npm run build-prod
* it fails

**Related code:**

https://github.com/Yohandah/ionic-bug-toast

**Comment by liamdebeasi** [comment]
Thanks for the issue. For Ionic Angular users `<ion-toast>` was only ever intended to be used via the `ToastController` dependency injection. As a result, we do not have `<ion-toast>` in our proxy list here: https://github.com/ionic-team/ionic-framework/blob/master/angular/src/directives/proxies.ts. This is likely why you are receiving this warning.

To fix this, I recommend using the `ToastController` instead of placing the component in the template directly. (I did not notice this in the original comment you linked to because I was using vanilla JS). The solution posted in https://github.com/ionic-team/ionic-framework/issues/17450#issuecomment-504183616 should be fine instead.
