### ISSUE TITLE
bug: title runs into button when inside ion-toolbar (ios only)

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic-framework#23264]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
title runs into the button when inside ion-toolbar and its mode is "ios" or no mode is set and the app runs under ios. please note that everything works fine if mode="md" or the app runs under android.

Here are the screenshots demonstrating the problem
***iOS***
![ios](https://user-images.githubusercontent.com/3608222/116963728-5b3fdc00-acb2-11eb-9143-8ce35549e404.png)

***Android***
![android](https://user-images.githubusercontent.com/3608222/116963756-698df800-acb2-11eb-9ec1-7560a98e0b6d.jpg)

***Browser***
![browser](https://user-images.githubusercontent.com/3608222/116963763-6bf05200-acb2-11eb-928d-f14729a5bc06.png)

**Expected behavior:**
Title must not runs into the button

**Steps to reproduce:**
Here is the repository to demo the problem https://github.com/ryaa/ion-toolbar-text-overlap

**Related code:**
See the repository above

**Other information:**
N/A

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.12.4 (/Users/alexryltsov/.nvm/versions/node/v12.16.3/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.6
   @angular-devkit/build-angular : 0.1102.11
   @angular-devkit/schematics    : 11.2.11
   @angular/cli                  : 11.2.11
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run                             : not installed

System:

   NodeJS : v12.16.3 (/Users/alexryltsov/.nvm/versions/node/v12.16.3/bin/node)
   npm    : 6.14.11
   OS     : macOS Big Sur
```

**Comment by ryaa** [comment]
Adding position: relative to ion-title seems to be fixing the issue.
Is there any specific reason that position is absolute for ion-title - see https://github.com/ionic-team/ionic-framework/blob/master/core/src/components/title/title.ios.scss#L10?

**Comment by liamdebeasi** [comment]
Thanks for the issue. `ion-title` on iOS has `position: absolute` so that it remains centered between the buttons on either side when used in the header. Here is a comparison:

| `position: absolute` | `position: relative` |
| -------------------- | ------------------ |
| ![Screen Shot 2021-05-04 at 10 54 39 AM](https://user-images.githubusercontent.com/2721089/117023513-2d18c700-acc7-11eb-998f-4ceb05484117.png) | ![Screen Shot 2021-05-04 at 10 54 50 AM](https://user-images.githubusercontent.com/2721089/117023531-3013b780-acc7-11eb-8423-2f48b8314f53.png) |

The downside is that `absolute` removes the element from the normal document flow, so some properties do not work as normally expected. That being said, how `ion-title` is being used in your example application is not really how it is intended to be used in the Framework. Usage examples should be improved in the docs, but `ion-title` should be used as a "top level" header inside of `ion-header` or `ion-footer` rather than a general heading component.

A better usage here would be to use `ion-item` instead without an `ion-toolbar`:

```html
<ion-item>
  <ion-label>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at tortor lobortis, molestie enim nec, ultrices tortor</ion-label>
  <ion-button slot="end">
    <ion-icon slot="icon-only" name="close-outline"></ion-icon>
  </ion-button>
</ion-item>
```

I am going to close this as this is more of a usage issue than a bug in Ionic Framework.
