### ISSUE TITLE
feat: Tree Shaking Ionic components

### ISSUE THREAD

**Issue by codewithtushar** [ionic-team/ionic-framework#23306]
# Feature Request

**Ionic version:**

[x] **4.x**
[x] **5.x**

**Describe the Feature Request**

I've been using ionic in my angular projects (mostly portals), after running webpack-bundle-analyzer i don't see unused ionic components getting removed, i tried with --prod build but no luck

**Describe Preferred Solution**

 my app heavily depends on tables & forms, i'll be using material tables  for now

**Comment by liamdebeasi** [comment]
Thanks for the issue. Work is already underway to improve tree shaking with Ionic component in Ionic Framework v6. The main issue here is because of Stencil Lazy Loading, Webpack incorrectly thinks that every Ionic component is needed, so it bundles everything. Moving off Stencil Lazy Loading should address this issue.
