### ISSUE TITLE
bug:  Ionic 5 Angular - after router constructor is not working

### ISSUE THREAD

**Issue by dineshmaths1** [ionic-team/ionic-framework#23329]
Hii,
I am using ionic5 with angular 11 this is my router url 'dashboard'  .
if i back to dashboard url  api is not hitting  also ngoninit.
i want to refresh new data.
how to fix?

**Comment by DwieDima** [comment]
Hi @dineshmaths1, this is not a bug of ionic, but a intentional behavior of angular for performance reasons.

you can change the route strategy for your dashboard page

```
import { Router } from '@angular/router';
constructor(private router: Router) {
    this.router.routeReuseStrategy.shouldReuseRoute = () => false;
}
```

or you could subscribe to route params inside `ngOnInit()`

```
  import { ActivatedRoute } from '@angular/router';
  constructor(private activatedRoute: ActivatedRoute) { }

 ngOnInit() {
 this.activatedRoute.params
      .subscribe((params) => {
         // your api calls will get triggered every time here
      }
}
```

I've found an article which adresses your issues in more detail.

https://medium.com/angular-in-depth/refresh-current-route-in-angular-512a19d58f6e

Hope that helps.

**Comment by elvisgraho** [comment]
Is there a way to globally set the router to force components ngOninit every time no matter what when navigating?

**Comment by DwieDima** [comment]
> Is there a way to globally set the router to force components ngOninit every time no matter what when navigating?

i havent tried it myself, but you can define your own route strategy inside app.module.ts.
Maybe you can override the `IonicRouteStrategy` and set `shouldReuseRoute` to false
