### ISSUE TITLE
bug: @ionic/react-router@5.6.7" has unmet peer dependency "@ionic/core@5.6.7"

### ISSUE THREAD

**Issue by avalanche1** [ionic-team/ionic-framework#23346]
# Bug Report
I have a vanilla starter ionic-react app. When doing `yarn install`, I get tf warning in the console: 
`@ionic/react-router@5.6.7" has unmet peer dependency "@ionic/core@5.6.7"`.
And also:
` @testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4"`
Plz fix the dependencies.

**Ionic version:**

[ ] **4.x**
[x] **5.6.7**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.14.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.7

Capacitor:

   Capacitor CLI   : 3.0.0
   @capacitor/core : 3.0.0

Utility:

   cordova-res : not installed
   native-run  : 1.3.0

System:

   NodeJS : v16.1.0 (/usr/local/bin/node)
   npm    : 7.11.2
   OS     : macOS Mojave

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. What version of Yarn are you using?

**Comment by avalanche1** [comment]
`1.22.10`

**Comment by liamdebeasi** [comment]
Thanks! I can resolve the `@ionic/react-router@5.6.7" has unmet peer dependency "@ionic/core@5.6.7"` warning, but the `@testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4"` warning is not something we are able to control. Looking at https://github.com/testing-library/user-event/issues/551#issuecomment-770337264, this seems to be an intentional change.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23351, and a fix will be available in an upcoming release of Ionic Framework.
