### ISSUE TITLE
bug: Ionic React Router - Not navigating off of "/" route

### ISSUE THREAD

**Issue by creativiii** [ionic-team/ionic-framework#23440]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When using React Navigation it seems like once the `/` route has been rendered, it will precede every other route. So navigating to `/test` from `/` will just not work.

**Expected behavior:**

React Router, over which React Navigation is built, uses a priority system. So if the `/` page is the last rendered route in a list of routes, it will not take precedence over the others.

I realise this may have been done on purpose, but if that is the case it should probably be mentioned front and center on the docs.

**Steps to reproduce:**

[I created a StackBlitz example to show the problem.](https://stackblitz.com/edit/ionic-react-routing-sjrn41?file=src%2FApp.tsx)

**Comment by creativiii** [comment]
Hi Liam, this is not a bug with React Router. As mentioned in my post React Router uses the order the components are added to decide what to render first.

If the `/` is left for last then everything else will render correctly without `exact`.

I'm pretty sure this is a bug with Ionic React, could we reopen it?

**Comment by liamdebeasi** [comment]
I did not say this was a bug in React Router. It looks like your second example has the `/path` route defined first and the `/` route defined second. I may have copy and pasted the first example wrong, but regardless this is still not a bug in Ionic React.

In the [Router in Ionic React](https://ionicframework.com/docs/react/navigation#routing-in-ionic-react) documentation, it says you need to use the `exact` prop on your `/` path even if it defined last. The docs give the following example:

```js
const App: React.FC = () => (
  <IonApp>
    <IonReactRouter>
      <IonRouterOutlet>
        <Route path="/dashboard" component={DashboardPage} />
        <Redirect exact from="/" to="/dashboard" />
      </IonRouterOutlet>
    </IonReactRouter>
  </IonApp>
);
```

The reason why this behavior varies slightly is that Ionic React will keep old views in the DOM so we can quickly transition back to them via the swipe to go back gesture. As a result, we need to be more careful about matching paths to views otherwise we will show the wrong view. This is different from `BrowserRouter` which only renders one view at a time.

**Comment by liamdebeasi** [comment]
Also this behavior difference between `IonRouterOutlet` and `BrowserRouter` is mentioned in our docs here: https://ionicframework.com/docs/react/navigation#ionrouteroutlet
