### ISSUE TITLE
bug: ion-select not emitting event ionChange

### ISSUE THREAD

**Issue by Avratz** [ionic-team/ionic-framework#23459]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
Im trying to listen to @ionChange from ion-select in Vue 3 and its not working. In Vue 2.x works fine for some reason.

**Expected behavior:**
@ionChange event fired from ion-select

**Steps to reproduce:**
Im not importing the components from @ionic/vue. I am trying to use javascript version of the framework inside a vanilla js app with vue3 from CDN, without a bundler

**Related code:**
```
	<ion-select 
		interface="action-sheet"    
		:value="filter"
		@ionChange="filter = $event.target.value"
	>
		<ion-select-option value="project">By proyect</ion-select-option>
		<ion-select-option value="client">By client</ion-select-option>
	</ion-select>

```

	app.config.isCustomElement = tag => tag.startsWith('ion-')
	app.mount('#app')

**Comment by liamdebeasi** [comment]
Sorry, I meant to reply to this before I added the `ionitron: support` label. We strongly recommend importing the components from `@ionic/vue` as it provides Vue wrappers that make it easier to use `v-model`, listen for events, and bind properties. If you are using the vanilla Web Components without this integration, things are likely going to be much more difficult to use.

I closed this since it sounds like you are having trouble integrating Ionic Framework into your application rather than reporting a particular bug in the Framework. In these cases, we recommend posting on the [Ionic Fourms](https://forum.ionicframework.com/) for assistance as we do not provide support on GitHub.
