### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by maljac** [ionic-team/ionic-framework#23460]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
Provide a different method to create e.g. `Modal` in order to inject/construct the `ModalComponent`.

Let's say we have a common select component that should be used as `modalComponent`. The select component itself extends some abstract component which needs some record service:

```
class CommonSelectComponent<T, U> extends BaseListComponent<T, U> {

  constructor(modelService: BaseModelService<T>)

}
```

The actual model services extend the `BaseModelService<T>`:

```
class ProductService extends BaseModelService<T>{}
class CustomerService extends BaseModelService<T>{}
```

When creating the actual modal in a common modalsService there is no possible way to manipulate the injector / pass a actual instance into the `CommonSelectModal`:

```

class ModalService {
  ...
  createSelectModal(service: BaseModelService<T>) {
      const modal = await this.modalController.create({
        component: CommonSelectComponent,
        ...this.commonProps()
      });
  }
...
``` 
Naturally the creation fails with `No provider for BaseModelService!`

**Describe Preferred Solution**
- 

**Describe Alternatives**
- 

**Related Code**

Maybe relevant code: https://github.com/ionic-team/ionic-framework/blob/master/angular/src/providers/modal-controller.ts#L22

**Additional Context**

I think the intention of issue #22453 is similar to the feature request.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Angular recommends injecting your service directly into your modal component, so if you are getting a `No provider for BaseModelService!` error, then the injection likely is not in the correct place.

Can you reproduce this issue in an Ionic starter app and provide a link to the repo?

**Comment by maljac** [comment]
While I found a solution for this problem (which is quite stupid), I think that the feature request is still relevant. 

> Angular recommends injecting your service directly into your modal component, so if you are getting a No provider for BaseModelService! error, then the injection likely is not in the correct place.

As I wrote, I know this behaviour / the Angular recommendations and the error I got is totally clear for me. What I wanted to bring on the table is the request for a possibility to create a modal with the `ModalController` in a different way (maybe with a custom injector etc. in order to provide specific instances to the constructor).

**Comment by liamdebeasi** [comment]
Thanks for the additional information. I think this functionality is better implemented on a per application basis since it seems very specific to the application. 

I talked with the team and this is not a feature we are looking to add at the moment.  Going against what Angular recommends in terms of dependency injection is not something we are comfortable doing. As mentioned in https://github.com/ionic-team/ionic-framework/issues/22453#issuecomment-724228343, one idea is you could use the `providers` array in your modal's NgModule to provide a new instance of the service to your modal.

I recommend posting on the [Ionic Forums](https://forum.ionicframework.com/) and you should be able to get assistance implementing the behavior you want in your application.
