### ISSUE TITLE
bug: Angular min/max validation not working on ion-input

### ISSUE THREAD

**Issue by tn185070** [ionic-team/ionic-framework#23480]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Angular min/max validation is not working on ion-inputs of type number.

**Expected behavior:**

min/max validation works on ion-inputs.

**Steps to reproduce:**

Type a number outside of the allowed range into the input and see that the form is still valid. 

**Related code:**

StackBlitz with regular `input` and `ion-input` demonstrating the issue: https://stackblitz.com/edit/ionic-angular-v5-qyn5kf?file=src/app/app.component.html.

**Other information:**

 #20163 and #18240 reported this previously but at that time the issues were closed because it was a bug in Angular. Now Angular has fixed their bug in version 12 (angular/angular#39063) but the validation is still not working for ion-inputs. If I change ion-input to a input then the validation works.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 12.0.0
   @angular-devkit/schematics    : 12.0.0
   @angular/cli                  : 12.0.0
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   NodeJS : v14.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.11.3
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. The problem here appears to be that the min and max validators in Angular look specifically for `input[type=number]`, but we need the validators to see `ion-input[type=number]`, so the max/min validators are never setup on the `ion-input` components in your test app: https://github.com/angular/angular/blob/master/packages/forms/src/directives/validators.ts#L168

Other validators, such as https://github.com/angular/angular/blob/master/packages/forms/src/directives/validators.ts#L619, do not have this restriction as they only look for the attributes, allowing them to pick up `ion-input`.

One option here is to extend the `MaxValidator` and `MinValidator` directives with selectors that allow for `ion-input`, but I am trying to understand why these new validators are restricted to only `input` while other validators such as `maxlength` are not, despite `maxlength` only being available for input and textarea. I reached out to the Angular team for clarification, so hopefully we should have an idea as to how to solve this issue soon.

**Comment by liamdebeasi** [comment]
I touched based with the Angular team and it looks like this change was done so as to not conflict with 3rd party libraries that have their own max/min validators. I think extending the validators with a custom selector for `ion-input` seems like to best option here.

**Comment by JulienLecoq** [comment]
Any news about this issue?
