### ISSUE TITLE
feat: Toast Style on iOS

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#23514]
# Feature Request

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[X] **6.x**

**Describe the Feature Request**

Since the new iOS Toast style is being adopted with the new version of iOS would be great to have it as a component in ionic. The toast style can be seen here along with its animation considering the current toast animation does not seem proper also

<img width="1152" alt="Screenshot 2021-06-25 at 9 34 43 PM" src="https://user-images.githubusercontent.com/61012396/123432941-81706100-d5fd-11eb-9f1b-368d28443817.png">

**Comment by BerkeAras** [comment]
@farisfaisalthena  Thanks for your issue. I already restyled it (for iOS 14, but I could update for iOS 15). Unfortunately the Pull Request was rejected and closed with this reason: https://github.com/ionic-team/ionic-framework/pull/22676#issuecomment-792880404

You can find the PR here: #22676

**Comment by farisfaisalthena** [comment]
@BerkeAras that would be great. I did noticed that the toast on some native ios device apps has the new style so i dont think its for privacy focused only 🤔

**Comment by BerkeAras** [comment]
@farisfaisalthena Oh really :D Could you give an example of an app that uses the new style?

**Comment by farisfaisalthena** [comment]
>Could you give an example of an app that uses the new style?

Sorry for not providing more context. The information can be seen here (https://github.com/ionic-team/ionic-framework/issues/23423#issuecomment-856740471)

**Comment by liamdebeasi** [comment]
Thanks for the issue. As I mentioned in https://github.com/ionic-team/ionic-framework/pull/22676, we do not have plans to implement this since the intended usage is for system notifications only.

I checked with the team and confirmed that this type of notification is not available to native Swift developers either, so the example application provided likely implemented something custom. That being said, if this is something you would like in your application, you should be able to customize your `ion-toast` components using the provided CSS Variables and Shadow Parts.
