### ISSUE TITLE
bug: custom elements build, ionic components not defining children

### ISSUE THREAD

**Issue by tho-masn** [ionic-team/ionic-framework#23571]
# Bug Report

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[x] **6.x**

**Current behavior:**
Using the `ion-select` Vue component in combination with the option `interface="popover"` doesn't work correctly. If the popover gets triggered, the content is not displayed correctly in v6-beta.0, as you can see from the screenshots below.

v5:

![Screenshot 2021-07-02 at 10 43 20](https://user-images.githubusercontent.com/23264228/124247847-92036880-db22-11eb-9f47-3ad0df07d1bb.png)

v6:

![Screenshot 2021-07-02 at 10 43 51](https://user-images.githubusercontent.com/23264228/124247858-93cd2c00-db22-11eb-8e6b-9feb50da64d0.png)

**Expected behavior:**
Popover of `ion-select` component should be displayed correctly.

**Steps to reproduce:**
Sample code for v5: https://github.com/tho-masn/ionic-issues/tree/v5-ion-select-popover
Sample code for v6: https://github.com/tho-masn/ionic-issues/tree/v6-ion-select-popover

**Comment by stewones** [comment]
This is so sad ;(

**Comment by LevSaltsyn** [comment]
i fix this problem like that:
`  <ion-select
                      class="standart-values-select"
                  
                      interface="popover"
                      onIonChange={(event) => {
           
                        this.standardValueChanged(event, axis);
                      }}
          
                      **value={`${this.size[axis]}`}**
                    >
                      {this.sizes[axis].standardValues.map((size: number) => (
                        <ion-select-option **value={`${size}`}**>
                          {size}
                        </ion-select-option>
                      ))}
                    </ion-select>`
                    
                    
                    Value mast be as **string**.
                    
                 "@ionic/core": "6.0.0-beta.6",
                 "@stencil/core": "2.8.1",

**Comment by liamdebeasi** [comment]
The problem here is that Ionic components that use other Ionic components inside of them do not get their child components registered when using the Custom Elements build.

So in this case, `ion-select` uses an internal `select-popover` component, but the `select-popover` component never gets defined when using the Custom Elements build.

This issue also impacts components like `ion-datetime` because it uses other components such as `ion-item`, `ion-popover`, etc. As a temporary workaround, you can place instances of these child components in your app to make sure they are defined and hide them with `display: none`.

The Stencil team has developed a fix, and we are in the process of testing and verifying that it fixes the issue. We hope to have this fix out soon. Thanks!

**Comment by willmartian** [comment]
This issue has been resolved in #24191, and the fix will be available in Ionic v6.0.0-rc.3. Thanks everyone!
