### ISSUE TITLE
bug: [VUE] "ion-page not exists" warning shows up if ion-page is wrapped by a sub component

### ISSUE THREAD

**Issue by tho-masn** [ionic-team/ionic-framework#23675]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

I'm using a "BasePage" component in my ionic vue project, so I don't have the page creation overhead on every page.
After this commit (https://github.com/ionic-team/ionic-framework/commit/3cebcb08833d891bbbb829d344e70ecd12c6d4b8) I'm always getting the following console warning:

![Screenshot 2021-07-23 at 10 38 50](https://user-images.githubusercontent.com/23264228/126758103-0c7eafc7-0ac2-4e54-85ab-edc027c06b99.png)

The ion-page component is there, it's just wrapped in a sub component.

### Expected Behavior

The warning should not be present, if the ion-page component is added to the page within a sub component

### Steps to Reproduce

- Create a BasePage component, which includes the ion-page component
- Use the BasePage component in any view
- Check console for error

### Code Reproduction URL

https://github.com/tho-masn/ionic-issues/tree/no_ion_page_component_warning

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23677, and a fix will be available in an upcoming release of Ionic Framework.

I changed the `<ion-page>` detection so that it only fires when trying to transition a page that does not have `<ion-page>`. The downside is that if you land on a view directly without a transition, the warning will not fire, but whenever you try to transition to/from the page you will get the warning.
