### ISSUE TITLE
bug: (vue) Switching between tabs with a query string messes up route

### ISSUE THREAD

**Issue by boboldehampsink** [ionic-team/ionic-framework#23699]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

I have a url with a custom query param, i.e.: `http://localhost:8080/meer?domain=dCWh5t1dnF.pwa.autosociaal.nl`, which is the "meer" tab. When I go to the "start" tab the url changes to `http://localhost:8080/start?domain=dCWh5t1dnF.pwa.autosociaal.nl`. When I click the "meer" tab again it again changes back to `http://localhost:8080/meer?domain=dCWh5t1dnF.pwa.autosociaal.nl`. Now, when I click the start tab again it suddenly becomes: `http://localhost:8080/startdomain=dCWh5t1dnF.pwa.autosociaal.nl?domain=dCWh5t1dnF.pwa.autosociaal.nl`

I have this router lifecycle hook in place to make it happen:

```
router.beforeEach(async (to, from, next) => {
  if (from.query.domain && !to.query.domain) {
    next({ ...to, query: from.query });
    return;
  }

  next();
});

```

### Expected Behavior

The pathname should just be `start` or `meer`, not `startdomain`

### Steps to Reproduce

Create a tabs setup with this router lifecycle hook:

```
router.beforeEach(async (to, from, next) => {
  if (from.query.domain && !to.query.domain) {
    next({ ...to, query: from.query });
    return;
  }

  next();
});
```

In this app it is also reproducable: https://7cu0jmqxdb.appflowapp.com/tabs/tab1?domain=dCWh5t1dnF.pwa.autosociaal.nl - start clicking between the tabs and see the route pathname of tab1 change between the clicking to tab1domain

### Code Reproduction URL

https://7cu0jmqxdb.appflowapp.com/tabs/tab1?domain=dCWh5t1dnF.pwa.autosociaal.nl

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.16.3 (/Users/bob/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.6.12

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v14.17.3 (/Users/bob/.nvm/versions/node/v14.17.3/bin/node)
   npm    : 6.14.13
   OS     : macOS Big Sur
```

**Comment by Predarion** [comment]
Same issue here, query params on a route within tabs are not working, when switching back to a tab.
- Navigate to tabs/tab1/subpage?exampleparam=test
- Tab on second tab in tab bar --> App goes to tabs/tab2
- Tab on first tab in tab bar --> error: 
No match found for location with path "/tabs/tab1/subpageexampleparam=test"
fullPath is: "/tabs/tab1/subpageexampleparam=test?exampleparam=test"

The path gets messed up.

**Comment by Predarion** [comment]
@boboldehampsink have you resolved this somehow?

**Comment by boboldehampsink** [comment]
@Predarion no, still no fix

**Comment by Predarion** [comment]
I created a reproduction (based on the Ionic Vue tabs starter) myself, as the initial link of @boboldehampsink does not work (access denied).

### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [x] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [x] I have searched for existing issues that already report this problem, with success: found this issue here.

### Ionic Framework Version

- [ ] v4.x
- [x] v5.x
- [x] v6.x

### Current Behavior

I think the screenrecording explains it quite well:

https://user-images.githubusercontent.com/24892172/141449859-d016d734-49ba-4e61-a413-81db462494da.mov

### Expected Behavior

When executing step 5, I expected to be routed to tab2/subpage having the path and query parameter set corretly, i.e. URL: 
```
http://localhost:8100/tabs/tabs2/subpage?test=this-is-a-test-value
```

###  Steps to Reproduce 

1. Run app in terminal using
```
ionic serve
```

2. go to http://localhost:8100
3. You will be redirect to Tab1. Now, press "Tab2" button in Tabbar
4. You will be routed to Tab2. Now press the RouterLink "Go to: /tabs/tab2/subpage"
5. You will be routed to Tab2Subpage. Now press "Tab1" button in Tabbar
6. You will be routed to Tab1. Now press "Tab2" button in Tabbar
7. Routing will now fail as the app tries to route to 
```
http://localhost:8100/tabs/tab2/subpagetest=this-is-a-test-value?test=this-is-a-test-value
```

### Code Reproduction URL

https://github.com/Predarion/ionic-vue-tabs-routing-query-bug

###  Ionic Info 

```
Ionic:

   Ionic CLI       : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.8.5

Capacitor:

   Capacitor CLI      : 3.3.1
   @capacitor/android : not installed
   @capacitor/core    : 3.3.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (/usr/local/bin/node)
   npm    : 8.1.0
   OS     : macOS Big Sur
```

### Additional Information

I also tested this with

```
"@ionic/vue": "6.0.0-rc.2",
"@ionic/vue-router": "6.0.0-rc.2",
```

so its also a Ionic v6 issue!

**Comment by Predarion** [comment]
@liamdebeasi to me, this is quite a critical bug, I would really appreciate your effort if you look into it!

**Comment by liamdebeasi** [comment]
Can you try the following dev build and let me know if it fixes the issue?

```
npm install @ionic/vue@5.10.0-dev.202112011701.ac1402b @ionic/vue-router@5.10.0-dev.202112011701.ac1402b
```

**Comment by Predarion** [comment]
**Works!** 

I just tested the dev build in the reproduction project as well as our actual project.

Thank you very much for your effort, I really appreciate it!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24297, and a fix will be available in an upcoming release of Ionic Framework.
