### ISSUE TITLE
feat: Expose `data` in ActionSheet button props

### ISSUE THREAD

**Issue by godenji** [ionic-team/ionic-framework#23700]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Currently it is impossible to thread `data` through chained ActionSheet instances -- one has is to resort to mutable state via button `handler` to simulate missing data property (yes, the property exists, but is only populated when invoking `dismiss`, which is useless for cases where the user selects an item from the list).

### Describe the Use Case

```typescript
this.action.create({ handler: () => this.mutable = someData, ... }).then(outer => {
  outer.onDidDismiss().then(x => {
    this.action.create({...}).then(inner => {
      const d = this.mutable // only option is mutable state
      inner.onDidDismiss().then(...)
      inner.present()
    })
  })
  outer.present()
})
```

### Describe Preferred Solution

```typescript
this.action.create({ buttons: [{data: ...}], ... }).then(outer => {
  outer.onDidDismiss().then(x => {
    this.action.create({...}).then(inner => {
      const d = x.data // data threaded through, no instance level props
      inner.onDidDismiss().then(...)
      inner.present()
    })
  })
  outer.present()
})
```

### Describe Alternatives

It was suggested in the forum to hijack the `role` property as a substitute, which would work if one were only passing `string`s, but falls apart for any other data type.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please describe the problem you are trying to solve/the user case?

**Comment by godenji** [comment]
`ActionSheet`s can be useful where rapid user interactions (e.g. clicking several options in succession) are required; with the existing design the only way to manage state is via button `handler`, which is side effecting (i.e. state has to be maintained at class level via some mutable instance).

The alternative solution is to expose `data` property at the `buttons` level such that on every `onDidDismiss` event built-up state can be accessed via its `data` property (much like `role` currently works), rather than relying on `handler` call to mutate class level state.

**Comment by liamdebeasi** [comment]
Thanks. Can you provide a code example of what you are trying to do? It would be helpful to see any workarounds you have developed as well as an interactive example of any problems that arise.

**Comment by godenji** [comment]
There are no workarounds that I know of, mutable state is the only possible approach since side effecting `handler` is all we have to work with.

Here's a contrived non-abstracted example of what threaded ActionSheet `data` could look like:
```typescript
this.action.create({
  header: 'Select Type',
  buttons: [{
    text: 'SomeEnumType',
    data: { type: SomeType }, // thread through data object
    handler: () => {} // no mutable state required to build up data object
  }], ... 
}).then(outer => {
  outer.onDidDismiss().then(x => {
    this.action.create({
      header: 'Select Target',
      buttons: [{
        text: 'SomeEnumTarget',
        // append "parent" data if exists
        data: x?.data ? { ...x.data, target: SomeTarget } : { target: SomeTarget },
        handler: () => {}
      }], ...
    }).then(inner => {
      inner.onDidDismiss().then(x => {
        if (x?.data?.target) ....
      })
      inner.present()
    })
  })
  outer.present()
})
```

**Comment by liamdebeasi** [comment]
Thanks for the additional information. Could you please describe how the mutable state causes issues in your application? This approach is what `ion-select` does internally: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/select/select.tsx#L241-L243

**Comment by godenji** [comment]
> Could you please describe how the mutable state causes issues in your application?

Where doesn't mutable state cause issues? :)

Joking aside, when setting a single value, mutable state isn't difficult to maintain/keep track of, but when you're dealing with multiple conditions that affect instance level state, then switching to an immutable approach makes sense.

Imagine you have a class property `state` of some object type which is built up based on various conditions. There is nothing preventing another developer from setting the state to whatever they deem convenient ("oh, what hassle all this is, I need the state to be `{x: ..., y: ..., z: ....}` here"), and doing that anywhere in the ActionSheet event chain.

With the immutable approach there is no global state that can be modified, just local state along the chain of events (which can of course be modified in place, but at least its local to the given scope).

**Comment by liamdebeasi** [comment]
Thanks, that makes sense. The current approach seems to work for `ion-select` since that only deals with setting a single value like a string or a number. Building up an object over time certainly gets tricky and is error prone with the current approach.

I think adding a `data` property to `ActionSheetButton` makes sense. I am going to add the `help wanted` label as I think this would be a good issue for someone looking to contribute to Ionic Framework. In terms of what is needed to implement this:

1. Add the `data` property to `ActionSheetButton`: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/action-sheet/action-sheet-interface.ts#L19
2. Update the `this.dismiss` call in `buttonClick` to pass in `button.data` instead of `undefined`: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/action-sheet/action-sheet.tsx#L161-L164 There should be no breaking change here since `button.data` itself would be `undefined` is not set by the user.
3. Update the interfaces in `readme.md`: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/action-sheet/readme.md#actionsheetbutton (these are not automatically generated)
4. Add tests in the `test` directory. 
5. Update the usage examples in `usage` to show how to extract the data from the button in `onDidDismiss`:

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23744, and this feature will be available in an upcoming release of the Ionic Framework v6 beta.
