### ISSUE TITLE
bug: Swipe issue in iframe on Ionic

### ISSUE THREAD

**Issue by Algoritm211** [ionic-team/ionic-framework#23721]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

I use YouTube iframe in Ionic app and I have card carousel of videos in my app. The problem is that the user has to swipe across the cards, but the user cannot swipe on the iframe to switch to other cards - swiping on the iframe does not work.

### Expected Behavior

Swipe works on an iframe and the user can switch cards in the carousel using a swipe.

### Steps to Reproduce

Now my code looks like this:

```javascript
const VideoSegmentComponent: React.FC<PropsType> = React.memo(({ videos }) => {
  const [isLoading, setIsLoading] = useState<boolean>(true)
  const slideOpts = {
    slidesPerView: 1.05,
    spaceBetween: 16,
    speed: 400
  }
  const videosMap = videos?.slice().reverse().map((item, index) => {
    const { query } = queryString.parseUrl(item.url)
    return (
      <IonSlide key={item.title + item.url} style={
        {
          background: 'white',
          margin: `${index === 0 ? '0 0 0 16px' : '0'}`,
          boxShadow: '0 6px 8px rgb(0 0 0 / 10%)',
          borderRadius: '8px',
          position: 'relative',
          zIndex: '500',
          display: 'flex',
          flexDirection: 'column',
        }
      }>
        <iframe style={{
          width: '100%',
          height: '192px',
          borderRadius: '4px 4px 0px 0px',
          border: 'none',
        }}
                src={`https://www.youtube.com/embed/${query.v}`}
                title='YouTube video player'
                frameBorder='0'
                onLoad={() => {
                  setIsLoading(false)
                }
                }
                allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture'
                allowFullScreen />
        <Skeleton isLoading={isLoading}>
          <IonSkeletonText animated style={{ height: '192px', borderRadius: '4px 4px 0px 0px', border: 'none' }} />
        </Skeleton>
        <h3 style={{ textAlign: 'start', margin: '16px', fontSize: '17px' }} dangerouslySetInnerHTML={{
          __html: item ? (item.title as string) : ''
        }} />
      </IonSlide>
    )
  })
  return (
    <IonSlides options={slideOpts} style={{
      margin: '50px 0px',
      padding: '0 32px 0 0',
      minHeight: '85vh'
    }}>
      {videosMap}
    </IonSlides>
  )
})
```

### Ionic Info

Ionic:

   Ionic CLI       : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.10

Capacitor:

   Capacitor CLI      : 3.0.2
   @capacitor/android : 3.0.0
   @capacitor/core    : 3.0.2
   @capacitor/ios     : 3.0.2

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v16.5.0 (/usr/local/Cellar/node/16.5.0/bin/node)
   npm    : 7.19.1
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment]
Thanks for the issue. With the upcoming release of Ionic Framework v6 we will be deprecating `IonSlides` and `IonSlide` component. As a result, we have a freeze on new feature development and bug fixes for these components (with the exception of critical security fixes).

We recommend using Swiper.js directly, which is the technology that powers `IonSlides`. The good news is that since the underlying technology is the same, the migration should be easy. Please see our migration guide for more information: https://beta.ionicframework.com/docs/api/slides#migration.

Given this is an issue with swiping inside of an iframe it is more likely that this is a bug in Swiper.js than it is a bug in `IonSlides`. Migrating to using Swiper.js and updating it to the latest version might fix the issue for you. If it does not, I recommend creating an issue on the [Swiper GitHub Repo](https://github.com/nolimits4web/swiper). Thanks!
