### ISSUE TITLE
feat: autocomplete component

### ISSUE THREAD

**Issue by snimavat** [ionic-team/ionic-framework#23799]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

It would be great to have an autocomplete / autosuggest input/select component, which lets user pick already existing value and has option to allow user to enter new values which does not already exist.

Most of components libs eg Vuetify / Element plus comes with similar components.

### Describe the Use Case

Eg. Tags drop down, that allows user to select existing tag, or enter new tag.

### Describe Preferred Solution
- Autocomplete with existing options
- Async capability (Load from server)
- Custom rendering of options
- Option to allow user to enter new values if not already exist (Should be possible to enable/disable this)
- Allow single / multiple values

### Describe Alternatives
- None, need to manually implement

**Comment by liamdebeasi** [comment]
Hi everyone,

We recently released a playground that shows how to implement this pattern in an Ionic application: https://ionicframework.com/docs/api/select#typeahead-component

This mobile-optimized typeahead component makes use of existing Ionic components which is why we opted to create a playground instead of creating a dedicated component. I am going to close this, but let me know if there are any questions.
