### ISSUE TITLE
bug: deprecating ion-virtual-scroll means no easy way to use this feature in pure web components or Stencil.js

### ISSUE THREAD

**Issue by adrm** [ionic-team/ionic-framework#23945]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

We are getting deprecation warnings for ion-virtual-scroll in our Stencil.js + ionic app. Reading the docs, it seems that your plan is to remove ion-virtual-scroll in favor of framework-specific solution. This means that this feature won't be as easily available for users using ionic outside the three major frameworks. I am especially concerned about the Stencil.js case, because we use it as framework for our app and because this was a surprise for me since Stencil.js is also a product you support.

### Expected Behavior

There should be a path forward to allow users of ionic without the three main frameworks to keep using virtual scroll. Otherwise, this will be pretty breaking for any users not on Angular, React or Vue.

### Steps to Reproduce

1. Try to find a non-deprecated way to use virtual scroll from ionic framework without depending on the three major frameworks.
2. Realize there is not.

**Comment by liamdebeasi** [comment]
Thanks for the issue! We definitely hear you on the frustrations around vanilla JS apps not currently having a good virtual scrolling solution.

With Ionic v6 we want to focus on delivering high quality app experiences. Part of this is realizing that we cannot perfectly serve every single use case. Supporting Stencil as a framework and virtual scroll in vanilla JS are two of those use cases.

For the Stencil part, the docs state that [Stencil is not a framework](https://stenciljs.com/docs/faq#is-stencil-a-framework) and so unfortunately this is not a use case we are looking to support at the moment.

For the vanilla JS virtual scroll component, I think it is important to look at _why_ there is no good vanilla JS solution currently. The biggest point here is that it is incredibly challenging to build a virtual scroll component that works for a single JS framework, let alone every single use case, across any framework or environment. This can be seen with the `ion-virtual-scroll` component itself. While it worked for some use cases, there are dozens of issues open that were sometimes in conflict with one another. In other words, we realized it was impossible for us to deliver a high quality virtual scrolling experience for every use case.

I can understand the disappointment around this deprecation but there are a few options for moving forward:

1. There is a new `content-visibility` CSS property that enables the user agent to skip an element's rendering work until it is needed. Support for this has landed in Chrome and seems like a promising way of ensuring only the content that is visible is rendered: https://web.dev/content-visibility/
2. You could fork `ion-virtual-scroll` in your project to keep using it. Since `ion-virtual-scroll` itself is a Stencil component, it should be a matter of copy and pasting the component and associated utilities into a directory in your project. Please note the existing issues for `ion-virtual-scroll` as they would be present in this copied code.
3. You could implement your own virtual scroll (not recommended). There are some tutorials out there that walk you through the steps on how to approach building this: https://dev.to/adamklein/build-your-own-virtual-scroll-part-i-11ib

I am going to close this as there is nothing actionable on the Ionic side. We appreciate you taking the time to provide us with your feedback. Thank you!

**Comment by adrm** [comment]
That new FAQ was a tough pill to swallow but I understand that it is a logic path for the project. We will plan accordingly.

Anyway, thanks a lot for your thoughtful response and for clearing out any doubts. I understand the difficulty of implementing virtual scroll, and that is where my worries came from. We will not be implementing it ourselves, so we will ponder the alternatives.
