### ISSUE TITLE
feat: Expandable transitions 

### ISSUE THREAD

**Issue by roman-rr** [ionic-team/ionic-framework#23947]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

It would be nice to have such transition styles for routes and modals. 

### Describe Preferred Solution

<details>
  <summary>Apple Store</summary>
 <img src="https://user-images.githubusercontent.com/10646478/133805589-94528f26-6fd0-4829-b396-9e7faa377af2.gif">
</details>
<details>
  <summary>Instagram</summary>
 <img src="https://user-images.githubusercontent.com/10646478/133807154-6e6bcfc2-d437-4608-92c4-441db613203a.gif">
</details>

### Related Code

Example from framework7 with js 
https://f7appstore.netlify.app/

**Comment by liamdebeasi** [comment]
Thanks for the issue. We had a feature request like this previously, and we decided that this was better served as a code example in the docs since there is no "one size fits all" approach to this behavior. We have an open issue on our docs here: https://github.com/ionic-team/ionic-docs/issues/1514

I am going to close this in favor of https://github.com/ionic-team/ionic-docs/issues/1514.
