### ISSUE TITLE
feat: Provide a mechanism for putting resource-id attributes on elements

### ISSUE THREAD

**Issue by jyeary** [ionic-team/ionic-framework#23975]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Android allows for adding `resource-id` attributes to HTML elements to allow create unique  IDs for the element. This is supported by providing an XML file that has the resource IDs defined and for annotating the element with that particular tag to create it.

### Describe the Use Case

Automated UI testing tools use unique iDs to locate HTML elements. Android allows this to be handled through the use of `resource-id` attributes attached to the elements.

### Describe Preferred Solution

I see a couple of potential solutions: 
* Read the `res/values/filename.xml`  and allow for integrating the `android:id="@id/XXXX` into to the ionic components to generate `resource-id` attributes.
* Support `android:id=@+id/XXX` to generate a new ID resource with the name XXX. The `@+id` tells Android to create the ID. 
* Create a passthrough mechanism to add additional attributes to the ionic components. 

### Describe Alternatives

There is currently no known mechanism to add the `resource-id` to components from ionic. In Appium, we have had to look for specific text values and use selectors to attempt to get other nodes in the tree.

### Related Code

The code would look something similar to this:

`<ion-input andoid-id="@+id/emailAddress" ></ion-input>`

### Additional Information

Please see https://developer.android.com/guide/topics/resources/more-resources#Id

**Comment by mlynch** [comment]
Hey @jyeary, I assume you're using Appium with something like WebDriverIO?

If so, you shouldn't need any special system for adding resource ids to Ionic elements, because Ionic elements live in the Web View context. Instead, you switch to the Web View context and select them with DOM queries. For example, you can add `id="email-address"` and then select it using WebDriverIO queries.

Here's an example of an E2E test using Appium and WebDriverIO in an Ionic app: https://github.com/ionic-team/capacitor-testapp/pull/232/files#diff-2f276f4093ce2166c97d5a80f4fa1328876b705c9bf654f1f012142564cdfe53R36

Does this make sense? Also if you'd like to talk more about E2E testing in Ionic/Capacitor apps, we would love to dig in here. If so, feel free to email me at max@ionic.io and I'll connect you with the right people on our end!
