### ISSUE TITLE
feat: allow ion-ripple-effect to be automatically added in ios mode

### ISSUE THREAD

**Issue by mevans** [ionic-team/ionic-framework#23990]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Configuration option to automatically include the `ion-ripple-effect` element in iOS mode, like how it's done for md mode.

### Describe the Use Case

I'm working on an app where we have the mode forced to iOS for styling reasons. We're looking to add ripple effects to the clickable elements, but as our mode is set to ios, the `ion-ripple-effect` element isn't automatically added. This means we have to manually add this element to all our buttons etc

### Describe Preferred Solution

Configuration field

### Describe Alternatives

Manually adding the ion-ripple-effect to every possible ripple element

**Comment by HyperLife1119** [comment]
I used directive to achieve this feature.
https://github.com/HyperLife1119/OnChat-Web/blob/master/src/app/directives/ripple/ripple.directive.ts

**Comment by liamdebeasi** [comment]
Thanks for the issue! I discussed this feature with the team, and we do not feel this feature is a good fit for Ionic.

The purpose of Ionic is to provide components the look and feel like their native iOS and Android counterparts. As a part of that, we intentionally created the ripple effect to only run in Material Design (MD) mode as the ripple effect does not appear in the iOS Interface Guidelines. We feel that modifying the iOS mode theme to add ripple effects would go against these guidelines and break the native look and feel.

I am going to close this issue, but we came up with a couple alternatives that you could consider:

1. Wrap your interactive components in Angular components so that they automatically render and configure the ripple effect. This is similar to your ripple effect directive, but you would use the custom components instead of adding directives to each Ionic component.
2. Use `mode="md"` to force buttons and items to run in Material Design mode to add the ripple effect, but then customize the styling to make them look closer to the iOS designs. You may need to play with the styles a bit, but this might be a more performant option as you can avoid custom components or directives and only worry about the CSS.

Thank you!
