### ISSUE TITLE
bug: ion-nav does not work in react

### ISSUE THREAD

**Issue by smorris1709** [ionic-team/ionic-framework#24002]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

There isn't rich documentation available on how to use ion-nav
Using IonNav to implement nested routing inside an IonModal in React gives framework delegate is missing error

### Expected Behavior

nested routing should work.

### Steps to Reproduce

https://codesandbox.io/s/confident-waterfall-ctdnr?file=/src/pages/Home.tsx

Click  the button to open modal then click next to go to the next page.

### Code Reproduction URL

https://codesandbox.io/s/confident-waterfall-ctdnr?file=/src/pages/Home.tsx

**Comment by milang** [comment]
@liamdebeasi @sean-perkins any progress on this issue?

Our use-case is exactly what the documentation describes:

> https://ionicframework.com/docs/api/nav
> Unlike Router Outlet, Nav is not tied to a particular router. This means that if we load a Nav component, and push other components to the stack, they will not affect the app's overall router. **This fits use cases where you could have a modal, which needs its own sub-navigation, without making it tied to the apps URL.**

I created a code reproduction repository that uses the latest Ionic (6.1.1) and React (18), showing that the issue is still present (please use branch `test-ionnav`):
https://github.com/milang/ionic-simplevitejs/tree/test-ionnav

```sh
git clone https://github.com/milang/ionic-simplevitejs.git
cd ionic-simplevitejs
git checkout test-ionnav # <= switch branch
yarn && yarn dev
```

I tried using `push` method ([lines 63-67 in `src/App.tsx` uncommented](https://github.com/milang/ionic-simplevitejs/blob/test-ionnav/src/App.tsx#L63-L67)) => unsuccessful

<img width="680" alt="IonNav.Push" src="https://user-images.githubusercontent.com/42297/164147140-8dff87fe-5c63-40a9-afb3-783ceff3d3b3.png">

I also tried using `root` property on `IonNav` component ([lines 56-62 in `src/App.tsx` uncommented](https://github.com/milang/ionic-simplevitejs/blob/test-ionnav/src/App.tsx#L56-L62)) => unsuccessful

<img width="680" alt="IonNav.Root" src="https://user-images.githubusercontent.com/42297/164147442-14fc889c-8c39-4646-bda0-1d480119f0aa.png">

---

Is there a workaround that allows forward and backward animations to be used in modal dialogs when using React? Based on the following article I assume `ion-nav` works in Angular, but I would appreciate guidance for React as well:
https://ionicframework.com/blog/how-to-navigate-in-ionic-modals-with-ion-nav/

Related issue in `ionic-docs` repository links to a _solution_, but when playing around with it I did not find it very reliable (and the code is quite hacky):
https://github.com/ionic-team/ionic-docs/issues/1345#issuecomment-1031082691

Is there a better way?

**Comment by milang** [comment]
@liamdebeasi @sean-perkins any progress on this issue?

**Comment by sean-perkins** [comment]
@milang no need to ping us multiple times on the status of an issue. If an issue is open, it still is an active problem. If an issue has an attached PR, it is in progress. If an issue is closed with an attached commit, it is resolved and available in the next release (or nightly build). 

This issue is still open and an active problem.

**Comment by sean-perkins** [comment]
The dev-build is available here to test: `6.1.12-dev.11656705976.18fe5a46`

If you need an example of `IonNav` with React, you can look at the test app example: https://github.com/ionic-team/ionic-framework/blob/b2a27e0b623a603b536dc23ab409662219323acb/packages/react/test-app/src/pages/navigation/NavComponent.tsx

**Comment by milang** [comment]
@sean-perkins @liamdebeasi thank you for the update. I switched to the dev-build above and used `<IonNav>` with a trivial `<HelloWorld>` component:
https://github.com/milang/ionic-simplevitejs/blob/simple-ionnav/src/App.tsx#L33

However, I observed two issues:
1. `rootParams` value is ignored, `root` component is always rendered with `undefined` props
2. When `<HelloWorld>` is included via `<IonNav>` and I edit anything in `<HelloWorld>`, hot-reloaded page becomes blank. However, if I comment line 33 and uncomment line 34 (including `<HelloWorld>` directly, not via `<IonNav>`), hot-reloading works flawlessly.

To test the sample:
```sh
git clone https://github.com/milang/ionic-simplevitejs.git
cd ionic-simplevitejs
git checkout simple-ionnav # <= switch branch
yarn && yarn dev
```

**Comment by sean-perkins** [comment]
@milang thanks for the follow-up. I am going to split out your first mentioned problem into a new issue to track.

The second issue sounds like a duplicate of: #25507, navigation elements that use a stack of views clear incorrectly starting in React 18. React 18 unmounts and remounts components when running in dev mode to prepare for a future change in React for resuming state.

**Comment by sean-perkins** [comment]
New issue is available here: https://github.com/ionic-team/ionic-framework/issues/25602

**Comment by milang** [comment]
@sean-perkins I updated the sample again, removing `rootParams` as per your new warning and using memoized component instead (which is a bit more annoying, but it works).

However, even after I downgraded React to v17, the blank-screen-after-hot-reload issue persists => see branch `simple-ionnav-react17` in the same repository, https://github.com/milang/ionic-simplevitejs.

**Comment by sean-perkins** [comment]
@milang I'm open to feedback with the `rootParams`. One drawback I found with using `rootParams` is that the type signature does not inherit from the JSX component. Whereas the memorized approach directly taps into the props/type signature defined. 

Here is an updated build to play with the hot reload behavior: `6.1.14-dev.11657592563.15d82c05`. It appears to no longer clear the page, but may be "off by one" from the last save of the hot reload.

**Comment by sean-perkins** [comment]
@milang the opinionation to use memorized components is no longer required. You can select the implementation pattern that best meets your needs (memorized components or `rootParams`). 

Here is an updated dev-build: `6.1.15-dev.11657908598.17be2d80`

**Comment by milang** [comment]
@sean-perkins thank you very much for your updates! `IonNav` now works for me in both `rootParams` mode and in memoized component mode. I agree with you that from type-checking perspective the memoized approach is better than `rootParams`. Great point.

I noticed that with `6.1.15-dev.11657908598.17be2d80` the `rootParams` approach has the "off by one" behaviour you mentioned when hot-reloading changes (https://github.com/milang/ionic-simplevitejs @ `simple-ionnav` branch), while memoized approach works as expected (no cleared page, no off-by-one) in both React 17 (https://github.com/milang/ionic-simplevitejs @ `simple-ionnav-react17` branch) and React 18 (`simple-ionnav-react17~1`).

**Comment by milang** [comment]
@sean-perkins when I started using `IonNav`'s `push` and `pop` methods, there seems to be a problem with transition animations in `6.1.15-dev.11657908598.17be2d80`.

The prototype with Ionic `6.1.15-dev.11657908598.17be2d80` is available in my standard repo, https://github.com/milang/ionic-simplevitejs, branch `recursivemodalnav`. The "recursive modal dialog" is implemented here: https://github.com/milang/ionic-simplevitejs/blob/recursivemodalnav/src/App.tsx#L34-L56.

This is what it looks like in current version of Edge browser (stable channel)

![IonNav_Ionic6-1-15-dev-11657908598-17be2d80](https://user-images.githubusercontent.com/42297/179369020-31c04f39-627a-4e82-a467-9881dc915cb3.gif)

Now compare this with exactly the same code, but running against Ionic `6.1.14` (the latest stable release). This prototype is available in branch `recursivemodalnav-ionic6114`, and only differs from the previous branch in one commit, https://github.com/milang/ionic-simplevitejs/commit/afa528509c4e0cb7ea649cc14c023a7c65ff71db, that changes `package.json` and the lockfile. As you can see, in current Ionic the animations are perfect (iOS mode).

![IonNav_Ionic6-1-14](https://user-images.githubusercontent.com/42297/179369014-5da3e0e3-67dd-458a-90a9-4e2c25357f24.gif)

**Comment by sean-perkins** [comment]
@milang thanks for the follow-up! I believe the transition behavior is resolved by the combination of my two open PRs:
- https://github.com/ionic-team/ionic-framework/pull/25638
- https://github.com/ionic-team/ionic-framework/pull/25603

I created a dev-build with both PRs combined: `6.1.15-dev.11658162113.1784b217` and it appears to resolve the issue with  transitions in your reproduction.

**Comment by milang** [comment]
@sean-perkins the transitions in development build `6.1.15-dev.11658162113.1784b217` work great for me, thank you.

One last observation: while the hot reload works as expected in this development build (no blank screen, no off-by-one immediately visible issue), I noticed that hot reloading seems to get `<IonNav>` component into a strange mode. I captured this in the following screencast:

1. At 0:11 I changed title of the modal dialog, and it got correctly updated (at this point there were supposed to be 3 views in the stack: level 1 (root), level 2, and level 3); however when I tried to pop back to previous view, an exception was thrown (0:16). It seems that `<IonNav>` internally resets the stack to the root view (i.e. we cannot "pop" because there is nothing to pop), but the view remains at whatever position it was before the update.
2. At 0:22 I changed title of the modal dialog again (without reloading the page). This time the view updated not just the title prefix, but also reset level to 1 (this seems to better reflect the internal state change). However, while at this point pushing views works as expected, popping them always resets back to level 1 (root view) instead of the previous view (at 0:28 and again at 0:34).

[IonNav.webm](https://user-images.githubusercontent.com/42297/179622319-d97a5472-f74b-4ac8-9bad-b999340476d8.webm)

**Comment by milang** [comment]
@sean-perkins I tried upgrading the `IonNav` prototype to the latest [Ionic 6.2.0 release](https://github.com/ionic-team/ionic-framework/releases/tag/v6.2.0), but the transition animations seem to be broken in iOS mode, and not applied at all in Android mode. The behaviour is identical in both React 17 and 18.

(Prototype available in https://github.com/milang/ionic-simplevitejs, branches `recursivemodalnav` and `recursivemodalnav-react17`)

[IonNav.webm](https://user-images.githubusercontent.com/42297/181355501-9a4001b5-29d2-4afd-b1f4-dfb111aa2389.webm)

**Comment by sean-perkins** [comment]
@milang thanks for the heads up, will take a look now 👍

**Comment by sean-perkins** [comment]
@milang I've been able to diagnose the problem to 6.1.15 with our change to support custom sized dialogs. These styles are problematic: 

```css
ion-modal .ion-page {
  position: relative;

  contain: layout style;

  height: 100%;
}
```

I'm going to split out our conversation into a new issue to track this fix.
