### ISSUE TITLE
bug: v6, describe how to account for es modules in project

### ISSUE THREAD

**Issue by dashreel** [ionic-team/ionic-framework#24026]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When using next-build with ionic/core 

I get this error with beta 6 version 6 or greater

```export { setAssetPath, setPlatformOptions } from '@stencil/core/internal/client';
^^^^^^

SyntaxError: Unexpected token 'export'
```

### Expected Behavior

Would build like it does with beta 6 version 5

### Steps to Reproduce

run next build with ionic beta 6 version 6 or great with ionic/core

**Comment by Polarisation** [comment]
Thank you, transpiring the Ionic/Stencil modules looks like a promising and reasonable solution, once the Stencil bug is fixed.

**Comment by liamdebeasi** [comment]
Hi everyone,

A couple updates here:

1. We have a branch open that will update Ionic Vue and Ionic React starters to automatically compile ES Modules down to CommonJS (CJS) so that Jest tests will work.
2. We have written a migration guide for developers going to Ionic 6 using React or Vue. I have provided it below for those looking to make the migration now, but it will also be part of a full migration guide when Ionic 6 ships.

I am going to close this issue out as the main work required to get this issue resolved has been completed. Keep an eye out for the full migration guide as it will detail other breaking changes in Ionic 6. Thanks!

-----

## Jest Migration

Ionic 6 now ships as ES Modules. ES Modules are supported in all major browsers and bring developer experience and code maintenance improvements. Developers testing with Jest will need to update their Jest configuration as Jest does not have full support for ES Modules as of Jest 27.

This update involves using Babel to compile Ionic's ES Modules down to the CommonJS (CJS) format, a format that Jest can understand. Once Jest ships support for ES Modules, this change will no longer be necessary. See https://github.com/facebook/jest/issues/9430 for updates on ES Modules support in Jest.

If you are starting fresh with a new Ionic app, this configuration is done for you in our starter applications. For those with existing Ionic apps, follow the steps below to get Jest working with Ionic 6.

### Ionic Vue

1. In your Jest config (either in `jest.config.js` or the `"jest"` field in your `package.json`), add the following `transformIgnorePatterns`:

```
modules.exports = {
  ...,
  transformIgnorePatterns: ['/node_modules/(?!@ionic/vue|@ionic/vue-router|@ionic/core|@stencil/core|ionicons)']
}
```

### Ionic React

For developers using Create React App (CRA), there is currently no way to update the `transformIgnorePatterns` in a Jest config file. This is a CRA restriction and not something Ionic has control over. We can, however, pass the `transformIgnorePatterns` directly into the `react-scripts test` command.

1. In your `package.json`, update the "test" field in the "scripts" object:

```
"scripts": {
  "test": "react-scripts test --transformIgnorePatterns 'node_modules/(?!(@ionic/react|@ionic/react-router|@ionic/core|@stencil/core|ionicons)/)'",
  ...
}
```
