### ISSUE TITLE
feat: add alignment property to `counter` directive on IonItem

### ISSUE THREAD

**Issue by not-a-designer** [ionic-team/ionic-framework#24084]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

add an optional string value to the `counter` directive to allow control over positioning within the IonItem, such as 'start', 'end', and 'center'. With no value it could default to 'start' as it currently functions

### Describe the Use Case

MD docs shows the input `counter` as aligning to the right/end which is not possible yet, unless an IonNote in the `helper` or `error` slot is present

### Describe Preferred Solution

counter as a string instead of a boolean, defaulting to 'start' if undefined

```
<ion-item [counter]="'start'|'center'|'end'"><ion-item>
```

### Describe Alternatives

::part(item-bottom) for shadow DOM
[ ionic-framework/item.tsx at e3996cfbd50f5e9ae54ffcbe2594124e3b9969b0](https://github.com/ionic-team/ionic-framework/blob/e3996cfbd50f5e9ae54ffcbe2594124e3b9969b0/core/src/components/item/item.tsx#L368)

OR

css variables for counter:
```
--counter-color
--counter-float //?
--counter-font-size
```

**Comment by sean-perkins** [comment]
There is a draft PR in the works (#24335) that will solve a few challenges discussed in this feature request.

The counter will consistently display right aligned with appropriate spacing between the slotted helper/error contents (if present). The counter will also be exposed with a CSS shadow part `counter`.

**Comment by sean-perkins** [comment]
Update on my end, we ended up splitting the scope of the PR to address the bug and moved this feature proposal into our internal review process.

**Comment by liamdebeasi** [comment]
Hi everyone,

In Ionic 7 we are introducing a new syntax for working with `ion-input`. As part of this, we will be moving the counter/helper/error functionality onto `ion-input`. Since this component does not use the Shadow DOM, there should be no additional APIs needed for developers to access these elements using CSS directly.

We will have an Ionic 7 beta in the future where developers can test and provide feedback. There will also be a migration guide to show how to update to the new input syntax.

The work required to resolve this has been completed, so I am going to close this thread. Let me know if there are any questions.
