### ISSUE TITLE
bug: Open sms app with longer text, Ionic toolbar disappears. cordova-sms-plugin

### ISSUE THREAD

**Issue by umairrafiq1133** [ionic-team/ionic-framework#24135]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [x] v5.x
- [X] v6.x

### Current Behavior

I am using this cordova-sms-plugin to send sms from my app. When I send a text which is shorter, everything works as expected but when text is longer and sms app opens, coming back to app will hide the toolbar irrespective of whether I sent the sms or not. When inspected in Safari, I can see the toolbar if I add padding-top from `ion-safe-area-top` to `162px`.

### Expected Behavior

Toolbar shoudlnt disappear. As per my understanding, size of webview is being changed on opening sms app with longer text.

### Steps to Reproduce

install cordova-sms-plugin
open sms app by using a longer text message to send.
come back to app

### Ionic Info

Ionic:
   Ionic CLI                     : 6.14.1 (/Users/dijitalbrains/.nvm/versions/node/v12.16.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.6
   @angular-devkit/build-angular : 0.1002.3
   @angular-devkit/schematics    : 10.2.3
   @angular/cli                  : 10.2.3
   @ionic/angular-toolkit        : 3.1.1

Capacitor:
   Capacitor CLI   : 3.2.5
   @capacitor/core : 3.2.5

Utility:
   cordova-res (update available: 0.15.3) : 0.15.1
   native-run                             : 1.5.0

System:
   NodeJS : v12.16.1 (/Users/dijitalbrains/.nvm/versions/node/v12.16.1/bin/node)
   npm    : 6.13.4
   OS     : macOS Big Sur

**Comment by umairrafiq1133** [comment]
For now I have fixed using some css.

```
sms(phoneNumbers: string[], message: string) {
		return new Promise((resolve, reject) => {
			const options = {
				android: {
					intent: 'INTENT',
				},
			};

			document.body.style.height = '100%';
			document.body.style.marginTop = '0px';

			this.smsPlugin
				.send(phoneNumbers, this.parseMessage(message), options)
				.then(
					() => {
						resolve('success');
					},
					() => {
						reject('error');
					}
				)
				.finally(() => {
					setTimeout(() => {
						const bodyHeight = document.body.offsetHeight;
						const deviceHeight = window.screen.height;
						document.body.style.marginTop = bodyHeight - deviceHeight + 'px';
						document.body.style.height = deviceHeight + 'px';
					}, 200);
				});
		});
	}
```

**Comment by umairrafiq1133** [comment]
I have created a public repository and reproduced the issue.
Here's the link to repo.
https://github.com/umairrafiq1133/ionic-view-bug

**Comment by umairrafiq1133** [comment]
https://user-images.githubusercontent.com/18613802/139842953-1ffea157-0385-48b5-af0f-2c25f3dbc2af.mp4

**Comment by umairrafiq1133** [comment]
@liamdebeasi any update?

**Comment by liamdebeasi** [comment]
Hi there,

You do not need to ping me for updates. We will take a look at your reproduction when we have a chance. Thanks!

**Comment by sean-perkins** [comment]
Hello @umairrafiq1133 thanks for reporting this issue and providing a screen recording 👍 

Can you additionally provide what iOS version and device you are using to verify? For reference, I am on iOS 14.8.1 with an iPhone XS Max and the toolbar remains in the proper location after following your replication steps.

Thank you!

https://user-images.githubusercontent.com/13732623/140947066-ad8cbde9-ef04-43ce-8235-4305d4f27489.mp4

**Comment by umairrafiq1133** [comment]
@sean-perkins ios version 15.1

**Comment by subhankhalid402** [comment]
I have same issue.

**Comment by sean-perkins** [comment]
@umairrafiq1133 thank you. I've been able to reproduce this issue on device with iOS 15.1.

I have replicated the issue using a capacitor plugin for SMS as well. You can close your open issue in the cordova plugin's repository, as it's not responsible for this problem.

I believe the issue is within `ion-content`, likely in the timing of how we calculate the offset values for top and bottom. An odd visual difference between iOS 14 vs. iOS 15 (or when using a short amount of text vs. long text), is that the backdrop is black when it's in a broken state and displays the modal sheet appearance when it's functional (can be seen between your video and mine).

This will require more research from our team to pinpoint the issue. I'll let you know when we have an update.

**Comment by sean-perkins** [comment]
@umairrafiq1133 @subhankhalid402 

I have found a resolution to the issue. It appears that both `MFMessageComposeViewController` and `MFMailComposeViewController` will cause the webview to resize between iOS 14 to 15.

You will need to install `@capacitor/keyboard` into your project(s) to resolve this issue.

```bash
npm i @capacitor/keyboard
```

Next, before you open the SMS plugin/keyboard, set the resize behavior to none.

```ts
import { Keyboard } from '@capacitor/keyboard';

...

async openSmsApp() {
  await Keyboard.setResizeMode({
    mode: KeyboardResize.None
  });
  ...
  await this.smsPlugin.send(phoneNumbers, message, options);

  await Keyboard.setResizeMode({
    // Change this value if you aren't using ion-app
    mode: KeyboardResize.Ionic
  });
```

Remember to sync your capacitor plugins after installing the dependency.

```bash
npx cap sync ios
```

<video src="https://user-images.githubusercontent.com/13732623/141926563-c22019c5-de78-49fd-8e9f-86b013b4e39d.mp4"></video>

Let me know if this resolves the issue on your end. I've checked locally with both the Cordova and Capacitor plugin, on iOS 15.1

**Comment by umairrafiq1133** [comment]
@sean-perkins If using ionic app, you dont need to do this?

```
await Keyboard.setResizeMode({
    // Change this value if you aren't using ion-app
    mode: KeyboardResize.Ionic
  });
```

**Comment by sean-perkins** [comment]
> @sean-perkins If using ionic app, you dont need to do this?
> 
> ```
> await Keyboard.setResizeMode({
>     // Change this value if you aren't using ion-app
>     mode: KeyboardResize.Ionic
>   });
> ```

@umairrafiq1133 if your application is making use of a keyboard internally, for example inputs, you will want to reset the resize mode on iOS back to its original state. The `@capacitor/keyboard` plugin has a special mode for Ionic applications that targets the `ion-app` element, and resizes that node instead of resizing the document body of the webview. I would advise starting with that resize mode for Ionic applications and then using another resize mode if edge cases apply.

If your application doesn't make use of the keyboard (outside of the SMS plugin), you can likely set the resize mode on application bootstrap once. For Angular applications, you can do this in the `ngOnInit` life cycle hook of the `AppComponent`.

**Comment by umairrafiq1133** [comment]
@sean-perkins Thanks. Issue is fixed for me.
