### ISSUE TITLE
bug: ionic@5.8.4 Influence “ionic": "driftyco/ionic-bower#1.3.5” style in Micro-Frontends project

### ISSUE THREAD

**Issue by XueMeijing** [ionic-team/ionic-framework#24180]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

i'm using micro-app which is a kind of Micro-Frontends to build a project, it contains two sub project, one is angular +     "ionic": "driftyco/ionic-bower#1.3.5", the other is react + "@ionic/react": "^5.8.4",  but it seems that once i import IonApp in react project, the angular project style changes and appeared shadow-root (open), can anyone give me some suggestions? here are two screenshots
![image](https://user-images.githubusercontent.com/35559153/140672489-0ce5281f-b4f4-4a25-a333-7cddaef8f133.png)
![image](https://user-images.githubusercontent.com/35559153/140672505-deedca77-a63b-4ac3-9e52-22ad289b4227.png)

### Expected Behavior

i wish angular style shows normal after i import IonApp in another react sub project

### Steps to Reproduce

the steps are in Current Behavior, sry for my poor English

**Comment by liamdebeasi** [comment]
Thanks for the issue. The issue here is you have two conflicting versions of Ionic: One using Ionic 1/2 and one using Ionic 5. Ionic 5 uses Web Components with the Shadow DOM and Ionic 1/2 does not. Loading Ionic 5 overrides the previous `<ion-content>` and you get the new `<ion-content>` that uses the Shadow DOM.

At the moment we only support using one version of Ionic in an app at a time. To resolve this, we recommend building with only Ionic 5.

**Comment by XueMeijing** [comment]
> At the moment we only support using one version of Ionic in an app at a time. To resolve this, we recommend building with only Ionic 5.

ok, i understand it now, thanks for your explain,  best wishes~
