### ISSUE TITLE
bug: datetime should not scroll to month is entire month is disabled

### ISSUE THREAD

**Issue by himanshusukhpal** [ionic-team/ionic-framework#24208]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Disabled months shouldn't get populated or be scrolled to

![image](https://user-images.githubusercontent.com/10000755/141270827-1b519f3b-94ad-4a6d-8b5e-32907a56ba17.png)

Even the official docs are showing this problem 

![image](https://user-images.githubusercontent.com/10000755/141271880-227ea80d-c3f2-4031-b0a7-a89f3b338d6d.png)

### Expected Behavior

The left or right arrow/swipe ability that if lead to a disabled month can be disabled for the current month

![image](https://user-images.githubusercontent.com/10000755/141271029-a21bee75-29a9-4bdf-8799-b33a2d06e4ec.png)

### Steps to Reproduce

Ion-Datetime calendar's default functionality

**Comment by Yura13** [comment]
@sean-perkins @liamdebeasi 
After this fix appears a new issue.
Previously I've set a date to 19 January and saved it.  In my app, I have logic that I can change the date only during the current month. I can't change the date from 19 January to 9 February because navigation to next month doesn't work but the next month button is enabled.
![image](https://user-images.githubusercontent.com/17030431/153172754-7d554637-5621-402e-a8bc-7ddf4772a15f.png)
