### ISSUE TITLE
bug: `ion-item` background appearance when using counter or helper/error slots

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/ionic-framework#24333]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

In v6 a new container was introduced into `ion-item` to contain the help/error text and counter display. This new container does not inherit the background appearance of the item. Without an exposed variable, developers are unable to theme this new container space and it will always render as the list/parent container's background appearance.

### Expected Behavior

`ion-input` should support a CSS property or CSS shadow part to style this new container.

### Steps to Reproduce

Use either the `counter` feature with `ion-item` or slot contents through `slot="error"` or `slot="helper"` when changing the background appearance of `ion-item`.

### Code Reproduction URL

https://codesandbox.io/s/romantic-tu-3nj1l?file=/src/app/app.component.html

**Comment by Spinnenzunge** [comment]
Would second a `part="bottom"` for the bottom container in `ion-item` as well

**Comment by liamdebeasi** [comment]
Hi everyone,

In Ionic 7 we are introducing a new syntax for working with `ion-input`. As part of this, we will be moving the counter/helper/error functionality onto `ion-input`. Since this component does not use the Shadow DOM, there should be no additional APIs needed for developers to access these elements using CSS directly.

We will have an Ionic 7 beta in the future where developers can test and provide feedback. There will also be a migration guide to show how to update to the new input syntax.

The work required to resolve this has been completed, so I am going to close this thread. Let me know if there are any questions.
