### ISSUE TITLE
bug: Ionic/core iOS Card Modal Blurry

### ISSUE THREAD

**Issue by omar2205** [ionic-team/ionic-framework#24351]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When using `ion-modal` element

```html
<ion-modal is-open="false" id="card-modal">
  <ion-content>Modal Content</ion-content>
</ion-modal>
```

The modal is very blurry
![image](https://user-images.githubusercontent.com/1373867/145333538-3c135dc6-fe75-4471-a714-d4df64b9616c.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/1373867/145333712-7994c94d-4f71-45af-8236-354fdccf66ab.png)

### Steps to Reproduce

<s>https://cdpn.io/omar2205/debug/wvrWeqK/DqrDdYyagZor</s>

https://codepen.io/omar2205/pen/wvrWeqK

**Comment by liamdebeasi** [comment]
Thanks for the issue. I cannot access your CodePen. Can you make a new one? In general, we recommend testing on a physical device as these simulated views do not always handle sub-pixel rendering perfectly.

**Comment by omar2205** [comment]
@liamdebeasi sorry I linked the debug view by accident, here it is:
https://codepen.io/omar2205/pen/wvrWeqK

**Comment by liamdebeasi** [comment]
Thanks. The problem here is you are targeting the wrong element for `presentingElement`. Both your page view and your `ion-modal` are children of `ion-app`, so by setting the `presentingElement` to `ion-app`, you are causing the new modal to get scaled as well. This is causing the blurry behavior described in the original post.

You should be targeting only the page view for `presentingElement`, not your entire application.

Here is an example of the correct usage: https://codepen.io/liamdebeasi/pen/JjrKzmm

Can you try this in your app and let me know if it fixes the issue?

**Comment by omar2205** [comment]
Yep, that fixed it. I tried presenting different elements with the same scaling problem.

I tried modifying my codepen but the same scaling issue
https://codepen.io/omar2205/pen/wvrWeqK

**Comment by omar2205** [comment]
To get it working, I had to add another class (to my .ion-page), is there a reason?

**Comment by liamdebeasi** [comment]
`ion-app` also received the `.ion-page` class when it is initialized, so your `querySelector` is likely picking that up first.

**Comment by omar2205** [comment]
Alright, thanks @liamdebeasi.
