### ISSUE TITLE
bug: primary toolbar inside header with collapse fade

### ISSUE THREAD

**Issue by natqe** [ionic-team/ionic-framework#24436]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

`IonToolbar` with color `primary` not showing inside of `IonHeader` defined with `collapse` of type `fade`

### Expected Behavior

`IonToolbar` should be showing inside of `IonHeader` no matter of his properties

### Steps to Reproduce

```jsx
import '@ionic/core/css/core.css'
import { IonApp, IonContent, IonHeader, IonToolbar, setupIonicReact } from '@ionic/react'
import { createRoot } from 'react-dom'

setupIonicReact()

createRoot(document.getElementById('root')).render(<IonApp>
  <IonHeader collapse="fade">
    <IonToolbar color="primary">my title</IonToolbar>
  </IonHeader>
  <IonContent>
    Hello World
  </IonContent>
</IonApp>)
```

**Comment by sean-perkins** [comment]
Hello Nathan, if you have time it'd be extremely helpful to have a live code reproduction to test with and verify against. Thanks!

**Comment by natqe** [comment]
@sean-perkins I'm able whenever u need me. 
Though i created a snippet that u can run on a react-ionic repo and see the results on the browser.
```jsx
import '@ionic/core/css/core.css'
import { IonApp, IonContent, IonHeader, IonToolbar, setupIonicReact } from '@ionic/react'
import { createRoot } from 'react-dom'

setupIonicReact()

createRoot(document.getElementById('root')).render(<IonApp>
  <IonHeader collapse="fade">
    <IonToolbar color="primary">my title</IonToolbar>
  </IonHeader>
  <IonContent>
    Hello World
  </IonContent>
</IonApp>)
```

**Comment by sean-perkins** [comment]
Following up, the `collapse="fade"` implementation of the `IonHeader` relies on using opacity to gradually fade the toolbar into the view once overflow scroll occurs. 

The implementation that we followed was from native iOS:

<video src="https://user-images.githubusercontent.com/13732623/148266471-feef6388-1f7e-4549-a48d-96578cc0cdfe.mp4"></video>

The toolbar isn't displayed until after you scroll the title off the view.

If you are wanting the toolbar to be initially visible, I would recommend not using `collapse="fade"`. 

Please let me know if this helps solve any confusion or if I am misinterpreting the bug.

**Comment by natqe** [comment]
@sean-perkins but its happens only when using it with `color="primary"` on the toolbar

**Comment by sean-perkins** [comment]
@natqe could you help describe what the expected behavior would look like with `color="primary"`?

Currently the effect for the fade will transition the toolbar opacity from 0 to 1. When no color is supplied, the foreground color is black on a white background. This causes the toolbar text to appear visible.

For `color="primary"` the text is initially white and the page container is also white. This causes the bar to appear not visible, while it is technically in the view. 

Having the text color initially blue and transitioning to white would require a lot more complexity to the current effect and wouldn't be in alignment with the iOS appearance. It could also potentially cause display issues where during the transition the toolbar text would not be legible to certain users.
