### ISSUE TITLE
bug: unable to control IonMenu programmatically using MenuController

### ISSUE THREAD

**Issue by nika1001** [ionic-team/ionic-framework#24497]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When I try to programmatically toggle ion-menu using `await menuController.toggle(menuId)`, menu does not open.

### Expected Behavior

In previous versions of Ionic (5.9.3) calling toggle on menuController opened the menu correctly - see my other branch https://github.com/nika1001/ionic6-menu-controller-issue/tree/ionic5-working-menu
I would like to have the same behavior also in Ionic6. 

### Steps to Reproduce

1. Start an application provided in the github: https://github.com/nika1001/ionic6-menu-controller-issue
2. Pressing buttons under "Toggle menu by MenuController" header does nothing

### Code Reproduction URL

https://github.com/nika1001/ionic6-menu-controller-issue

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (C:\Tools\nvm\v16.10.0\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 6.0.1

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.10.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.0.0
   OS     : Windows 10

### Additional Information

Reason for using menuController is that I need multiple menus on the same side and in order to do that I had to first enable a menu to be toggled: 
```
const toggleMenu = async (menuId: string) => {
  await menuController.enable(true, menuId)
  await menuController.toggle(menuId)
}
```
Inspired by: https://forum.ionicframework.com/t/allow-multiple-menus/189934/4

If I don't enable the menu, I can toggle only 1 of the menus assigned to "start" side. This is demonstrated by buttons under "Toggle menu directly" header in my demo application: https://github.com/nika1001/ionic6-menu-controller-issue

**Comment by sean-perkins** [comment]
Thanks for reporting this! While the behavior of only having one enabled menu at a time is a known limitation to how we currently approach multiple menus, the behavior for toggling the enabled state and displaying the menu does appear to have regressed from v5 to v6.

We'll track this bug and share an update when we are able. Thanks!

**Comment by ruiminxu** [comment]
Hey, I’m also having the same problem but with await menuController.close(). Is there a fix for the problem?

**Comment by nika1001** [comment]
@sean-perkins could you please provide us with some estimate about when the fix could be available? We would like to make a transition from v5 to v6 but this is a blocker for us.

**Comment by alejandroledesma** [comment]
@sean-perkins I'm in same situation that @nika1001. This issue is a blocker for us to transition v6.

**Comment by Cyral** [comment]
Also blocked on v6 upgrade due to this

**Comment by sean-perkins** [comment]
Hello all, at this time we do not have an update to share with the status of this bug. I understand the importance this bug may have to your application and would gladly welcome any further diagnosis or debugging that can help narrow the scope of the issue.

For example, if anyone could help narrow which version of Ionic regressed this behavior, that would help significantly in my ability to provide a resolution. If the issue is present in the official 6.0.0 release, stepping through the beta releases would be my recommendation. 

In the interim, I'll discuss this issue with the team and the blocker it causes for v6 migrations. 

Thanks all!

**Comment by Cyral** [comment]
@sean-perkins 

I did some testing today using @nika1001's sample repo and it appears the issue was introduced in 6.0.0.beta-6. beta-5 works as expected.

Note that I got some cryptic errors on most beta versions that required installing @stencil/core@2.9.0 as a workaround, described [here](https://github.com/ionic-team/ionic-framework/issues/24153#issuecomment-958052376).

**Comment by mlegenhausen** [comment]
The problem is that there are two `menuController`s one you import via `@react/core` and one which is used internally by (for me) the `@ionic/react` components. It seems that the bundling of ionic is currently broken. You can see this when you use the webpack bundle analyzer where you will see that ionic is included twice in your application. Once via `@ionic/core/dist/esm-es5` and via `@ionic/core/components` where the later is used by `@ionic/react`. When you import the `menuController` from `@ionic/core` you import it from `@ionic/core/dist/esm-es5/index-f4d45e1e.js` and the `@ionic/react` `IonMenu` component imports it from `@ionic/core/components/index5.js` which results in completely isolated instances of the `menuController`.

I use `@ionic/core@6.0.9` and `@ionic/react@6.0.9`.

**Comment by mlegenhausen** [comment]
I found a solution to the problem. By using `@ionic/core/components` instead of `@ionic/core` you use the same imports that `@ionic/react` is using so it will pick up the same `menuController`. I am still getting ionic included twice in my bundle, but I will investigate this further.

**Comment by sean-perkins** [comment]
@mlegenhausen thanks for the work on this issue. I have confirmed:
1. `@ionic/core` is being bundled because of the `componentOnReady` import.
2. The import for `menuController` must come from `@ionic/core/components`.

I'll open a PR to get this resolved and add you as a co-contributor for the assistance.

**Comment by sean-perkins** [comment]
Here is a dev build if someone would like to confirm in their applications:
```
6.0.14-dev.11648082573.18baa25a
```

**Comment by mlegenhausen** [comment]
@sean-perkins Thanks. I can confirm that the double import does not happen anymore :)

**Comment by Cyral** [comment]
@sean-perkins Unfortunately the menu issue is still happening.

Using [https://github.com/nika1001/ionic6-menu-controller-issue/](https://github.com/nika1001/ionic6-menu-controller-issue/tree/ionic5-working-menu) and running `npm i @ionic/react@6.0.14-dev.11648082573.18baa25a`, the "toggle by MenuController" buttons are still not working. I also installed @ionic/react@^5 (and changed setupIonicReact to setupConfig) to confirm that their repo did work in Ionic 5.

Note that one of the menu's in their demo should have side="end" rather than "start", otherwise only the second button works even on Ionic 5.

**Comment by sean-perkins** [comment]
@Cyral when confirming the issue, did you update the import path:

https://github.com/nika1001/ionic6-menu-controller-issue/blob/6cb476175748774a2f33931ff028caffd5251573/src/App.tsx#L1

to:

```
import { menuController } from "@ionic/core/components";
```

**Comment by Cyral** [comment]
@sean-perkins Thanks, that did the trick. I misread your earlier message and thought you meant that was the change you made in Ionic and not the change we needed to make.

Also, a minor issue but WebStorm (and probably other IDEs) still want to import `menuController` from @ionic/core rather than @ionic/core/components. Future users may run into this issue when their IDE adds the import upon auto-complete. I'm not entirely sure how the logic works for deciding where to import from, but maybe it would use the correct import if it wasn't exported from @ionic/core still.

**Comment by sean-perkins** [comment]
Appreciate the follow-up! I also want to review our migration docs + existing usage examples to make sure all references are correct. 

I know there are a variety of issues with the type inference/import paths reported by Webstorm users that needs further investigation. 

We may be able to conditionally export the barrel file for custom elements build (React/Vue) vs. Angular to eliminate `@ionic/core` being inferred as an import path (v6). We are actively preparing for Angular to move to custom elements build in v7, which should also help clean-up these differences greatly.
