### ISSUE TITLE
bug: @ionic-native rxjs peer dependency version error

### ISSUE THREAD

**Issue by phyr0s** [ionic-team/ionic-framework#24496]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

Native plugins wrapper is not valid with ionic 5.X and angular 13

### Expected Behavior

Expected to compile with angular 13

### Steps to Reproduce

Just create new project upgrade to angular 13 and lastest version of ionic V5

### Ionic Info

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
  Ionic CLI                     : 6.18.1
   Android SDK Tools : 26.1.1 
   NodeJS            : v16.13.1
   npm               : 8.1.2
   OS                : macOS Monterey
   Xcode             : Xcode 13.1 Build version 13A1030d

 Ionic Framework               : @ionic/angular 5.9.3
   @angular-devkit/build-angular : 13.1.1
   @angular-devkit/schematics    : 13.1.1
   @angular/cli                  : 13.1.1
   @ionic/angular-toolkit        : 5.0.3

```

### Additional Information

```
Found: rxjs@7.4.0 (angular 13)

Error --> 
 peer rxjs@"^5.5.0 || ^6.5.0" from @ionic-native/core@5.36.0
```

**Comment by sean-perkins** [comment]
Hello @phyr0s thanks for reporting this issue.

You will need to move all `@ionic-native/*` packages to their new package name: `@awesome-cordova-plugins/*`. As of ~ September 27, 2021 all Cordova plugins were moved to a community maintainer. You can read the official [blog here](https://ionicframework.com/blog/a-new-chapter-for-ionic-native/).

Daniel has since updated those packages so that the dependencies will satisfy the minimum requirements for Angular 13. 

Thanks!
