### ISSUE TITLE
The swipe to close is not working for Ionic Sheet Inline Modal

### ISSUE THREAD

**Issue by shivammalvia1292dva** [ionic-team/ionic-framework#24529]
<ion-modal trigger="trigger-button"
           [isOpen]="isOpen"
           [breakpoints]="[0.1, 0.5, 1]"
           [initialBreakpoint]="0.5"
           [swipeToClose]="true"
>
  <ng-template>
    <app-modal-data></app-modal-data>
  </ng-template>
</ion-modal>

The swipe to close mentioned on the top does not works if i add or remove it, 

The modal swips to bottom but does not completey closes, Can you please help me how to completely close the modal in this inline way ?

**Comment by sean-perkins** [comment]
@shivammalvia1292dva in the future please use our issue template when opening an issue in the repository. Support related issues should be posted on the forums or in the discord.

In the docs we mention that `swipeToClose` has no effect with sheet modals:
- https://ionicframework.com/docs/api/modal#sheet-modal

> Note: The `swipeToClose` property has no effect when using a sheet modal as sheet modals must be swipeable in order to be usable.

The breakpoint property must be `0` instead of `0.1` would be where I would start.
