### ISSUE TITLE
feat: Support for UWP

### ISSUE THREAD

**Issue by enthudev** [ionic-team/ionic-framework#24523]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Restore support for Windows UWP apps 

### Describe the Use Case

According to this thread https://github.com/ionic-team/ionic-framework/issues/20754#issuecomment-598236728, support for Windows UWP apps was revoked in v5 as UWP didn't support Webview2 to load apps using Chromium engine. 

Microsoft backported Webview2 to WinUI 2 in 2.7 prerelease and might include it in a stable release in the future. With this support can you bring back the support for UWP in a future version at least as an experimental feature?

### Additional Information

Related Microsoft links:
https://docs.microsoft.com/en-us/windows/apps/winui/
https://blogs.windows.com/msedgedev/2021/08/31/webview2-windows-app-sdk-winui2-runtime-cdp-helper/

**Comment by liamdebeasi** [comment]
Thanks for the issue. The work required here is more around what Microsoft does and does not support in the webview, rather than what Ionic supports. With WebView, Microsoft only supported the EdgeHTML version of Microsoft Edge. Ionic does not support the EdgeHTML version of Microsoft Edge, so WebView and Ionic were incompatible.

With WebView2, Microsoft supports the Chromium version of Microsoft Edge, which is what Ionic supports as well. As as a result, you can build Ionic apps using WebView2.

It looks like you can use WebView2 in WinUI 2 to achieve a UWP with Ionic: https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2. Note that it is in public preview, so some features may not be available.

Does this answer your question?
