### ISSUE TITLE
bug: ion-datetime UTC time does not correspond to timezone

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/ionic-framework#24578]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Hi, ion-datetime UTC time does not correspond to timezone.
![example](https://user-images.githubusercontent.com/18282247/149543981-2ed0b7d9-809a-4d1e-b09c-184584040fe1.png)

### Expected Behavior

As Angular does (in the example) UTC time with Z at the end, it should correspond to the device's timezone.

### Steps to Reproduce

```
date: string = '2022-01-14T15:00:00.000Z';
<ion-datetime [value]="date" presentation="time"></ion-datetime>
Angular UTC {{ date | date:'HH:mm' }}
```

### Code Reproduction URL

https://stackblitz.com/edit/ionic-angular-v5-ss445m?file=src%2Fapp%2Fapp.component.html

### Ionic Info

Ionic:

Ionic CLI : 6.18.1

Utility:

cordova-res : not installed globally
native-run : 1.5.0

System:

NodeJS : v17.3.0
npm : 8.3.0
OS : Windows 10

**Comment by sean-perkins** [comment]
Hello @Marius-Romanus thanks for the issue!

A decision that we made with the updated datetime component in v6, was to eliminate the responsibilities of timezone formatting from the component. Instead, we recommend using a battle-tested package, such as `date-fns` to format the date value in the respective timezone.

Please checkout our call-out to this in the "Parsing dates" section: https://ionicframework.com/docs/api/datetime#parsing-dates

Angular's date pipe however, does have baked-in functionality related to timezones: https://github.com/angular/angular/blob/master/packages/common/src/pipes/date_pipe.ts#L182

Let me know if this helps resolve your issue or if I misunderstood the issue. Thanks again!

**Comment by Marius-Romanus** [comment]
When the format is in Zulu and not with a specific time zone for example "+01:00". Shouldn't it scroll to the user's time zone? Both angular and date-fns behave like this by default, without the need to pass any additional parameters, I update the example with date-fns.

In the third parameter that you have passed me as an example, the following is indicated:
* @param timezone A timezone offset (such as `'+0430'`), or a standard UTC/GMT, or continental US
   * timezone abbreviation. When not supplied, either the value of the `DATE_PIPE_DEFAULT_TIMEZONE`
   * injection token is used **or the end-user's local system timezone**.

**Comment by Marius-Romanus** [comment]
In case it helps, I'm currently formatting to a Date, then reformatting it back to an ISO string but with hours instead of Z.

`formatISO(new Date('2022-01-14T15:00:00.000Z'))`

**Comment by sean-perkins** [comment]
@Marius-Romanus appreciate the follow-up, I also had to discuss with the team to become familiarized on the timezone implementation details with datetime 👍 

Your approach for formatting the date string is correct and the recommended approach with the v6 component. If you are wanting to show a date string in a specific timezone, you will need to make sure the date string is already in that time zone prior to assigning it to `ion-datetime` (or format it, if it is not). 

This was an intentional change in v6, based on the complexity of trying to manage all the timezone logic in v5 and getting it wrong. While it may seem like an extra implementation detail on your end, it does offer additional flexibility to your application with how you decide to handle timezones and also adds extra capacity to the Ionic team, to focus on the features of the datetime component. 

Let me know if you have any additional questions. I do appreciate the bug report and reproduction app. It's having community members like yourself, that helps make Ionic successful!

**Comment by Marius-Romanus** [comment]
I have no question. I take this opportunity to congratulate you for the work you all do. I will help in any way I can.

**Comment by sean-perkins** [comment]
Thanks @Marius-Romanus! Appreciate YOU! I created a PR to better explain this behavior in the `ion-datetime` docs, to make it easier for the next person!
