### ISSUE TITLE
bug: ion-input height and text alignment does not match Material design

### ISSUE THREAD

**Issue by sverdlov** [ionic-team/ionic-framework#24639]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

The alignment of input is incorrect.
![image](https://user-images.githubusercontent.com/15052094/150819321-1e7f93f1-e793-4da4-aa05-c11c6913ac79.png)

### Expected Behavior

Expecting see correct behavior like in Material UI
![image](https://user-images.githubusercontent.com/15052094/150819842-68e5c04d-0165-41b7-8cf6-3114f310b496.png)
[Material Text Field](https://material.io/components/text-fields#usage)

### Steps to Reproduce

Just create project from scratch. Use following code
```
<ion-item mode='md' fill='outline'>
    <ion-label position='floating'>Login</ion-label>
    <ion-input></ion-input>
</ion-item>
```

### Ionic Info
Ionic CLI                     : 6.18.1 (/home/andrew/.nvm/versions/node/v14.17.3/lib/node_modules/@ionic/cli)
Ionic Framework               : @ionic/angular 6.0.3
@angular-devkit/build-angular : 13.0.4
@angular-devkit/schematics    : 13.0.4
@angular/cli                  : 13.0.4
@ionic/angular-toolkit        : 5.0.3

**Comment by sean-perkins** [comment]
@sverdlov thanks for reporting this issue. After comparing the two design implementations, these are the immediate differences I have identified:

Item|MD|Ionic|
|---|---|---|
|Item height|56px|57px|
|Vertical input text alignment|Center to container (~20px top/bottom)|Undetermined (17px top/26px bottom)|

Is there any other design issues you are noticing that you would like to include?

**Comment by sean-perkins** [comment]
Updating the title and tracking as a bug based on previous comment.

**Comment by enriqueloz88** [comment]
Any news on this? The text alignment inside the ion-input is clearly wrong when fill="outline" on the item. There is too much space at the bottom of the input
![image](https://user-images.githubusercontent.com/61509169/167034428-7bb9207a-3423-4275-993a-0becb5963d35.png)

**Comment by Yura13** [comment]
When do you plan to fix this issue because text alignment looks awful?

**Comment by sean-perkins** [comment]
The team is actively working on two upcoming releases and has not prioritized this issue yet.

This repository is open source however and the alignment and height differences have been [documented above](https://github.com/ionic-team/ionic-framework/issues/24639#issuecomment-1020572909). If this issue is a pain point for you and your application, we would gladly welcome a pull request that works to resolve this problem. 

Thanks!

**Comment by enriqueloz88** [comment]
By lowering the height of the field a bit you can get the text inside to be more or less centered:

```
.md .item-fill-outline {
  &::part(native) {
    height: 50px;
  }
}
```

It's probably not the best solution since the input really should be 56px following the Material Design specifications, but for now it does the trick for me. I'm waiting to see if the ionic team or someone else comes up with a better solution (I've tried to investigate the css further and I can't find any)

**Comment by liamdebeasi** [comment]
Thanks for the report. In Ionic 7 we are introducing a new syntax for working with ion-input. This issue is fixed when using that new syntax. We will have an Ionic 7 beta in the future where developers can test and provide feedback. There will also be a migration guide to show how to update to the new input syntax.

The work required to resolve this has been completed, so I am going to close this thread. Let me know if there are any questions.
