### ISSUE TITLE
feat: leverage advances in webkit

### ISSUE THREAD

**Issue by LifeIsStrange** [ionic-team/ionic-framework#24684]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Webkit is kind of an abondonware and is in a tragic state. Moreover it is indeed a crime against humanity that Apple is doing by banning access to non-webkit browsers.
Regardless of this, webkit is slowly progressing towards being slightly less mediocre and those advances should be leveraged by Ionic in order to allow devs to provide a better user experience.

https://firt.dev/ios-15.4b
See e.g push notifications (although has bugs), better PWA and CSS support 

### Describe the Use Case

Make the web great again.

### Describe Preferred Solution

.

### Describe Alternatives

.

### Related Code

.

### Additional Information

.

**Comment by liamdebeasi** [comment]
Thanks for the issue. While we appreciate the feedback, this is not the place to air grievances about WebKit. Instead, I recommend providing constructive feedback to the WebKit developers directly (See: https://webkit.org/getting-started/#staying-in-touch)/

As for taking advantage of new features provided by browsers, this is something we are doing on a regular basis. In particular, the `scroll-behavior` and native image lazy loading features are things we are interested in.

Ionic Framework only deals with the user interface, so features such as Web Push are outside the scope of what Ionic Framework handles. This does not mean that Ionic Framework does not support push notifications, it means that Ionic Framework does not prevent you from using push notifications in your application.

I think this discussion would be more constructive if you opened up feature requests for specific things you would like to see inside of Ionic, rather than give us a list of browser features. If you are interested in doing that, I am happy to continue this conversation. For now, I am going to close this issue. Thanks.

**Comment by LifeIsStrange** [comment]
@liamdebeasi Thanks, great answer, this issue can be closed as I have no specifics.
As a reminder, I believe Ionic has a lot of potential regarding improving layout performance by leveraging extensively CSS: contain (and related extensions, such as container-queries)
Thanks for the great work :)
