### ISSUE TITLE
bug(router): navChanged should run hooks and cancel navigation when there is no matching routes

### ISSUE THREAD

**Issue by vicb** [ionic-team/ionic-framework#24728]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

`navChanged()` is triggered when a `<ion-nav>` or a `<ion-tabs>` updates their view.

The method has a few problems:
- when no route is found for the updated view it should stay on the current view (effectively cancelling the navigation),
- it does not take the hook into account meaning that it will bypass any hooks.

The changes required to fix this are broad and encompass the router, `<ion-nav>` and `<ion-tabs>`.

### Expected Behavior

1) It should no be possible to activate a view when there is no matching route,
2) The hooks should be executed.

### Steps to Reproduce

I'll submit one or more PR to fix this with reproduction and e2e tests.

### Ionic Info

bash: ionic: command not found :)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a GitHub repo I can use to verify this behavior?

**Comment by vicb** [comment]
As i mention in my initial report the PR will have a test case that fails with the current code.
I'll send that PR when the one i have pending is merged.

**Comment by liamdebeasi** [comment]
Thanks for the issue. As I mentioned in https://github.com/ionic-team/ionic-framework/pull/24645#issuecomment-1048224542, we are looking to encourage users to interact with the router via `<ion-router>` and are looking to remove the functionality where `ion-nav` and `ion-tabs` directly notify the router.

I agree that this behavior is not correct, but because of the changes we are looking to make this is not something we are able to address at the moment. Thanks!
