### ISSUE TITLE
bug: Ionic Angular bundles compiler.mjs, even with aot enabled

### ISSUE THREAD

**Issue by maxcodefaster** [ionic-team/ionic-framework#24731]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Blank ionic Angular app bundles compiler.mjs and forms.mjs into the main vendor.js

![image](https://user-images.githubusercontent.com/35369883/152791861-02bfecee-ae11-4e95-bbca-5fd21c180932.png)

### Expected Behavior

Ionic angular apps should compile and be bundled without compiler.mjs and forms.mjs in den main chunk. This will reduce initial bundle size about 300kb+ gzipped, which is about a third.

### Steps to Reproduce

Create any ionic angular starter app. Run `ng build --stats-json` and `webpack-bundle-analyzer www/stats.json`

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.2
   @angular-devkit/build-angular : 13.2.2
   @angular-devkit/schematics    : 13.2.2
   @angular/cli                  : 13.2.2
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.4
   @capacitor/android : 3.3.4
   @capacitor/core    : 3.3.4
   @capacitor/ios     : 3.3.4

Utility:

   cordova-res (update available: 0.15.4) : 0.15.1
   native-run                             : 1.5.0

System:

   NodeJS : v17.3.0 (/usr/bin/node)
   npm    : 8.4.1
   OS     : Linux 5.16

**Comment by maxcodefaster** [comment]
> Thanks for the issue! This issue has been labeled as `needs reproduction`. This label is added to issues that need a code reproduction.
> 
> Please reproduce this issue in an Ionic starter application and provide a way for us to access it (GitHub repo, StackBlitz, etc). Without a reliable code reproduction, it is unlikely we will be able to resolve the issue, leading to it being closed.
> 
> If you have already provided a code snippet and are seeing this message, it is likely that the code snippet was not enough for our team to reproduce the issue.
> 
> For a guide on how to create a good reproduction, see our [Contributing Guide](https://ionicframework.com/docs/contributing/how-to-contribute#creating-a-good-code-reproduction).

https://github.com/ionic-team/starters/tree/main/angular/official

**Comment by liamdebeasi** [comment]
I took a closer look at this, and I think the issue here is that you were doing a dev build, not a production build.

When doing a development build, treeshaking/dead code elimination does not run. As a result, additional code may be pulled into your bundle. When doing `ng build`, I was able to see that both `compiler.mjs` and `forms.mjs` were pulled into the final build.

However, when doing `ng build --configuration production`, only `forms.mjs` was pulled in. In other words, `compiler.mjs` was not included in the final result.

In terms of `forms.mjs` being included, this is to be expected. Ionic Angular automatically registers different control value accessors that you can use on form components such as `ion-input`, `ion-textarea`, and more. These control value accessors import information from `@angular/forms`: https://github.com/ionic-team/ionic-framework/blob/main/angular/src/directives/control-value-accessors/value-accessor.ts#L2. As a result, I would expect @angular/forms to be included in the initial chunk.

Are you able to see this on your end?

**Comment by maxcodefaster** [comment]
Yes using the --configuration production option solved the issue. Thank you.
