### ISSUE TITLE
bug: the ion-refresher create a conflict with the fixed elements in IOS

### ISSUE THREAD

**Issue by loicparent** [ionic-team/ionic-framework#24774]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

**When**
The bug appears when I add an ion-refresher in the ion-content when I have also some fixed elements in the page. (For example, if I use fixed tabs in the page). This bug appears only in IOS (builded app).

**What**
The fixed elements doesn't be relative to the document but to the parent element ion-content.

**Why**
Because the ion-refresher add a translateZ that cause a conflict with the position fixed.

### Expected Behavior

The refresher doesn't have any impact on the element with a fixed position.

### Steps to Reproduce

1. Create a page
2. Add the component ion-content
3. Inside this component, add a component ion-refresher.
4. In the ion-content, add a new element: `<div style="width:100%;height:30px;background-color:red;position:fixed;top:0;left:0;"></div>`
5. Add enough content to have the scrollbar
6. Open the builded app in ios.
7. Scroll in this page and see that the fixed element doesn't stay fixed.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/Users/loicparent/.nvm/versions/node/v14.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.9.2
   @angular-devkit/build-angular : 12.2.14
   @angular-devkit/schematics    : 12.2.14
   @angular/cli                  : 12.2.14
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.3.3
   @capacitor/ios     : 3.3.3

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   ios-sim : 8.0.2
   NodeJS  : v14.15.0 (/Users/loicparent/.nvm/versions/node/v14.15.0/bin/node)
   npm     : 6.14.8
   OS      : macOS Big Sur
   Xcode   : Xcode 13.0 Build version 13A233

### Additional Information

I tried to fix this using a workaround that consist to remove the transform using js.
This one works but not for the first scroll event and above all, this is not a good idea/practice.

Could someone help me to find a fix?

Thanks :)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you create a sample GitHub repo I can use to verify this issue?

**Comment by loicparent** [comment]
Hello @liamdebeasi,

Thanks for your quick reply!
Ok, I will add this sample repo probably on Monday.

Have a nice weekend!
_Loïc_

**Comment by loicparent** [comment]
Hello @liamdebeasi,

Here is the link to the demo repository: https://github.com/loicparent/ionic-refresher

✅. When you launch "ionic serve", it works correctly.
✅  When you launch "ionic cap run android", it works correctly.
❌  When you launch "ionic cap run ios", it doesn't work (the fixed elements scroll in the page).

I hope this demo will help to identify the problem.

_Kind regards_

**Comment by liamdebeasi** [comment]
Thanks! I've seen this one a few times before, and unfortunately there is no good solution. This behavior exists due to a long-standing bug with how WebKit handles `position: fixed` inside of non-body scrollable containers.

Using `slot="fixed"` works because content in that slot is not part of the scrollable container. The solution for your app would be to place the red square inside of the `fixed `slot. However, this is not possible due to `ion-refresher` wanting you to set `slot="fixed"` directly on the element. I think it makes sense to allow for it to be used inside of a container. (I.e. refresher could be wrapped in a div that has `slot="fixed"`).

**Comment by liamdebeasi** [comment]
Here is a dev build if you would like to test:

```
npm install @ionic/angular@6.0.8-dev.1644878646.e4f7407
```

You will need to do the following things after installing the dev build:

1. Create a `div` that wraps both `ion-refresher` and `<div class="fixed">`.
2. Add `slot="fixed"` to this newly created `div`.
3. Add `style="width: 100%"` to this newly created `div`.
4. Remove `slot="fixed"` from `ion-refresher`.

**Comment by loicparent** [comment]
Hi @liamdebeasi,
Thanks for the help! This works fine in this case :)

However, this solution doesn't fix the initial problem in my app :-/
I simplified the demo to show the issue but in my app, I actually have tabs in the content and they have to stay fixed when they arrive at the top of the content. So in my case, the fixed element should be placed in the scrollable content.

I have updated the repo to show you another demo with similar tabs.

_Kind regards_

**Comment by liamdebeasi** [comment]
Hmm, I am not sure this particular behavior is the same issue as I see a consistent behavior in both Chrome and Safari.

I think it would be better to use `position: sticky` in this instance. So instead of having the scroll listener and switching between relative and absolute positioning, you could set the following on `.tabs`:

```css
.tabs {
  position: sticky;
  top: 0;
}
```

Can you try that and let me know if it helps?

**Comment by liamdebeasi** [comment]
I'm not sure I fully understand the issue as it is in your application. Do you have a video of how the behavior on iOS?

**Comment by loicparent** [comment]
Hello @liamdebeasi, yes can show you the render in the app.

**Note**: these changes are not yet in production so I can't display all the contents but you can see the renders below:

<table border="0">
 <tr>
    <td width="50%" valign="top">
<b style="font-size:30px">With refresher (and the bug):</b><br><br>
You can see that the tabs and the active position in the table don't stay fixed.
</td>
    <td width="50%" valign="top">
<b style="font-size:30px">Without refresher:</b><br><br>
In this demo, the tabs menu and the active position in the table are correcty fixed in the visible section until the user scroll enough to show another section or the arrive to the position of the active row in table.
</td>
 </tr>
 <tr>
   <td>
<video src="https://user-images.githubusercontent.com/11327909/154658813-a2d94865-7e69-4045-a800-f7c522248b99.mp4"></video>
</td>
    <td>
<video src="https://user-images.githubusercontent.com/11327909/154658845-7175281f-819c-464b-8bbc-6f0aa6ba1420.mp4"></video>
</td>
 </tr>
</table>

**Comment by liamdebeasi** [comment]
Thanks! I was able to replicate the same behavior on the 2nd video with `position: sticky` and using refresher.

Here is a video of it in Safari: 

https://user-images.githubusercontent.com/2721089/154746688-7199b67a-4758-4a97-9539-6d4613798ad2.mov

In this example the sticky elements are not direct children of the scrollable container.

The markup I used looks like this:

```html
<div class="container" *ngFor="let a of [1,2,3]">
  <div class="title">Container {{ a }} title</div>

  <ion-list>
    <ion-item *ngFor="let e of array_long; let i = index;" [class.sticky-item]="i === 30">
      <ion-label *ngIf="i !== 30">Item {{ i }}</ion-label>
      <ion-label *ngIf="i === 30">Container {{ a}} Item {{ i }}</ion-label>
    </ion-item>
  </ion-list>

</div>
```

(I do have a refresher in here, I just didn't include it in the code snippet).

The CSS I used looks like this:

```css
.sticky-item {
  --background: blue;

  position: sticky;
  bottom: 0;

  z-index: 1;
}

.container {
  margin: 0 0 20px 0;
}

.title {
  background: blue;
  color: white;

  padding: 10px;

  position: sticky;
  top: 0;

  z-index: 2;
}
```

I recommend giving `position: sticky` another shot. It seems very close to what you are trying to achieve.

That being said, the reason for the original behavior is not due to a bug in Ionic, so I am going to close this issue out. If you need additional help implementing `position: sticky`, I recommend posting on the [Ionic Forum](https://forum.ionicframework.com/). Thanks!

**Comment by loicparent** [comment]
Hello @liamdebeasi,

After adaptation (following your example), I arrive to manage it using `position: sticky;` but, I had to change a bit the structure by avoiding having a parent item with `overflow: hidden|auto|scroll;` and also by avoiding having a sticky element inside the item (=> `.item__inner`) and so by placing the sticky element as a direct child of the content.

**So it works, tkanks!** However, with sticky element, there is no way to detect if the element is at the initial position or if it is "sticky" (=> there is not pseudo-class that allow to change the style depending on it. So, I still have to use scroll detection to handle this.

I agree that this is not an Ionic bug since this is related to the way WebKit works with fixed elements but it could be very nice to avoid (if possible) using translate3D with the refresher though ;)

Thanks again for your help & have a nice day :)
