### ISSUE TITLE
bug: Item with Outline does not display properly when inside a List

### ISSUE THREAD

**Issue by RobertWeaver** [ionic-team/ionic-framework#24814]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Using an Item component inside a List with the fill set to Outline is rendered with a partial border.

![image](https://user-images.githubusercontent.com/6476560/154653039-db213b05-ec06-40e1-bd21-37085e5e6127.png)

### Expected Behavior

The Item should display with the complete border when used with or without a List

![image](https://user-images.githubusercontent.com/6476560/154653223-d3d7dd24-4753-49c4-b8a3-156e9f89b22e.png)

### Steps to Reproduce

Use the code below inside of an Ionic Application.

```
      <ion-list lines="full">
        <ion-item fill="outline" mode="md">
          <ion-label position="floating">Ion Item Outline with List</ion-label>
          <ion-input value=""></ion-input>
          <ion-note slot="helper">Helper Text</ion-note>
          <ion-note slot="error">Error Text</ion-note>
        </ion-item>
      </ion-list>
```

### Code Reproduction URL

https://codesandbox.io/s/ion-item-with-outline-display-error-idyy8f

### Ionic Info

Using custom elements version of Ionic.

### Additional Information

I believe this CSS is overriding the Outline border-width css. If I uncheck it then the .item-fill-outline will be used and then display correctly.
 
![image](https://user-images.githubusercontent.com/6476560/154654464-ed8b6a17-9201-4095-86d6-97b12deb9f27.png)

![image](https://user-images.githubusercontent.com/6476560/154654607-70e35432-b036-4865-8c3e-ca4167ec36f5.png)

**Comment by sean-perkins** [comment]
Hello @RobertWeaver thanks for reporting this issue.

I do see the visual inconsistencies you are reporting. Unfortunately Material design does not reference an exact implementation for multiple outlined controls in a list (they apply outline style at the text field level, we are doing it at the item level)

We will likely have to avoid the style override and introduce additional spacing between items, as just applying the border style causes visual crowding between multiple outline items with helper text.

We'll capture as a bug and prioritize, thanks!

**Comment by liamdebeasi** [comment]
Thanks for the report. In Ionic 7 we are introducing a new syntax for working with ion-input. As part of this, we moved the filled/outline styles to the input itself. We also released new guidance on how to use these outline/filled styles. When using outline/filled styles, inputs should not be used inside of an `ion-item`. The reason is that outline/filled inputs visually define the input container, so adding them into an item (which also defines the container) is not necessary. See https://ionicframework.com/docs/v7/api/input#filled-inputs for more information.

Ionic 7 is currently in beta, and developers can find a migration guide on our documentation website: https://ionicframework.com/docs/v7/updating/7-0

I am going to close this thread, but let me know if there are any questions.
