### ISSUE TITLE
bug: router does not wait for components to unmount before going back

### ISSUE THREAD

**Issue by JeremyDfr** [ionic-team/ionic-framework#24853]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

A blank page is displayed when changing the quick page

### Expected Behavior

No blank page when changing page

### Steps to Reproduce

I have a navigation component, I change my route from the home page to an alert page, I come back to the home page and quickly return to the alert page and the white page is displayed, still using the navigation component

### Code Reproduction URL

https://github.com/JeremyDfr/Bug-Reproduction-24853/tree/main

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/home/jeremy/.nvm/versions/node/v14.18.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.9.3

Capacitor:

   Capacitor CLI      : 3.0.2
   @capacitor/android : 3.0.2
   @capacitor/core    : 3.0.2
   @capacitor/ios     : 3.4.1

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 1.5.0)   : 1.4.0

System:

   NodeJS : v14.18.1 (/home/jeremy/.nvm/versions/node/v14.18.1/bin/node)
   npm    : 8.3.0
   OS     : Linux 5.13

### Additional Information

I use nested route, I have a parent and child part.
I have other route in the child part but the bug appeared only on these 2 routes.

```javascript
{
    path: '/children',
    name: 'Children',
    meta: {
      requiresAuth: true,
    },
    component: () => import("@/views/children/Children.vue"),
    children: [
      {
        path: "",
        component: () => import("@/views/children/Home.vue"),
        meta: {
          requiresAuth: true,
        },
      },
      {
        path: "alert",
        component: () => import("@/views/children/Alert.vue"),
        meta: {
          requiresAuth: true,
        },
      },
    ]
  }
```

Here my navigation component
```javascript
<template>
  <ion-footer>
    <ion-toolbar>
      <div class="mainNavigation">
        <nav v-if="navigation === 'parent'">
          <router-link class="mainButton--green" to="/parent/childrens">Mes <strong>enfants</strong></router-link>
          <ul>
            <li>
              <router-link to="/parent" replace>
               Accueil
              </router-link>
            </li>
            <li>
              <router-link to="/blog">
               Blog
              </router-link>
            </li>
            <li>
              <router-link to="/profil">
                Profil
              </router-link>
            </li>
          </ul>
        </nav>
        <nav v-else>
          <router-link class="mainButton--pink" to="/children/alert">
            Alerte
          </router-link>
          <ul>
            <li>
              <router-link to="/children" replace>
                Accueil
              </router-link>
            </li>
            <li>
              <router-link to="/blog">
                Blog
              </router-link>
            </li>
            <li>
              <router-link to="/profil">
                Profil
              </router-link>
            </li>
          </ul>
        </nav>
      </div>
    </ion-toolbar>
  </ion-footer>
</template>

<script>
import {defineComponent} from "vue";
import {IonFooter, IonToolbar} from "@ionic/vue";

export default defineComponent({
  name: "ParentsNavigation",
  components: {
    IonFooter,
    IonToolbar
  },
  props: {
    navigation: null
  }
});
</script>

```

**Comment by JeremyDfr** [comment]
The reproduction
https://github.com/JeremyDfr/Bug-Reproduction-24853/tree/main

**Comment by tigohenryschultz** [comment]
My app is having a issue with the HTML root not getting 'hydrated' set, I wonder if it is as at related

**Comment by JeremyDfr** [comment]
@tigohenryschultz
How can I solve this problem ? You may have a solution ?

**Comment by tigohenryschultz** [comment]
Not sure if it is the same problem, do your root HTML element have a missing 'hydrated' class?

**Comment by liamdebeasi** [comment]
If you are using Ionic 6 there is no hydration, so the `hydrated` class will not show up.

This appears to be a different problem, but I am still digging into it.

**Comment by tigohenryschultz** [comment]
My stylesheet code was still expecting a hydrated class so I just added this to temp fix my problem in App.vue:

  ```
  created(){
      document.documentElement.classList.add('hydrated');
    },
```

The style code from the @ionic/core seemed to still load CSS expecting hydrated class to exist

**Comment by liamdebeasi** [comment]
For v6 you can have it expect the `.ion-ce` class now: https://github.com/ionic-team/ionic-framework/blob/99c91eff8764c9a1630adedab6a9765dd9754f7d/core/src/css/structure.scss#L29-L31

Ionic Angular still uses hydration which is why we need to support both. In the future we won't have to worry about hydration as much.

**Comment by tigohenryschultz** [comment]
What core version should I be on then?
```

 "@ionic/core": "5.9.3",
    "@ionic/vue": "^6.0.8",
    "@ionic/vue-router": "^6.0.8",
```

**Comment by liamdebeasi** [comment]
You shouldn't install `@ionic/core` separately. Installing `@ionic/vue` will automatically install the correct `@ionic/core` version.

For example, installing `@ionic/vue@6.0.8` will cause `@ionic/core@6.0.8` to also get installed.

**Comment by liamdebeasi** [comment]
Regarding the issue reported in the first post:

This issue is happening because users are pushing the alert page again before the alert page has been fully unmounted.

Reproduction steps:

1. Start on `/children`.
2. Click "Alert". App is now on `/children/alert`.
3. Click "Home". App is now on `/children`.

Note: According to the app code provided, this is a replace operation. This means the state of `/children/alert` is replaced with the new state of `/children` and the Alert component should be unmounted.

4. Quickly click "Alert". App is now on `/children/alert`. 

Because the Alert unmounting process happens mid page transition, you should get a blank screen.


@JeremyDfr Could you please provide your use case for this routing setup? In particular, we are interested in understanding why you have to replace the state of `/children/alert` with that of `/children`.

**Comment by tigohenryschultz** [comment]
We have a similar route structure in our app and a user could go from a system/alerts to view a specific alert. system/alerts/view/x and nothing would stop them from spamming in/out of these. Depending on how large they are this would cause this race condition unmounting/remounting to the outlet?

**Comment by liamdebeasi** [comment]
For most cases, no. The reason is that we remove pointer-events inside of the outlet during transitions.

In the example posted in https://github.com/ionic-team/ionic-framework/issues/24853#issuecomment-1054726912, the buttons that trigger routing exist outside of the outlet that is transitioning and still receive pointer events. I suppose we could remove pointer events from the entire app during transition, but I'd want to do heavy testing to make sure that does not break anything.

**Comment by JeremyDfr** [comment]
@liamdebeasi 
Thanks for your reply

My app have two parts, children and parent, they are nested routes /children and /parent with the replace.
I don't want users to go back to the login page with the back button, so I added the replace.

But, if I remove the replace, the back button will give me a blank page when spamming, you can look in the reproduction I added the concern without the replace in second point.

**Comment by liamdebeasi** [comment]
Thanks! I think we should account for this behavior. The problem is that Ionic waits for the transition, but does not wait for any framework clean up to happen. In this case, it is not waiting for pages to get unmounted before proceeding with the next transition. As a result, the old component is still considered to be mounted when the next transition starts.
