### ISSUE TITLE
feat(ion-alert): add shadow parts

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#24947]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The ability to override ion-alert globally by using shadow parts.

### Describe the Use Case

The ability to override ion-alert globally by using shadow parts.

### Describe Preferred Solution

expose parts for `native`, `backdrop`, `content`, `header`, `message` and `buttons`

example for part `native`:

```scss
ion-alert::part(native) {
   .alert-head {
       //some css styling
   }
    .alert-head {
       //some css styling
   }
    .alert-message {
       //some css styling
   }
   .alert-button-group {
       //some css styling
      button {
       //some css styling
       }
   }
}
```

### Describe Alternatives

Currently you have to provide cssClass to every ion-alert.

The following example is not working with all css properties:

```scss
ion-alert .alert-wrapper {
   //some css styling
}
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. `ion-alert` does not use the Shadow DOM, so Shadow Parts cannot be enabled. You should be able to target elements directly such as the header, message, buttons, etc. Is there a particular issue you are running into with this?

**Comment by liamdebeasi** [comment]
Thanks! I think the issue here is with CSS specificity. The Ionic styles target a more specific selector than `ion-alert .alert-wrapper`, so our styles get applied over your styles. This is why we encourage developers to use the `cssClass` property when customizing these components. This feature results in your selectors being more specific than our selectors.

We are tracking specificity improvements in https://github.com/ionic-team/ionic-framework/issues/17425, so I am going to close this in favor of that thread. We are actively exploring improvements to styling in overlay components (alert, action sheet, etc), so this is helpful feedback.

**Comment by DwieDima** [comment]
oh my bad, changing the css properties to

```scss
border-radius: 5px !important;
  --max-width: 335px;
```

did the trick.

sorry, I'll close the ticket!
