### ISSUE TITLE
bug: iOS 15 bottom toolbar not collapsing on scroll [PWA]

### ISSUE THREAD

**Issue by roman-rr** [ionic-team/ionic-framework#24948]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [X] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

As current trend for Progressive apps is growing here is pretty high needs to have good user experience with browser apps, as well as platform apps.

Currently, bottom search toolbar is always expanded. After investigation i found that `position:fixed` and `overflow:hidden` on `<body>` element cause scroll freezing. 

Full-sized search toolbar take many much space of the ionic application.

![expanded](https://user-images.githubusercontent.com/10646478/158648007-889e92ac-77a6-44a0-9c49-fdf2947f254b.png)

### Expected Behavior

Expected to have collapsed toolbar to small version. 

![collapsed](https://user-images.githubusercontent.com/10646478/158648960-d145dae0-60d4-448b-94bb-1dbb0431a84a.png)

### Steps to Reproduce

```bash
$ ionic start my-pwa-ionic // create any project
$ cd my-pwa-ionic
$ ng add @angular/pwa
$ npm install -g firebase-tools
$ ionic build --prod
$ firebase deploy
```

Open PWA application with safari browser on iOS device or emulator.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.9
   @angular-devkit/build-angular : 13.1.4
   @angular-devkit/schematics    : 12.2.15
   @angular/cli                  : 13.1.4
   @ionic/angular-toolkit        : 4.0.0

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 27 other plugins)

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.5.0) : 1.4.0

System:

   Android SDK Tools : 26.1.1 (/Users/romanrr/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v16.13.2 (/usr/local/bin/node)
   npm               : 8.1.2
   OS                : macOS Monterey
   Xcode             : Xcode 13.2 Build version 13C5066c

**Comment by liamdebeasi** [comment]
Thanks for the issue. We received a similar request a while back. When your scrollable content is on the `<body>`, the URL bar collapses as you scroll. If the scrollable content is in a non-body element, the URL bar does not collapse as you scroll.

In order to do page transitions, swipe to go back, and more we need to have the scrollable content be in `ion-content`, which is a non-body element. As a result, the URL bar does not collapse as you scroll in Ionic apps.

Unfortunately, this behavior is an intended feature of Safari and is not something Ionic is able to control. I checked with the Safari team at Apple when iOS 15 was released, and they noted that you can still collapse the toolbar by pressing the "aA" button in the URL bar then pressing "Hide Toolbar". This is the recommended workaround if you are looking for more screen space when browsing in mobile Safari.

Please see https://github.com/ionic-team/ionic-framework/issues/19081#issuecomment-948987368 for additional context surrounding this limitation.

I am going to close this as there is nothing actionable from our end. Thank you!

**Comment by roman-rr** [comment]
Don't sure if it is possible, but created feature request for webkit 
https://bugs.webkit.org/show_bug.cgi?id=237973

**Comment by liamdebeasi** [comment]
Thanks! If you have a production application you can link them to, that tends to help with issue prioritization.
