### ISSUE TITLE
feat: ion-datetime customizable header (the picker + arrows)

### ISSUE THREAD

**Issue by RodrigoSaPessoa** [ionic-team/ionic-framework#25001]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

It would be great if users could **edit the header of the ion-datetime** (the picker + arrows).

For example, I have no interest in changing the current year so having a picker with the years in it can be confusing for the user.
Instead, it would be great to have the ability to change this layout. My suggestions would to allow the freedom to:
- only have the arrows, and each arrow is on the respective start/end slot of the header
- have label in the middle of the header
- make the picker unclickable
- to have a picker that instead of showing month and year, it shows only the month

Also it would be great to have the ability to choose the **color of the arrows separately from the component**.

### Describe the Use Case

Some header examples.

1.  [MY LABEL]........................< >

2.  <............[MY LABEL]............>

3. [MONTH PICKER]........................< >

**Comment by sean-perkins** [comment]
@RodrigoSaPessoa thanks for the feature request!

Can you explain this portion in more detail:
> I have no interest in changing the current year

Min/max would prevent users from both swiping and using the expanded calendar view to change the current month/year. Allowing customization to the datetime header would not prevent users from accessing the previous/next calendar year.

**Comment by sean-perkins** [comment]
@RodrigoSaPessoa this was an intentional decision & alignment with how native date pickers function. Preventing users from being able to quickly change their month/year, when no `min` or `max` constraint is in place, is a regression to our desired user experience.

With your use case, I would recommend:
```html
<ion-datetime min="2022-01-01" max="2022-12-31"></ion-datetime>
```

It will:
- Limit selection to the current year
- Prevent the ability to swipe to the next or previous year
- Expanding the month/year selector will only show available months within the current year

Forcing users starting in January to tap 11 times to the right to get to December, would not be a good experience for users.

Our goal for the datetime component is solving the common needs for selecting dates in a native experience. If you are still set on customizing the header, there may be alternative libraries that expose that level of customization and flexibility. 

Thanks!
