### ISSUE TITLE
bug: ion-modal with ng-template not rendered in custom component

### ISSUE THREAD

**Issue by shseah601** [ionic-team/ionic-framework#25095]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Based on current ion-modal guide, the usage of inline ion-modal is understandable even using ion-datetime with ion-modal.
When trying to create a new custom component that will have an ion-modal component, the ion-modal content inside ng-template is not rendered. The suggested code for using ion-modal is adding the ng-template for the modal content.
```
<ion-modal>
  <ng-template>
    modal content goes here...
  </ng-template>
</ion-modal>
```

Currently ion-modal without ng-template rendered inside custom component, but not sure what happens here.

### Expected Behavior

Having consistent behaviour with normal ion-modal usage and custom component usage.

### Steps to Reproduce

1. Create a new custom component
2. Use ion-modal with ng-template inside the custom component.

I had created a stackblitz for this issue: https://stackblitz.com/edit/ionic6-angular13-am5obj?file=src%2Fapp%2Fapp.component.html

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.15
   @angular-devkit/build-angular : 13.3.2
   @angular-devkit/schematics    : 13.3.2
   @angular/cli                  : 13.3.2
   @ionic/angular-toolkit        : 2.3.3

Utility:

   cordova-res (update available: 0.15.4) : 0.15.2
   native-run (update available: 1.5.0)   : 1.3.0

System:

   NodeJS : v16.13.1 (/usr/local/bin/node)
   npm    : 8.1.2
   OS     : macOS Monterey

### Additional Information

Had checks similar issue #23561.

**Comment by sean-perkins** [comment]
Hello @shseah601 thanks for the issue!

So the problem here, is you are encapsulating your form component in a new `NgModule`, without importing `IonicModule` on that module. Our Ionic web components are shipped in `@ionic/angular` as Angular directives. When you import `IonicModule.forRoot()` in your main app module, it is both declaring the web components (using our hydrated build) and declaring the Angular directives that match the Ionic tag names.

When using SCAM (single component angular modules), you will need to re-import modules that declare components, directives and pipes that are used within that component module's template. 

The fun thing here, is since our components are web components, without importing `IonicModule` you are actually using the vanilla web component implementation, instead of our custom Angular implementation. Which is why `ng-template` doesn't work and the slotted content does.

Here is an updated Stackblitz that shows the experience working as intended with the suggested changes: https://stackblitz.com/edit/ionic6-angular13-pmfnu7

Let me know if you have questions and if that resolves the issue for you.
