### ISSUE TITLE
feat: Collapsible large title on Android (Material Design 3)

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic-framework#25157]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Ionic support Large Title Design at iOS design only But in recent Android design, Large Title is adapted.

This is Pixel5a / Android12
![スクリーンショット 2022-04-20 午後4 01 37](https://user-images.githubusercontent.com/9690024/164169666-96a6318b-6bd8-4ec0-ae53-4adf262ee716.png)

I think Ionic will support  Large Title at Android design  is better.

### Describe the Use Case

We can keep up with the latest Android designs. It also eliminates the implementation difference between iOS and Android, making Ionic easier to use.

### Additional Information

I know https://github.com/ionic-team/ionic-framework/pull/23151 , but 

- Android adapt large title currently
- Need to start discuss

**Comment by rdlabo** [comment]
Memo: In current version, we can implement Android Large Title with this code.

```html
<ion-header [translucent]="false" mode="ios">
  <ion-toolbar [mode]="platform.is('android') ? 'md': undefined">
    <ion-title>{{ title }}</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content [fullscreen]="true">
  <ion-header collapse="condense" mode="ios">
    <ion-toolbar [mode]="platform.is('android') ? 'md': undefined">
      <ion-title size="large">{{ title }}</ion-title>
    </ion-toolbar>
  </ion-header>
```

**Comment by sean-perkins** [comment]
I am uncertain that the iOS and Android pattern are the same, when looking at the MD design document: https://material.io/components/app-bars-top#behavior (scroll to the last example in the section).

Material - the title acts as a separate bar that is animated into the top bar and back to it initial position when scrolled up. 
iOS - the title element is hidden and the title text is faded in when the scroll changes. 

Is your feature request to support the behavior of the MD spec on Android?

**Comment by rdlabo** [comment]
@sean-perkins Hi, thanks for reply.

> Material - the title acts as a separate bar that is animated into the top bar and back to it initial position when scrolled up.

Yes, `Material Design 2` has these behavior.
But `Material Design 3` may follow iOS style: https://m3.material.io/components/top-app-bar/overview

![](https://i.gyazo.com/784701d8d5c3f2087937b97f34fc80e1.gif)

With that in mind, it may be sufficient to just use the current Large Title on Android.

**Comment by sean-perkins** [comment]
Perfect! Thanks for the reply and the additional detail. 

This does make sense and also reduces unnecessary differences in iOS vs. MD implementations. While we don't currently have any active plans around supporting all of Material Design 3 at this time (rounded corner fabs, etc.), this change is straightforward and makes use of an existing implementation pattern.

If others from the community would like to see this feature in Ionic Framework, please be sure to 👍  the original issue, so we can prioritize high interest features. 

Thanks!

**Comment by hellokingdom** [comment]
I would like to see this natively supported too. We currently mimic the guidelines using the iOS collapsible title but it would be good not to have to switch the mode and made the current manual adjustments.

**Comment by liamdebeasi** [comment]
Hi everyone,

The team recently met to discuss this feature. If we proceed with Material Design 3 support, we would like to add it as a separate mode rather than backporting certain features to Material Design 2. We feel cherry-picking certain features would create a fragmented design system where certain MD3 features are backported to MD2 but do not quite fit with the overall theme. As a result, we have no plans to backport the large title feature from MD3 to MD2.

We have https://github.com/ionic-team/ionic-framework/issues/24282 which tracks broader Material Design 3 support. If we proceed with Material Design 3 support in Ionic we would like to have feature parity with the specification. This will include some kind of top app bar behavior as detailed in https://m3.material.io/components/top-app-bar.

Please follow https://github.com/ionic-team/ionic-framework/issues/24282 for updates on Material Design 3 support. I am going to close this, but let me know if there are any questions. Thanks!
