### ISSUE TITLE
bug: ion-slides doesn't work properly if it comes from another page

### ISSUE THREAD

**Issue by oricosta8** [ionic-team/ionic-framework#25164]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [x] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

I have a ion-slider for a TikTok clone i'm trying to recreate with ionic and when I change between pages, the ion-slider doesn't work properly and doesn't let me drag or change of slide. But if i refresh the page with F5 i works fine unless that duplicates the events like ionSlideTap and i got 2 inputs 

### Expected Behavior

The expected behavior is to work like when i refresh the page that i can navigate well and access to all the slides

### Steps to Reproduce

I made a video to show you how it works, you can't replicate this because the project is in local databasa and also has api responses from a laravel project

Video: https://youtu.be/UYU6ZvCxCeA

### Code Reproduction URL

https://github.com/oricosta8/SyncTone

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\orico\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 6.0.14
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v16.14.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue!

Starting with Ionic 5.7.0, we deprecated `ion-slides` in favor of having developers install Swiper.js directly in their projects. This gives developers access to new features, an improved developer experience, and bug fixes that they did not have access to when using `ion-slides`.

Since `ion-slides` uses Swiper.js under the hood, this migration should allow the functionality of your slides to remain exactly the same.

As a result of this deprecation, we have suspended any new development on `ion-slides` with the exception of critical fixes, such as resolving security issues.

I am going to close this issue out, but we strongly encourage you to try out the latest version of Swiper.js in your project. We have found that upgrading to the latest version of Swiper.js resolved a large number of common problems that Ionic developers were running into.

Please see https://ionicframework.com/docs/api/slides for more information on this change as well as a step by step migration guide for your apps. Developers will have approximately 1 year to migrate, starting from the initial deprecation in September 2021.

I understand this may not be the immediate resolution you were hoping for, but we think this change will significantly improve the developer experience in the long run by placing control of slides back in the hands of the developers.
