### ISSUE TITLE
bug: circular, lines-sharp, and lines-sharp-small not getting --spinner-color applied in ion-loading

### ISSUE THREAD

**Issue by dexster** [ionic-team/ionic-framework#25180]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Specifying the --spinner-color has no effect on a 'circular' spinner. All other spinner shapes work as expected.

### Expected Behavior

Spinner color should respect defined custom color

### Steps to Reproduce

In an Angular 13 project add a spinner.

I am running Angular 13.3 but if the issue is due to the naming I mentioned in additional Info below then I expect this issue is not framework specific 

```
const loader = await this.loadingController.create({
          spinner: 'circular',
          cssClass: 'my-spinner'
        });

```
```
// CSS
.my-spinner {
  --spinner-color: red;
}
```

### Ionic Info

Ionic:

   Ionic CLI : 6.18.2

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.14.0
   npm    : 8.3.1
   OS     : macOS Monterey

### Additional Information

Should this line not  be named 'circular' instead of 'circle'?

https://github.com/ionic-team/ionic-framework/blob/a6a772a38d15419ad4a60b6afeb66d91f6736934/core/src/components/spinner/spinner.scss#L122

**Comment by dexster** [comment]
https://stackblitz.com/edit/angular-ivy-etyain?file=src%2Fapp%2Fapp.component.html

**Comment by sean-perkins** [comment]
@dexster the SVG contents for that specific variation uses `fill: currentColor;`.

If you update your example to:

```css
ion-spinner {
  color: red;
}
```

The appropriate styles will apply. Can you confirm the same on your end?

**Comment by dexster** [comment]
@sean-perkins I am using --color currently which is working. Would the resolution then be to update the ion-loading docs for this specific use case or will you be looking at getting this to use --spinner-color?

**Comment by liamdebeasi** [comment]
There are a couple of issues here:

1. Your `--spinner-color` variable targets `ion-spinner`. 
`--spinner-color` is a CSS Variable on `ion-loading`, not `ion-spinner`. Your selector should be `ion-loading` instead.

2.  The circular style never gets `color` set when used inside of `ion-loading`.
See https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/loading/loading.scss#L70-L77. We probably need to add `.spinner-circular` here.

The circular style was added in https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/loading/loading.scss#L70-L77, but the author never updated `ion-loading` to take advantage of this. 

It also looks like the `lines-sharp` and `lines-sharp-small` spinners are affected by this. We should probably just change the selector to `ion-spinner` instead of selecting every single variant of the spinner.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
6.1.5-dev.11652120974.1cbc4603
```

This dev build applies to all of the Ionic packages (@ionic/angular, @ionic/core, etc)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25261, and a fix will be available in an upcoming release of Ionic Framework.

Please feel free to continue testing, and let me know if you run into any issues.
