### ISSUE TITLE
feat: support setting ion-select interfaceOptions="{ subHeader: 'xyz' }" via ion-label

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/ionic-framework#25252]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Currently, `ion-select` will automatically 'slurp' the value of `ion-label` from its shared parent `ion-item` component. This works great when labels are short and sweet, but... not so great when more detail is required, e.g, when there are any kind of associated descriptions styled into the ion-item / ion-label.

It would be immensely convenient to be able to follow a convention to set the `subHeader` of the `ion-select` using some kind of CSS class, like "ion-select-sub-header". This would prevent needing to specify `interfaceOptions` on every `ion-select` that needs a description:

![image](https://user-images.githubusercontent.com/362329/167227550-759df966-6fc7-45c3-a580-8f30b786fe24.png)

![image](https://user-images.githubusercontent.com/362329/167227539-720b182c-42ec-4f4f-b75c-0e4108d3ce85.png)

And the ideal state:

![image](https://user-images.githubusercontent.com/362329/167227874-e5f6ed2c-53dc-4491-aa84-d4551370ef90.png)

### Describe the Use Case

This would reduce duplication of code / text when creating inputs with descriptions.

### Describe Preferred Solution

provide a CSS class "shortcode" to allow specifying individual values to be pulled into the `ion-select` interface options.

e.g:
```
   <ion-label class=ion-text-wrap>
                Group cards by
                <p class=ion-select-sub-header>
                  Choose how cards in decks are grouped.
                </p>
              </ion-label>
```

### Describe Alternatives

ignore block-level content or nested elements when pulling the value out of <ion-label>, or duplicate the HTML DOM for those elements

### Related Code

```
            <ion-item>

              <ion-label class=ion-text-wrap>
                Group cards by
                <p class=ion-select-sub-header>
                  Choose how cards in decks are grouped.
                </p>
              </ion-label>

              <ion-select ... [interfaceOptions]="{ header: 'Group cards by', subHeader: 'Choose how cards in decks are grouped.
' }">
                <ion-select-option *ngFor="let mode of groupByModes" [value]="mode">
                  {{mode | uppercase}}
                </ion-select-option>
              </ion-select>

            </ion-item>
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you help me understand why using `subHeader` in `interfaceOptions` is not ideal here? In general, we try to avoid duplicating functionality.

**Comment by liamdebeasi** [comment]
Thanks for the additional information, and apologies for the delay in response.

I discussed this with the team, and this is not a feature we are looking to add to Ionic at this time. We are looking to decouple `ion-label` and `ion-item` from form components such as `ion-select` in order to make these form components easier to work with. When we do that, we could explore adding properties directly on `ion-select` for `header`, `message`, `subHeader`, etc in order to alleviate this pain point. However, this means that any features we add right now regarding `subHeader` would be undone once we decouple these form components. We do not have a timeline for this decoupling, but it is high on our priority list.

As a workaround, you could try creating a custom Angular directive that automatically sets `subHeader` in `interfaceOptions`. You could create a special class like `.custom-sub-header-label` and have the directive look for that class.
