### ISSUE TITLE
feat: add `didPresent` and `willPresent` methods for `ion-modal`

### ISSUE THREAD

**Issue by rhenriquez28** [ionic-team/ionic-framework#25250]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The feature will allow users to know if the modal they have will begin being presented or is already present, similar to how `onDidDismiss` and `onWillDismiss` work.

### Describe the Use Case

I have a sheet modal that I want to access via `ModalController.getTop()`. With this model ref, I want to access the `setCurrentBreakpoint` method and modify the current breakpoint of the modal. However, when I call it, nothing happens but there's no error, exception, or warning being thrown either. 

After some experimentation, I realized that I couldn't use `setCurrentBreakpoint` until the modal is fully presented. However, I don't have anything other than the `present` method to let me know if the modal is already present or not. In this instance, I've already called `present` in a service and I only want to know if the modal is already present, without calling `present` in the modal component, so that I can change the breakpoint depending on what's happening in the component.

### Describe Preferred Solution

The solution I would prefer would be something along the lines of `onDidDismiss` and `onWillDismiss`. Just a good old Promise that resolves when the condition is true.

Example:

`const modal = await modalController.getTop()`
`await modal.didPresent()`
`await modal.setCurrentBreakpoint(1)`

**Comment by sean-perkins** [comment]
@rhenriquez28 when opening the modal, is there any reason you are not setting `initialBreakpoint` instead of trying to call `setCurrentBreakpoint`? This would be a better UX, as the modal would animate to your desired breakpoint when it is presented, instead of waiting until the transition is completed, and then re-animating to the desired breakpoint.

**Comment by rhenriquez28** [comment]
Hi @sean-perkins , actually, I am setting `initialBreakpoint` when creating the modal on the service. That isn't actually the issue. The issue is that when the modal is presented and the modal component is created, it makes a call to the backend. If the backend call fails, I need to modify the current breakpoint to present the error message better within the modal.

However, since I don't know whether the backend call will fail before or after the modal is fully presented (let's say that at the very moment the modal opens the user loses its internet or something), then `setCurrentBreakpoint` will do nothing and the error message will look quite ugly without the user swiping the modal to see it properly.

**Comment by sean-perkins** [comment]
In the interim, I would recommend awaiting `modal.present()` as that will let you know when the modal is presented and the transition is complete, so you can change the breakpoint value.

Stackblitz example: https://stackblitz.com/edit/angular-ddvtv4?file=src%2Fapp%2Fapp.component.ts

Alternatively, you could add an event listener to the modal to attach to the emitted events.

Stackblitz example:https://stackblitz.com/edit/angular-ddvtv4?file=src%2Fapp%2Fapp.component.ts

You will notice in both examples, the transition is jumpy, as the animation curve is from `0` to the initial breakpoint, and then the initial breakpoint to the new value. 

For exposing methods for `didPresent`/`willPresent`, I do not know the history as to why only dismiss events were exposed as functions. I will need to ask Liam next week, but I do see the benefits of having that API be consistent and available. I will classify this as a feature request, pending any reasoning he provides 👍

**Comment by rhenriquez28** [comment]
Thanks! Yeah, I'm actually doing a mix of both right now. After `modal.present` I emit a value via a Subject that the component subscribes to and that way the component can know whether it can use `setCurrentBreakpoint` or not. However, adding an event listener seems a much better way to solve the problem.

It did seem strange to me that they weren't exposed as functions as well, but since I noticed that the events existed in the stencil component already, I figured I would just let you know of this edge case and suggest a solution. 

Thanks for the help @sean-perkins ! I'll be looking forward to seeing the reasonings and what comes out of this :)

**Comment by sean-perkins** [comment]
@rhenriquez28 follow-up after discussing with Liam. 

Both the `willDismiss` and `didDismiss` method were introduced to the public API so that developers could easily access the `data` and `role` values returned from the overlay. 

With `willPresent` and `didPresent`, these events do not return information back to the developer that isn't already accessible from awaiting the calling function.

For example:
```ts
async function presentModal() {
  const modal = this.modalCtrl.create(...);
  // modal.willPresent 
  await modal.present();
  // modal.didPresent
}
```

Since you can create a modal and present it separately, the subject approach is likely the ideal implementation pattern for Angular applications. 

```ts
@Injectable() 
export class MyService {

  doThing$ = new Subject<void>();

  constructor(private modalCtrl: ModalController) {}

  async presentModal() {
    const modal = await this.modalCtrl.create(...);
    await modal.present();
    this.doThing$.next();
  }

}
```

After listing these examples, it feels like this is a documentation issue. The benefits of introducing `didPresent`/`willPresent` methods, dilutes the reasoning of the original `didDismiss`/`willDismiss` and also doesn't provide extra value/context that isn't already available (through slightly different usage patterns).

Do you have any feedback on benefits of those methods would provide that aren't easily covered with these alternatives? If not, I'd be happy to document some of these patterns.
