### ISSUE TITLE
bug: ion-img is leaking event listeners..

### ISSUE THREAD

**Issue by LifeIsStrange** [ionic-team/ionic-framework#25283]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

It looks like ion-img is leaking event listeners, which keeps growing. This affects memory, energy, and performance.
https://github.com/ionic-team/ionic-framework/issues/19242#issuecomment-556182556
this issue was explained inside an apparently unrelated issue. A proper issue was never been made, and therefore this issue has been ignored over the years.

### Expected Behavior

No event listener leaking.
ion-img is critical for performance so this should be prioritarized, especially since the original author has already made an investigation for the cause
@lincolnthree
@liamdebeasi friendly pings

### Steps to Reproduce

https://github.com/ionic-team/ionic-framework/issues/19242#issuecomment-556182556
It was reproduced recently.

### Ionic Info

.

**Comment by LifeIsStrange** [comment]
It was reproduced by @ramikhafagi96 in 2021
https://github.com/ionic-team/ionic-framework/issues/19242#issuecomment-820337642
I have not faced this issue personally, I don't have a reproducer and few available time right now.
So feel free to redeprioritize this issue

**Comment by liamdebeasi** [comment]
It's going to be hard to fix the issue unless we can reproduce it first. If anyone has a GitHub repo that reproduces the issue, feel free to post it here.

**Comment by lincolnthree** [comment]
@LifeIsStrange I'd recommend putting together a new example/reproduction of this issue. As Liam said, I think this will be difficult to trace without it. I haven't used `<ion-img>` since my initial comment because it was so fundamentally broken at that point.

I do not know if it is still broken. Based on the code in stencil, it does not look like it would have been resolved.

**Comment by ramikhafagi96** [comment]
@lincolnthree @LifeIsStrange I wrote an article about [solving memory leaks in Ionic/Angular applications](https://engineering.cartona.com/solving-memory-leaks-issues-in-ionic-angular/) and I explained in a separate section exactly the issue in `ion-img` attribute and how I solved it, you can check it out and I will try to create a sample project to reproduce the issue and share it with you

**Comment by LifeIsStrange** [comment]
Excellent blog!

> ion-img component implemented by Ionic didn't clean up its IntersectionObserver references properly. If you checkout the code for the [implementation](https://github.com/ionic-team/ionic-framework/blob/master/core/src/components/img/img.tsx), you will find that the IntersectionObserver doesn't get disconnected on the component destroy.

So I guess that is the concrete issue Ionic should fix.

**Comment by liamdebeasi** [comment]
As I mentioned in https://github.com/ionic-team/ionic-framework/issues/25283#issuecomment-1125292454, I still need a GitHub repo that I can use to verify this behavior.

Once the image source loads, we automatically disconnect the IntersectionObserver and free it up for garbage collecton: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/img/img.tsx#L78

In the event that the image source never loads and the `ion-img` is destroyed, the IntersectionObserver should be destroyed too: https://w3c.github.io/IntersectionObserver/#lifetime

> An [IntersectionObserver](https://w3c.github.io/IntersectionObserver/#intersectionobserver) will remain alive until both of these conditions hold:
> - There are no scripting references to the observer.
> - The observer is not observing any targets.

The scripting reference to the observer exists in the `ion-img` component itself. So if `ion-img` is garbage collected, the reference to the observer is gone.

It sounds like there are scenarios where the `ion-img` element is not being garbage collected. It could be that since the IntersectionObserver reference is inside of `ion-img`, the `ion-img` element is unable to be garbage collected. However, I am unable to reproduce that on my end so having a reproduction would be very helpful here.
