### ISSUE TITLE
bug: ensure that default month shown is always in bounds

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic-framework#25320]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Datetime, if no explicit value provided, always pre-select the current date which, in some use cases, leads to the behavior as described here https://github.com/ionic-team/ionic-framework/issues/25296

### Describe the Use Case

See https://github.com/ionic-team/ionic-framework/issues/25296

### Describe Preferred Solution

Allow to out out and avoid the datetime to preselect any day in the calendar grid, when no explicit value is provided.

### Describe Alternatives

None

### Related Code

See https://github.com/ionic-team/ionic-framework/issues/25296

### Additional Information

See https://github.com/ionic-team/ionic-framework/issues/25296

**Comment by liamdebeasi** [comment]
Thanks for the issue. If we updated `ion-datetime` such that the pre-selected date was guaranteed to always be within bounds, would that be an acceptable solution for your use case?

**Comment by ryaa** [comment]
> Thanks for the issue. If we updated `ion-datetime` such that the pre-selected date was guaranteed to always be within bounds, would that be an acceptable solution for your use case?

yes. can you please also make sure that the time picker is pre-populated taking into consideration the min value (both in the time picker itself and in its popover)?
This should prevent empty and confusion time picker and show valid and correct values there.

Thank you

**Comment by liamdebeasi** [comment]
The team met regarding this issue. Here is our current plan for addressing:

**When no `value` is set:**
- The datetime will render the calendar on an in-bound month and will never start the user out of bounds.
- It will use the following algorithm to determine which month to render:
1. If the minimum month > today’s month, show the minimum month.
2. If the maximum month < today’s month, show the maximum month.
3. Otherwise, show today’s month.


- The time picker will show all possible values until you select a date at which point it will only show the times that are in bounds according to the date you selected.

**When a `value` Is set:**
- The datetime will add a console.warn informing the developer that the current value is out of bounds.
- The datetime will render the calendar on a current in-bound month. It will use the above algorithm to determine which month to render.

----

In neither case will the datetime modify the `value` set.

**Comment by ryaa** [comment]
> The team met regarding this issue. Here is our current plan for addressing:
> 
> **When no `value` is set:**
> 
> * The datetime will render the calendar on an in-bound month and will never start the user out of bounds.
> * It will use the following algorithm to determine which month to render:
> 
> 1. If the minimum month > today’s month, show the minimum month.
> 2. If the maximum month < today’s month, show the maximum month.
> 3. Otherwise, show today’s month.

What will be the pre-selected date on the calendar in each of the above cases? Specifically, for the case 3 (the min and today months are the same) and the min date is greater then today

> * The time picker will show all possible values until you select a date at which point it will only show the times that are in bounds according to the date you selected.

What if the pre-selected date will be in the disabled (out of bounds) date?

> **When a `value` Is set:**
> 
> * The datetime will add a console.warn informing the developer that the current value is out of bounds.
> * The datetime will render the calendar on a current in-bound month. It will use the above algorithm to determine which month to render.
> 
> In neither case will the datetime modify the `value` set.

**Comment by liamdebeasi** [comment]
> What will be the pre-selected date on the calendar in each of the above cases? Specifically, for the case 3 (the min and today months are the same) and the min date is greater then today

As of Ionic 6.1.3 we no longer pre-select a date (The selected date is the one with the filled circle. The outlined circle indicates today's date). See https://github.com/ionic-team/ionic-framework/commit/98969395abd400cc44d2d3825581a63eb64a56e0. Instead, we focus on which month to start the date picker on. (Note: I had previously referenced "pre-selected dates" in our other threads, but I got my terminology mixed up.)

So if the min date is greater than today, the datetime would still default to showing the current month. However, no date would be pre-selected due to the changes in v6.1.3.

> What if the pre-selected date will be in the disabled (out of bounds) date? 

As a result of these changes, the initial month shown would always be in bounds. This assumes correct usage of datetime. For example, setting a max that is less than the min date could show an out of bounds month. However, that is not considered correct usage.

**Comment by sean-perkins** [comment]
Hello @ryaa would you like to test with this dev-build: `6.1.7-dev.11653495960.1767ad49` and let me know if the behavior is improved? 

This covers the behavior change of rendering a month within the min/max range, when no value is set initially (following the rules Liam defined above). 

Thanks!

**Comment by ryaa** [comment]
> Hello @ryaa would you like to test with this dev-build: 6.1.7-dev.11653495960.1767ad49 and let me know if the behavior is improved?

@sean-perkins I tested with the dev build you mentioned above and everything seems to be working fine. Even though the time picker is enabled but its popover shows the values (it is not empty) and no error logged in the console when any selection is made - see below
![Screen Shot 2022-05-26 at 12 25 37](https://user-images.githubusercontent.com/3608222/170459959-b1ec9fb7-3a42-44b8-a1ee-f579d902f7e5.png)

Thank you very much for the quick turnaround on this

**Comment by sean-perkins** [comment]
@ryaa once the PR is reviewed and approved by the team, it will be available the following Tuesday/Wednesday (and as part of the nightly builds). I would estimate the team will have capacity to review within the week, so aiming for next week's release.
