### ISSUE TITLE
bug: previous tab button remains in active state when using android back button

### ISSUE THREAD

**Issue by milanharia** [ionic-team/ionic-framework#25359]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When you use the android back button to go back to the previous tab, you are correctly routed to the previous tab but the tab bar shows both the previous tab and current tab as active. From my limited testing, this only seems to happen on some devices, not all.

### Expected Behavior

The previous tab button should go back to the inactive state.

### Steps to Reproduce

Use the tabs starting template app. From one tab navigate to a new tab, press the android back button to go back to the first tab. Both tabs will appear in the 'active' state.

https://user-images.githubusercontent.com/76167627/170528418-91c05cfa-ab2a-4660-8afa-6795f8124144.mp4

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.1.7

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.14.2 (/usr/local/bin/node)
   npm    : 8.7.0
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the issue. I cannot reproduce this. What device are you testing on?

Here is what the behavior I see on Android 12 on a Pixel 4a.

https://user-images.githubusercontent.com/2721089/170564399-cb8793f8-a3b9-4e98-a977-a143a283c422.mp4

**Comment by milanharia** [comment]
Thank you for your response. The device it did not work on was a Samsung Galaxy S10e. We also tested it on the following devices and it works fine:

- OnePlus 7 Pro (Android 11)
- Pixel 2 (Android 11)
- Pixel 4a (Android 12)

**Comment by liamdebeasi** [comment]
What version of the Android webview is your Samsung Galaxy S10e running? You can find this by logging `window.navigator.userAgent` when debugging the app in Chrome Dev Tools.

**Comment by milanharia** [comment]
'Mozilla/5.0 (Linux; Android 12; SM-G970F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/101.0.4951.61 Mobile Safari/537.36'

**Comment by liamdebeasi** [comment]
Are there any errors in the console when you reproduce the issue on your end?

**Comment by milanharia** [comment]
Something really strange - this issue does not occur when running the dev tools but the tabs are flashing (nothing in the console).

https://user-images.githubusercontent.com/76167627/170720975-0f38327e-94ac-4dc0-bc7a-225b0ce40e38.mp4

**Comment by liamdebeasi** [comment]
Thanks! Is there any additional information that can help me reproduce this behavior? Unfortunately, I will not be able to fix the issue if I cannot first reproduce it.

If you enable the navigation bar on the Galaxy S10 and press the virtual back button (instead of the swipe), does that reproduce the issue too? You should be able to enable it in Settings > Display > Navigation Bar.

**Comment by milanharia** [comment]
This reproduces the issue as well.

https://user-images.githubusercontent.com/76167627/171512482-26014aea-d67b-481c-b1aa-72883ae204ec.mp4

**Comment by liamdebeasi** [comment]
Thanks! Are you able to see if the `<ion-tab-button>` elements for both Tab 1 and Tab 2 have the 'tab-selected' class applied when you reproduce the issue?

**Comment by liamdebeasi** [comment]
Thanks for the additional info. Since the `tab-selected` class is only applied to the current tab, yet multiple tabs remain  activated, it is likely that this is a rendering issue in the Chromium webview.

It sounds like this is specific to the Samsung Galaxy S10 phones. (I tried on a Galaxy S6 and could not reproduce the issue there either). I am going to see if one of my colleagues has an S10 that we can test this with.

**Comment by amandaejohnston** [comment]
Thanks for the issue! Apologies for the delay in responding. After investigation, I have found that the root problem here is the `any-hover: hover` CSS media query.

The duplicate active styling you're seeing after hitting the back button is actually the tab button's hover styling: https://github.com/ionic-team/ionic-framework/blob/86b7000bcd1b4519e8c20907050e15ba7c99bab0/core/src/components/tab-button/tab-button.scss#L101-L105 The hover state is activated when tapping the tab button initially, and then doesn't go away when using the hardware back button. This results in one active button and one hovered button, both using the same color. In theory, the `@media (any-hover: hover)` line should filter out mobile devices that can't hover, but this isn't the case for some Android devices due to an issue with Chromium.

A workaround would be to disable the hover styling via CSS:
```
ion-tab-button::part(native):hover {
  color: inherit;
}
```

I'm going to merge this issue with https://github.com/ionic-team/ionic-framework/issues/18570, as the two have the same root cause. I will be following up there after I've done some further digging on possible workarounds we can use on the Ionic side. Thanks again for the report!
