### ISSUE TITLE
bug: Ionic does not work with CDNs when used with SSR (sveltekit)

### ISSUE THREAD

**Issue by MarianDabrowski** [ionic-team/ionic-framework#25398]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The styles of ion-components (ion-button) do not apply after page refresh, and the components doe not work.
<img width="1607" alt="image" src="https://user-images.githubusercontent.com/28215295/171843120-d8c4fe50-fe17-4608-9a0f-92530d2582f6.png">

### Expected Behavior

The styles of ionic components shall apply after refresh, I would expect the component to work as expected.

### Steps to Reproduce

Please clone the repo [repo](https://github.com/MarianDabrowski/sveltekit-ionic-app)

`npm install`

`npm run dev`

Try refreshing the page to see the behaviour.

### Code Reproduction URL

https://github.com/MarianDabrowski/sveltekit-ionic-app

### Ionic Info

[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 6.19.0

Utility:

   cordova-res : 0.15.4
   native-run  : not installed globally

System:

   NodeJS : v17.8.0
   npm    : 8.5.5
   OS     : macOS Monterey

### Additional Information

The issue may be similar to #25100  
but here I try to use ionic from CDN, so therefore the difference.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This does appear to be related to https://github.com/ionic-team/ionic-framework/issues/25100, so I am going to merge the two.

Both Ionic React and Ionic Core (CDN) have the same base code that is responsible for applying styles which is why they are likely related. Please follow #25100 for updates. Thanks!

I also noticed that if you refresh a few times, sometimes the styles are applied correctly. There could be a race condition here too.
