### ISSUE TITLE
bug: rtl, datetime next/prev icons are in the wrong order

### ISSUE THREAD

**Issue by HamzaAdam** [ionic-team/ionic-framework#25427]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

<img width="292" alt="Screenshot 2022-06-08 at 4 18 50 PM" src="https://user-images.githubusercontent.com/17048792/172603838-836a1e2d-6b5c-45cd-9994-980c53c2f0a0.png">

### Expected Behavior

The icons in the top right corner for changing month should be in reverse order.

### Steps to Reproduce

just make whole app direction to rtl by default app direction is ltr. In HTML tag in index.html add dir attribute like that dir="rtl"

### Ionic Info

"@ionic/angular": "^6.0.0",
"@angular/core": "~13.0.0",
"@capacitor/core": "3.4",

**Comment by dviravr** [comment]
the same happens if just the `ion-datetime dir="rtl"`
![צילום מסך 2022-06-16 080513](https://user-images.githubusercontent.com/53183214/173995299-b6b40b4e-52da-47b5-853a-94008c2146bc.png)

**Comment by amandaejohnston** [comment]
Hi folks; it looks like the original issue reported here had already been fixed at some point since, but the bug mentioned in the above comment (with `dir="rtl"` placed on the `ion-datetime` directly) was still present. That has now been fixed by https://github.com/ionic-team/ionic-framework/pull/26195, and the update will be available in a future release of Ionic. Closing this out 👍
