### ISSUE TITLE
feat: ion-datetime month confirmation buttons

### ISSUE THREAD

**Issue by picheli20** [ionic-team/ionic-framework#25531]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Have a option to add a confirmation button on the `month-year` pick (when seeing as calendar, for example, `date`, `date-time`, etc.), similar to the one that we can add on the day picker (`showDefaultButtons="true"`).

### Before
![Screenshot 2022-06-24 at 10 23 43](https://user-images.githubusercontent.com/3877606/175495972-6a4f9c5e-f7e7-4d7b-ae17-411574d0ec23.png)

### After
![Screenshot 2022-06-24 at 10 32 12](https://user-images.githubusercontent.com/3877606/175496762-823c76e7-1bfc-43e7-b9c0-578bb8a16ded.png)
ps: Maybe not exactly the same texts, but this is just to show the idea.

### Describe the Use Case

While running some tests on my application, I noticed that almost all the users, when opening the month/year picker from the calendar, if it's his first time seeing the design, they really struggles to learn how to confirm the month/year selection and go back to the days.

Most of the time clicking outside of the modal or closing the picker thinking that will confirm his pick.

### Additional Information

This might be related to the #24477

**Comment by liamdebeasi** [comment]
Thanks for the issue. This was an intentional design choice. Prior to Ionic 6.1.4, the Cancel/Done buttons were displayed on `presentation="date"` when the month/year picker was opened. Those buttons were always intended to confirm selection of a date, and they were never intended to close that particular view.

However, we received feedback in https://github.com/ionic-team/ionic-framework/issues/24998 and https://github.com/ionic-team/ionic-framework/issues/24962 where this caused quite a bit of confusion because some developers thought the buttons were meant to simply close the particular view. As a result of that feedback, we made the decision to remove the Cancel/Done buttons when the month+year view is displayed.

While we can add another set of Cancel/Done buttons, I do not think that would lead to a better experience as it makes it hard to distinguish between buttons that confirm the month/year view and buttons that confirm the entire date selection.

**Comment by liamdebeasi** [comment]
On a related note, you might be interested in the new wheel picker feature we are working on: https://github.com/ionic-team/ionic-framework/issues/23981#issuecomment-1155695703

This feature will allow users to select month, day, and year from a wheel picker that includes Cancel/Done buttons. This feature should alleviate some of the confusion around how to confirm/cancel month and year selection. This has not shipped yet, but we are looking to ship this in an upcoming minor release of Ionic.
