### ISSUE TITLE
bug: ion-header and ion-footer do not render custom elements with ionic component inside with vanilla js

### ISSUE THREAD

**Issue by int0x80-sys** [ionic-team/ionic-framework#25600]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When i create a custom component using vanilla js and the web components api, if my custom component has ionic elements inside, these are not render in ion-header and ion-footer, but they are render in e.g ion-content:

![image](https://user-images.githubusercontent.com/73644770/178110795-9614fdb9-2a1d-43ef-a7ae-e7ce8a6ef716.png)

### Expected Behavior

My custom component was render with all his internal elements

### Steps to Reproduce

Create a simple html like this:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script type="module" src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"></script>
  <script nomodule src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ionic/core/css/ionic.bundle.css" />
  <script>
    class Foo extends HTMLElement {

      constructor() {
        super();
      }

      connectedCallback() {
        this.innerHTML = /*html*/`
          <form novalidate>
            <h1>H1</h1>
            <h1><ion-text color="primary">H1</ion-text></h1>
          </form>
        `;
      }
    }

    customElements.define('foo-comp', Foo);
  </script>
  <title>Document</title>
</head>
<body>
  <ion-app>
    <ion-header>
      <foo-comp></foo-comp>
    </ion-header>
    <ion-content>
      <foo-comp></foo-comp>
    </ion-content>
    <ion-footer>
      <foo-comp></foo-comp>
    </ion-footer>
  </ion-app>
</body>
</html>
```

**Comment by sean-perkins** [comment]
Hello @int0x80-sys thanks for this issue.

The problem here is with using the hydrated bundle of `@ionic/core`. With it, the components will be lazily hydrated once they are requested/defined. 

IonContent behaves slightly different here, because it waits for the web components within the scroll element to be ready.

To work around this issue, you can set the inner HTML for your custom web component into the next frame using `requestAnimationFrame`:  https://codepen.io/sean-perkins-ionic/pen/dymXRaz

You could also try using the custom elements bundle instead of the hydrated bundle. 

Can you let me know if this alleviates your problem?

**Comment by int0x80-sys** [comment]
Hi. Sorry for the late reply. I saw the answer but I forgot to close the issue. It's works for me.

Thank you so much!
