### ISSUE TITLE
bug: ion-select popover does show the selected value in the opened popover

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic-framework#25759]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The ion-select with multiple=true and compareWith function does not show the selected value in the opened popover when the selected value is string and the value to compare against is number. compareWith works correctly returning true for the selected value.
NOTE: if both, the selected value and the value to compare against are numbers, all work fine.

### Expected Behavior

The opened popover must show the selected value

### Steps to Reproduce

1) open this link https://ionic6-angular13-lfygtv.stackblitz.io
Note the selected value (text) is shown correctly
2) tap on the select control
Note that in the opened popover no value is selected - see below
<img width="381" alt="Screen Shot 2022-08-15 at 09 07 44" src="https://user-images.githubusercontent.com/3608222/184584801-4ca97443-00ae-4622-87bb-66fcdca51363.png">

### Code Reproduction URL

https://stackblitz.com/edit/ionic6-angular13-lfygtv?file=src/app/app.component.html

### Ionic Info

See https://stackblitz.com/edit/ionic6-angular13-lfygtv?file=src/app/app.component.html

### Additional Information

if both, the selected value and the value to compare against are numbers, all work fine.

**Comment by liamdebeasi** [comment]
Thanks for the issue. The problem here is we reverse the order of the parameters when checking if the checkboxes are checked or not. As a result, `val1` is the string value and `val2` is the number value. You can fix this by converting both `val1` and `val2` to a number.

-----

However, this is something we should fix. When we rendering the selected text in the `ion-select` label, we pass in the option value first and the `ion-select` value second: https://github.com/ionic-team/ionic-framework/blob/f47c5de1e621181630ebcf151e80a40cbefd5676/core/src/components/select/select.tsx#L689

When creating the alert checkboxes we do pass in the `ion-select` value first and the option value second: https://github.com/ionic-team/ionic-framework/blob/f47c5de1e621181630ebcf151e80a40cbefd5676/core/src/components/select/select.tsx#L318 (Note: even though the second variable is called `value`, it is actually the value of the option, not the value of the select component.

However, the underlying implementation for `isOptionSelected` expects the `ion-select` value first and the compare value second.

**Comment by liamdebeasi** [comment]
Here is a dev build if you are interested in giving the fix a test:

```
npm install @ionic/angular@6.2.3-dev.11660665239.14e6a993
```

Note: You may need to test this in a local Ionic application. StackBlitz has some issues with installing dev builds in non-Web Container instances.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25764, and a fix will be available in an upcoming release of Ionic Framework. Please feel free to continue testing the dev build.

Note: As a result of this change, the param order will now match what is stated on the docs: https://ionicframework.com/docs/api/select#comparewith

The first parameter will be the `ion-select` value, and the second parameter will be the value of an `ion-select-option`.
