### ISSUE TITLE
Request to re-use the ionic components for web app dashboards UI. Which have look and feel for website.

### ISSUE THREAD

**Issue by bawasaab** [ionic-team/ionic-framework#25788]
It there any plan to convert or made compatibility of ionic components to website look and feel along with ios and android.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please clarify the request? Are you looking to have Ionic components adapted for a desktop layout?

**Comment by bawasaab** [comment]
Yes am requesting to have a solution by which developer can use the same code and able to create a website which looks like web components not as ios or android components or you can extend the angular material components and made ionic as a super set of angular material components

**Comment by liamdebeasi** [comment]
Thanks for the clarification. Ionic Framework is a toolkit that primarily targets mobile/tablet layouts. Adapting all Ionic components for desktop layouts is not something we are looking to do at this time. However, we do make changes to improve the experience on desktop/larger screen layouts in areas such as keyboard and mouse, accessibility, and more.

I will say that our documentation could use some clarification on this front. We do mention desktop apps as a platform you can build for, but we should be clear in saying that Ionic is focused on mobile apps.

We are looking to introduce a new feature in the future that lets developers opt-out of the iOS or Android styling. This feature will allow developers to theme components however they would like. This may be something that is valuable for your use case. We will have more to announce on this feature in the future.

I am going to close this since the feature request is out of scope for this project, but let me know if you have any additional questions. Thanks!
