### ISSUE TITLE
bug: ionChange event not triggered if ionButtons in ion-datetime

### ISSUE THREAD

**Issue by RAPHAELSTZ** [ionic-team/ionic-framework#25793]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When using an **ion-datetime** element in a page the ion-change event does not trigger if 
ion-buttons is placed inside the **ion-datetime** element;

See stackblitz

### Expected Behavior

ionChange is supposed to trigger whenever a value changes in a dateTime element even if there are ion-buttons inside.

### Steps to Reproduce

Try to trigger ionChange on a ion-dateTime element like in stackblitz.

### Code Reproduction URL

https://stackblitz.com/edit/angular-sqweu1?file=src%2Fapp%2Fexample.component.html,src%2Fapp%2Fexample.component.ts

### Ionic Info

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v16.14.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.3.1
   OS     : Windows 10

**Comment by sean-perkins** [comment]
@RAPHAELSTZ the behavior you describe is the current expected behavior of the datetime when using `showDefaultButtons="true"` or slotting custom buttons and using the `datetime#confirm()` API to commit value changes.

This behavior is outlined here: https://ionicframework.com/docs/api/datetime#buttons.

If you desire to have the value change emitted for each selection, do not slot buttons into the datetime, but rather have them as siblings:

```html
<div class="container">
  <ion-datetime></ion-datetime>
  <!-- Your buttons -->
</div>
```

Please let me know if this resolves your issue.

**Comment by RAPHAELSTZ** [comment]
Yes perfect, it does the trick, thanks for the quick response :)

**Comment by RAPHAELSTZ** [comment]
Solved
