### ISSUE TITLE
feat: animate native/body/ionic height by keyboard height dynamically instead of setting it on event end

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/ionic-framework#26090]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

When having inputs or content stick to the footer, showing the keyboard hides this content and after the keyboard ends its animation the content comes back. 

### Describe the Use Case

This really doesn't look native and in rare cases it looks buggy when the tab navigation flickers.

> https://github.com/muuvmuuv/issue-ionic-framework-26090

<img src="https://user-images.githubusercontent.com/11534760/194891152-602114ec-1360-4fa3-87de-6d69ba1cf5cf.gif" width="350px" />

### Describe Preferred Solution

Animate the height of ionic/native/body by the keyboard in-animation. Like in this post: https://www.advancedswift.com/animate-with-ios-keyboard-swift/

Copied from above link:
![keyboard-gif](https://user-images.githubusercontent.com/11534760/194888629-aeee389c-d5d3-4af3-a7f7-1e2145ffe5c9.gif)

**Comment by muuvmuuv** [comment]
@amandaejohnston added a repl, problem video and copied the solution video from the link I shared :)

**Comment by DwieDima** [comment]
Sadly this is WebKit related and there is no performant way to get this behavior

https://github.com/ionic-team/ionic-framework/issues/22368#issuecomment-713708615

Hopefully it will be possible at some point

**Comment by muuvmuuv** [comment]
In the link I shared (sorry, I am not a Swift pro), he's demonstrating a pretty smooth behavior. Would it not be possible to animate the body in the same way, like so that it looks like window resizing on the desktop, for example?

**Comment by liamdebeasi** [comment]
Hey there,

So the main thing to note about the Swift example is that the layout in the app is not resizing when the keyboard opens. In your Ionic example, the layout resizes which is why you get the layout shifts. This is due to the Capacitor Keyboard plugin's default behavior of resizing the layout when the keyboard opens.

The closest thing to the Swift example would be to use the Capacitor Keyboard plugin config to set the "resize" mode to "none": https://capacitorjs.com/docs/apis/keyboard#configuration

This will cause the layout viewport to never resize when the keyboard opens, thus avoiding the layout shifts.

----

From there, you will need to do something similar to what is being done in this section of the Swift blog post: https://www.advancedswift.com/animate-with-ios-keyboard-swift/#animate-with-the-ios-keyboard

You will need to use a CSS `transform` to move the text input above the keyboard. Here's some pseudo code of what I mean:

```js

import { Keyboard } from '@capacitor/keyboard';

const input = document.querySelector('ion-input');

Keyboard.addListener('keyboardWillShow', info => {
  const { keyboardHeight } = info;

  input.style.setProperty(
    'transform',
    `translate3d(0, ${keyboardHeight}px, 0)`
  );
});

Keyboard.addListener('keyboardWillHide', () => {
  input.style.setProperty(
    'transform',
    `translate3d(0, ${keyboardHeight}px, 0)`
  );
});
```

Another difference to note is that the Swift example lets you translate the input with the keyboard animation. There is no way to keep these perfectly in sync in Ionic because the keyboard animation happens in "native world" and the input animation happens in "web world". However, you can use an easing curve to get the animations to be pretty close.

```css
ion-input {
  transition: transform 300ms ease-in-out;
}
```

I am using the "ease-in-out" curve, but you may want to try some other easing curves to see what works best.

-----

I recommend giving that a try as it should get you pretty close to the Swift example.

**Comment by liamdebeasi** [comment]
I also wanted to clarify what was said in https://github.com/ionic-team/ionic-framework/issues/26090#issuecomment-1274394081. This is not a WebKit bug or an "issue" with WebKit. This is a matter of working across two different layers: web and native. As a result, some configuration on the application side will be needed. You would likely run into the same issue if you disabled webview resizing in a Chromium-based Ionic app too.

**Comment by muuvmuuv** [comment]
Thanks for that detailed explanation, that really sounds logically. I will give your example a try. Hopefully, then it will look a little bit smoother :D

Is there a way to always get the right amount of transition duration on native side like a swift API to get the duration the keyboard would possibly take?

**Comment by liamdebeasi** [comment]
Capacitor does not expose this information, but I believe the animation is a spring animation (instead of a cubic bezier). Knowing the duration likely will not help since CSS does not support spring animations yet. When I've tried to do this in my own Ionic apps, I've found that a a duration of ~300ms was about right combined with a cubic bezier timing function.

**Comment by muuvmuuv** [comment]
Nice, that works pretty well. Few improvements I made are that I used that curve from here: https://gist.github.com/jondot/1317ee27bab54c482e87

And I logged the duration to console to set it to the exact value. Could that be something Keyboard can expose to me, the duration?

**Comment by muuvmuuv** [comment]
For anyone that wants a copy-paste Angular Directive:

<details>
<summary>Details</summary>

```ts
import { DOCUMENT } from '@angular/common'
import { Directive, ElementRef, Inject, OnDestroy, OnInit } from '@angular/core'
import { PluginListenerHandle } from '@capacitor/core'
import { Keyboard, KeyboardResize } from '@capacitor/keyboard'
import { Animation, AnimationController } from '@ionic/angular'

@Directive({
  selector: '[keyboardFlying]',
})
export class KeyboardFlyingDirective implements OnInit, OnDestroy {
  readonly input = this.elementReference.nativeElement

  private animation: Animation

  private keyboardWillShowListener?: PluginListenerHandle
  private keyboardWillHideListener?: PluginListenerHandle

  private resizeModeBackup?: KeyboardResize

  constructor(
    @Inject(DOCUMENT) private document: Document,
    private elementReference: ElementRef<HTMLElement>,
    private animationController: AnimationController
  ) {
    // https://gist.github.com/jondot/1317ee27bab54c482e87
    this.animation = this.animationController
      .create()
      .addElement(elementReference.nativeElement)
      .easing('cubic-bezier(.17,.54,.42,.79)')
      .duration(250)
  }

  ngOnInit(): void {
    const safeAreaTop = Number.parseInt(
      getComputedStyle(this.document.documentElement).getPropertyValue(
        '--ion-safe-area-bottom'
      ),
      10
    )

    void Keyboard.getResizeMode().then(({ mode }) => {
      this.resizeModeBackup = mode
      void Keyboard.setResizeMode({ mode: KeyboardResize.None })
    })

    void Keyboard.addListener('keyboardWillShow', ({ keyboardHeight }) => {
      const toValue = (keyboardHeight - safeAreaTop) * -1
      this.animation.keyframes([
        { offset: 1, transform: `translate3d(0, ${toValue}px, 0)` },
      ])
      void this.animation.play()
    }).then((listener) => {
      this.keyboardWillShowListener = listener
    })

    void Keyboard.addListener('keyboardWillHide', () => {
      this.animation.keyframes([{ offset: 1, transform: 'translate3d(0, 0, 0)' }])
      void this.animation.play()
    }).then((listener) => {
      this.keyboardWillHideListener = listener
    })
  }

  ngOnDestroy(): void {
    if (this.resizeModeBackup) {
      void Keyboard.setResizeMode({ mode: this.resizeModeBackup })
    }

    if (this.keyboardWillShowListener) {
      void this.keyboardWillShowListener.remove()
    }

    if (this.keyboardWillHideListener) {
      void this.keyboardWillHideListener.remove()
    }
  }
}
```

</details>

**Comment by liamdebeasi** [comment]
> And I logged the duration to console to set it to the exact value. Could that be something Keyboard can expose to me, the duration? It is used here (but 0.2 added) https://github.com/ionic-team/capacitor-plugins/blob/main/keyboard/ios/Plugin/Keyboard.m#L130

I recommend filing a feature request on https://github.com/ionic-team/capacitor-plugins. (I do not work on Capacitor, so I am not sure if this is feasible)

-----

It sounds like the original issue has been resolved with your solution in https://github.com/ionic-team/ionic-framework/issues/26090#issuecomment-1287768737, so I am going to close this. Please let me know if you have any additional questions. Thanks!
