### ISSUE TITLE
bug: White screen on IOS 14.2 with production build

### ISSUE THREAD

**Issue by dragermrb** [ionic-team/ionic-framework#26141]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Default ionic app (sidemenu template) doesn't work on IOS 14.2 with production build. Only a blank screen is displayed (only with production build config)

### Expected Behavior

Display default app (sidemenu template)

### Steps to Reproduce

```sh
ionic start ionic-test-app sidemenu --capacitor
cd ionic-test-app
ionic cap add ios
npm run build
npx cap sync -c production
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.1
   @angular-devkit/build-angular : 14.2.6
   @angular-devkit/schematics    : 14.2.6
   @angular/cli                  : 14.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.3.0
   @capacitor/android : not installed
   @capacitor/core    : 4.3.0
   @capacitor/ios     : 4.3.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v14.18.1 (/Users/mrodriguez/.nvm/versions/node/v14.18.1/bin/node)
   npm    : 8.19.2
   OS     : macOS Monterey

**Comment by sebaferreras** [comment]
I'm having a similar issue on my end too. Just like mentioned above, it only happens when using a production build running the app on a device or simulator using any version of iOS below 14.5

Not 100% sure about this, but when investigating the issue I found that the `inset` CSS property is not being applied when I see the blank page:

<img width="249" alt="Screenshot 2022-10-16 at 14 37 27" src="https://user-images.githubusercontent.com/17194770/196035749-ac9206b8-4f48-497d-b099-50f4a6f8d414.png">

And seems like in fact it's not supported in Safari (iOS) below 14.5:

https://caniuse.com/?search=inset
<img width="1452" alt="Screenshot 2022-10-16 at 14 33 42" src="https://user-images.githubusercontent.com/17194770/196035763-55cc3a81-f264-4e7a-8053-b7aabe268c03.png">

When running the app on iOS 14.5 or above it works fine but I noticed that untoggling that style produces the exact same issue. Again, maybe this is not related at all but thought about sharing it here just in case if it could help someone else when invetigating the issue.

--- 

Ionic info:

```

Ionic:

   Ionic CLI                     : 6.20.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.15
   @angular-devkit/build-angular : 13.3.9
   @angular-devkit/schematics    : 13.3.9
   @angular/cli                  : 13.3.9
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.2, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 23 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   Android SDK Tools : 26.1.1 (/Users/sebastian/Library/Android/sdk)
   ios-deploy        : 1.11.4
   ios-sim           : 8.0.2
   NodeJS            : v14.20.0 (/usr/local/Cellar/node@14/14.20.0/bin/node)
   npm               : 6.14.17
   OS                : macOS Monterey
   Xcode             : Xcode 14.0.1 Build version 14A400
```

**Comment by vc-rakesh** [comment]
I am facing the same issue. have you found any fix for this? @sebaferreras

**Comment by sebaferreras** [comment]
@dragermrb @vc-rakesh

Seems like this is a duplicate of https://github.com/ionic-team/ionic-framework/issues/25929

**Comment by dragermrb** [comment]
Updating the .browserslistrc file works fine for me on IOS 14.2

From:

```
last 2 iOS major versions
```

To:
```
last 3 iOS major versions
```

Thanks @sebaferreras !!!

**Comment by vc-rakesh** [comment]
@dragermrb That works
Thanks

**Comment by KirstenStake** [comment]
You have all saved me after 10 hours of trying to figure out why some of our users were getting a white screen in our app after migrating to Capacitor 4. Thank you!! @sebaferreras @vc-rakesh @dragermrb
