### ISSUE TITLE
bug: Chrome fires ionSlideDrag sometimes instead ionSlideTap

### ISSUE THREAD

**Issue by papagei-ma** [ionic-team/ionic-framework#26161]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When clicking on the slides, sometimes an ionSlideDrag is trigged instead of ionSlideTap.

### Expected Behavior

ionSlideTap is always triggered.

### Steps to Reproduce

1. new Project.
2. include ion-Slides. 
3. Add a normal `writeToConsole(eventType) {console.log(eventType); }` function.
4. run the function on ionSlideDrag with eventType drag, and on ionSlideTap with eventType tap.
5. open the application on chrome, and click about 10 times, and mind the printed messages. 

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.2
   @angular-devkit/build-angular : 13.3.9
   @angular-devkit/schematics    : 13.3.9
   @angular/cli                  : 13.3.9
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.1.0
   @capacitor/android : 4.1.0
   @capacitor/core    : 4.1.0
   @capacitor/ios     : 4.1.0

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.1) : 1.6.0

System:

   NodeJS : v14.18.1 (~/.nvm/versions/node/v14.18.1/bin/node)
   npm    : 6.14.15
   OS     : macOS Monterey

### Additional Information

Event If I use swiper, as ion-slides are to be deprecated, the problem is still there.

**Comment by amandaejohnston** [comment]
Thanks for the issue. The `ion-slides` component is [currently deprecated](https://ionicframework.com/docs/api/slides#how-long-do-i-have-to-migrate) and will be removed in the upcoming Ionic v7 release. If you're still seeing the problem in Swiper, we would recommend opening an issue on the Swiper repo instead: https://github.com/nolimits4web/swiper/issues

I'm going to go ahead and close this out since `ion-slides` is only receiving critical bug fixes, and if things persist in Swiper, this isn't a bug in Ionic. Thank you!

**Comment by papagei-ma** [comment]
Fair Enough. thank you @amandaejohnston
