### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by goltra** [ionic-team/ionic-framework#26229]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I have a custom css class for ion-searchbar component. I used it for all browser and ios. 
```
ion-searchbar.custom{
  --background: #4b6aa9;
  --color: #fff;
  --placeholder-color: #fff;
  --icon-color: #fff;
  --clear-button-color: #fff;
  --border-radius: 8px;
 ```
In browser it works fine  but in iOS --background property is not working.  To make it work I had to do this workarround:
```
ion-searchbar.ios.custom {
  input { 
    background: #4b6aa9 !important;
  }
}
```

### Expected Behavior

As say documentation  applying class to ion-searchbar where modify --background property, it should modify in all platforms.

### Steps to Reproduce

Only place a ion-searchbar component inside a ion-toolbar in the content section and define styles for it.
You wil see it look differnte in browser and iOS

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.4
   @angular-devkit/build-angular : 14.0.6
   @angular-devkit/schematics    : 14.0.6
   @angular/cli                  : 14.0.6
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : 6.0.0, browser, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 21 other plugins)

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.1) : 1.2.2

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you provide a reproduction of the issue? I'm not able to reproduce this on my end: https://codepen.io/liamdebeasi/pen/bGKevpB

**Comment by goltra** [comment]
I have seen problem is when is into ion-toolbar and it has set color property..  only in iOS (I only checked it in simulator)
```<ion-toolbar color="blanco">
        <ion-searchbar class="custom" placeholder="what do you want to search?"></ion-searchbar>
</ion-toolbar>````
I think it is having a wrong behavior. If I have set a background to de ion-searchbar it should prevalice over ion-toolbar color.

![image](https://user-images.githubusercontent.com/1634767/199995408-6aebb922-7b4a-431e-a48a-7655f1e5f0a6.png)

**Comment by sean-perkins** [comment]
@goltra in iOS when the searchbar is used within a toolbar, the background styles are overridden to be semi-transparent. This is to align to the human interface guidelines of iOS.

Related code: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/searchbar/searchbar.ios.scss#L183-L186

While not recommended, to override this behavior you would need to do two things:

1. In SASS, define a new opacity value for `$searchbar-ios-input-background-color-alpha` (defaults to: `.07`).
2. Use the CSS variable `--ion-color-contrast-rgb` to set the background color for iOS.

e.g.:
```css
ion-searchbar.custom {
 --ion-color-contrast-rgb: 75, 106, 169;
}
```

Note: This value **must** be an RGB value, not a HEX.

Possible other alternatives:
1. Set the `mode` on `ion-toolbar`.

e.g.:
```css
<ion-toolbar mode="md">
  <ion-searchbar class="custom"></ion-searchbar>
</ion-toolbar>
```

2. Use a `div` with custom styling instead of `ion-toolbar`.


Can you try any of these suggestions and let me know if that resolves your issue?

**Comment by goltra** [comment]
@sean-perkins thanks for your teach me more and thanks for your solution. I have set mode to md and work like a charm...
