### ISSUE TITLE
bug(modal): ionBreakpointDidChange event won't trigger for react and vue

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#26272]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

`ionBreakpointDidChange ` won't fire for react and vue. For Angular it is working as expected.

### Expected Behavior

`ionBreakpointDidChange ` should fire for react and vue

### Steps to Reproduce

Vue
https://stackblitz.com/edit/angular-ezxupn?file=src/components/Example.vue

React
https://stackblitz.com/edit/angular-2ncajc?file=src/main.tsx

Angular
https://stackblitz.com/edit/angular-hyv5vk?file=src/app/example.component.ts

### Ionic Info

using latest version: `6.3.6`

### Additional Information

related to posted issue on forum

https://forum.ionicframework.com/t/ionbreakpointdidchange-not-firing-event/226446/1

**Comment by liamdebeasi** [comment]
Thanks for the report. Events in Vue are emitted as kebab case instead of camel case, so it would be `ion-breakpoint-did-change` instead of `ionBreakpointDidChange`. This was done to align with https://vuejs.org/guide/essentials/component-basics.html#case-insensitivity.

For the React example, `modal.current` is `null` when you try to set the event listener so no event listener is added: `modal?.current?.addEventListener`. `modal.current` is `null` because you never assign the ref anywhere.

**Comment by DwieDima** [comment]
@liamdebeasi thank you for clarification!

**Comment by liamdebeasi** [comment]
You are welcome. I am going to close this, but let me know if you have any additional questions.
