### ISSUE TITLE
bug: React lifecycle hooks fired twice

### ISSUE THREAD

**Issue by gianlucamozzillo** [ionic-team/ionic-framework#26359]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Lifecycle events are fired twice. This happens with all the hooks.

### Expected Behavior

Lifecycle events should be fired properly when needed. For example `useIonViewDidEnter` 

### Steps to Reproduce

1. Initialise a new Ionic Project with React and the tab-based template
2. Add the ionViewDidEnter hook to the Tab1.tsx: 
`const Tab1: React.FC = () => {
  useIonViewDidEnter(() => {
    console.log('ionViewDidEnter event fired');
  })
...
`
3. Run `ionic serve`
4. You'll find the log twice in the console

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.4 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.3.8

Capacitor:

   Capacitor CLI      : 4.3.0
   @capacitor/android : not installed
   @capacitor/core    : 4.3.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v18.11.0 (/opt/homebrew/Cellar/node/18.11.0/bin/node)
   npm    : 8.19.2
   OS     : macOS

**Comment by sean-perkins** [comment]
@gianlucamozzillo this behavior is due to React Strict Mode. This does not apply in a production build.

React runs effects twice (the lifecycle hooks use `useEffect`) when strict mode is enabled in dev builds to detect side effects. 

Additional resources: https://stackoverflow.com/questions/61254372/my-react-component-is-rendering-twice-because-of-strict-mode/61897567#61897567

If you do not want this behavior in dev builds, you could remove/disable strict mode.
