### ISSUE TITLE
feat(radio): update style for ios spec

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#26400]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The UI of IOS radio has been changed in version 16 (see ringtones):

![IMG_BA4670D07CDA-1](https://user-images.githubusercontent.com/26873275/205269995-d073cbdb-edba-480a-9899-3e7022034ce9.jpeg)

Current Ionic radio:

![image](https://user-images.githubusercontent.com/26873275/205270068-248e6b83-8a8e-4a1c-8466-9834330d34d1.png)

### Describe the Use Case

To match latest IOS 16 radio styles

### Describe Preferred Solution

- new icon
- larger icon
- thicker icon

**Comment by liamdebeasi** [comment]
Thanks for the feature request. The team has opted to improve the consistency of our checkmark indicators in Ionic instead of trying to do a pixel-for-pixel match of native iOS. We also considered using an Ionicon instead, but even that design does not perfectly match the native iOS checkmark. In an upcoming major release of Ionic we will be aligning the checkmarks in both radio and checkbox to have a more consistent appearance: https://github.com/ionic-team/ionic-framework/pull/28729/files#diff-304fe1936261a3302297cc1c6ed6cd295517a8a95bfb0532a3884cdf7d1e2099
