### ISSUE TITLE
bug: <ion-modal> does not overlay correctly with nested dialogs that are smaller than the first one

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/ionic-framework#26481]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

If you open multiple instance of `<ion-modal>` on top of each other then the backdrop will not be properly applied for the second dialog.

If the second dialog is smaller then the will not render correctly.

For example:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/2199401/207464139-b101fcca-230f-4e1e-a1df-a6a0f8a0a6f1.png">

### Expected Behavior

It should be possible to display a modal dialog from another modal dialog.

### Steps to Reproduce

1. display a modal dialog
2. click on a button within the dialog to display a nested dialog
3. set the width for the second dialog to be smaller than the first dialog
4. overlay will show both dialogs at once

### Ionic Info

Ionic:

   Ionic CLI : 6.18.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.12.1
   npm    : 8.19.2
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the report. This is an intentional behavior designed to prevent backdrops and box shadows from stacking. For example, if you have multiple modals of the same size then the box shadow/backdrop will appear to progressively get darker until the background is completely black with no opacity.

Typically we recommend using a popover for the reported use case as it is a smaller overlay that can appear anywhere on your page: https://ionicframework.com/docs/api/popover

However, if you would like to continue using this nested `ion-modal` you can customize Ionic's default behavior by setting the `--backdrop-opacity` and `--box-shadow` CSS variables. Something like the following show would:

```css
ion-modal {
  --backdrop-opacity: 0.32;
  --box-shadow: 0 28px 48px rgba(0, 0, 0, 0.4);
}
```
