### ISSUE TITLE
feat: ion-datetime, allow close parent modal on click 

### ISSUE THREAD

**Issue by alon42** [ionic-team/ionic-framework#26531]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

when `ion-datetime` is in popover/modal, and date/date-time grif, I want to be able to close it when the user clicks on a specific date.
instead of clicking the date, and then clicking "Done".

For this to happen, I want to add "close-pop-on-click" property. (default `false`, for backward compatibility)
when set to true, I suggest the next behavior:
1. when clicking (not scrolling) on wheels, it will trigger `ion-wheel-clicked` event (exposed to component)
1.1. when in date-time/date configuration, the internal wheel state, will close itself and will return to the grid
1.2  when in wheel style only configuration it will trigger the close of the parent modal/popover through the `closeParentOverlay()` method.

2. when in grid style state, we will expose the event `ion-grid-clicked` for the programmer 
2.1 when clicking on the grid and `close-pop-on-click` is `true` it will trigger closing the parent modal/popover through the `closeParentOverlay()` method.

### Describe the Use Case

I am building an app where the datetime is opened in a popover, and I want to minimize the number of clicks the user need for interacting with the `ion-datetime` modal.

currently in order to select a date in another month:
1. click on `ion-datetime-button`
2. click on the year-month button in the top left
3. scroll to find the current year month
4. click on the year-month button again to close it (and there is no good UI hint for that)
5. click on the desired day
6. click on done

I want it to be:
1. click on `ion-datetime-button`
2. click on the year-month button in the top left
3. scroll to find the current year month
4. click **anywhere** on the year-month wheel to close it
5. click on the desired day

when opening time in the `date-time` grid, it is even more needed, because the user needs to understand to click outside of the wheel component, and clicking inside of it, makes more sense.

### Describe Alternatives

for a workaround, you can close the modal when date value changes, by the next code:
```
onValueChanged(){
 ...
 if (!ionDateTimeElement.classLists.contains("month-year-picker-open")) {
    mofdalElement.dismiss();
}
}
```

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you help me understand the problem you are trying to solve? I understand you want to minimize the number of clicks, but is there a particular reason for wanting to do this?

My concern with adding this behavior is it has the potential to degrade the user experience for people who accidentally select a date. When a datetime is displayed inline, users who accidentally select a date can quickly select a new one. With this proposed pattern, the user would have to re-open the overlay in order to correct their mistake.

**Comment by alon42** [comment]
Thank you for taking the time responding in this deatils.

I totaly see and understant your concern, and it's important to NOT change the current component behaviour.

But I think that we can agree that reducing the amount of clicks of interacting with the datepicker is desirable (if the developer wants to).

I'm building an app, and I want the user to interact with it as fast as they can and any redundant click is wastefull. so In my scenario, the UX will allow mistakes to happen here and there, and this is desirable because the user going to interact a lot with the `ion-datetime` so a mistake here and there will be learned and corrected whortly.
I'm sure that I'm not the only one who prefer to have smoother interaction with the component. 

Back to your concern, if the default interaction will remain the same, and only if the developer will set a parameter to `true` it will change the behaviour, it will give other developers more freedom to use the component based on their own need, while not changing anything to anyone who uses it now.

Currently I am looking for a replacement for the `ion-datetime` becasue of this lack of flexability by the component, and I prefer to donate this time to the community and add the missing features to the component instead of integrating a new one.

**Comment by liamdebeasi** [comment]
Thanks for the additional information. As I mentioned in my previous post, you can already get this behavior today using the `ionChange` event, so I do not think it makes sense to re-implement this internally.

Here is an example: https://codepen.io/liamdebeasi/pen/jOpyoZq

**Comment by ReneZeidler** [comment]
I've encountered the same issue as described here. The way that the current date-picker works seems unintuitive and doesn't match the implementation of the default date-picker included in Chrome, Edge and Firefox.  
On all of those browsers, the included date-picker (of a `<input type="date">` element) is closed automatically when clicking on a specific day. Other mouse interactions, i.e. switching months, don't close the date-picker.

I'm unable to get the same behavior to work with `ion-datetime`. The codepen by @liamdebeasi closes the modal when clicking on a date, but it also closes the modal when switching the month/year using the month-year-picker in the top left of the modal, which is not a desired behavior. The previous/next month arrows don't have this problem, because they don't automatically select a new date when switching months. (This is also inconsistent behavior - the browser date pickers always automatically select a new date when switching months using any method, for what it's worth.)

A very hacky workaround I'm using now is comparing the previous value of the date input to the new value, and only dismissing the modal if the day has changed (not the month or the year). This kinda works, but it has several issues (doesn't close the modal when clicking on the same day as already selected, *does* close the modal when switching from the 31st of one month to a 30-day month without clicking on a day).  
It also relies on knowing the previous value, which ionChange doesn't provide. I'm accessing the previous value using Angular's `valueChanges.pipe(pairwise())` of a reactive form, which also doesn't always work (e.g. when setting the value programatically while suppressing events with `{ emitEvent: false }` to prevent an infinite loop of event handlers).

It would be nice to have a native `dismissOnSelect` option for the `ion-datetime` calendar view.

**Comment by liamdebeasi** [comment]
As I understand it, the value added by this feature is it reduces the need for an additional tap after selecting a date. I will talk with the team about this feature request, but I think the downsides of this feature outweigh the value that it adds. There are a few reasons for this:

1. This feature is very specific to the grid layout and is confusing when used with `preferWheel`. We try to avoid adding features that are specific to a particular layout, unless they have a broad use case (for example, the disable date feature is specific to the grid layout).
2. There are edge cases such as changing the month as noted in https://github.com/ionic-team/ionic-framework/issues/26531#issuecomment-1376977699 that can make this behavior inconsistent. For example, changing the month in the "change month/year" view _does_ select a new date but would not dismiss the picker under this proposal.
3. By adding this feature, there is the potential to increase the number of taps required when a user accidentally selects a date.

------

> On all of those browsers, the included date-picker (of a <input type="date"> element) is closed automatically when clicking on a specific day. Other mouse interactions, i.e. switching months, don't close the date-picker.

This is only true for desktop devices. When using `<input type="date" />` on a mobile device, the date picker requires explicit confirmation before dismissing.

| safari on ios | chrome on android |
| - | - |
| ![IMG_1765](https://user-images.githubusercontent.com/2721089/211568377-7e3bcb42-00f8-492f-b087-84978595c343.PNG) | ![Screenshot_20230110-084531](https://user-images.githubusercontent.com/2721089/211568400-2965e2ab-6542-416d-b2a1-cf158f21a7e6.png) |

**Comment by alon42** [comment]
Thanks again, 
and I really appreciate your detailed answer and the time you give for this issue.

But I suggest that it will be better to give the developer the ability to do what he wants, instead of deciding for him.
I understand that maybe ionic is maybe an opinionated framework, but if we want mass adoption, let's at least give the developers the ability to use it in their use cases and not force them to work the way we think is the right one.
I just want to clarify again that I want to add a property that will be `false` by default, so the developer will choose to use it based on his own needs and will have the flexibility for it.

I totally understand your point of view, but eventually, my clients get a date-time picker that is less easy to use than the other DateTime pickers in the market, because of the coding standard, and I'll have to find a better workaround around this problem.

**Comment by liamdebeasi** [comment]
Do you have any examples of this pattern being implemented in a mobile application?

**Comment by ReneZeidler** [comment]
E.g. Google Calendar on iOS:
https://user-images.githubusercontent.com/5558742/211594503-305f9116-f555-4448-a14a-019ff69ffc3b.MOV

Only one tap is needed to set a date, no separate confirmation button, and the calendar closes automatically.

**Comment by liamdebeasi** [comment]
Thanks! I put together a demo that uses `ion-accordion` and is close to what Google Calendar does: https://codepen.io/liamdebeasi/pen/rNryvbO

---

I discussed this with the team, and we do not think this feature is a good fit for Ionic. When adding features to Ionic, even if they are opt-in, we try to add features that minimize the risk of misuse. At the moment, there is too much risk associated with this feature as I noted in https://github.com/ionic-team/ionic-framework/issues/26531#issuecomment-1377318740. One of the trade offs of this approach is it means we often do not have all the "bells and whistles" that other projects may have, but we also feel it is important to discourage patterns that are not widely used in mobile applications.

I am going to close this issue, but thank you for taking the time to submit a feature request.

**Comment by ReneZeidler** [comment]
> One of my colleagues also recommended this alternative: https://codepen.io/liamdebeasi/pen/bGjqxVa

Thanks for posting this workaround. This is what I'm looking for, it works much better than using ionChange.
(Note for anyone wanting to use this as well, `event.path` is non-standard and doesn't work in Firefox, use `event.composedPath()` instead.)
