### ISSUE TITLE
bug:  Ionic/react output is not compatible with Remix.js

### ISSUE THREAD

**Issue by GalO005** [ionic-team/ionic-framework#26548]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I have an issue with "export"(I assume that related to transpile). 
I installed ionic framework for my Remix app, but I got the following exception: "Unexpected token 'export'"
export { setAssetPath, setPlatformOptions } from '@stencil/core/internal/client';

### Expected Behavior

Transpile with success in Remix app

### Steps to Reproduce

I created a new Remix app => installed capacitor.js (and running all the process for Ios & android) => installed ionic framework => use some elements (in root app) such as: 
```
`import { IonContent, IonHeader, IonTitle, IonToolbar } from '@ionic/react';
import {setupIonicReact} from '@ionic/react';
setupIonicReact()`
```

### Ionic Info

```
export { setAssetPath, setPlatformOptions } from '@stencil/core/internal/client';
^^^^^^

SyntaxError: Unexpected token 'export'
```

**Comment by sean-perkins** [comment]
Hello @GalO005 thanks for reporting this issue.

The problem is that Remix does not support ESM modules:
> Remix compiles your server build to CJS and doesn't bundle your node modules. CJS modules can't import ESM modules.

Source: https://remix.run/docs/en/v1/pages/gotchas

We will not be able to support Remix until that is resolved (with Ionic Framework). You _should_ be able to use Capacitor to my knowledge with Remix. 

Can you let me know if this answers your issue?

**Comment by GalO005** [comment]
@sean-perkins I think that it's an issue. 
Thanks!

**Comment by sean-perkins** [comment]
@GalO005 that sections mentions the `serverDependenciesToBundle` option in the `remix.config.js`. Have you tried adding the Ionic/Stencil dependencies to that configuration to see if it improves the experience?

For example:
```
serverDependenciesToBundle: [/.*@ionic.*/, /.*ionicons.*/, /.*@stencil.*/],
```

**Comment by GalO005** [comment]
@sean-perkins It solved the previous error, but It can't load some elements from Ionic. I got an error: **Hydration failed because the initial UI does not match what was rendered on the server.**
I think it related to [https://remix.run/docs/en/v1/guides/styling#css-in-js-libraries](https://remix.run/docs/en/v1/guides/styling#css-in-js-libraries)
I didn't find any solution from Ionic side like styleComponents (in example)
Do you have any idea? how can I to import all the css of Ionic and inject into 'entry.server.tsx' file? 

Thanks

**Comment by sean-perkins** [comment]
Ionic's web components are not architected in a way that is compatible with many types of SSR hydration. Since web components are hydrated on render, their mark-up will not match the server generated mark-up, causing hydration to fail. 

e.g.:
```html
<ion-button>Hello</ion-button>
// Upgrades to
<ion-button class="hydrated">Hello</ion-button>
```

There are also other contributing factors, such as how we reflect classes to the host element for styling changes. 

I unfortunately do not have a recommendation for getting this to work in Remix. Remix is currently not one of our target integrations with Ionic and I do not have familiarity working with it. You may be able to try the Discord or Forums to see if other community members use Remix and have recommendations for configuring Remix to better support these scenarios.
