### ISSUE TITLE
bug: Pickers Blur Errors

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/ionic-framework#26579]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Hi!,

in my opinion, there is a rather serious bug with the pickers and the blur, because if you don't click on them to focus the modal or popover, the blur doesn't work. For example in a date picker, you can move the mouse wheel around the dates and click out, but this will not trigger the blur event. The same thing happens with mobile devices, if you move the numbers but without clicking on them, when blurring, the event does not activate, however it does if you click on one of the numbers because it already has focus.

regards!

### Expected Behavior

Assign focus to the modal or popup so that the blur event is triggered when clicking outside the picker.

### Steps to Reproduce

https://stackblitz.com/edit/angular-ytgaqn?file=src%2Fapp%2Fexample.component.html,src%2Fapp%2Fexample.component.ts

Check how if you move the time with the mouse scroll and click outside the ionBlur event is not activated

### Ionic Info

Ionic:

Ionic CLI : 6.20.6

Ionic Framework : @ionic/angular 6.4.1

@angular-devkit/build-angular : 15.0.4

@angular-devkit/schematics : 15.0.4

@angular/cli : 15.0.4

@ionic/angular-toolkit : 7.0.0

Capacitor:

Capacitor CLI : 4.6.1

@capacitor/android : 4.6.1

@capacitor/core : 4.6.1

@capacitor/ios : not installed

Utility:

cordova-res : 0.15.4

native-run : 1.7.1

System:

NodeJS : v18.12.1

npm : 9.2.0

OS : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce the reported behavior, but things seem to be working as intended here. If you do not click the wheel picker, it never receives focus and will not later receive a blur event. As a result, only scrolling the wheel picker and then dismissing the modal will not cause `ionBlur` to be dispatched. We follow the browser implementation for focus/blur, so this behavior is consistent with what the web platform does.

In your example app, focus is moved to the `ion-modal` so that focus events stay trapped within the overlay. However, we intentionally do not focus the `ion-datetime`. If you are trying to detect when the modal is dismissed, I recommend listening for modal lifecycle events such as `ionModalDidDismiss`.

**Comment by Marius-Romanus** [comment]
Hello @liamdebeasi , thanks for the answer.

Doesn't it seem weird to have the blur event that sometimes works and sometimes doesn't, depending on whether or not the user has clicked on the time?

It is true, that I had not realized, in this particular case it can be taken with the closing of the modal.

But what if it is not inside a modal? How would you know if the user has changed the time and clicked on another element?
I give you the example:


https://user-images.githubusercontent.com/18282247/211378413-ad17f980-610f-499e-af7e-cda323eff96d.mp4



https://stackblitz.com/edit/angular-rvas9d?file=src%2Fapp%2Fexample.component.html,src%2Fapp%2Fexample.component.ts

But as you tell me, if this is intentional you can close the issue.
Thank you very much to all the ionic team, you do a great job!

**Comment by liamdebeasi** [comment]
> Doesn't it seem weird to have the blur event that sometimes works and sometimes doesn't, depending on whether or not the user has clicked on the time?

The `ionBlur` event is supposed to be dispatched after the datetime loses focus. If the datetime never had focus in the first place, then I would not expect `ionBlur` to fire. This is the same behavior as `<input type="date" />`: https://codepen.io/liamdebeasi/pen/wvxJBLN

In the attached example, if you click the "Set Value" button, then the `blur` event never fires. If you first focus the input by clicking on it, and then click the "Set Value" button, then the `blur` event fires because the `input` lost focus.

> But what if it is not inside a modal? How would you know if the user has changed the time and clicked on another element?

The `ionChange` event should be used for this purpose. This event allows you to tell when the the user has changed the time. From here, you can use `document.activeElement` if you want to see if a non-datetime element is focused.

There are many ways a datetime value can be changed, so I do not recommend writing code that relies heavily on user interaction to check if the value has changed. For example, your application could asynchronously update the value of the datetime. In this case, `ionBlur` would not fire either since the datetime was never focused.

**Comment by Marius-Romanus** [comment]
Ok, I understand that point of view. Thank you very much, greetings.
