### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by mark-baumann** [ionic-team/ionic-framework#26585]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I have a App which works local well. If I run the command `ionic build` I get a www Package. I uploaded the www Package to my Webserver and get a white page with the error message **Failed to load ressource: the server responded with a status code 404**

### Expected Behavior

I expected the app will be shown on my homepage because it is only JS Files, SVG, HTML and CSS

### Steps to Reproduce

To reproduce, you have to clone my Repo from Git. Than run `ionic build` and extract the folder to your webserver.

### Code Reproduction URL

github.com/mark-baumann/aktivitaeten

### Ionic Info

Ionic:

   Ionic CLI : 6.20.6

Utility:

   cordova-res : 0.15.4
   native-run  : not installed globally

System:

   NodeJS : v18.13.0
   npm    : 8.19.3
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the report. There's not a lot of information about your server setup to go off here, but I would make sure that the server is finding the `index.html` file correctly. Ionic Framework does not handle application deployment, so this appears to be more of a configuration issue than an Ionic issue.

I recommend looking at https://angular.io/guide/deployment#basic-deployment-to-a-remote-server which should show you how to deploy an Angular app to a remote server. Since Ionic Framework is only responsible for the user interface, the steps should be the same.

**Comment by mark-baumann** [comment]
I also found this issue which has something to do with the bug: https://forum.ionicframework.com/t/failed-to-load-resource-the-server-responded-with-a-status-of-404-not-found-in-ion-calendar/183720

**Comment by liamdebeasi** [comment]
The problem here is that your application is deployed to a subdirectory, but the app is still trying to pull from the root. For example, it is trying to load  from `https://markb.de/runtime.25d551c89c20818c.js` when it should be loading from `https://markb.de/app/runtime.25d551c89c20818c.js`. 

You need to configure your application to load from the subdirectory. Something like this should work:

```
ng build --base-href=/app/
```

`--base-href` is an Angular CLI flag. You could also specify this in `angular.json` so you do not need to pass this flag on every build. This guide shows how to do that: https://angular.io/guide/i18n-common-deploy

> I also found this issue which has something to do with the bug: https://forum.ionicframework.com/t/failed-to-load-resource-the-server-responded-with-a-status-of-404-not-found-in-ion-calendar/183720

That is a different bug and had to do with a 3rd party calendar library.

**Comment by mark-baumann** [comment]
You made my day Bro!!! @liamdebeasi
