### ISSUE TITLE
bug: ionic v6 with react: Page transitions not working with nested routes

### ISSUE THREAD

**Issue by luantrasel** [ionic-team/ionic-framework#26649]
**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[x] **6.x**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**
The page transition does not work correctly on the **first time** I navigate to a nested route, if I go back and navigate to that route again, it works. If I navigate to a regular route that is not nested it works everytime. The swipe back on iOS also doesn't work correctly with the nested routes. On Android it seems to be working correctly.

On the video I click to go to next page, click to go back, go next page and swipe back

https://user-images.githubusercontent.com/26885974/213702004-504f68d5-8b8f-4cc0-8bd9-818789c830c5.MP4

**Expected behavior:**
Page transitions and swipe back on iOS should always animate correctly

On the video I click to go to next page, click to go back, go next page and swipe back

https://user-images.githubusercontent.com/26885974/213702095-36fca03f-0ff3-4d56-ab78-836582cd03ed.MP4

**Steps to reproduce:**

You can test it with the sample application I created: https://github.com/luantrasel/ionic-routing-sample-app

The issue is visible even on browser, if you use an iPhone as device on chrome dev tools. For swipe back you need a real device to test. All you need to do is click on header on "Go to page 2" and you'll notice that on 1st time it wont be animated.

**Related code:**

Home.tsx
```
    <IonPage>
        <IonRouterOutlet>
            <Route exact path="/" component={Tab1} />
            {/* Animation / Swipe back does NOT work */}
            <Route path="/tab2" component={NestedRoutes} /> >> this way we have the issue I'm reporting
            {/* Animation / Swipe works correctly */}
            {/* <Route path="/tab2" component={Tab2} /> */} >> using the route like this it works
        </IonRouterOutlet>
    </IonPage>
```

NestedRoutes.tsx

```
    <IonPage>
        <IonRouterOutlet>
            <Route exact path="/tab2" component={Tab2} />
        </IonRouterOutlet>
    </IonPage>
```

**Other information:**

Related issue #26606

**Ionic info:** 

```
Ionic:

   Ionic CLI       : 6.19.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.5.0

Capacitor:

   Capacitor CLI      : 4.6.2
   @capacitor/android : not installed
   @capacitor/core    : 4.6.2
   @capacitor/ios     : 4.6.2

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v14.20.1 (/Users/luantrasel/.nvm/versions/node/v14.20.1/bin/node)
   npm    : 6.14.17
   OS     : macOS Monterey
```

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce the reported behavior, but this is not a bug in Ionic. As noted in the [Ionic React Documentation for Tabs](https://ionicframework.com/docs/react/navigation#child-routes-within-tabs), child views within tabs should be rendered as sibling routes.

Nested routes should only be used when you want to render content in multiple outlets at once. Tabs is a great example of this because `IonTabBar` is rendered in the top-level outlet, but the actual tab content is rendered in the nested outlet inside of `IonTabs`.


Your routing config in `AppPhone.tsx` should look something like this instead:

```jsx
<IonTabs>
  <IonRouterOutlet>
    <Route exact path="/">
      <Tab1 />
    </Route>
    <Route exact path="/tab2">
      <Tab2 />
    </Route>
</IonRouterOutlet>
  <IonTabBar slot="bottom">
    <IonTabButton tab="main" href="/">
      <IonIcon icon={triangle} />
      <IonLabel>Main</IonLabel>
    </IonTabButton>
  </IonTabBar>
</IonTabs>
```
The `Home.tsx` and `NestedRoutes.tsx` components are not needed since you only need one nested outlet (the one inside of `IonTabs`).

**Comment by luantrasel** [comment]
Thanks @liamdebeasi 

Creating the routes as sibling worked. Our code has all routes on subcomponents, we had them encapsulated so we could handle their state in a proper way. We tried to add the routes in a react fragment, in a Route component but none of this worked. Now we are refactoring it to have all routes as siblings and still thinking on how to handle their states.

Just thought would be good to mention our issues to you. Maybe it could be an improvement for the future. Or maybe is there a workaround for it so we can encapsulate the Routes on a subcomponent?

**Comment by liamdebeasi** [comment]
Glad to hear that siblings routes resolved the issue. React Fragments are a bit tricky with mobile apps. The reason is that Ionic needs the current page _and_ the previous page to exist in the DOM at the same time in order for gestures such as swipe to go back on iOS to work. I'm not sure how have your other app setup, but my recommendation would be to encapsulate the contents of a page as a fragment rather than the page component itself.

We do have some routing improvements coming in the future that should make these kinds of patterns easier to implement. For the tabs use-case, we are looking to add console warnings that will detect incorrect usages to help developers implement correct tabs patterns.

I am going to close since the issue is resolved, but let me know if you have any questions. Thanks for the report!
