### ISSUE TITLE
bug: Opening on-screen keyboard in Safari and Chrome 108+ causes the entire app to be scrollable

### ISSUE THREAD

**Issue by darrylnoakes** [ionic-team/ionic-framework#26702]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

In Chrome 108 and later, when the on-screen keyboard is open (e.g., an input is focused), the Visual Viewport is smaller than the Layout Viewport, causing the entire app to be scrollable (including headers, footers, etc.).

This behavior is also present in Safari, as it uses the same layout/visual viewport behavior.

### Expected Behavior

The body element should be resized to the height of the Visual Viewport so that the app is not made scrollable.

### Steps to Reproduce

1. View an app that has input, using Chrome 108 or later.
2. Focus the input, causing the OSK to open.
3. The entire app becomes scrollable.

### Ionic Info

``` 
Ionic:

   Ionic CLI       : 6.16.3 (C:\Users\Darryl\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.5.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.4.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.19.2
   OS     : Windows 10
```

### Additional Information

This can probably be fixed by using CSS dynamic viewport units to set the body element to the dynamic viewport size.
Chrome 108 also includes support for these, so this change should be fully compatible.
However, I am not sure if these units account for the OSK.

**Comment by liamdebeasi** [comment]
Thanks for the report. I agree that this behavior is not ideal. However, we need platform-level changes in order to correctly implement the desired behavior. I have provided more details below:

## Problem

(Most of this is what was noted in the original post).

When the On-Screen Keyboard (OSK) presents, the Visual Viewport resizes and the Layout Viewport remains the same size. The difference between the two layouts is explained here: https://developer.mozilla.org/en-US/docs/Web/CSS/Viewport_concepts

As a result, it is possible to scroll the viewport causing the `ion-header` to be scrolled offscreen. Closing the keyboard moves the `ion-header` back to the correct location, so this issue is limited to when the OSK is displayed.

This is a confusing behavior as only the `ion-content` should be scrollable. This issue impacts apps running in a browser and as a PWA. This issue should not impact apps running in Capacitor because developers have access to webview resizing APIs (at least on iOS).

As noted in the original post, Dynamic Viewport Units cannot be used to resolve the issue since they do not account for the OSK.

## Solution

There are two solutions that would resolve the issue.

### Solution 1: Resize the layout viewport when the keyboard opens

This approach is not desirable because it would cause any footers or tabbars to be pushed above the keyboard. This can cause layout shifts since the layout itself is resizing. While it is likely the simplest solution, it is also the most disruptive in terms of the layout. It also breaks the "app-like" feel of Ionic since native apps do not resize the layout when the OSK is shown. For example, focusing the search input on the iOS App Store does not push the tab bar above the keyboard.

However, developers can implement a workaround on their own by using [Keyboard Lifecycle Events](https://ionicframework.com/docs/developing/keyboard#keyboard-lifecycle-events) to set the `<body>` height.

### Solution 2: Prevent the visual viewport from resizing when the keyboard opens

This approach provides the most "app-like" experience since any footers or tabbars stay fixed to where they were before the OSK opened. However, in order to do this we need browsers to support the [Virtual Keyboard API](https://developer.chrome.com/docs/web-platform/virtual-keyboard/). Developers can then use `navigator.virtualKeyboard.overlaysContent = true` to prevent any resizing when the OSK is shown.

This API is not without its tradeoffs. For starters, this API is not supported on iOS at the time of writing. Additionally, using `overlaysContent = true` means that the visual viewport events would no longer fire, breaking [Ionic's Keyboard Lifecycle Events](https://ionicframework.com/docs/developing/keyboard#keyboard-lifecycle-events) as well as any developer-code that relied on the Visual Viewport resize events.

------

Solution 1 is something that developers can implement today in their browser/PWA applications. However, this behavior is not guaranteed to be appropriate for all applications. As a result, we think which configuration to use is best decided by the developers.
