### ISSUE TITLE
bug(range): can start scroll on range

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#26728]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

When i try to start scrolling on mobile and the first touch is on a `ion-range` element, i can't scroll and instead focus the range.

This results in a buggy felling in behavior as i want to scroll. We have a filter page where we have many range elements and it's hard to scroll like that.

### Expected Behavior

It should be possible to start scrolling with the first tap on a range component

### Steps to Reproduce

Mobile App: Try start scrolling on a range component

### Ionic Info

Let me know if this is relevant

**Comment by liamdebeasi** [comment]
Thanks for the report. This appears to be the same as https://github.com/ionic-team/ionic-framework/issues/25595. The original post notes trying to scroll on desktop, but both issues are caused by the same code. 

We disable scrolling so that you cannot accidentally scroll while dragging the range, but this approach is a bit heavy-handed: https://github.com/ionic-team/ionic-framework/blob/9d6ec2925cb2314d5379b864aef467b34afbb318/core/src/components/range/range.tsx#L352

This approach means that simply swiping over a range causes scrolling to be disabled as stated in the original post. I noted in https://github.com/ionic-team/ionic-framework/issues/25595#issuecomment-1179056471, that using Pointer events should resolve this issue as scrolling does not happen if the pointer is captured. Using that API should allow scrolling as long as the gesture is not captured (which should not happen when scrolling).

**Comment by EinfachHans** [comment]
Okay, i found that issue, but thought it might be a different bug, because the desktop-note. Feel free to merge the two issues. Would love to see this fixed! 😊 

Fyi: the Workaround mentioned [here](https://github.com/ionic-team/ionic-framework/issues/25595#issuecomment-1330293954) enables the scrolling but then i'm able to scroll and use the range at the same time which is also not perfect

**Comment by liamdebeasi** [comment]
Merging with https://github.com/ionic-team/ionic-framework/issues/25595. Thanks again for the report!
