### ISSUE TITLE
bug:  ion-input unresponsive on lower half of viewport

### ISSUE THREAD

**Issue by Yonava** [ionic-team/ionic-framework#26787]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

Ion-Input element takes multiple seconds to respond when clicked when rendered on the lower half of the viewport. On the upper half of the viewport, ion-input responds normally to touch gestures. The laggy behavior persists when building the application on the XCode emulator with capacitor.

### Expected Behavior

Ion-Input should respond to touch gestures without taking a performance hit on the top and bottom half of the viewport.

### Steps to Reproduce

Create an empty tab navigation ionic Vue app. Inside the content of any of the tab views, place 

### Code Reproduction URL

https://github.com/Yonava/ionic-slow-input-bug

### Ionic Info

Ionic:

   Ionic CLI : 6.20.6

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.13.2
   npm    : 8.1.2
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you clarify what it means for an input to be "responsive"? Are you referring to how long it takes for the keyboard to open, or how long it takes for the input to be adjusted above the keyboard?

**Comment by Yonava** [comment]
> Thanks for the report. Can you clarify what it means for an input to be "responsive"? Are you referring to how long it takes for the keyboard to open, or how long it takes for the input to be adjusted above the keyboard?

Of course. I am referring to a 1-2 second delay for the input to focus and the cursor to appear after it is clicked.

**Comment by Yonava** [comment]
Here is a screen recording. As you can see, I am selecting the input field and moving my cursor away. 1-2 seconds later the input field focuses

https://user-images.githubusercontent.com/76519301/218536179-db9b6174-af64-475e-9dd8-b945fc29743f.mov

**Comment by Kilhog** [comment]
I was going to report the same problem, I think it's related to a scroll animation to put the field "at the correct position" when the keyboard appears

**Comment by liamdebeasi** [comment]
Does this issue reproduce on a physical device? If so, can you provide a screen recording of that?

Ionic has a scroll assist utility that ensures text inputs are not covered by the on-screen keyboard. This utility assumes that it needs to wait for the keyboard to open and the webview to resize. However, this is not happening on the simulator since the virtual keyboard is disabled in favor of connecting the hardware keyboard. As a result, this delay is present.

**Comment by clementMercierDev** [comment]
Yes, the issue was reproduced on a physical device.
Here is a video of the problem : 

https://youtube.com/shorts/9XZr_DMmPb0

**Comment by liamdebeasi** [comment]
> Yes, the issue was reproduced on a physical device. Here is a video of the problem :
> 
> https://youtube.com/shorts/9XZr_DMmPb0

This is slightly different than what is being reported. In your sample Ionic needs to wait for the webview to resize in order to adjust the input. The delay there is correct, and I have a more in-depth explanation (with a workaround) here: https://github.com/ionic-team/ionic-framework/issues/26801#issuecomment-1431606369
