### ISSUE TITLE
bug: Top Level Await

### ISSUE THREAD

**Issue by gofish543** [ionic-team/ionic-framework#26832]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

The following line in `main.ts` gives the below exception...
```javascript
const storage = new Storage();
await storage.create();
```

![image](https://user-images.githubusercontent.com/10394554/220205548-4f958538-23d1-47ed-924a-c2a3d584fa2b.png)

How can I enable top level support for this framework? There is no documentation anywhere on this feature, and the framework does not allow for the extension of a webpack file to enable the experimental feature.

### Expected Behavior

-

### Steps to Reproduce

-

### Ionic Info

-

**Comment by liamdebeasi** [comment]
Hi there,

Please fill out the template entirely when filing bug reports/feature requests. This allows us to better assist you. There's not a lot of information to go off here, but enabling top-level await is not something that is enabled within Ionic Framework which is why there are no docs on it.

This appears to be an error from Webpack. According to StackOverflow, this can be enabled in `webpack.config.js`: https://stackoverflow.com/questions/72474803/error-the-top-level-await-experiment-is-not-enabled-set-experiments-toplevelaw

This is more of a support question, so I encourage you to post on the [Ionic Forum](https://forum.ionicframework.com/) instead. We use this GitHub tracker exclusively for bug reports and feature requests.
