### ISSUE TITLE
bug: using fill=outline and helperText on ion-input can cut off text, worse when using ion-item

### ISSUE THREAD

**Issue by ptmkenny** [ionic-team/ionic-framework#26913]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [ ] v6.x
- [X] v7.x
- [ ] Nightly

### Current Behavior

When using helperText on ion-input, the text of a second ion-input element can be cut off by the helperText of the first.

![helpertext-issue](https://user-images.githubusercontent.com/1451472/222863177-643c717b-4c6c-4d52-bfed-337f3988e2f1.png)

This problem is worse when using ion-item to hold inputs:

![helpertext-ionitem-issue](https://user-images.githubusercontent.com/1451472/222863181-f3d2c993-6744-43e8-b6f2-e758797e4f6d.png)

### Expected Behavior

I expect no text to be cut off when putting components next to each other.  (I expect the padding/margin to be sufficient that they can be stacked.)

### Steps to Reproduce

See tab 1 in the attached repo.

### Code Reproduction URL

https://github.com/ptmkenny/ionic-26861/tree/helperText

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.20.8 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.0.0-dev.11677608949.16e25264

Capacitor:

   Capacitor CLI      : 4.7.0
   @capacitor/android : not installed
   @capacitor/core    : 4.7.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v19.6.0 (/opt/homebrew/Cellar/node/19.6.0/bin/node)
   npm    : 9.4.0
   OS     : macOS

```

**Comment by liamdebeasi** [comment]
Thanks for the report. There are a couple issues here:

1. Your application uses `fill` styles on inputs inside of `ion-item`. Since the `fill` style visually defines the input container, inputs that use `fill` should not be used in `ion-item`. This is noted on the docs: https://ionicframework.com/docs/v7/api/input#filled-inputs


2. Since the `fill` styles can be used outside of `ion-item`, we intentionally do not define any margins because we do not know how your inputs are going to be used. It's up to the developer to define what the margins are for each input. This is what libraries such as [Material Design Components for the Web](https://material-components.github.io/material-components-web-catalog/#/component/text-field) and [MUI](https://mui.com/material-ui/react-text-field/) do with their outline/solid text field. Here is one way you can account for the margins: https://codepen.io/liamdebeasi/pen/XWPapXY
This example uses a CSS grid container and sets the "grid-gap" property to ensure that there is spacing between each row/column.

**Comment by liamdebeasi** [comment]
We are planning new "best practice" docs on how to use inputs in items/lists which should provide some better guidance than what we have right now. The original issue has been resolved, so I am going to close this. We'll be working on those docs soon. Thanks for the report!
