### ISSUE TITLE
bug: IonCheckbox inside IonItem will invalidate IonItem's button prop

### ISSUE THREAD

**Issue by immortalt** [ionic-team/ionic-framework#27004]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

If you put a IonCheckbox inside IonItem, you cannot disable the RippleEffect of IonItem even if set button={false}
```react
 <IonItem button={false}>
          <IonCheckbox slot="start"></IonCheckbox>
 </IonItem>
```
![image](https://user-images.githubusercontent.com/17811951/227064080-089ea6ed-886e-4486-b6d9-8da49a0eb52f.png)

### Expected Behavior

In my case, I want to disable the RippleEffect or button effect of IonItem, and allow IonCheckbox to be clicked individually without affecting other elements in IonItem.
For example, for a Todo List Item,
only clicking the IonCheckbox will finish this task,
and clicking the IonItem will open a new page to edit this task,
and clicking the IonCheckbox should not cause the RippleEffect effect of IonItem.
Currently, the IonItem is a huge mix, it mix the behaviours of it's sub elements badly.

At least, I think IonItem's behaviour should follow the button={false}.
There shouldn't be such special cases to cause IonItem become a button.

### Steps to Reproduce

1. Create a ionic 6 project
2. Add this to the main page: 
```react
 <IonItem button={false}>
          <IonCheckbox slot="start"></IonCheckbox>
 </IonItem>
```
3. Click the IonItem and you will find button={false} not works.

### Ionic Info

Ionic:
   Ionic CLI       : 6.20.8 (C:\Users\xxx\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 6.6.2
   native-run  : 1.7.2
System:
   NodeJS : v16.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.3
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. This is the intended behavior of IonItem. As noted in the [ion-item docs](https://ionicframework.com/docs/api/item#button), the `button` property on `ion-item` will cause a `button` tag to be rendered. When you place a checkbox in the item, we render a ripple effect cover so that you can click anywhere inside of the item to trigger the checkbox. However, the item itself is not a button, so setting the `button` property to `false` has no effect. In other words, the `button` property on `ion-item` has nothing to do with the content you place inside of `ion-item`.

In your TodoList use case, you might end up rendering a text input so users can edit the value of the todo item. In this case, the checkbox ripple effect "cover" does not get rendered because there are multiple interactive elements inside of `ion-item`: https://codepen.io/liamdebeasi/pen/ZEMmqMQ
