### ISSUE TITLE
bug: form controls do not have enough margin

### ISSUE THREAD

**Issue by whydoievenneedthis** [ionic-team/ionic-framework#27129]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Consider the following snippet:
```
<ion-content>
  <ion-radio-group>
    <!-- pre-migration version -->
    <ion-item>
      <ion-label>
        <div translate>xx</div>
      </ion-label>
      <ion-radio slot="start"></ion-radio>
    </ion-item>
    <ion-item>
      <ion-label>
        <div translate>xx</div>
      </ion-label>
      <ion-radio slot="start"></ion-radio>
    </ion-item>

    <!-- post-migration version with ion-item -->
    <ion-item>
      <ion-radio slot="start" label-placement="end" translate>
        <div translate>xx</div>
      </ion-radio>
    </ion-item>
    <ion-item>
      <ion-radio slot="start" label-placement="end" translate>
        <div translate>xx</div>
      </ion-radio>
    </ion-item>

    <!-- post-migration version without ion-item -->
    <ion-radio slot="start" label-placement="end" translate>
      <div translate>xx</div>
    </ion-radio>
    <ion-radio slot="start" label-placement="end" translate>
      <div translate>xx</div>
    </ion-radio>
  </ion-radio-group>
</ion-content>
```

The first block is the 6.x version of the radio buttons. For the second one, the label was moved into the body of the radio as the migration guide suggested, but the ion-item element was kept. For the third one, the ion-item element was dropped as well.

This snippet renders the following:
![image](https://user-images.githubusercontent.com/87586203/230187318-a6a3c184-41a6-415c-ae19-21b70e4c067b.png)

The third block I don't want to go too much details into, I assume the `<ion-item>` plays an important role in rendering the widget the way I want it to look. I just wnat to note that despite what the documentation says, it cannot just be removed without breaking a lot of things.

More important are the functional aspects.
- The red highlight indicates the click area. For the old version, the radio button can be selected when clicking anywhere in the whole row. The new version, however, requires precise clicking either on the text or the circle. Also important that when I hover over the line both with the older and the newer version, the whole row receives the light gray highlight, which can be confusing (I expected the presence of the highlight to indicate that I can click anywhere to select the radio button).
- With the old version, the grey item separator line reaches under the label, while with the new version it does not. If the label is longer (like it was in my original), the difference is even more noticeable, and will look awful when the consecutive lines contain labels of different width:
![image](https://user-images.githubusercontent.com/87586203/230189887-54fd850b-d4d6-40fb-84a7-388b6f166b11.png)
- The label is too close to the radio button, which looks bad both when there is just a small amount of text, and when there is a large amount of text. This is something I was able to fix with some custom css, but I think it should be looking nicer out of the box.
- When there is a lot of text in the label part, it fills out the whole row, there is no top and bottom padding, which looks awful. This I could not fix.

### Expected Behavior

Summarized from the above section:
- whole row should be clickable
- gray separator line should be visible under the label
- space between radio button and label text should be bigger
- padding above and below the label should be present

### Steps to Reproduce

1. Pull in the snippet above in any component.
2. Check the output.

### Ionic Info

[WARN] You are not in an Ionic project directory. Project context may be missing. // this is incorrect btw

Ionic:

   Ionic CLI : 7.0.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v19.8.1
   npm    : 9.5.1
   OS     : Windows 10

NX workspace. What you are interested in is probably the following:
    "@ionic/angular": "7.0.1",
    "@ionic/core": "7.0.1",

    "@angular-devkit/build-angular": "15.2.5",
    "@angular-devkit/core": "15.2.5",
    "@angular-devkit/schematics": "15.2.5",
    "@angular/cli": "15.2.5",

    "@capacitor/core": "4.7.3",
    "@capacitor/android": "4.7.3",
    "@capacitor/cli": "4.7.3",
    "@capacitor/ios": "4.7.3",

**Comment by liamdebeasi** [comment]
Thanks for the report. There a few concerns here:

**1. Radios cannot be removed from the item without "breaking"**.

The reported layout behavior is intentional. The "minimal" layout (i.e. no padding, margins, etc) is designed to give developers more flexibility with how form controls like radios are laid out on a page. In older versions of Ionic, radios were always assumed to be used inside of lists. In Ionic 7 developers can (but don't have to) remove the radio from an item for more layout flexibility. Since we don't know how you are going to use the radio outside of the item, we do not make assumptions about sizing, margins, padding, etc.

**2. Precise clicking is required for the radio**

In this case, you should not be using `slot="start"`. I'd recommend using `justify="start"` and `label-placement="end"` instead: https://codepen.io/liamdebeasi/pen/rNqNaJg?editors=1010

Putting a radio/checkbox in the start slot is useful when you have other form controls to place inside of the item.  In your case, you only have the radio with the visible label, so the start slot is not needed. This will allow you to click anywhere on the item to activate the radio.

**3. Multi-line text does not have enough padding in items**

You can add this by setting padding on the content you pass into the radio:

```html
<ion-radio justify="start" label-placement="end" style="padding: 10px 0px">
  <div class="ion-text-wrap ion-padding-vertical">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam nunc, facilisis at odio eu, eleifend elementum eros. Sed scelerisque imperdiet felis, egestas faucibus sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin maximus, ipsum at euismod feugiat, nibh ligula gravida arcu, non tempor nulla diam et tellus. Mauris eget bibendum metus. In sed tellus ultricies, vulputate est quis, blandit arcu. Praesent ultricies mattis lacus, interdum molestie nulla convallis id. Pellentesque tempus feugiat nisl, ut dapibus metus feugiat at. Nunc turpis massa, consequat et lectus eu, egestas eleifend risus. Cras eu efficitur est. Sed sed laoreet erat. Integer sit amet consectetur metus, at tristique eros. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
  </div>
</ion-radio>
```

I'll check with the team to see if there is something we can do to improve this experience.

**4. The label is too close to the radio**

This value was chosen for consistency with other form components, but it looks like this should be 16px instead of 8px to align with Material Design: https://m2.material.io/components/selection-controls

**Comment by whydoievenneedthis** [comment]
Thanks for the quick feedback, it was very helpful.

The example above was a bit oversimplified, I have a couple radio buttons and checkboxes (haven't gotten to those yet with the migration), all in forms with other elements around them, they are pretty much never standalone. Eg:
![image](https://user-images.githubusercontent.com/87586203/230414591-6371abd6-d90b-43a1-8a4a-e5fe0f002fc8.png)
After applying your suggestions, the results came out much nicer. 

I have two more questions/issues, if you don't mind.

The first one is regarding the gray separator line. Now it reaches under the radio button itself, but not to the whole width of the line, like an input field would (red highlight). Is it possible to have it removed from under the button, so it only reaches to the beginning of the label (get it out from the red highlight)?

The second one might be considered nitpicking, but there is still a small dead zone regarding the clicking at the beginning and end of the row, marked in yellow, where the hover highlight is already visible (this is there in the codepen example as well). On the left side it corresponds to the zone that doesn't have the gray separator line, and on the right it's roughly the same width. With the splash effect it is even more pronounced:
![image](https://user-images.githubusercontent.com/87586203/230416461-64b82811-9fa2-4651-82e6-9f5361c8d933.png)
Is there a way this could be covered as well? (Visually this padding is present as well eg. for the input fields, however clicking on that part still puts the focus into the input, and selects any text that was already present.)

**Comment by liamdebeasi** [comment]
> The first one is regarding the gray separator line. Now it reaches under the radio button itself, but not to the whole width of the line, like an input field would (red highlight). Is it possible to have it removed from under the button, so it only reaches to the beginning of the label (get it out from the red highlight)?

My understanding of the iOS Design System is you should not do this if you have a form control (like a radio) and an associated label. Apple typically uses the pattern you described when there is either a) multiple form controls (like a checkbox and an input) or b) a single form control and text that is _not_ associated with the form control.

Here's an example with the Mail app on iOS:

![IMG_2037](https://user-images.githubusercontent.com/2721089/230440487-64b8565d-ebfc-4e02-9213-2caf5b0c484c.jpg)


The checkbox is in the "start" slot, but the text that is in the item isn't necessarily the checkbox's label, it's just text that describes the entire item.

Here's another example on the Reminders app:

![IMG_2036](https://user-images.githubusercontent.com/2721089/230440656-d48d6b55-56bb-44f0-8e87-17c0c28cc4f4.jpg)

The checkbox is in the "start" slot, but then there is a text input in the main part of the item. (You can tap "Milk" to edit the name of the reminder).

We're working on a new guide for items + lists for our docs that will cover use cases like these, because it's not really clear right now.

> The second one might be considered nitpicking, but there is still a small dead zone regarding the clicking at the beginning and end of the row, marked in yellow, where the hover highlight is already visible (this is there in the codepen example as well). On the left side it corresponds to the zone that doesn't have the gray separator line, and on the right it's roughly the same width. With the splash effect it is even more pronounced:

We trying to figure out how best to fix this. This "worked" with the old syntax, but the way we did it was error-prone, so we're looking at alternatives.

**Comment by liamdebeasi** [comment]
For tracking purposes: The main issue here that the team needs to fix is increasing the margin between the label and the control from 8px to 16px. This should be done for checkbox, radio, input, textarea, select, and range when the label and the control are on the same line.

Example: https://github.com/ionic-team/ionic-framework/blob/ca9b9b65d2b738bac9e29017039e4d14cf8400d2/core/src/components/radio/radio.scss#L168
