### ISSUE TITLE
IOS displays a white screen while swiftly scrolling

### ISSUE THREAD

**Issue by jaisonjam1988** [ionic-team/ionic-framework#27133]
**Ionic version:**

Ionic CLI  **7.0.1 (/usr/local/lib/node_modules/@ionic/cli)**
Ionic Framework  **@ionic/angular 7.0.1**

**Presently, when scrolling quickly, a white screen is displayed, followed by data after one or two seconds. But with slow scrolling, it functions perfectly. And it works quite well on Android smartphones.**

**I am using '@angular/cdk/scrolling' for the scrolling feature.**

**The same problem with "ion-infinite-scroll" and "ion-refresher" persisted in Ionic 6.**

[x ] bug report
[ ] feature request

**Comment by jaisonjam1988** [comment]
I appreciate your reply.

You may access the copied issue here. : https://github.com/jaisonjam1988/ionic7-scroll-issue-ios

**Comment by liamdebeasi** [comment]
I can reproduce the reported behavior, but this does not appear to be a bug in Ionic. The problem here is your `itemSize` is wrong for iOS mode. Items are 56px tall on Android but are only 44px tall on iOS. You should update `itemSize` to account for this difference:

```html
<cdk-virtual-scroll-viewport [itemSize]="itemSize" minBufferPx="900" maxBufferPx="1350">
```

```ts
import { Config } from '@ionic/angular';

itemSize = 56;

constructor(private config: Config) {
  this.itemSize = config.get('mode') === 'ios' ? 44 : 56;
}
```

**Comment by jaisonjam1988** [comment]
The code has been updated as previously described and pushed to github also. But the problem is still present.

Is this iOS's standard scrolling behaviour?

**Comment by liamdebeasi** [comment]
This is not iOS's standard scrolling behavior, and this does not appear to be an Ionic Framework bug. You are using Angular CDK Scroller, so all virtual scroll rendering is handled by that library.

There are a few things you may want to try:

1. Adjust the `minBufferPx` and `maxBufferPx` values according to https://material.angular.io/cdk/scrolling/overview#scrolling-over-fixed-size-items. This will adjust how much extra content is rendered beyond what is visible in the viewport.
2. There is a similar issue reported on https://github.com/angular/components/issues/24943 that has a workaround using `position: absolute` (see https://github.com/angular/components/issues/24943#issuecomment-1155497884). You might want consider trying that to see if it improves the experience.
3. Consider commenting on https://github.com/angular/components/issues/24943 with a reproduction case. It is possible that this behavior is a bug in Angular CDK Scrolling.

I am going to close this, as I don't see anything that would indicate this is an Ionic bug. I was also able to reproduce the reported behavior with a `<div>` instead of an `<ion-item>`. Let me know if you have any questions.
