### ISSUE TITLE
feat: Module.forRoot() Config for label-placement from ion-input

### ISSUE THREAD

**Issue by SvenBudak** [ionic-team/ionic-framework#27151]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

In general, I would appreciate it if we could set all relevant component settings globally, but at the moment, I would already be very happy if we could define the "label-placement" attribute for ion-input globally:

Something like this:

```ts
IonicModule.forRoot({
    mode: 'md',
    inputLabelPlacement: 'stacked',
})
```

Would you agree with me on this? I would be very happy if this feature request were implemented. Then, I can remove this attribute in many files, and at least have a little more clarity in my HTML files :)

**Comment by SvenBudak** [comment]
It also would be cool if the "color" attribute can be set globally for every component.

for example i do alot times over and over again:
```html
<ion-toolbar color="primary">
```
and
```html
<ion-input color="secondary">
```

**Comment by amandaejohnston** [comment]
Thank you for the request. The usual most effective way of accomplishing this would be to create a wrapper component, which renders the Ionic component with the props you need set automatically, and use that instead. Would that work for your use case?

**Comment by SvenBudak** [comment]
Sure, that works, but in my opinion, it's not a good solution. I mean, there's already a config for Ionic. Why shouldn't one be able to define a basic behavior of Ionic components there? Or better yet, why should it be reserved for just a few individual functions and not for all? You can also define the toastDuration, and in my opinion, you should be able to define everything in the same way.

If you work with NRWL/NX, for example, you would otherwise have to migrate endless wrapper components if you want to create another app in the same CI. With the config, all you would need to do is transfer the config and you're done.

Or if you work in a company where many developers are working on a project, but not all of them are perfectly familiar with the CI of the respective app, errors can quickly occur, such as one developer setting the label-placement to a different value than it should be. This could be prevented with a global config, and none of the developers would have to deal with the intricacies of the components anymore.

**Comment by amandaejohnston** [comment]
Thanks for the added details. I spoke with the team on this, and we agree that while we sympathize with the desire to avoid repetition while migrating or prevent accidental errors, it would be best to keep the API light here and not add additional config options. The existing ones that let you define component props are legacy and are kept mostly for backwards compatibility.

Setting all component props via the global config is not a pattern we want to encourage, mainly because the config is not reactive (i.e. you can't update it during runtime), so you lose flexibility with your components taking that route. The recommended path is still to use a wrapper component, or a custom directive if you're using Angular (which I'm assuming you are, judging from your initial code snippet).

I'm going to go ahead and close this out since we aren't planning on adding this feature at this time, but please let me know if you have any other questions.
