### ISSUE TITLE
bug: Swipe back gesture not working when loading the same view twice with the same key

### ISSUE THREAD

**Issue by keygun-development** [ionic-team/ionic-framework#27211]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [x] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

When loading the same view with the same key the view won't be added to the rendered views, because it thinks it is already rendered. I've tested this in a vue 3 application with `@ionic/vue`.

The view with the duplicate key will de-render and you're on the view with the different key. When trying to swipe back another time using the IOS swipe gesture this won't work, because the view with the duplicate key has been removed from the router-outlet. When using the `<ion-back-button></ion-back-button>` the view will be rendered again and the expected result is good.

### Expected Behavior

I expected that the view with the duplicate key would be rendered twice inside the router-outlet. I don't think this is a clever way of fixing the problem. What I'd rather like to see is something that `vue-router` does support and that's a `key` property. This way we can define the key ourself and wouldn't stumble upon this problem, because now we can generate a unique id foreach view that will be rendered.

### Steps to Reproduce

1. Create a `@ionic/vue` application.
2. Have a view with a duplicate key (A key in vue is based of the current slug).
3. Load the view once
4. Load another view **without swiping back** which has a different key
5. Load the first view another time **without swiping back**
6. Now swipe back using the IOS swipe gesture

### Code Reproduction URL

[Vue-ionic-app](https://github.com/keygun-development/vue-app)

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.9 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.7.0

Capacitor:

   Capacitor CLI      : 4.7.1
   @capacitor/android : 4.7.1
   @capacitor/core    : 4.7.1
   @capacitor/ios     : 4.7.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.20.0 (/opt/homebrew/Cellar/node@16/16.20.0/bin/node)
   npm    : 8.19.4
   OS     : macOS Unknown

### Additional Information

Check the repo's readme for a video which showcases the broken history

**Comment by keygun-development** [comment]
Thanks I'll provide a reproduction after work

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce the reported behavior, but this is not a bug in Ionic. Routing in mobile apps differs from how routing would normally happen in a web application.

In this case, pushing the same route multiple times is an antipattern (i.e. /article/1 --> /archive --> /article/1). This can create a confusing user experience if the user has entered data on the older page. For example, if the user entered their email on the first `/article/1` page, that email would not show up on the second instance of `/article/1`.

Ionic tries to be clever and it will re-use the original view for `/article/1`, but this is a behavior we would like to change and instead provide a console warning when this usage happens.

For your particular app, you should configure it so that it goes back to the original `/article/1` page instead of pushing a new view.

**Comment by keygun-development** [comment]
Thanks for clarifying! Going back to the original page will be the fix for this issue. I'd love to see something like a console warning for other people stumbling upon this problem thinking it's a bug.
