### ISSUE TITLE
feat: Support Angular `esbuild-builder` to build Ionic production app

### ISSUE THREAD

**Issue by hakimio** [ionic-team/ionic-framework#27251]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

In `v15` Angular introduced experimental `esbuild` support. It's supposed to significantly improve production bundle build times. Unfortunately it doesn't work with "Ionic Angular" because Ionic dynamically imports components via runtime evaluation.

[angular-cli issue with more info](https://github.com/angular/angular-cli/issues/24990#issuecomment-1505940865)

### Describe the Use Case

Faster CI builds.

**Comment by liamdebeasi** [comment]
Thanks for the report. We do not have plans to add esbuild support at this time since it is experimental in Angular. However, we do have plans in the future to offer a way of using Ionic components without dynamically importing them. That should allow developers to test out the experimental esbuild support without Ionic needing to support any experimental APIs internally.

I am going to close this, but we hope to share more on the non-dynamic import solution soon.
