### ISSUE TITLE
bug: Ionic forum requesting read-write access to my public & private repositories

### ISSUE THREAD

**Issue by trakhimenok** [ionic-team/ionic-framework#27329]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I have a support question and wanted to post to https://forum.ionicframework.com/

But it presented be with this login:

![image](https://user-images.githubusercontent.com/533159/235185483-81664cc8-712f-4a23-8361-b93fa759dff3.png)

I'm usually not paranoid but why you need access to my repos at all? Even read access to public ones?

Read access to private is a problem - I keep secrets in some of them.

And while I myself not concerned you'll mess with my repose providing a write access is a potential thread as if hackers get access to your tokens they can do a lot of bad things to a lot of people.

### Expected Behavior

You request only personal information & email. No access to repos.

### Steps to Reproduce

Try to login to https://forum.ionicframework.com/

### Code Reproduction URL

https://forum.ionicframework.com/

### Ionic Info

Not applicable - not sure where to report it as https://forum.ionicframework.com/ is not accessible without granting too much permissions.

**Comment by liamdebeasi** [comment]
Hey there!

I reached out to the team responsible for maintaining this, and my understanding is that this is happening because the login permissions are tied to Appflow (CI/CD infrastructure for deploying applications). When logging into the Ionic Forums we **do not** read your repos (public or private), but I agree that this is a confusing experience. The team has expressed an interest in implementing granular permissions when logging in with GitHub which should resolve this issue.

We use this tracker for bugs/feature requests for Ionic Framework, not for the Ionic Forums so I am going to close this. However, I've escalated this internally so the team that maintains this is aware of the login behavior. Please let me know if you have any other questions.
