### ISSUE TITLE
bug: TypeError: Cannot read properties of null (reading 'remove')

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic-framework#27341]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

node_modules_ionic_core_dist_esm_ion-backdrop_entry_js.js:2 ERROR TypeError: Cannot read properties of null (reading 'remove')
    at destroyModule (update-swiper.js:58:24)
    at update-swiper.js:80:11
    at Array.forEach (<anonymous>)
    at updateSwiper (update-swiper.js:73:16)
    at SwiperContainer.updateSwiperOnPropChange (swiper-element-bundle.js:168:17)
    at SwiperContainer.set (swiper-element-bundle.js:221:12)
    at EmulatedEncapsulationDomRenderer2.setProperty (platform-browser.mjs:643:17)
    at BaseAnimationRenderer.setProperty (animations.mjs:292:27)
    at elementPropertyInternal (core.mjs:10801:18)
    at ɵɵproperty (core.mjs:13521:9)

### Expected Behavior

No run-time errors.

### Steps to Reproduce

**Git repo:** https://github.com/Sampath-Lokuge/ionic-swiper-issue

### Ionic Info

Ionic:

   Ionic CLI                     : 7.0.1 (C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.0.4
   @angular-devkit/build-angular : 15.2.7
   @angular-devkit/schematics    : 15.2.7
   @angular/cli                  : 15.2.7
   @ionic/angular-toolkit        : 8.0.0

Capacitor:

   Capacitor CLI      : 4.8.0
   @capacitor/android : 4.8.0
   @capacitor/core    : 4.8.0
   @capacitor/ios     : 4.8.0

Utility:

   cordova-res : 0.15.3
   native-run  : 1.7.1

System:

   NodeJS : v18.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.5.1
   OS     : Windows 10

### Additional Information

This happens only on the first load of the app. The Swiper functionality is working fine.

`html`

```
<swiper-container
  [initialSlide]="0"
  [speed]="400"
  [pagination]="false"
  [slidesPerView]="2"
  [modules]="swiperModules"
>
  <swiper-slide class="margin-right-5" *ngFor="let i of items">
    <ion-card class="width-100-pct" [style.height]="200">
      <ion-card-content class="ion-text-center">
        <app-home-item [item]="i" [isFavouritedItem]="isFavourited[i?.itemId]"></app-home-item>
      </ion-card-content>
    </ion-card>
  </swiper-slide>
</swiper-container>
```

**Comment by Sampath-Lokuge** [comment]
The problem is on this parameter ` [pagination]="false"`
Can you tell me how to set that?

**Comment by liamdebeasi** [comment]
Is `pagination` a Swiper-related property?

**Comment by Sampath-Lokuge** [comment]
Ionic doc says like so:

https://ionicframework.com/docs/angular/slides#properties 

i.e. `pager	Use the pagination property instead.`

So I had `ion-slides` like so.

<ion-slides pager="false" [options]="slideOptions" mode="md">

So I have used it like so:

```
<swiper-container
  [initialSlide]="0"
  [speed]="400"
  [pagination]="false"
  [slidesPerView]="2"
  [modules]="swiperModules"
>
```

**Comment by Sampath-Lokuge** [comment]
Please see this repo: https://github.com/Sampath-Lokuge/ionic-swiper-issue

Page: https://github.com/Sampath-Lokuge/ionic-swiper-issue/blob/main/src/app/home/home.page.html

> ionic serve

And just `refresh` the browser with the `dev console` opened. 

Error on the first load:

re.mjs:8400 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'remove')
TypeError: Cannot read properties of null (reading 'remove')
    at destroyModule (update-swiper.js:58:24)
    at update-swiper.js:80:11
    at Array.forEach (<anonymous>)
    at updateSwiper (update-swiper.js:73:16)
    at SwiperContainer.updateSwiperOnPropChange (swiper-element-bundle.js:168:17)
    at SwiperContainer.set (swiper-element-bundle.js:221:12)
    at EmulatedEncapsulationDomRenderer2.setProperty (platform-browser.mjs:643:17)
    at elementPropertyInternal (core.mjs:10801:18)
    at Module.ɵɵproperty (core.mjs:13521:9)
    at HomePage_Template (home.page.html:8:21)
    at resolvePromise (zone.js:1211:31)
    at resolvePromise (zone.js:1165:17)
    at zone.js:1278:17
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at core.mjs:23896:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:23896:36)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Object.onInvokeTask (core.mjs:24197:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
h

**Comment by Sampath-Lokuge** [comment]
I think the Ionic bug here is it doesn't have an Ionic Slider on Ionic 7 that worked nicely for many years for our apps. You have suggested using Swiper and now it is not working with Ionic. They do not accept Ionic apps. They ask to reproduce this on an Angular-only app. Then who will solve this?

**Comment by liamdebeasi** [comment]
I'm able to reproduce this issue even after removing all Ionic-related code from the application, so I don't think this is an Ionic bug. The Swiper team requested a non-Ionic reproduction so that they could rule out Ionic as the source of the issue. In this case, I don't see any indication that Ionic is the source of this bug. You can check this by doing the following:

1. Remove usages of any `ion-` components (You can change `ion-router-outlet` to `router-outlet`)
2. Remove `IonicModule` from `app.module.ts`.
3. Remove Ionic CSS in `global.scss`.

**Comment by Sampath-Lokuge** [comment]
I was able to find out the Ionic bug here.

i.e. `[pager]="true"` is not working with `swiperModules = [IonicSlides];` implementation. And  `[initialSlide]="3"` also not working. But this works ` [slidesPerView]="2"`. I hope it can have more none working properties here with Ionic.

**Comment by Sampath-Lokuge** [comment]
Can you show the `swiper component` set up here for the above error?

**Comment by liamdebeasi** [comment]
This is in `home.page.html`:

```html
<swiper-container [pagination]="false">
  <swiper-slide>Slide 1</swiper-slide>
  <swiper-slide>Slide 2</swiper-slide>
  <swiper-slide>Slide 3</swiper-slide>
</swiper-container>
```

**Comment by Sampath-Lokuge** [comment]
Yes, this is wrong. We need to use `pagination="true"` here. 

But hence we use `swiperModules = [IonicSlides];` we must able to use [pager]="true" here with property bindings. But it doesn't work.

**Comment by Sampath-Lokuge** [comment]
No, it works like so too without any errors `pagination="false"`

My question here is why we need this `swiperModules = [IonicSlides];` if we cannot use Ionic properties with swiper. e.g. `[pager]="true"` doesn't work?

**Comment by liamdebeasi** [comment]
As explained in the [Swiper migration guide](https://ionicframework.com/docs/angular/slides#the-ionicslides-module), the `IonicSlides` module is **not** required to use Swiper.js.  You can exclude it if you do not need it.

Additionally, the [properties section of the migration guide](https://ionicframework.com/docs/angular/slides#properties) also calls out that certain properties have changed names. This means that the `pager` property is now the `pagination` property. The `IonicSlides` module configures certain properties on the Swiper instance. It does not allow you to continue referencing the `pager` property. You can see all the properties is configures here: https://github.com/ionic-team/ionic-framework/blob/02d722e9e1526ff2ca461c2a79db4332e001135e/core/src/components/slides/IonicSlides.ts#L4

I've taken a look at the sample reproduction a few times now, and I don't see anything that would indicate this is an Ionic bug. However, I was able to reproduce the reported error outside of Ionic. I recommend filing an issue with the Swiper team and including a reproduction of this problem happening **outside of Ionic**. Providing a reproduction of the issue outside of Ionic is very important because it allows the Swiper developers to rule out Ionic as the source of the issue.

**Comment by Sampath-Lokuge** [comment]
It doesn't have a problem with their component hence they do not use `property bindings`. They just use `attribute bindings` like so and it works without error `https://swiperjs.com/element#pagination-navigation-scrollbar` and this works `pagination="false"`.

But with Ionic, we use `property bindings` and it doesn't work  [pagination]="false". This is an Ionic bug here.

**Comment by liamdebeasi** [comment]
Ionic only manages the property bindings on Ionic components. Swiper Element is **not** an Ionic component. It looks like Swiper Element does not support property bindings, which is why you are running into this issue. As I mentioned in https://github.com/ionic-team/ionic-framework/issues/27341#issuecomment-1530047999, this is not an Ionic bug. If you want to use Angular property bindings with Swiper Element, you should file a feature request on https://github.com/nolimits4web/swiper.

**Comment by liamdebeasi** [comment]
Swiper Element expects you to use `pagination` as an attribute, so you should use Angular's attribute binding in the meantime: https://angular.io/guide/attribute-binding

So instead of `[pagination]="true"` you should do `[attr.pagination]="true"`

**Comment by agustinhaller** [comment]
Hi @liamdebeasi I'm experiencing the same issue. Is there a chance it's something related to [this issue](https://github.com/ionic-team/ionic-framework/issues/26722#issuecomment-1422266983)?

**Comment by Sampath-Lokuge** [comment]
@agustinhaller What is your issue? This works for me:

```
<swiper-container
  [initialSlide]="0"
  [speed]="400"
  [pager]="false"
  [slidesPerView]="2"
  [modules]="swiperModules"
>
  <swiper-slide *ngFor="let s of shopCurations">
  //content
  </swiper-slide>
</swiper-container>
```
