### ISSUE TITLE
feat: Angular 16/TypeScript 5 Support

### ISSUE THREAD

**Issue by godenji** [ionic-team/ionic-framework#27384]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Angular 16 has just been released, and with it some breaking changes, most notably as far as current Ionic is concerned, TypeScript 4.8 is no longer supported. According to corresponding [package.json](https://github.com/ionic-team/ionic-framework/blob/main/angular/package.json#L88) it looks like Ionic/Angular is on TS 4.7.x.

Here's the [changelog](https://github.com/angular/angular/blob/main/CHANGELOG.md)

Angular v16 seems like an absolutely epic release, lot's to like there -- hopefully Ionic users can benefit in the not too distant future.

### Describe the Use Case

Ionic users can benefit from the latest & greatest in Angular v16.

**Comment by sean-perkins** [comment]
Hello @godenji, are you having any specific issues with using Ionic Framework with Angular 16? 

Our test infrastructure validated Angular 16's RC releases against `@ionic/angular@7` and I also verified with a blank starter project that developers can upgrade their apps to use Angular 16 and Typescript 5 today. 

We will be updating our starters so that the default experience will use the latest version of Angular in the near future.

**Comment by godenji** [comment]
You can close this, my upgrade attempts were failing due to missing peer
deps unrelated to Angular upgrade (i.e. legacy ionic native cordova plugins
that I needed to migrate to Capacitor).

**Comment by godenji** [comment]
@sean-perkins  there is one blocker that I and others have hit in attempting to upgrade to Angular 16 --see  [ionic-storage issue](https://github.com/ionic-team/ionic-storage/issues/293)
