### ISSUE TITLE
feat: Using component SLOT in modalController 

### ISSUE THREAD

**Issue by szahharenko** [ionic-team/ionic-framework#27612]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

While rendering component using `modalController.create({ component: 'sample-component'})` it is not possible to pass content for `sample-component` `<slot/>`

### Describe the Use Case

Slot functionality is very flexible and gives a lot of possibilities. Right now only possible way to render is convert slot content into properties.

### Describe Preferred Solution

Add `slot` property for `ModalOptions`
`modalController.create({ component: 'sample-component', slot: <h1>I'm a slot content</h1> })` 

### Describe Alternatives

Only possible solution right now is pre-define all possible content, and use them as component properties.

**Comment by szahharenko** [comment]
> > Thanks for the report. Modals and popovers are designed to accept a single component. You have a couple options for adding slotted content:
> > 
> > 1. Create a new component that encapsulates `sample-component` with your slotted content. This means creating a `wrapped-sample-component` component that renders the following:
> > 
> > ```
> > <sample-component>
> >   <div>my slotted content</div>
> > </sample-component>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > From here, you could pass `wrapped-sample-component` to the `component` property on the `modalController` instead of `sample-component`.
> > 
> > 2. Create the `sample-component` element before calling `modalController.create` and set the slotted content. This involves calling `document.createElement`. This approach is not recommended as it involves using `innerHTML` which can open your app to XSS vulnerabilities if the content being passed is not trusted.
> > 
> > ```js
> > const cmp = document.createElement('sample-component');
> > cmp.innerHTML = '<div>my slotted content</div>';
> > 
> > const modal = await modalController.create({ component: cmp });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do either of these work for your use case?
> 
> Not really, my case is I created a nice looking `are-you-sure?` dialog with YES/CANCEL buttons, and some sad smile face... so I want to have a flexible way to deliver this modal content... like header, description, etc... so slot was good way to do it... so `innerHTML` is not exactly what i'm looking for :) but thx for suggestion

`<Host>`
`        <img src={getAssetPath('./assets/sad-face.svg')} />`
`        <slot/>`
`        <organism-section-footer`
`          buttons={this.actionButtons}`
`        ></organism-section-footer>`
`</Host>`

**Comment by liamdebeasi** [comment]
Thanks for the reply. In that case, I recommend adding properties to the `are-you-sure` component. The component would then be responsible for rendering the header, description, etc content. From there, you can pass `are-you-sure` to the modalController and then the appropriate component properties:


```js
await modalController.create({ 
  component: 'are-you-sure', 
  componentProps: { header: 'Header Text', description: 'Description text' }
});
```

Note that this approach only allows for plaintext. If you need custom HTML you'll want to create a separate component that encapsulates both `are-you-sure` and your custom HTML (which is the first scenarios I described in https://github.com/ionic-team/ionic-framework/issues/27612#issuecomment-1580694821).

Since the requested behavior can be achieved in the two ways I described, I am going to close this. If you have questions about implementation patterns I recommend posting on the [Ionic Forums](https://forum.ionicframework.com/). Thanks!
