### ISSUE TITLE
Two menus and only one will be displayed on large devices

### ISSUE THREAD

**Issue by leocharrua** [ionic-team/ionic-framework#27613]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Get two menus together, and only one of the menus (the main menu) will be displayed on large devices, and the other one (the settings menu) should be hidden like on smaller devices.

### Describe the Use Case

I’m trying to get together two menus:

```
<ion-split-pane contentId="main-content">
   <ion-menu side="start" menuId="master" contentId="main-content">
      ... Main Menu ...
   </ion-menu>
   <ion-menu side="end" menuId="settings" contentId="main-content">
      ... Settings Menu ...
   </ion-menu>
   <ion-router-outlet id="main-content"></ion-router-outlet>
</ion-split-pane>
```

Is it possible that only one of the menus (the main menu) will be displayed on large devices? The other one (the settings menu) should be hidden like on smaller devices.

I trying add when="false" at ion-split-pane tag, but both menues are affected.

**Comment by liamdebeasi** [comment]
Thanks for the report. At the moment we don't have support for configuring the `when` property independently for multiple menus within the split pane. However, you could probably hide the settings menu using `display: none` which is what `when` is doing under the hood.

```css
/* Hide the settings menu on screens less than or equal to 992px in width */
@media screen and (max-width: 992px) {
  .settings-menu {
    display: none;
  }
}
```

**Comment by leocharrua** [comment]
Thanks for your answer. 

I added `class="settings-menu"` at the menu with `menuId="settings"` and in the scss file:

```
.settings-menu {
   display: none;
}
```

But when I activate the settings menu it not showing.

I must do anything else to get it working?

Thanks

**Comment by liamdebeasi** [comment]
The menu adds a `.menu-enabled` class whenever the menu is enabled. You can try using that class to conditionally apply `display: none`

**Comment by leocharrua** [comment]
I'm sorry, I don't realize what you're telling me. Can you be more specific?
Thanks

**Comment by liamdebeasi** [comment]
Since you are hiding the menus using `display: none`, calling `menuEl.open()` isn't going to work because your `display: none` styles are still applied. You'll want to make sure that those styles are removed when opening the menu. The other option is to disable/enable the menu first using the `disabled` property which will take care of hiding/showing the menu for you.

However, `ion-split-pane` isn't really designed to be used like this so I would caution against it. Instead, I recommend having a single menu and having settings be another view such as a modal.

**Comment by leocharrua** [comment]
Sorry, but could you consider the mentioned functionality? I think if Ionic supports multiple side menus, it should also support that these have different behaviors, right?

**Comment by liamdebeasi** [comment]
Can you provide your use case for this feature? (What you are trying to implement in your app)

**Comment by leocharrua** [comment]
For example, right now, the user want two menues: 

1) The classic menu to access the functionality of the App
2) A menu that is displayed only in the lists, which allows to apply filters and ordering modes

Both menus should be hidden on small screens, but on the rest, menu 1 should always be visible and 2 always hidden.

**Comment by liamdebeasi** [comment]
Do you have examples of native apps that implement this dual-menu pattern? Side menus are typically top-level components, so using menus in this way is not recommended. You might want to try using a modal or a popover for the second menu for filtering/ordering.

**Comment by leocharrua** [comment]
I don't have any example of "native app", but the solution of two menus is perfect for the client. Obviously, you can show a "modal" with the filter/sort options, but with the menus it is very elegant and works perfect.

**Comment by liamdebeasi** [comment]
I'm mainly trying to understand why two menus is the preferred solution here. Given that this isn't a recommended pattern on mobile, I'm a bit hesitant to add this feature for all Ionic devs.

**Comment by leocharrua** [comment]
For example, the side menu allows you to apply the filters and see the result in the list at the same time, it does not block the view like a modal does.
An example of native app could be the ebay app.

**Comment by liamdebeasi** [comment]
The Ebay app has a single menu in this case, which is different from the use case provided on this thread. I understand the benefit of using a menu to apply filters, but I'm trying to understand why both views need to be separate menus.

**Comment by leocharrua** [comment]
The main menu is for navigate to the functions of all App, the other menu (filters) is only for the list pages that need the filter/sort actions.

**Comment by liamdebeasi** [comment]
Thanks for the additional information. I brought this up with the team, and we do not have plans to add the requested functionality at this time.

As I noted above, nested menus is an anti-pattern and not recommended. The [Material Design Guidelines](https://m3.material.io/components/navigation-drawer/guidelines#422511cb-e9d6-41b5-b342-609fba2c5d01) also state that menus should not be used with other primary navigation components (menu is a primary navigation component). Ionic follows the iOS and Material Design guidelines for our components.

In terms of alternatives, I previously proposed using a modal instead of the secondary menu. You could also use a popover instead of a modal or make the modal a sheet modal if you want to let users see the content underneath. Another idea is to make the primary menu a tabs component using `ion-tabs` and keep the secondary menu. This would violate the Material Design guidelines, but it is an option if your app's UI is custom and deviates from the Material Design guidelines. I believe the Ebay app you mentioned does something similar.

I am going to close this, but let me know if you have any questions.
