### ISSUE TITLE
ionKeyboardDidShow and ionKeyboardDidHide browser keyboard events stopped working

### ISSUE THREAD

**Issue by guy-a** [ionic-team/ionic-framework#27654]
https://github.com/ionic-team/ionic-framework/blob/d3232dcc007738fae851660bd818c8056b48b7d2/core/src/utils/keyboard/keyboard.ts#LL34C2-L34C2

Keyboard.getEngine() returns false and never undefined, hence the else block will never run and visualViewport.onresize is never registered.

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce the behavior. As mentioned, the problem is if Capacitor is available but the Keyboard plugin is not, that function returns `false`. If Capacitor is not available it returns `undefined`. Our automated tests do not have Capacitor available so we did not catch this case during testing. I will work on a fix.

**Comment by liamdebeasi** [comment]
Thanks for the report. This is fixed in Ionic v7.0.14 which came out a few minutes ago.

**Comment by guy-a** [comment]
Thank you for the extremely fast response and fix :)
