### ISSUE TITLE
feat: Update package.json to latest

### ISSUE THREAD

**Issue by vitalijalbu** [ionic-team/ionic-framework#27717]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Would be great to have all latest versions for ionic start CLI

<img width="389" alt="Screenshot 2023-06-29 alle 09 43 19" src="https://github.com/ionic-team/ionic-framework/assets/40239902/226df94e-7d22-42e9-a7d6-4a9522f3d10e">

### Describe the Use Case

Using ionic CLI there are several libraries to update

### Describe Preferred Solution

Update them all

**Comment by liamdebeasi** [comment]
Hi there,

Most of these dependencies are running the latest version when you do an `npm install`. For example, `@ionic/react: ^7.0.0` will actually install `7.1.1` since the `^` says to install the latest minor/patch version while avoiding major releases.

You can test this by running `npm ls [package name]`:

```shell
npm ls @ionic/react

├─┬ @ionic/react-router@7.1.1
│ └── @ionic/react@7.1.1 deduped
└── @ionic/react@7.1.1

```

The libraries highlighted in red will need to be manually updated by us because `^` will not install the latest major release. I have added a PR in https://github.com/ionic-team/starters/pull/1787 to address those changes.

The exception is for the React Router packages because we do not support React Router v6 yet. We are tracking support for this in https://github.com/ionic-team/ionic-framework/issues/24177.


------

I am going to close this since https://github.com/ionic-team/starters/pull/1787 will resolve this, but let me know if you have any questions.
