### ISSUE TITLE
bug: ion-select voice over recognizing as buttons

### ISSUE THREAD

**Issue by Malnag** [ionic-team/ionic-framework#27728]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Ion-select when voice over is on both on iOS and android it reading the options as buttons 

### Expected Behavior

When voice over is on it has to read out all the options and ask the user to select one option

### Steps to Reproduce

Ion-select with voice over 

### Ionic Info

Ion-select ion-select-option with array of options

**Comment by liamdebeasi** [comment]
Thanks for the report. `ion-select` is a button, so it being announced as such is the intended behavior. The options are only announced once the select dialog is presented. This behavior aligns with the native `<select>` behavior: https://codepen.io/liamdebeasi/pen/VwVbWXw

Can you please clarify what your expected behavior is?
