### ISSUE TITLE
feat: Consider adding repo-review badge to README

### ISSUE THREAD

**Issue by richardanderson001** [ionic-team/ionic-framework#27912]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Thanks for creating this repo!

Would you be interested in adding a **review** badge to the README?

<a href='https://github.com/repo-reviews/repo-reviews.github.io/blob/main/create.md' target="_blank"><img alt='Github' src='https://img.shields.io/badge/review-100000?style=flat&logo=Github&logoColor=white&labelColor=888888&color=555555'/></a>

### Describe the Use Case

These help the open-source community collect and share UX stories via http://repo-reviews.github.io and thereby increase productivity, sponsorship, and cross-pollination on a global scale.

Happy to provide one in a PR!

**Comment by liamdebeasi** [comment]
Thanks for opening this issue! I can definitely appreciate reviewing repos with the goal of helping improve them. In particular, documenting experiences contributing and running projects locally is valuable. As project maintainers we sometimes overlook the rough edges in getting started with building a project locally since we do not go through that flow every single day.

However, I would prefer that GitHub issues continue to be the recommended route for suggesting improvements to Ionic Framework. The benefit of issues is that it enables the team to have a conversation with the reporter and make sure we are addressing the root problem. While the proposed badge makes it easy to provide feedback, that feedback does not necessarily always get back to the team, and we are unable to easily follow up with the reviewer. As a result, we do not have plans to add the proposed badge. I am going to close this, but let me know if you have any questions. Thanks again!

**Comment by richardanderson001** [comment]
Thanks, what a thoughtful response!

When someone writes a review, they are automatically prompted to submit an issue in the reviewed repo, thereby notifying the repo so any issues in it can be flagged.  However the purpose of reviews is not to flag issues, but share UX stories- for example:
- the repo could be working as intended, but might not be a suitable fit for a particular user, stack, or implementation
- the repo could be losing momentum, core team moved on, or have other development meta-issues that would be helpful sharing
- particular critical issues are `wontfix` or on a long-term roadmap

In these cases, it can save a person hours if not days of work to read through reviews (I speak from personal experience, which is why I'm a fan).

I hope that helps to explain the goal of sharing UX stories in an independent, transparent, and centrally-located repo.  

Completely understand and respect your choice to close as not planned 👍
