### ISSUE TITLE
feat: export openURL utilities 

### ISSUE THREAD

**Issue by mikaelkaron** [ionic-team/ionic-framework#27911]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

It would be nice to have the framework utilities exported for general use. I'm personally interested in [`openURL`](https://github.com/ionic-team/ionic-framework/blob/main/core/src/utils/theme.ts#L40) but other utilites would also be great.

My current solution is to replicate the exact code (as I'm doing the exact same thing) but this feels like a waste of bytes.

### Describe the Use Case

Avoid replicating common code, promote best practice, stay DRY?

### Describe Preferred Solution

Exporting framework utils

### Describe Alternatives

copy-pasta

**Comment by liamdebeasi** [comment]
Thanks for the report. Are there things that you are unable to do without access to our implementation of `openURL`, or is this mainly focused on reducing code duplication?

**Comment by mikaelkaron** [comment]
reducing code duplication and staying up-to-date with routing in ionic.

**Comment by liamdebeasi** [comment]
Thanks for the reply. We are open to exporting the `openURL` utility. Are you interested in creating a PR for this?

**Comment by akshathphillips** [comment]
Hello. I am interested in working on this. Is this still relevant?

**Comment by liamdebeasi** [comment]
Yes, we would love a community contribution! To add this feature, we need to ensure the following function is exported from the 4 main Ionic packages: https://github.com/ionic-team/ionic-framework/blob/71a7af0f52fe62937b1dea1ca2739e78801a2a6d/core/src/utils/theme.ts#L40

Core: https://github.com/ionic-team/ionic-framework/blob/main/core/src/index.ts
Angular: https://github.com/ionic-team/ionic-framework/blob/main/packages/angular/src/index.ts
React: https://github.com/ionic-team/ionic-framework/blob/main/packages/react/src/components/index.ts
Vue: https://github.com/ionic-team/ionic-framework/blob/main/packages/vue/src/index.ts

I recommend making your branch based off the `feature-7.5` branch since that is the next scheduled feature release. Let me know if there are any questions.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28295, and the feature will be available in an upcoming release of Ionic Framework.
