### ISSUE TITLE
bug: AlertButton types do not autocomplete with available options

### ISSUE THREAD

**Issue by izyumidev** [ionic-team/ionic-framework#27965]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Support for autocomplete for the two types defined `cancel` and `destructive`, and also supports any arbitrary string if passed in.

### Describe the Use Case

Whenever using the AlertButton, autocomplete will help with correctness, such as not making mistakes with spelling.

### Describe Preferred Solution

Solution listed in https://github.com/ionic-team/ionic-framework/pull/27940

**Comment by NextThread** [comment]
hey, can I work on this?

**Comment by sean-perkins** [comment]
Hello @aapl-yumi thanks for creating this ticket! I think we should track this as a bug with the existing implementation. I'll update the title accordingly. 

We had a similar issue with Ionic colors with the `color` attribute in the past and it is a limitation of doing a union type with a `string`. We ended up using a `Record<never, never>` union to resolve it for that problem - likely should do a similar thing here. 

I'll reply to your PR with more feedback shortly, but we should address this 👍 

@NextThread I appreciate your interest in contributing! Since the work is already in progress, I don't think this ticket would be a good one for you to pick up. If there are any other tickets that you are interested in or if you are generally interested in contributing to open source in general - you can message me in the Ionic discord and I'd be happy to help get you started!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27940, and a fix will be available in an upcoming release of Ionic Framework.
