### ISSUE TITLE
feat: integrate sheet modals into card modal animation

### ISSUE THREAD

**Issue by ngmiduc** [ionic-team/ionic-framework#28016]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Hi!

Is there actually a way to make the card-modal animation work with a page that has an opened sheet modal? For the moment, the sheet modal is not resizing. I was wondering if there are any ways to make it work.

### Describe the Use Case

1. User is opening a sheet modal with some action buttons.
2. The action buttons are opening a card modal to process a specific action
3. The sheet modal should stay open, so when the user cancels the process, the user returns to the sheet modal.

### Describe Preferred Solution

1. The opened sheet modal should resize too when its parent is resized for the card-style animation.
2. Allow to add an array with presenting elements.

### Related Code

https://stackblitz.com/edit/angular-yw7orl?file=src%2Fapp%2Fexample.component.html

**Comment by liamdebeasi** [comment]
Thanks for the report. This is already possible with Ionic. Instead of passing the base page to `presentingElement` you should pass the sheet modal instance.

Here is an example: https://stackblitz.com/edit/angular-yw7orl-fzwjux?file=src%2Fapp%2Fexample.component.ts,src%2Fapp%2Fexample.component.html

Note that in this case the main page content does not resize. This is the correct behavior because it is the sheet modal that presents the card modal, not the page element. This is also the behavior found in applications like Apple Maps. Tapping "More" in the sheet modal opens a card modal, and the sheet modal scales.

I am going to close this since the request is already possible in Ionic, but let me know if you have questions.
