### ISSUE TITLE
feat: checkbox, radio, range, toggle expose label shadow part

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/ionic-framework#28300]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

As for all other input elements like ion-select and ion-input, ion-range should also get the new implementation of labels with a part attribute attached for styling and customizations.

![image](https://github.com/ionic-team/ionic-framework/assets/11534760/78f9b6df-a1cc-42fc-8956-5548f95b99c0)

### Describe the Use Case

I am building a consistent styling for all input elements in our app where the label is outside the input box, but the input box has a shadow and other styling. This works for all other elements pretty well, thanks for the work in that.

![image](https://github.com/ionic-team/ionic-framework/assets/11534760/c487657b-af34-4e55-b077-4b2a497a0460)

### Describe Preferred Solution

Slots

### Describe Alternatives

No shadow-dom

### Additional Information

~~I remember that there have been a lot of label issues opened, but couldn't find one related to slots and ion-range.~~

**Comment by muuvmuuv** [comment]
Ah yes, sorry, it's not clear because it is both named “slot”. I mean for styling, that I have a slot in HTML to select via CSS when it is in the shadow-dom. Alternatively, avoid shadow-dom like it's in some other ion components when using labels. I think it is really inconsistent between components.

**Comment by liamdebeasi** [comment]
When using the label slot all of the content is in the light DOM, so you can style it directly: https://codepen.io/liamdebeasi/pen/qBLgdpR

**Comment by muuvmuuv** [comment]
Liam I am so sorry, I meant "part"... hard week, pretty under stress with migrating our forms module and implementing other features.

Here is my repl. You see that range has shadow-dom without [part], ion-input has no shadow-dom and ion-select has shadow-dom but with [part]. That is what I meant with inconsistency.

https://codepen.io/muuvmuuv-the-selector/pen/ExGrjRg

**Comment by liamdebeasi** [comment]
Thanks for the clarification. So the reason why there appears to be styling inconsistency is two reasons:

1. **You're using different APIs meant for different use cases.**

The "label" shadow part on `ion-select` is designed for use cases where you want to render the label and the container separately. For example, developers may wish to have a border around the container and have the label render outside of that container. We don't provide a "label" shadow part on the range because that component does not have the same use case as the select.

The "label" slot is for developers who wish to only customize the label. We provide slotted labels all of our form controls so you can style the labels in a consistent manner.

2. **Input does not use the shadow DOM due to an old WebKit bug.**

We do have plans to consolidate our form controls to use the Shadow DOM, but we need to wait for drop support for older versions of iOS unfortunately.

**Comment by muuvmuuv** [comment]
Thanks, so then it makes sense ion-input differs.

> For example, developers may wish to have a border around the container and have the label render outside of that container. We don't provide a "label" shadow part on the range because that component does not have the same use case as the select.

This is exactly what I want to acomplish (see my screenshot) but not possible at the moment due to no access to the inner shadow-dom with the part attribute.

I don't really understand how the both cases differ for label. The label slot becomes the shadow part on ion-select and I need to use the slot because the label is coming from our backend with HTML.

As you see in my link above (updated it with styling), I have no problems styling the other controls, but the ion-range has no part's attributes I could select.

**Comment by liamdebeasi** [comment]
Thanks for the clarification. I think it makes sense to just expose the shadow part for the components since it's confusing that some form controls have it and some do not.

**Comment by AntoscencoVladimir** [comment]
@liamdebeasi Hello, is there any update please? I have an issue with ion-radio and new implementation, I can't adjust the margin of the label because label part is not exposed.
This codepen https://codepen.io/liamdebeasi/pen/qBLgdpR also not working.
The ion-radio is placed in ion-item and I need to have possibility to adjust height and also the margin between ion-radio and label (for this exposing part will be enough thought)

Thanks in advance!

**Comment by Deval99** [comment]
I am using ion-select, and i want to customise the label
it uses ion-popover instead of ion-select-option, as i am using interface="popover"
slot attribute adds a label inside ion-select-option, not in ion-popover

main problem is, label is inside ion-radio,
![image](https://github.com/ionic-team/ionic-framework/assets/47087136/eb39e919-d58e-4817-b5e4-096ffe2abef6)
unlike previous version
![image](https://github.com/ionic-team/ionic-framework/assets/47087136/de98d4ae-e094-4a80-a76e-ad3c2cecfc11)
