### ISSUE TITLE
feat: CSS Shadow Parts targeting the ion-toggle label

### ISSUE THREAD

**Issue by CallumMcFadgen** [ionic-team/ionic-framework#28382]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Need some way to reduce the margin-bottom of the ion-toggle in the new syntax (version 7.4 upwards).  Currently the margin-bottom of the ion-toggle label-wrapper has no CSS variables or shadow parts that can be targeted.

### Describe the Use Case

The label on the ion-toggle appears to have a greater margin-bottom than the other labels, making the appearence of a multi input form look inconsistent, see pic.

![Screenshot 2023-10-12 at 16 05 43](https://github.com/ionic-team/ionic-framework/assets/52138880/01feae0a-839c-4eb8-8289-37c475b614e5)

### Describe Preferred Solution

New CSS Shadow parts or CSS variables allowing styling for the ion-toggle label.

**Comment by liamdebeasi** [comment]
Thanks for the report. If we adjusted the margins on the toggle to be consistent with the other form controls, would that resolve the issue for you?

**Comment by CallumMcFadgen** [comment]
Hi Liam,

I think that just adjusting the margin would solve our problem, we haven't got any additional styling on the labels for any of form controls and dont have any plans to add any so if you adjust that bottom margin for the ion-toggles text-label-wrapper to match the other form controls then it should give our forms a consistent appearance :)

Thanks,
Callum

**Comment by SebastianKohler** [comment]
I would be very interested in a shadow part targeting the ion-toggle label, in order to, for instance, apply a bold or italic font or a background color to it.

In my app I use background colors on certain parts of text to highlight certain things (like persons, place names), and you can toggle which text highlights should be visible. The highlight color is displayed on the toggle, but currently I have to apply it to the background of the whole ion-toggle component since I can't target the label only:

![ion-toggle](https://github.com/ionic-team/ionic-framework/assets/74658813/74a8d2c6-8296-493e-a05d-9443bfe3cab6)

What I would like to be able to achieve is applying a background only to the labels, like this:

![ion-toggle-label](https://github.com/ionic-team/ionic-framework/assets/74658813/719c3db1-7cdb-4e06-8cec-af075d0d2a80)

**Comment by liamdebeasi** [comment]
Thanks everyone! I think exposing the label part here makes sense. We already have a request for this in https://github.com/ionic-team/ionic-framework/issues/28300, so I am going to merge the two threads. Let me know if there are any questions.
