### ISSUE TITLE
bug: RouterDirection 'none' is missing

### ISSUE THREAD

**Issue by mpaland** [ionic-team/ionic-framework#28475]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

in file /core/src/components/router/utils/interface.ts, line 66, the type `'none'` is missing on the `RouterDirection` type.
This gives a ```error TS2322: Type '"none"' is not assignable to type 'RouterDirection | undefined'``` when building.

I tried to use:
```
 <ion-item :class="{active: currentRoute == '/devices'}" style="--background: none" :detail="false" router-link="/devices" router-direction="none">
```

### Expected Behavior

No Lint error.

### Steps to Reproduce

Using router-direction="none"

### Ionic Info

Ionic CLI       : 7.1.1 (C:\Users\Marco\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 7.5.3

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : not installed
   @capacitor/core    : 5.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.4

System:

   NodeJS : v18.17.1 (D:\nodejs\node.exe)
   npm    : 10.2.1
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. We should probably add this keyword since some of our routers implement it. The "none" keyword lets you disable animations whereas "root" clears the internal navigation stack and disables the animation. Long term we should probably see if we can improve this API since it's not immediately clear what the difference between the two is. Not every navigation component will actually use the "none" keyword, but for now I think it's important to unblock the type error.

Are you interested in making a PR for this?
