### ISSUE TITLE
feat: Restore old ion-datetime

### ISSUE THREAD

**Issue by van9petryk** [ionic-team/ionic-framework#28517]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Old ion-datetime, like in ionic v4, was awesome. Didn't understand why it was removed. I used it in my form from the box. Now I need to create my own component.

### Describe the Use Case

ion-datetime in form

**Comment by liamdebeasi** [comment]
Hey there,

Ionic supports the wheel picker layout that was found in v4: https://ionicframework.com/docs/api/datetime#wheel-style-pickers

If you'd like to continue showing the datetime in an overlay, we also have `ion-datetime-button` which handles that: https://ionicframework.com/docs/api/datetime-button

The datetime component also has logic built in such that the selected value will show up in form submission. I'm going to close this since the requested features are already available in Ionic.
