### ISSUE TITLE
feat: Make Ion-Datetime Wheel Picker More Desktop-Friendly

### ISSUE THREAD

**Issue by de-dan** [ionic-team/ionic-framework#28553]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

tl:dr; I want to basically reopen what's requested here: https://github.com/ionic-team/ionic-framework/issues/27414

With Ionic being a versatile framework catering to both mobile and web applications, there's a need for components that seamlessly optimize user experiences across platforms. Currently, the wheel picker in Ion-Datetime is primarily designed for mobile applications, leading to suboptimal user interactions on desktop.

While it's understood that the wheel picker UX is tailored for mobile, this limitation poses challenges for developers aiming to create applications that work seamlessly on both mobile and desktop environments. Simply stating that the wheel picker is not intended for desktop use doesn't provide a satisfying solution.

### Describe the Use Case

As a developer, I propose an enhancement that either introduces an alternative component or optimizes the existing wheel picker for desktop usage. The goal is to have a single, unified component that delivers an optimal experience on both mobile and desktop platforms.

It's noteworthy that the `<ion-datetime>` component already features a wheel picker for time selection on desktop. This implementation supports keyboard and mouse wheel controls, providing a comfortable user experience. However, users accustomed to clicking and dragging the numbers on the mobile version may face challenges on desktop due to differences in interaction patterns.

To address this, I suggest extending the `<ion-datetime>` features or incorporating the behavior seen in `<ion-picker>`, allowing users to click and drag numbers comfortably on the desktop version.

This enhancement would not only improve the user experience for desktop users but also simplify development for those seeking a consistent solution across platforms. It aligns with the spirit of Ionic's versatility and ease of use.

Thank you for considering this feature request. I believe it will contribute to a more seamless and enjoyable user experience for developers and end-users alike.

### Describe Preferred Solution

Enhance Ion-Datetime to offer a unified wheel picker experience across mobile and desktop platforms. Implement click-and-drag functionality for desktop users, ensuring a seamless transition for those accustomed to the mobile version. Retain support for keyboard and mouse wheel controls to provide a consistent and user-friendly experience. This solution maintains the simplicity of a single <ion-datetime> component while optimizing it for diverse user interactions, aligning with Ionic's commitment to versatility and ease of use.

**Comment by liamdebeasi** [comment]
Thanks for filing this feedback! We definitely appreciate the desire to have `ion-datetime` become more desktop-friendly. However, Ionic Framework is focused on mobile applications, and desktop applications are outside the scope of what Ionic Framework is designed for.

We had multiple desktop-focused initiatives in the past, but those did not work out because it was challenging to account for both desktop and mobile behaviors within the same component. For some components like `ion-reorder` or `ion-button` it was easy, but not so much for more complicated components such as `ion-datetime`. In those cases, we found that we had to compromise the mobile experience in order to get some desktop features.

After multiple attempts of trying to add desktop support into a mobile-specific framework, we decided to focus entirely on mobile. The team is prioritizing that commitment moving forward so unfortunately we do not have plans to add desktop enhancements to `ion-datetime` at this time. I am going to close this, but let me know if you have any questions.
