### ISSUE TITLE
bug: css-variables default values not available

### ISSUE THREAD

**Issue by ausminternet** [ionic-team/ionic-framework#28559]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I tried to get a border around an `<IonList inset>`. I looked up the variable for this case on https://ionicframework.com/docs/theming/themes and set the border for the list to `--ion-item-border-color` - and nothing happened.

After a bit of research and looking into the code I managed to find out that this variable seems to be only used to _change_ the default color of a border as it is defined in the ion item like:

```--border-color: var(--ion-item-border-color, var(--ion-border-color, var(--ion-color-step-250, #c8c7cc)));```

### Expected Behavior

I expect the variables from https://ionicframework.com/docs/theming to have their default values and to be available on `:root` of the App so that I can use them to make custom elements with the correct styles. 

### Steps to Reproduce

create ionic app and try to use some of the variables from https://ionicframework.com/docs/theming

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.5 (/Users/jah/.nvm/versions/node/v18.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.5.5

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : not installed
   @capacitor/core    : 5.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.16.0 (/Users/jah/.nvm/versions/node/v18.16.0/bin/node)
   npm    : 9.5.1
   OS     : macOS Unknown

**Comment by ausminternet** [comment]
Your example ist exactly what I _don't_ want to do: creating my own styling or recreating a default/ion-styling. Instead I would like to use the same styling that is used for the ion-item.

I would like to write:

```
div {
  border: var(--ion-border-width) solid var(--ion-item-border-color);
 }
 ```
 
 and get an div, that has the exact same border-color and border-width as an ion-item and has the correct values on ios and android.

**Comment by liamdebeasi** [comment]
The global variables exist so developers can override our defaults. These defaults are baked into Ionic so that components still render correctly even if these global CSS variables are not set. This is true for other global variables such as the color tokens.

Setting defaults for these variables will require all developers to have these tokens defined in their applications which is a breaking change. It also means that using the base Ionic components will not render correctly by default since those global tokens are not defined. For example, the playgrounds on https://ionicframework.com/docs/api/item render correctly even if `--ion-item-border-color` is not set.

-------

You example could be further simplified to look something like this:

```css
:root {
  --ion-border-color: var(--ion-color-step-250, #c8c7cc);
}

ion-list {
  border: 1px solid var(--ion-border-color);
}
```

The `--ion-color-step-250` is for dark mode, so you can safely omit this part if you do not plan to use dark mode in your app.
