### ISSUE TITLE
feat: Add support for having a scrollbar on the root document element.

### ISSUE THREAD

**Issue by KyleSmith0905** [ionic-team/ionic-framework#28561]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

(I've only tested for Angular using ionic start, minimum reproducible example hosted here: [https://mre--ionic-html-tag-scroll.web.app/tabs/tab1](https://mre--ionic-html-tag-scroll.web.app/tabs/tab1), repository here: [https://github.com/KyleSmith0905/mre--ionic-html-tag-scroll](https://github.com/KyleSmith0905/mre--ionic-html-tag-scroll))

Add an option to the ionic module such that the status tap to scroll up will work on web.

On iOS Capacitor, this feature is implemented, but not on the web.

### Describe the Use Case

There's a tradeoff between Ionic having control over the scrollbar, and using the default scrollbar on the root document. By using ion-content you gain custom scroll events and whatever, but then you lose support for the statusTap to navigate to the top.

In an app built around moving through a long list of items, being able to navigate to the top by pressing the tab bar is a worthy tradeoff.

### Describe Preferred Solution

Add a setting in the Ionic Module that would add a class to the root document that triggers pages to act more "plain", I guess.

Idk how this would affect navigation animations.

### Describe Alternatives

- Maybe browsers can implements an API, so maybe if we wait long enough Safari will support it.
- On Capacitor/Ionic I believe this feature comes by default with statusTap.

### Related Code

https://mre--ionic-html-tag-scroll.web.app/tabs/tab1

**Comment by liamdebeasi** [comment]
Hey there,

Ionic has scroll to top built in when using `ion-content`: https://github.com/ionic-team/ionic-framework/blob/388d19e04f83f85abd4602adb04cc71ac575764a/core/src/utils/status-tap.ts#L8. As noted, this only works in Cordova/Capacitor.

Enabling status tap on the root document element on web is not as simple as it sounds. To do this we'd need to have each view scroll on the body. This is a large breaking change that will cause features like swipe to go back to no longer work (since both views will need to be in the DOM, but only 1 view can scroll on the body at once). In short, we'd have to give up important features that make an app feel native. We've considered this change before, but in the end we didn't think the breaking changes and the feature-loss were worth the behaviors that we'd gain.

------

You also noted that users should be able to scroll content to the top when tapping an item in the tab bar. This is a separate feature that is being tracked in https://github.com/ionic-team/ionic-framework/issues/22558. As with the regular status tap behavior, this feature would be limited to Cordova/Capacitor only.

I'm going to close this in favor of the linked tab bar issue, but let me know if you have questions.
