### ISSUE TITLE
bug(vue): unable to use suspense with router outlet

### ISSUE THREAD

**Issue by mwahlhuetter** [ionic-team/ionic-framework#28581]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When using Suspense in conjunction with IonRouterOutlet and an async page, no page will be shown.
The router outlet is missing a vue component, that should be rendered, as a slot prop. The current way of rendering views also does not allow for a default slot which is needed to use supense.

When looking at the RouterView from the original vue-router, supense can be used in this way:
```vue
<RouterView v-slot="{ Component }">
  <template v-if="Component">
    <Suspense>
      <component :is="Component"></component>
      <template #fallback>
        Loading...
      </template>
    </Suspense>
  </template>
</RouterView>
```

This is currently not possible with ionic vue router:
```vue
<ion-router-outlet v-slot="{ Component }">
  <template v-if="Component">
    <suspense>
      <component :is="Component"/>
      <template #fallback>
        Loading...
      </template>
    </suspense>
  </template>
</ion-router-outlet>
```

### Expected Behavior

We should be able to use supense and the router outlet at the same time.

In order for this to work, I looked at the router outlet implementation and made a few changes.
I added the vueComponent to the props object.
```javascript
props = {
  ...props,
  ...routeProps,
  Component: c.vueComponent
};
```
I copied the ```normalizeSlot``` function from vue router and used it in the render function.

```typescript
...
return h(normalizeSlot($slots.default, props) || c.vueComponent, props);
...

function normalizeSlot(slot: Slot | undefined, data: any) {
  if (!slot) return null
  const slotContent = slot(data)
  return slotContent.length === 1 ? slotContent[0] : slotContent
}
```

Then we just need to pass the ```Component``` prop to the ```<component>``` and also bind all the props it, in order to get the ion page elements.

```vue
<ion-router-outlet v-slot="props">
  <template v-if="props.Component">
    <suspense>
      <component :is="props.Component" v-bind="props"/>
      <template #fallback>
        Loading...
      </template>
    </suspense>
  </template>
</ion-router-outlet>
```

### Steps to Reproduce

Use the IonRouterOutlet in conjuction with Suspense as described in the current behavior part.

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/home/mwahlhuetter/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.5.6 (/home/mwahlhuetter/projects/ape/frontend/node_modules/@ionic/vue)

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : not installed
   @capacitor/core    : 5.5.1 (/home/mwahlhuetter/projects/ape/frontend/node_modules/@capacitor/core)
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.18.2 (/home/mwahlhuetter/.nvm/versions/node/v18.18.2/bin/node)
   npm    : 9.8.1
   OS     : Linux 5.10

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you clarify how you plan to use Suspense in an Ionic app? At the moment this feature is experimental: https://vuejs.org/guide/built-ins/suspense.html

**Comment by mwahlhuetter** [comment]
So my basic use case is awaiting some fetching of data in a store which is then used in views.

I could work around this issue for now by using a suspense boundary inside every view, but this is a bit cumbersome because i would have to duplicate the loading state handler in each view and move everything inside the page into another component.

Its definitely not a blocker, but suspense is a really nice feature which makes some use cases super clean. Just wanted to bring this up so its on the radar.

**Comment by liamdebeasi** [comment]
Thanks for the added information! Supporting suspense on a per-route level will be tricky in mobile applications. Using suspense on a route-level tends to lower the perceived responsiveness of a mobile application. In general, a user's direct action should happen fairly quickly. For example, pushing a view as a result of a button click should happen as soon as the user clicks the button. Typically mobile apps will push the page to preserve application responsiveness and lazily load the inner contents of the page. I made an example so you can see the difference in perceived responsiveness:

| Route-level Suspense | Component-level Suspense |
| - | - |
| <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/afcbaeeb-8476-4329-ac03-1a223391c219"></video> | <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/d891b12f-c871-4109-8837-01f779649237"></video> |

In the demos above, the delay is exactly the same (~1500ms), but the second demo tends to be perceived to be more responsive since the user's direct action happens instantly whereas the user's direct action is delayed in the first demo.

We'll definitely keep this feature in mind as we collect more feedback from the community. However, given that this pattern tends to not be recommended in mobile apps and that this feature is experimental, we don't have plans to support this in Ionic at the moment.

**Comment by mwahlhuetter** [comment]
Alright, that makes total sense. Thank you for your comprehensive explanation!
