### ISSUE TITLE
feat: IonInput with typeahead feature

### ISSUE THREAD

**Issue by van9petryk** [ionic-team/ionic-framework#28634]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I saw example of typeahead component
https://ionicframework.com/docs/api/select#typeahead-component
but it not satisfy my requirements.

I need typeahead for ion-input component.

### Describe the Use Case

Sometimes I just need to provide some options for user to select, but the user can also put they own text inside ion-input.
Also, opening modal each time for typeahead can be frustrating, so need dropdown to appear aside to ion-input.

### Describe Preferred Solution

The best solution I saw was https://ng-bootstrap.github.io/#/components/typeahead/examples
It also detect available space on top and bottom of input and put dropdown in best place.
I cannot use it with ionic, because it have selector `input[ngbTypeahead]` and not sure if patch `ion-input[ngbTypeahead]` will help

![Screenshot_5](https://github.com/ionic-team/ionic-framework/assets/23365755/27924284-afbf-4eb0-a158-dbebf57e68b3)
![Screenshot_6](https://github.com/ionic-team/ionic-framework/assets/23365755/aa80d5e6-d3ad-482c-b3f8-5fd26332c32b)

### Describe Alternatives

Other good example is ng-select, but it is more about select, than simple input.

**Comment by liamdebeasi** [comment]
Thanks for the report. We created https://ionicframework.com/docs/api/select#typeahead-component as a way of showing how to implement a mobile-optimized typeahead component. The requested UI pattern works well on desktop. However, showing the dropdown below the input tends to not work well on mobile because the keyboard covers the dropdown when it opens: 
![image](https://github.com/ionic-team/ionic-framework/assets/2721089/5603e955-0dbc-451a-88bc-3d72e881fb5c)

While you can show the dropdown above the input instead, you are still constrained by screen space making this UI pattern difficult to use on mobile devices.

As a result, we do not have plans to implement this feature in Ionic.
