### ISSUE TITLE
feat: support `color` in `ion-list`

### ISSUE THREAD

**Issue by acontreras89** [ionic-team/ionic-framework#28683]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Accept the `color` attribute in `ion-list` so that all `ion-item-` (items, but also groups, dividers, and even item slidings) inherited the color.

### Describe the Use Case

This would enable easily creating lists with a specific, homogeneous color, e.g. `<IonList color="light">`

**Comment by liamdebeasi** [comment]
Thanks for the report. At the moment we don't have plans to add a `color` property to `ion-list` and have child components inherit it. Our primary concern is this goes against how the `color` property was designed. Components typically apply styles to itself when setting `color`. For example, setting `color="primary"` on `ion-content` changes the content background, but child elements inside of the content do not inherit that color.

There are some exceptions where inheriting does exist such as with `ion-segment` and `ion-segment-button`. The reason we do this is `ion-segment-button` is the only thing that should be used as a direct descendent of `ion-segment`. `ion-list` does not have this requirement because we do not dictate what can be used inside of `ion-list`. `ion-item` must be used in `ion-list`, but that's not the only element that can be added into the list. We think that adding `color` to `ion-list` and having some (but not all) children inherit will provide for a confusing developer experience.
