### ISSUE TITLE
feat: select with justify "center" option

### ISSUE THREAD

**Issue by st474ddr** [ionic-team/ionic-framework#28704]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I have already seen the article before.
https://github.com/ionic-team/ionic-framework/issues/27296
However, when I place an ion-select inside an ion-col, the methods mentioned in the article are ineffective.

### Describe the Use Case

My code:
```
 <ion-grid>
                <ion-row :class="selectValue === 'group' ? 'ion-justify-content-around' : 'ion-justify-content-center'">
                    <ion-col :size="selectValue === 'group' ? '3' : '6'">
                        <ion-select aria-label="TeamsType" :toggle-icon="caretDownSharp" 
                            interface="popover" v-model="selectValue">
                            <ion-select-option value="personal">personal</ion-select-option>
                            <ion-select-option value="group">group</ion-select-option>
                        </ion-select>
                    </ion-col>
                    <ion-col size="3" v-if="selectValue === 'group'">
                      test
                    </ion-col>
                </ion-row>
            </ion-grid>
```

I also add the CSS property
```
ion-select {
    width: auto;
    margin: 0 auto;
}
```

And it would look like:
<img width="366" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/17706261/59ffcc67-1a92-4e6a-8e99-198973f916c5">
The image shows that the `ion-select` is not centered.

By using developer tools
<img width="317" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/17706261/4544cf7a-4c02-4950-97c7-06d4fcc4fbbc">
It can be inferred that an invisible block is causing the select layout to be displaced.

### Describe Preferred Solution

1. Please provide a method to enable `justify-content: center` for `ion-select`.
2. Eliminate the invisible flex block.

**Comment by liamdebeasi** [comment]
Thanks for the report. It sounds like you want the select to be centered within the `ion-col` container. If so, then `justify-content: center` is likely not what you want here. The `justify` option controls the spacing between the label and the control itself. Your application does not use a label, so `justify` would have no effect.

Instead, you should instruct `ion-select` to use the minimum intrinsic width. Here's a demo: https://codepen.io/liamdebeasi/pen/NWoZWvW

I'd recommend setting a minimum overall width too otherwise the dimensions will change based on the size of the selected content. You can also optionally move the toggle icon so it moves all the way to the end of the select (which I show in the demo). I am going to close this since the desired behavior is already available in Ionic, but let me know if you have questions.

**Comment by st474ddr** [comment]
It works. 
Appreciate it.
