### ISSUE TITLE
bug: popover without ion-content not scrollable

### ISSUE THREAD

**Issue by capc0** [ionic-team/ionic-framework#29211]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When a popup is created via `PopoverController` with a custom `component`, the contents of the popup is not scrollable.

![image](https://github.com/ionic-team/ionic-framework/assets/27284008/dfae7d0a-c957-42e8-8448-9ecd18174a32)

### Expected Behavior

The content of the popup should be scrollable (as it used to be with previous versions).

![image](https://github.com/ionic-team/ionic-framework/assets/27284008/6a2e56e1-89d8-4055-8c08-cba3bf7fc4eb)

### Steps to Reproduce

1. Click on the button within the stackblitz
2. Resize/shrink the windows viewport 
3. Oberserve that options at the end are cut off and it is not possible to scroll

### Code Reproduction URL

https://stackblitz.com/edit/angular-vvbkmf?file=src%2Fapp%2Fapp.component.ts

### Ionic Info

see Stackblitz setup

### Additional Information

related to https://github.com/ionic-team/ionic-framework/pull/28965 & https://github.com/ionic-team/ionic-framework/issues/28963

a workaround is to set the following style in the globals:

```css
ion-popover > * {
  overflow-y: auto;
}
```

**Comment by liamdebeasi** [comment]
Thanks for the report. The problem here is related to https://github.com/ionic-team/ionic-framework/pull/28861. The code in the linked PR should have always applied, which means that this behavior should have never worked. Due to this bug the behavior noted here worked by chance.

I spoke with the team and we think it's worth trying to support this use case. We support [modals without `ion-content`](https://ionicframework.com/docs/api/modal#custom-dialogs), so we should probably support the same for `ion-popover` too.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/29215, and a fix will be available in an upcoming release of Ionic Framework.
