### ISSUE TITLE
feat: Remove ion-back-button text

### ISSUE THREAD

**Issue by KevinLeneschmidt** [ionic-team/ionic-framework#29281]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I want to be able to remove the text from the ion-back-button without using text="", because this breaks the page transitions like mentioned [here](https://github.com/ionic-team/ionic-framework/issues/29280).

### Describe the Use Case

Sometimes, you want to use the ion-back-button without any text, just the icon.

### Describe Preferred Solution

Explicitly setting text to null should remove any text from the ion-back-button, undefined can be still used to set the default 'Back' text.

### Related Code

Link to a [repo](https://github.com/KevinLeneschmidt/ionic-vue-ios-header)

### Additional Information
Ionic forum link to the topic [here](https://forum.ionicframework.com/t/ios-condense-header/240756/5)

_No response_

**Comment by thetaPC** [comment]
Thank you for submitting the issue!

I strongly advise retaining the text for improved web accessibility. However, I understand your desire to hide it visually. This can be [achieved using CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) since the text is accessible as a [shadow part](https://ionicframework.com/docs/api/back-button#css-shadow-parts). The code snippet below demonstrates how to hide the text while ensuring it remains accessible to screen readers.

```css
ion-back-button::part(text) {
  position: absolute;
  left: -9999px;
  top: auto;
  width: 1px;
  height: 1px;
  overflow: hidden;
}
```

I'm closing this issue as it can be resolved via styling. If you have any other concerns, please open a new PR.

**Comment by thetaPC** [comment]
Related [PR](https://github.com/ionic-team/ionic-framework/pull/29327)
