### ISSUE TITLE
bug: Lifecycle hooks ionViewWillEnter, ionViewDidEnter aren't fired when navigating back to the page

### ISSUE THREAD

**Issue by gultyayev** [ionic-team/ionic-framework#29282]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The ViewWillEnter, ViewDidEnter lifecycle hooks don't fire when I navigate back to the page when popping the stack by pressing the \<ion-back-button>

### Expected Behavior

According to the documentation those should fire always regardless whether the page was initialized or not.

### Steps to Reproduce

1. Click on "Child page"
2. Click on the back button in the header
3. Observe no logs from ViewWillEnter and ViewDidEnter

### Code Reproduction URL

https://stackblitz.com/edit/stackblitz-starters-rzsdv4?file=src%2Fmain.ts%3AL72

### Ionic Info

Ionic:
   Ionic CLI                     : 7.2.0
   Ionic Framework               : @ionic/angular 7.7.4
   @angular-devkit/build-angular : 17.3.0
   @angular-devkit/schematics    : 17.3.0
   @angular/cli                  : 17.3.0
   @ionic/angular-toolkit        : 11.0.1
Capacitor:
   Capacitor CLI      : 5.7.2
   @capacitor/android : 5.7.2
   @capacitor/core    : 5.7.2
   @capacitor/ios     : 5.7.2
Utility:
   cordova-res : not installed globally
   native-run  : 2.0.1
System:
   NodeJS : v20.11.1 (/Users/shultiaiev/homebrew/Cellar/node@20/20.11.1_1/bin/node)
   npm    : 10.2.4
   OS     : macOS Unknown

**Comment by thetaPC** [comment]
Thank you for submitting the issue!

This is working as intended. When you go from a tabs page to a non-tabs page (your child page), the entire tabs context is considered "leaving". However within the tabs context itself, Tab 1 is still active which is why the lifecycles are not firing on Tab 1 when going to a non-tabs page. You can test this by logging something in the `ionViewWillEnter` hook on the `TabsComponent`:

```ts
class TabsComponent {
  ionViewDidEnter() {
    console.log('view did enter 2');
  }

  ionViewWillEnter() {
    console.log('view will enter3');
  }
}
```

There's a [workaround](https://github.com/ionic-team/ionic-framework/issues/28078#issuecomment-1701313792) that might be of interest to you.
