### ISSUE TITLE
feat: Add shadow dom parts to ion-header, ion-toolbar

### ISSUE THREAD

**Issue by kenlnetherland** [ionic-team/ionic-framework#29517]
I have yet to find out how to style an ion-header.  No parts are exposed.  Please advise.

**Comment by thetaPC** [comment]
Thanks for submitting a feature request!

Please provide more context of what you would like to style along with use cases.

**Comment by kenlnetherland** [comment]
Is this a real person that responded.  I want to change the background color of the ion-header or ion-toolbar, lets say "red".  Its that simple.

**Comment by thetaPC** [comment]
We ask for use cases to better understand the request. This is important since we tend to follow the designs dictated by iOS and MD.

**Comment by kenlnetherland** [comment]
I understand.  I wasn't sure if I'm talking to a bot or a real person.  Are you a real person?  I've figured out how to set the background color for the ion-menu because it exposes parts via the ion-content as such:

.ion-secondary-background {
  ion-content::part(background) {
    background-image: var(--ion-secondary-background-image);
  }

  ion-item::part(native) {
    background-image: var(--ion-secondary-background-image);
  }
}

With ion-header or ion-toolbar, I do not see any shadow root parts to tap into.

**Comment by thetaPC** [comment]
The background color can be changed by using the following style:

```css
ion-header ion-toolbar {
  --background: red;
}
```

You can get a full [list of CSS variables](https://ionicframework.com/docs/api/toolbar#css-custom-properties-1) that targets the `ion-toolbar` on its docs page. This will allow you to style the component. I'll be closing this issue since customization can be done with the CSS variables. If you have any other issues, please feel free to open a new issue.

**Comment by kenlnetherland** [comment]
Thank you so much.  I'm just now realizing the --* custom attributes.  I knew of the --variables but didn't realize there was a special use case for this.  Thanks again!
