### ISSUE TITLE
bug: clicking the link inside the ion-checkbox toggles checkbox

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic-framework#29554]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

Clicking the link inside the ion-checkbox toggles (check/uncheck) the checkbox. See the details in the ionic doc https://ionicframework.com/docs/api/checkbox#links-inside-of-labels

### Expected Behavior

Clicking the link inside the ion-checkbox should not check a checkbox

### Steps to Reproduce

See the details here https://github.com/ryaa/links-inside-of-labels-issue

### Code Reproduction URL

https://github.com/ryaa/links-inside-of-labels-issue

### Ionic Info

Ionic CLI                     : 7.2.0 (/Users/alexryltsov/.nvm/versions/node/v20.11.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 8.2.0
   @angular-devkit/build-angular : 17.3.8
   @angular-devkit/schematics    : 17.3.8
   @angular/cli                  : 17.3.8
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 6.0.0
   @capacitor/android : not installed
   @capacitor/core    : 6.0.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v20.11.1 (/Users/alexryltsov/.nvm/versions/node/v20.11.1/bin/node)
   npm    : 10.5.0
   OS     : macOS Unknown

### Additional Information

See above

**Comment by brandyscarney** [comment]
Thank you for the issue! This is caused by the lack of an `href` on the `<a>` tag. You can see this behavior exists outside of Ionic Framework too: https://codepen.io/brandyscarney/pen/PovWWZN?editors=1011

I recommend adding `href="javascript:{}"` or `href="#0"` to the `a` so it continues to behave as a link if you do not want navigation. Here is a [blog post](https://weblog.west-wind.com/posts/2019/Jan/21/NonNavigating-Links-for-JavaScript-Handling) about this. Here is an example demo using an Ionic Framework checkbox: https://codepen.io/brandyscarney/pen/KKLNbgY?editors=1111
