### ISSUE TITLE
bug: Ion-datetime wrong translation

### ISSUE THREAD

**Issue by FranciskoNeves** [ionic-team/ionic-framework#29680]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

<img width="188" alt="Screenshot 2024-06-28 163324" src="https://github.com/ionic-team/ionic-framework/assets/22598113/2708af24-14f7-47b7-acac-0b0bd5ce5066">
The "W" (Wednesday) translation to Spanish, it's wrong.

### Expected Behavior

The translation of "Wednesday" to Spanish is "Miércoles", so the letter of Wednesday in Spanish should be "M" instead of "X".

### Steps to Reproduce

Run the code in the reproduction URL, and the error will appear.

### Code Reproduction URL

https://github.com/FranciskoNeves/IonDatetimeIssueReproduction

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 
   Ionic Framework               : @ionic/angular 6.7.5
   @angular-devkit/build-angular : 15.1.1
   @angular-devkit/schematics    : 15.1.1
   @angular/cli                  : 15.1.1
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : not installed
   @capacitor/core    : 4.6.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v20.11.0
   npm    : 10.2.4
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Ionic looks to be working correctly here. Ionic relies on the browser to give the correct [localized value](https://github.com/ionic-team/ionic-framework/blob/90893f46c930dbccd4251fa2f56bdde30b669158/core/src/components/datetime/utils/data.ts#L80), and it returns "X" for the `narrow` weekday type. My guess is it returns "X" because otherwise you'd have two "M" values, one for martes and one for miércoles, which could be confusing.

Even native iOS uses an "X" value when showing the narrow weekday. (iOS shows the narrow weekday only when the font is scaled up).
![IMG_3789](https://github.com/ionic-team/ionic-framework/assets/2721089/6efa6e19-a845-41b1-84f3-23a5e903bd97)
